### ISSUE TITLE
rev721 ARGB to DXT1

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#100]
Note : this bug may be caused by a combination of me using a VM and strange unusual DDS formatting.
Anyways, I decided to report it just in case, as Photoshop+Nvidia Tools is able to convert any ARGB to DXT1 without problems, whereas me3explorer crashes upon autofixing some ARGBs to DXT1. Preceding revs also crash.

The error :
![dxt1](https://cloud.githubusercontent.com/assets/12874678/10520185/3b0c2dc2-7369-11e5-8efa-1fce8f24eef5.PNG)
http://pastebin.ca/3197866

Testing files : http://filebin.ca/2J9AD3prJMU2/721_ARGB_to_DXT1.7z

**Comment by starkgate** [comment]
This bug changed slightly when I redid the test with rev722. This time me3explorer did not crash, instead, it flagged all these textures as AUTOFIX FAILED.
![bug100](https://cloud.githubusercontent.com/assets/12874678/11125045/1543bee2-8968-11e5-82b2-682edbcff9c3.PNG)
Here is a part of the log :
17:31:12:  Fixing: HMF_ARM_SHPa_Tor_Spec
     FORMAT -> Current: ARGB  Expected: DXT5
     MIPS -> Current: 1  Expected: 11
17:31:28:  Error checking texture: Une ou plusieurs erreurs se sont produites. (One or more errors happened)
17:31:28:  Fixing: HMF_ARM_SHPa_Slv_Spec
     FORMAT -> Current: ARGB  Expected: DXT1
     MIPS -> Current: 1  Expected: 11
17:31:31:  Error checking texture: No mipmaps loaded.
17:31:31:  Fixing: HMM_ARM_SHPa_Sld_Spec
     FORMAT -> Current: ARGB  Expected: DXT1
     MIPS -> Current: 1  Expected: 11
17:31:34:  Error checking texture: No mipmaps loaded.

**Comment by KFreon** [comment]
The issue here was due to the textures not actually being ARGB. 
They were mostly A8L8 which is an alpha/luminescence format, and a few RGB (no alpha).
Support for those two formats has now been added.

**Comment by starkgate** [comment]
Confirmed to work with 723. **But**, there is now a very noticeable quality loss compared to 718 autofixing, see #115.

**Comment by KFreon** [comment]
Roger that.
