### ISSUE TITLE
rev721/722 Wrong looking thumbnails/previews

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#102]
An image is worth a thousand words :
![bug](https://cloud.githubusercontent.com/assets/12874678/10520555/00859f74-736b-11e5-8d8a-59f0dfddfaf9.PNG)
Again, remember that I use a VM, so feel free to skip this bug if it isn't reproducible on a "normal" computer. As you can see, some thumbnails on the left are messed up, and some previews on the right too. I haven't noticed any logic in this.
Also, there is no scrolling bar on the image preview, so no way to see the image in it's entirety if I don't have a high-enough monitor resolution.

**Comment by Mgamerz** [comment]
I don't know if this is also related, but in Texplorer I have noticed
thumbnails are still broken for some items.
I know in 719 texplorer did not work but in 717 it did. I don't think
anything in 720 or 721 fixed it.

**Comment by starkgate** [comment]
You mean "broken" as in "missing" or "messed up" ?

**Comment by Mgamerz** [comment]
As in for me it would not start. On 717 it does.

**Comment by Mgamerz** [comment]
Also thumbnails would show up but some signs be distorted for some
textures. I couldn't get it to work when I tried adding a GUI texture and
eventually just gave up. I'm not a texture modder.

**Comment by KFreon** [comment]
Creeper, you got specs on that VM? Like number of threads/cores, RAM, processor speed, etc?
I had that issue a few times and it was due to the ordering of the threaded decoding. 
I fixed it on my end by letting Windows handling threading, cos it knows best :)

**Comment by starkgate** [comment]
2904 MB RAM, 2 processor cores @2.5 Ghz (the VM lists 2 processors with each one core, but that's not possible, right ?), 60 Go HDD.
So this shouldn't happen for "normal" me3explorer users ? That's good.

**Comment by KFreon** [comment]
Multi-processor boards exist, they're just problematic. Servers have multiple cpu's at least :)
It could still be something to do with threading and loading multiple things at once with load on the cpu from somewhere else.
I dunno...See if it still happens I guess.

Also, how are you getting the toolset? Just the releases, or the latest stuff from git?

**Comment by starkgate** [comment]
Just the releases.

**Comment by KFreon** [comment]
Does this still happen?

**Comment by starkgate** [comment]
I haven't seen it from the little testing I did, but I don't use my VM anymore. I have access to a proper W7 computer now.
You can close it, I'll reopen if needed.

**Comment by starkgate** [comment]
Aaand, I just ran into it again, this time not on the VM :
![preview](https://cloud.githubusercontent.com/assets/12874678/11958890/ca82ecac-a8ca-11e5-93df-98d6df7b29a0.PNG)
Test file : http://filebin.ca/2Qq9xa0Q5Lbf/MASSEFFECT3.EXE_0x07CE12D3.7z
It is a BMP, the preview problem appears once I autofixed it. Also, extracting then loading the autofixed BMP does this :
![capture](https://cloud.githubusercontent.com/assets/12874678/11959001/47b6ba96-a8cb-11e5-8bbf-0f86b04e724c.PNG)

**Comment by starkgate** [comment]
Fixed in 725. Another problem with previews happened, although I'm not sure it is a bug. See #126
