### ISSUE TITLE
rev721/722 Out of bounds error upon loading textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#103]
Last bug report for today^^. Loading a bunch of textures at a time often (as in "not always") results in .NET throwing an "Out of Bounds" error. Choosing to continue and ignore the error doesn't cause any harm, everything works fine.
![capture](https://cloud.githubusercontent.com/assets/12874678/10520645/8e6bc638-736b-11e5-927d-3ac6e80cac26.PNG)

**Comment by Mgamerz** [comment]
Can you post the full stack trace please.

**Comment by starkgate** [comment]
http://pastebin.ca/3199877
Steps to reproduce the error :
-Load some files (I use drag&drop, haven't tried using the Load button).
-Analyse, Clear all files
-Load another batch
Happens also sometimes when loading the first batch of texture files. It's very inconsistent.

**Comment by KFreon** [comment]
Reading over ones old code is perhaps the most frustrating and humbling thing one can do.
Utterly abysmal code it is.
I don't know why half of it is there.
Anyway, I'm pretty sure it's fixed now.
Reading over ones old code is perhaps the most frustrating and humbling thing one can do.
Utterly abysmal code it is.
I don't know why half of it is there.
Anyway, I'm pretty sure it's fixed now.

**Comment by starkgate** [comment]
I didn't notice this bug in 723 when doing my tests. But I didn't load huge amounts of textures either, maybe it requires some more testing to be sure. It's promising !

**Comment by KFreon** [comment]
Imma close it for now then. Just open a new one if it comes back :)
