### ISSUE TITLE
Missing namespace name in ME3Explorer/ModMaker?

### ISSUE THREAD

**Issue by badken** [ME3Explorer/ME3Explorer#104]
I tried installing a relatively old mod by WarrantyVoider: "Press Start Screen Remover" from nexusmods [link here](http://www.nexusmods.com/masseffect3/mods/148/?). I was using r718 of ME3Explorer, downloaded from github (I figured that was a good release to use since it was the latest release candidate).

The first time I tried it I got an old format error, and clicked Yes to update it, but that process just seemed to run forever, so I stopped it after about 15 minutes.

Then I read the discussion for the mod on nexusmods, and WV suggested just clicking "No" when it asks to update the mod. When I tried that, I got the following error window:

""Line: 3 Column: 19 (CS0234) The type or namespace name 'Scripting' does not exist in the namespace 'ME3Explorer' (are you missing an assembly reference?)"

I hit OK, and the Mod Maker continued chuggging along, and claimed that it had installed the mod anyway. When I tried it in the game, though, it didn't skip the start screen. The Mod Maker log from that failed attempt is here: https://drive.google.com/file/d/0B_fggl ... sp=sharing

FemShep suggested updating with r721, so I tried using the Version Switcher to update, but that caused a couple other problems (see problem #2 below). I eventually just downloaded r721 from github and tried that, but I got the same error I saw with r718.

Finally, I downloaded the latest stable release (r653) from github, and the mod worked with that release, and my game is now skipping the "Press Start" screen.

The weird thing is that this seems to be a very simple mod - it appears to just replace a number of bytes from the beginning of EntryMenu.pcc. Apparently the script is referencing an API that was removed from ModMaker? Also the attempt to update the mod appears to assume that it is a mesh mod, which it is not.

**Comment by KFreon** [comment]
[Try this one.](https://dl.dropboxusercontent.com/u/37301843/FIXED_WV_NoSplash.mod)
That mod is so old and unique that Modmaker can't automatically fix it.
