### ISSUE TITLE
Version Switcher fails when ME3Explorer install path contains spaces

### ISSUE THREAD

**Issue by badken** [ME3Explorer/ME3Explorer#105]
When trying to use Version Switcher to resolve another problem, it failed in the command window with a path not found error, because the path where I had ME3Explorer installed included a space. Probably a simple argument quoting problem in some batch file.

**Comment by Mgamerz** [comment]
Please use 721 to verify this version switcher issue still exists. 718 had some issues. I will fix if you can verify it failing.

**Comment by ghost** [comment]
Closing due to removal from toolset.
