### ISSUE TITLE
Version Switcher fails with access denied errors

### ISSUE THREAD

**Issue by badken** [ME3Explorer/ME3Explorer#106]
I am unable to use Version Switcher because it always fails with Access Denied errors when attempting to delete the existing version of ME3Explorer, even when run as Administrator.

Windows 7 Home Premium SP1 64-bit, using Microsoft Security Essentials, (fails even with MSE temporarily disabled). No other filesystemy system tools installed (though I do have the 7zip context menu enabled), volume not shared, nothing I'm aware of that could be keeping files open and causing access denied errors.

**Comment by Mgamerz** [comment]
If the folder is open in windows explorer it will get access denied attempting to delete the folder. The only solution would be to kill explorer.exe which is pretty undesirable behavior.

**Comment by badken** [comment]
I get an access denied at the end of the operation even with the explorer window closed. Going from 721->718, the older version was downloaded, extracted, copied in and launched, and a dialog window reported success, but the cmd window showed an access denied error and the exec subdirectory was missing.

**Comment by Mgamerz** [comment]
Make sure you AV is disabled. Texmod is included and can cause access
denied.

Otherwise can you submit a screenshot of the command prompt window.

**Comment by ghost** [comment]
Closing due to removal from toolset.
