### ISSUE TITLE
rev721/722 Wrong DDS header ?

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#108]
While trying to fix a bunch of DDS', I came across a quite peculiar situation. Autofixing the same DDS' in rev717/718 and 721 resulted in different outcomes. rev721's autofixed DDS' would be systematically 4 bytes smaller than 717/718's (tested with a dozen files). Moreover, loading 721's into 717/718 causes me3explorer to crash, whereas loading 717/718's into 721 poses no problems.

Some information gathered using WV's [DDS Checker](http://me3explorer.freeforums.org/viewtopic.php?f=9&t=2114) :
**717/718 autofixed DDS**
magic               : 0x20534444 - DDS 
dwSize          : 0x0000007C - 124
dwFlags         : 0x00021007 - [DDSD_CAPS] [DDSD_HEIGHT] [DDSD_WIDTH] [DDSD_PIXELFORMAT] [DDSD_MIPMAPCOUNT] 
dwHeight            : 0x00000800 - 2048
dwWidth         : 0x00000800 - 2048
dwPitchOrLinearSize : 0x00000000 - 0
dwDepth         : 0x00000000 - 0
dwMipMapCount       : 0x0000000C - 12
dwReserved1
                    00 = 0x00000000 - 00000000
                    01 = 0x00000000 - 00000000
                    02 = 0x00000000 - 00000000
                    03 = 0x00000000 - 00000000
                    04 = 0x00000000 - 00000000
                    05 = 0x00000000 - 00000000
                    06 = 0x00000000 - 00000000
                    07 = 0x00000000 - 00000000
                    08 = 0x00000000 - 00000000
                    09 = 0x00000000 - 00000000
                    10 = 0x00000000 - 00000000
ddspf.dwSize        : 0x00000020 - 32
ddspf.dwFlags       : 0x00000004 - [DDPF_FOURCC] 
ddspf.dwFourCC      : 0x31545844 - DXT1
ddspf.dwRGBBitCount : 0x00000000 - 0
ddspf.dwRBitMask        : 0x00000000 - 0
ddspf.dwGBitMask        : 0x00000000 - 0
ddspf.dwBBitMask        : 0x00000000 - 0
ddspf.dwABitMask        : 0x00000000 - 0
dwCaps          : 0x00401008 - [DDSCAPS_COMPLEX] [DDSCAPS_TEXTURE] [DDSCAPS_MIPMAP] 
dwCaps2         : 0x00000000 - 
dwCaps3         : 0x00000000 - 0
dwCaps4         : 0x00000000 - 0
dwReserved2         : 0x00000000 - 0

**721 autofixed DDS** (4 less Bytes). Crashes rev717-718. Lacks [DDSCAPS_COMPLEX] [DDSCAPS_MIPMAP] under dwCaps. No other difference between both, so I guess that must be the cause.
magic               : 0x20534444 - DDS 
dwSize          : 0x0000007C - 124
dwFlags         : 0x00021007 - [DDSD_CAPS] [DDSD_HEIGHT] [DDSD_WIDTH] [DDSD_PIXELFORMAT] [DDSD_MIPMAPCOUNT] 
dwHeight            : 0x00000800 - 2048
dwWidth         : 0x00000800 - 2048
dwPitchOrLinearSize : 0x00000000 - 0
dwDepth         : 0x00000000 - 0
dwMipMapCount       : 0x0000000C - 12
dwReserved1
                    00 = 0x00000000 - 00000000
                    01 = 0x00000000 - 00000000
                    02 = 0x00000000 - 00000000
                    03 = 0x00000000 - 00000000
                    04 = 0x00000000 - 00000000
                    05 = 0x00000000 - 00000000
                    06 = 0x00000000 - 00000000
                    07 = 0x00000000 - 00000000
                    08 = 0x00000000 - 00000000
                    09 = 0x00000000 - 00000000
                    10 = 0x00000000 - 00000000
ddspf.dwSize        : 0x00000020 - 32
ddspf.dwFlags       : 0x00000004 - [DDPF_FOURCC] 
ddspf.dwFourCC      : 0x31545844 - DXT1
ddspf.dwRGBBitCount : 0x00000000 - 0
ddspf.dwRBitMask        : 0x00000000 - 0
ddspf.dwGBitMask        : 0x00000000 - 0
ddspf.dwBBitMask        : 0x00000000 - 0
ddspf.dwABitMask        : 0x00000000 - 0
dwCaps          : 0x00001000 - [DDSCAPS_TEXTURE] 
dwCaps2         : 0x00000000 - 
dwCaps3         : 0x00000000 - 0
dwCaps4         : 0x00000000 - 0
dwReserved2         : 0x00000000 - 0

**Crash Report**
Nom d'événement de problème: APPCRASH
  Nom de l'application: ME3Explorer.exe
  Version de l'application: 1.1.718.684
  Horodatage de l'application:  55d4c49b
  Nom du module par défaut:    StackHash_dc86
  Version du module par défaut:    6.1.7601.22470
  Horodateur du module par défaut: 524b7e98
  Code de l'exception:  c0000374
  Décalage de l'exception: 000ce723
  Version du système:  6.1.7601.2.1.0.256.1
  Identificateur de paramètres régionaux: 1036
  Information supplémentaire n° 1:    dc86
  Information supplémentaire n° 2:    dc86ba0dc22a521f3979a3a311965735
  Information supplémentaire n° 3:    674b
  Information supplémentaire n° 4:    674b7d298013f7ed37c708c650bcdbfe

Lire notre déclaration de confidentialité en ligne :
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x040c

Si la déclaration de confidentialité en ligne n'est pas disponible, lisez la version hors connexion :
  C:\Windows\system32\fr-FR\erofflps.txt

**Testing files (original, 721 and 717 autofixed textures)** : http://filebin.ca/2MJtF2tOD6Rs/BugReport.7z

**Comment by KFreon** [comment]
The situation this would occur is if there's no mipmaps. 
The COMPLEX and MIPMAP flags don't get set. Don't know why that would break anything...

**Comment by starkgate** [comment]
Well, perhaps the 717/718 version require these flags to be there. If installing without these flags does not pose any problems, I suppose you could leave it as is as long as there is a new stable rev to replace 717/718.

**Comment by KFreon** [comment]
Yeah there'll be a new stable at some point. 
Hopefully once these bugs are done with.

**Comment by starkgate** [comment]
Same behaviour with textures autofixed using 723. Also, interesting to note that even Photoshop can't open 721-723 autofixed textures^^.
Comparison files between unfixed and autofixed using rev718, 721 or 723.
http://filebin.ca/2PjgFUPxE3Wd/DDS_Header.7z

**Comment by starkgate** [comment]
Hmm, there doesn't seem to be any difference with this in rev724. Same file size, same properties in DDS Checker when you compare 723 and 724 autofixed textures.

**Comment by starkgate** [comment]
Works with rev725. File sizes between 718 and 725 still aren't the same though, with 725 autofixed DDS' being 4 bits bigger than 718.

**Comment by KFreon** [comment]
4 bits or bytes? Also, is that with all formats or just specific ones?

**Comment by starkgate** [comment]
All formats I believe. It is in bytes. Sorry, these notations confuse me as they are named differently in French (i.e. we have 8 bits being 1 Byte or 1 octet). So, yes, 725 autofixed textures are bigger than 718.

With some more testing I noticed it is not always 4 Bytes. Sometimes it is 8, maybe other sizes too. I tested with 60 files, the file sizes between 718 and 725 were never the same.
![capture](https://cloud.githubusercontent.com/assets/12874678/11998502/4a1a36cc-aaa2-11e5-9a7c-189d0c477b50.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12874678/11998503/4a1c1eb0-aaa2-11e5-8358-af1036eb424c.PNG)
I don't understand why the "Size on disk" are the same though.
Big test file (60 textures unfixed, 718, 725) : https://mega.nz/#!Jg1UkLSI!vM5Ja-gC93Hx32FUFhPPrfM9aBV4oDlojCSMavfnP0I

**Comment by KFreon** [comment]
It's 8 bits to a byte here too :P
Interesting...but irrelevant if it works.
It does work right?

**Comment by starkgate** [comment]
It does, but only within 725. It won't work with 717/718 for example. Which won't be important as soon as we have a true stable release post-725, but is problematic in the meantime.
Also, more problematic is the fact that some of the 725 autofixed textures also can't be opened by Photoshop. All of them can't be opened by Gimp.

**Comment by KFreon** [comment]
Those last bits interest me. Some can't be opened by photoshop, and all gimp.
How curious...

**Comment by KFreon** [comment]
I can open all I tested in gimp.

**Comment by starkgate** [comment]
Ok, I suppose you changed the byte count again, because 726 DDS' are now only 4 bytes bigger than 718, and 8 bytes bigger than 724. The one 726 DDS I tried to load in 718 didn't crash it. Although I won't generalize yet, we may be on the right path^^.

**Comment by starkgate** [comment]
Test files : http://filebin.ca/2Riq010GFS3b

**Comment by KFreon** [comment]
I can open that in everything too.
So if they work but have extra stuff, I don't really care :)
I do wonder how they'll behave in Texplorer though since it does some checks on length. Can't remember how it figures out the expected length though...
- Testing is life.

**Comment by starkgate** [comment]
I don't use Texplorer for texture modding, apart for some searched for hashes and names, so these bug reports will most likely come from giftfish and other content modders.
And yeah, I thought having some originality in the naming of my test files would be a nice change :D.

**Comment by KFreon** [comment]
I mean that TPFTools uses Texplorer to install stuff, so just installing some autofixed textures will be the test to perform.
Much more interesting to click on too :)

**Comment by KFreon** [comment]
Most frustratingly, this is now a proper issue as ME1 and 2 explorer's don't like having the wrong sized image. 
I'll need to figure out how many random bytes to add to the end of images...

**Comment by KFreon** [comment]
Think this is fixed now.

**Comment by starkgate** [comment]
rev730 : Looks good, the autofixed DDS I tried out had the same size as it's 718 counterpart. It didn't crash rev718 too, as opposed to the 721 autofixed one, which is nice.
