### ISSUE TITLE
Build error while building with VS2012 and vs2015

### ISSUE THREAD

**Issue by rajasrijan** [ME3Explorer/ME3Explorer#109]
Error Log 

1>------ Rebuild All started: Project: Gibbed.IO, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: SevenZip, Configuration: Debug x86 ------
3>------ Rebuild All started: Project: AmaroK86.MassEffect3.WindowProgress, Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: Be.Windows.Forms.HexBox, Configuration: Debug Any CPU ------
1>  Gibbed.IO -> C:\ME3Explorer-master\Tools\Gibbed.IO\bin\Debug\Gibbed.IO.dll
5>------ Rebuild All started: Project: Gibbed.MassEffect3.FileFormats, Configuration: Debug Any CPU ------
3>  AmaroK86.MassEffect3.WindowProgress -> C:\ME3Explorer-master\AmaroK86\AmaroK86.MassEffect3.WindowProgress\AmaroK86.MassEffect3.WindowProgress\bin\Debug\AmaroK86.MassEffect3.WindowProgress.dll
6>------ Rebuild All started: Project: AmaroK86.ImageFormat, Configuration: Debug Any CPU ------
2>  SevenZip -> C:\ME3Explorer-master\Tools\SevenZip\bin\Debug\SevenZip.dll
5>  Gibbed.MassEffect3.FileFormats -> C:\ME3Explorer-master\Tools\Gibbed.MassEffect3.FileFormats\bin\Debug\Gibbed.MassEffect3.FileFormats.dll
7>------ Rebuild All started: Project: AmaroK86.MassEffect3.ZlibBlock, Configuration: Debug Any CPU ------
8>------ Rebuild All started: Project: AmaroK86.MassEffect3.DLCBase, Configuration: Debug x86 ------
6>  AmaroK86.ImageFormat -> C:\ME3Explorer-master\AmaroK86\AmaroK86.ImageFormat\AmaroK86.ImageFormat\bin\Debug\AmaroK86.ImageFormat.dll
9>------ Rebuild All started: Project: AmaroK86.ImageMipMapHandler, Configuration: Debug Any CPU ------
7>  AmaroK86.MassEffect3.ZlibBlock -> C:\ME3Explorer-master\AmaroK86\AmaroK86.MassEffect3.ZlibBlock\AmaroK86.MassEffect3.ZlibBlock\bin\Debug\AmaroK86.MassEffect3.ZlibBlock.dll
10>------ Rebuild All started: Project: AmaroK86.MassEffect3.TOCHandler, Configuration: Debug Any CPU ------
4>  Be.Windows.Forms.HexBox -> C:\ME3Explorer-master\Be.Windows.Forms.HexBox\bin\Debug\Be.Windows.Forms.HexBox.dll
11>------ Rebuild All started: Project: AmaroK86.INIHandler, Configuration: Debug Any CPU ------
11>  AmaroK86.INIHandler -> C:\ME3Explorer-master\AmaroK86\AmaroK86.INIHandler\INIHandler\bin\Debug\INIHandler.dll
12>------ Rebuild All started: Project: SaltTPF, Configuration: Debug Any CPU ------
9>C:\ME3Explorer-master\AmaroK86\AmaroK86.ImageMipMapHandler\AmaroK86.ImageMipMapHandler\ImageMipMapHandler.cs(23,17,23,27): warning CS0219: The variable 'headerSize' is assigned but its value is never used
9>  AmaroK86.ImageMipMapHandler -> C:\ME3Explorer-master\AmaroK86\AmaroK86.ImageMipMapHandler\AmaroK86.ImageMipMapHandler\bin\Debug\AmaroK86.ImageMipMapHandler.dll
13>------ Rebuild All started: Project: AmaroK86.MassEffect3.ME3Directory, Configuration: Debug Any CPU ------
10>  AmaroK86.MassEffect3.TOCHandler -> C:\ME3Explorer-master\AmaroK86\AmaroK86.MassEffect3.TOCHandler\AmaroK86.MassEffect3.TOCHandler\bin\Debug\AmaroK86.MassEffect3.TOCHandler.dll
8>  AmaroK86.MassEffect3.DLCBase -> C:\ME3Explorer-master\AmaroK86\AmaroK86.MassEffect3.DLCBase\AmaroK86.MassEffect3.DLCBase\bin\Debug\AmaroK86.MassEffect3.DLCBase.dll
14>------ Rebuild All started: Project: ME3LibWV, Configuration: Debug Any CPU ------
15>------ Rebuild All started: Project: AmaroK86.MassEffect3.DLCEditor, Configuration: Debug Any CPU ------
14>  ME3LibWV -> C:\ME3Explorer-master\ME3LibWV\bin\Debug\ME3LibWV.dll
16>------ Rebuild All started: Project: UDKLibWV, Configuration: Debug Any CPU ------
12>  SaltTPF -> C:\ME3Explorer-master\SaltTPF\bin\Debug\SaltTPF.dll
17>------ Rebuild All started: Project: KFreonLib, Configuration: Debug Any CPU ------
16>  UDKLibWV -> C:\ME3Explorer-master\UDKLibWV\bin\Debug\UDKLibWV.dll
18>------ Rebuild All started: Project: NDesk.Options, Configuration: Debug Any CPU ------
18>  NDesk.Options -> C:\ME3Explorer-master\Tools\NDesk.Options\bin\Debug\NDesk.Options.dll
13>  AmaroK86.MassEffect3.ME3Directory -> C:\ME3Explorer-master\AmaroK86\AmaroK86.MassEffect3.ME3Directory\AmaroK86.MassEffect3.ME3Directory\bin\Debug\AmaroK86.MassEffect3.ME3Directory.dll
19>------ Rebuild All started: Project: UDKExplorer, Configuration: Debug x86 ------
20>------ Rebuild All started: Project: ME3VanillaMaker, Configuration: Debug x86 ------
19>  UDKExplorer -> C:\ME3Explorer-master\UDKExplorer\bin\Debug\UDKExplorer.exe
20>  ME3VanillaMaker -> C:\ME3Explorer-master\ME3VanillaMaker\bin\Debug\ME3VanillaMaker.exe
15>  AmaroK86.MassEffect3.DLCEditor -> C:\ME3Explorer-master\AmaroK86\AmaroK86.MassEffect3.DLCEditor\AmaroK86.MassEffect3.DLCEditor\bin\Debug\AmaroK86.MassEffect3.DLCEditor.dll
21>------ Rebuild All started: Project: ME3Creator, Configuration: Debug x86 ------
22>------ Rebuild All started: Project: FemShep.VersionSwitcher, Configuration: Debug Any CPU ------
23>------ Rebuild All started: Project: Gibbed.MassEffect3.Coalesce, Configuration: Debug x86 ------
22>  FemShep.VersionSwitcher -> C:\ME3Explorer-master\VersionSwitcher\bin\Debug\VersionSwitcher.exe
23>  Gibbed.MassEffect3.Coalesce -> C:\ME3Explorer-master\Tools\bin\Gibbed.MassEffect3.Coalesce.exe
17>C:\ME3Explorer-master\KFreonLib\Helpers\SelectionForm.Designer.cs(118,45,118,57): warning CS0108: 'SelectionForm.CancelButton' hides inherited member 'Form.CancelButton'. Use the new keyword if hiding was intended.
17>C:\ME3Explorer-master\KFreonLib\Textures\ME3Texture2D.cs(690,65,690,75): warning CS1066: The default value specified for parameter 'archiveDir' will have no effect because it applies to a member that is used in contexts that do not allow optional arguments
17>C:\ME3Explorer-master\KFreonLib\Textures\ME3Texture2D.cs(690,91,690,99): warning CS1066: The default value specified for parameter 'fileName' will have no effect because it applies to a member that is used in contexts that do not allow optional arguments
17>C:\ME3Explorer-master\KFreonLib\Misc\BitConverter.cs(202,30,202,38): warning CS3021: 'BitConverter.GetBytes(uint)' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
17>C:\ME3Explorer-master\KFreonLib\Misc\BitConverter.cs(225,30,225,38): warning CS3021: 'BitConverter.GetBytes(ulong)' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
17>C:\ME3Explorer-master\KFreonLib\Textures\TexInfo.cs(385,17,385,21): warning CS0162: Unreachable code detected
17>C:\ME3Explorer-master\KFreonLib\PCCObjects\ME3PCCObjectSALTPCC.cs(485,21,485,28): warning CS0219: The variable 'counter' is assigned but its value is never used
17>C:\ME3Explorer-master\KFreonLib\Textures\ME2Texture2D.cs(316,17,316,22): warning CS0219: The variable 'count' is assigned but its value is never used
17>C:\ME3Explorer-master\KFreonLib\Textures\ME1Texture2D.cs(1224,21,1224,30): warning CS0162: Unreachable code detected
17>C:\ME3Explorer-master\KFreonLib\PCCObjects\ME3PCCObjectSALTPCC.cs(162,21,162,30): warning CS0414: The field 'ME3PCCObject.blocklist' is assigned but its value is never used
17>C:\ME3Explorer-master\KFreonLib\Textures\ME1Texture2D.cs(114,21,114,25): warning CS0414: The field 'ME1Texture2D.dims' is assigned but its value is never used
17>C:\ME3Explorer-master\KFreonLib\Textures\SaltDDSPreview.cs(31,22,31,28): warning CS0414: The field 'DDSPreview.stdDDS' is assigned but its value is never used
17>C:\ME3Explorer-master\KFreonLib\Debugging\DebugOutput.cs(21,20,21,25): warning CS0414: The field 'DebugOutput.count' is assigned but its value is never used
17>C:\ME3Explorer-master\KFreonLib\MEDirectories\MEExDirectories.cs(60,16,60,24): warning CS0414: The field 'MEDirectories.Thumpath' is assigned but its value is never used
17>  KFreonLib -> C:\ME3Explorer-master\KFreonLib\bin\Debug\KFreonLib.dll
24>------ Rebuild All started: Project: ME2Explorer, Configuration: Debug x86 ------
25>------ Rebuild All started: Project: ME1Explorer, Configuration: Debug x86 ------
21>  C:\ME3Explorer-master\Libraries\Microsoft.DirectX.Direct3D.dll
21>  C:\ME3Explorer-master\Libraries\Microsoft.DirectX.Direct3DX.dll
21>  C:\ME3Explorer-master\Libraries\Microsoft.DirectX.dll
21>  3 File(s) copied
21>  ME3Creator -> C:\ME3Explorer-master\ME3Creator\bin\Debug\ME3Creator.exe
21>  C:\ME3Explorer-master\ME3Creator\bin\Debug\ME3Creator.exe.config
21>  1 File(s) copied
25>C:\ME3Explorer-master\ME1Explorer\Selector.Designer.cs(84,45,84,57): warning CS0108: 'Selector.CancelButton' hides inherited member 'Form.CancelButton'. Use the new keyword if hiding was intended.
25>C:\ME3Explorer-master\ME1Explorer\Selector.cs(20,17,20,22): warning CS0219: The variable 'count' is assigned but its value is never used
25>C:\ME3Explorer-master\ME1Explorer\Unreal\Classes\Texture2D.cs(1193,21,1193,30): warning CS0162: Unreachable code detected
25>C:\ME3Explorer-master\ME1Explorer\Unreal\Classes\Texture2D.cs(69,21,69,25): warning CS0414: The field 'Texture2D.dims' is assigned but its value is never used
25>  ME1Explorer -> C:\ME3Explorer-master\ME1Explorer\bin\Debug\ME1Explorer.exe
24>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB3552: Resource file "DLCCrack\GiveEntitlements.resx" cannot be found.
26>------ Rebuild All started: Project: ME3Explorer, Configuration: Debug x86 ------
26>C:\ME3Explorer-master\ME3Explorer\ME3Explorer.csproj(1366,3): warning MSB4011: "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.WinFx.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.NetFramework.CurrentVersion.targets (115,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
26>C:\ME3Explorer-master\ME3Explorer\iv0bt5i2.tmp_proj(1303,3): warning MSB4011: "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.WinFx.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.NetFramework.CurrentVersion.targets (115,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
26>CSC : error CS0006: Metadata file 'C:\ME3Explorer-master\ME2Explorer\bin\Debug\ME2Explorer.exe' could not be found
26>  C:\ME3Explorer-master\VersionSwitcher\bin\Debug\VersionSwitcher.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\VersionSwitcher.exe
26>  1 File(s) copied
26>  C:\ME3Explorer-master\Resources\KismetFont.ttf -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\KismetFont.ttf
26>  1 File(s) copied
26>  C:\ME3Explorer-master\Resources\exec\bsdiff.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\bsdiff.exe
26>  C:\ME3Explorer-master\Resources\exec\bspatch.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\bspatch.exe
26>  C:\ME3Explorer-master\Resources\exec\cube.3ds -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\cube.3ds
26>  C:\ME3Explorer-master\Resources\exec\Decompress.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\Decompress.exe
26>  C:\ME3Explorer-master\Resources\exec\Decompress.exe.config -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\Decompress.exe.config
26>  C:\ME3Explorer-master\Resources\exec\Default.bmp -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\Default.bmp
26>  C:\ME3Explorer-master\Resources\exec\DefaultProp.xml -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\DefaultProp.xml
26>  C:\ME3Explorer-master\Resources\exec\demopcc.txt -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\demopcc.txt
26>  C:\ME3Explorer-master\Resources\exec\Folder-Open.ico -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\Folder-Open.ico
26>  C:\ME3Explorer-master\Resources\exec\Folder.ico -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\Folder.ico
26>  C:\ME3Explorer-master\Resources\exec\Gibbed.IO.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\Gibbed.IO.dll
26>  C:\ME3Explorer-master\Resources\exec\ICSharpCode.SharpZipLib.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\ICSharpCode.SharpZipLib.dll
26>  C:\ME3Explorer-master\Resources\exec\JobTemplate_Binary.txt -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\JobTemplate_Binary.txt
26>  C:\ME3Explorer-master\Resources\exec\JobTemplate_Binary2.txt -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\JobTemplate_Binary2.txt
26>  C:\ME3Explorer-master\Resources\exec\JobTemplate_Binary3DLC.txt -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\JobTemplate_Binary3DLC.txt
26>  C:\ME3Explorer-master\Resources\exec\JobTemplate_DLCReplace.txt -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\JobTemplate_DLCReplace.txt
26>  C:\ME3Explorer-master\Resources\exec\languages.xml -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\languages.xml
26>  C:\ME3Explorer-master\Resources\exec\LZOFull.bms -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\LZOFull.bms
26>  C:\ME3Explorer-master\Resources\exec\LZOTex.bms -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\LZOTex.bms
26>  C:\ME3Explorer-master\Resources\exec\NDesk.Options.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\NDesk.Options.dll
26>  C:\ME3Explorer-master\Resources\exec\nvdxt.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\nvdxt.exe
26>  C:\ME3Explorer-master\Resources\exec\offsets.txt -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\offsets.txt
26>  C:\ME3Explorer-master\Resources\exec\oggdec.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\oggdec.exe
26>  C:\ME3Explorer-master\Resources\exec\packed_codebooks.bin -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\packed_codebooks.bin
26>  C:\ME3Explorer-master\Resources\exec\Placeholder.ico -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\Placeholder.ico
26>  C:\ME3Explorer-master\Resources\exec\quickbms.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\quickbms.exe
26>  C:\ME3Explorer-master\Resources\exec\readdxt.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\readdxt.exe
26>  C:\ME3Explorer-master\Resources\exec\select.bmp -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\select.bmp
26>  C:\ME3Explorer-master\Resources\exec\template.code -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\template.code
26>  C:\ME3Explorer-master\Resources\exec\texconv.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\texconv.exe
26>  C:\ME3Explorer-master\Resources\exec\Texmod.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\Texmod.exe
26>  C:\ME3Explorer-master\Resources\exec\Texmod_Builder.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\Texmod_Builder.exe
26>  C:\ME3Explorer-master\Resources\exec\TexScript.txt -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\TexScript.txt
26>  C:\ME3Explorer-master\Resources\exec\TextDoc.jpg -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\TextDoc.jpg
26>  C:\ME3Explorer-master\Resources\exec\TPFTools.ico -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\TPFTools.ico
26>  C:\ME3Explorer-master\Resources\exec\ww2ogg.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\ww2ogg.exe
26>  C:\ME3Explorer-master\Resources\exec\XBoxLZX.bms -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\XBoxLZX.bms
26>  C:\ME3Explorer-master\Resources\exec\zlibber.exe -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\zlibber.exe
26>  C:\ME3Explorer-master\Resources\exec\zlibwapi.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\zlibwapi.dll
26>  39 File(s) copied
26>  C:\ME3Explorer-master\Libraries\lib3ds.Net.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\lib3ds.Net.dll
26>  C:\ME3Explorer-master\Libraries\lzo2.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\lzo2.dll
26>  C:\ME3Explorer-master\Libraries\lzo2helper.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\lzo2helper.dll
26>  C:\ME3Explorer-master\Libraries\Microsoft.DirectX.Direct3D.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\Microsoft.DirectX.Direct3D.dll
26>  C:\ME3Explorer-master\Libraries\Microsoft.DirectX.Direct3DX.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\Microsoft.DirectX.Direct3DX.dll
26>  C:\ME3Explorer-master\Libraries\Microsoft.DirectX.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\Microsoft.DirectX.dll
26>  C:\ME3Explorer-master\Libraries\Newtonsoft.Json.dll -> C:\ME3Explorer-master\ME3Explorer\bin\Debug\Newtonsoft.Json.dll
26>  7 File(s) copied
26>  Microsoft (R) COFF/PE Editor Version 14.00.23026.0
26>  Copyright (C) Microsoft Corporation.  All rights reserved.
26>  
26>LINK : fatal error LNK1104: cannot open file 'C:\ME3Explorer-master\ME3Explorer\bin\Debug\ME3Explorer.exe'
26>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4713,5): error MSB3073: The command "xcopy /f /y "C:\ME3Explorer-master\VersionSwitcher\bin\Debug\VersionSwitcher.exe" "C:\ME3Explorer-master\ME3Explorer\bin\Debug*"
26>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4713,5): error MSB3073: xcopy /f /y "C:\ME3Explorer-master\Resources" "C:\ME3Explorer-master\ME3Explorer\bin\Debug\"
26>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4713,5): error MSB3073: xcopy /f /y "C:\ME3Explorer-master\Resources\exec" "C:\ME3Explorer-master\ME3Explorer\bin\Debug\exec\"
26>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4713,5): error MSB3073: xcopy /f /y "C:\ME3Explorer-master\Libraries" "C:\ME3Explorer-master\ME3Explorer\bin\Debug\"
26>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4713,5): error MSB3073: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE..\Tools\vsvars32.bat"
26>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4713,5): error MSB3073: editbin /largeaddressaware "C:\ME3Explorer-master\ME3Explorer\bin\Debug\ME3Explorer.exe"" exited with code 1104.
========== Rebuild All: 24 succeeded, 2 failed, 0 skipped ==========

**Comment by KFreon** [comment]
> 26>LINK : fatal error LNK1104: cannot open file 'C:\ME3Explorer->master\ME3Explorer\bin\Debug\ME3Explorer.exe'

Looks like the exe is either in use, or otherwise inaccessible (security or something)?

**Comment by Mgamerz** [comment]
If a build step fails (which is almost always due to bad library
references) that file won't exist. Make sure you check  if anything is
failing to build and check that projects references. I never understand how
it keeps reverting no matter how many times everyone fixes it, its like a
haunted visual studio project. All the libs are in the libraries folder if
I recall.

**Comment by rajasrijan** [comment]
> 24>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2718,5): error MSB3552: Resource file "DLCCrack\GiveEntitlements.resx" cannot be found.

Removing "DLCCrack\GiveEntitlements.resx" fixed the problem.
