### ISSUE TITLE
Missing ModMaker function

### ISSUE THREAD

**Issue by Getorex** [ME3Explorer/ME3Explorer#110]
As per the thread in the ME3Explorer forums, I request that the former ability to create new *.mod files be reinstated.  It used to work in conjunction with Meshplorer so it was easy to create new mods that would allow users to add mesh mods to their games via Modmaker.  Somewhere down the line a year-and-a-half ago (roughly) that ability disappeared so it is now impossible to provide users with mod files that include mesh mods.  That leaves only handing out modded pcc files from a modders own game, or demands the creation of de novo DLC.  While DLC is a nice method it is quite complex to make work and the pcc file works but involves large file uploads and downloads.  The *.mod is much cleaner and smaller.  Alternatively, if the DLC method could be organically included in ME3Explorer so the process was easier/quicker then re-working the ModMaker function would be unnecessary.

**Comment by Getorex** [comment]
As for DLC mod making...it would greatly simplify things all around if texplorer and the me3tree.bin build process was modular.  Separate out the main game from the DLC so that if someone installs the game and either no, or just a few DLC, they can do the tree scan, mod their game, then add additional DLC later, including user-created DLC and then scan that new DLC in separately rather than having to revanilla their entire game and rescan the whole thing again.

**Comment by KFreon** [comment]
I've re-enabled both modmaker making mods and adding DLC's to the Tree.
Modmaker is just the old Compare PCC's method. Dunno if there's much else I can do there. Hopefully it works.

Adding DLC's is still experimental and I don't think it was ever tested. Just uses the same method of scanning as the main treescan, so it SHOULD work...
