### ISSUE TITLE
Autofix not working for some image/tree formats (Image Format not detected properly?)

### ISSUE THREAD

**Issue by matsmith83** [ME3Explorer/ME3Explorer#113]
I am having issues installing TPF files using TPF/DDS Tools 3.0 in rev723 of ME3Explorer.

For reference, the TPF files I'm using are those linked to in [this](http://me3explorer.freeforums.org/me2-hr-textures-mod-fixed-tpf-t772.html) thread.

Autofix fails whenever it attempts to fix files with **Image Format:** ATI2_3Dc **Tree Format:** ThreeDC (or a slight variation thereof).  Autofix simply hangs...

![image](https://cloud.githubusercontent.com/assets/16199364/11644436/053e59d6-9d44-11e5-83c2-297084a5dc66.png)

![image](https://cloud.githubusercontent.com/assets/16199364/11644482/6c2bd182-9d44-11e5-8d44-98f87e9338a2.png)

There is a case where autofix needs to fix a different File Tree Format, and succeeds without any issues...

![image](https://cloud.githubusercontent.com/assets/16199364/11644451/21837022-9d44-11e5-9fe5-d30440613d6e.png)

However, If I load the exact same TPF file in an earlier revision of ME3Explorer (rev718), this happens... 

![image](https://cloud.githubusercontent.com/assets/16199364/11644569/08abf366-9d45-11e5-9451-b1b804288038.png)

Where Rev723 detects certain files as **Image Format:** ATI2_3Dc **Tree Format:** ThreeDC, needing autofixing, Rev718 detects them as  **Image Format:** ThreeDC **Tree Format:** ThreeDC, not needing fixing.

I thought you would like to be made aware of this.

**Comment by KFreon** [comment]
I think I've fixed this, but I can't find any test textures like that one.
If you could extract that single texture and link it here, that'd be great.

**Comment by matsmith83** [comment]
OK, I've extracted an example texture using r723 and posted it...

http://1drv.ms/1YsAILG

Let me know if I've messed this up somehow!  If so, the texture is taken from "_EnD_tex_revamp_1.1.tpf", from the forum thread linked to in my initial post.  Also, the extracted texture is "KRO_ARM_HVY_Simp_Norm.dds", as that is the texture used in the screen-grabs above.

**Comment by KFreon** [comment]
I'm pretty sure I've fixed the format clash, but I'm much more interested in the weird colouring. 
Thanks for bringing that to my attention :D

**Comment by starkgate** [comment]
Works in 725, kinda. KRO_ARM_HVY_Simp_Norm is now detected as ATI2_3Dc instead of ThreeDc and not flagged anymore. Are ThreeDc and ATI2_3Dc the same thing ?

**Comment by matsmith83** [comment]
Bearing in mind what CreeperLava says is true, this particular issue seems to be fixed for me.

**Comment by KFreon** [comment]
Yes. 3Dc is ThreeDc. At one point, I decided that ATI2_3Dc was hard to read, so I changed it.
Boy was that a mistake...
