### ISSUE TITLE
rev723 Quality loss ARGB to DXT1

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#115]
There is a very noticeable quality loss when autofixing ARGB to DXT1 compared to 718 autofixing. This loss includes pixellated textures (just like the previous DXT5 to DXT1 conversion) and missing colors. The file size of 723 textures is ~3x smaller than 718, as if some colour layers had been removed altogether.
![capture](https://cloud.githubusercontent.com/assets/12874678/11763941/792249e2-a11e-11e5-9b1e-293e238d8074.PNG)
Another example where you can see the colour problem :
http://filebin.ca/2Pjdt3k1TNfV/ARGB_DXT5.7z

**Comment by KFreon** [comment]
Those images are completely broken for me. Can't open them in anything.
Also are those comparison images from the saved files themselves, or just the previews?
Because the previews are compressed JPGs to save space and time.

**Comment by starkgate** [comment]
Sorry, the file I linked apparently isn't the correct one and I can't find the example textures anymore. If you need them, I'll try to find another example.
The comparison image comes directly from saved files.

**Comment by starkgate** [comment]
No change here in 724. Correct test file is below :
http://filebin.ca/2Qx7ksJ0WJ8M/Test.7z

**Comment by KFreon** [comment]
This appears to be due to compression. I can't find anything that explains it :(

**Comment by starkgate** [comment]
Even the lacking colors ? I can't find the other test file I had linked, but it had some severe issues with a whole color layer not present. Also, you can't deactivate compression ?^^

**Comment by starkgate** [comment]
A comparison :
![sans titre](https://cloud.githubusercontent.com/assets/12874678/12002667/b4396af2-ab04-11e5-8ec2-f66be7fa7860.png)
718 had some problems with ARGB to DXT1 too, but less severe than 725.

**Comment by KFreon** [comment]
While I can't turn off compression since DXT1 is a compressed format, my algorithm does seem rather poor. I'll see what I can do.

**Comment by KFreon** [comment]
After a brutal 4 days of beating my head against the wall, I've made some improvements.
![image](https://cloud.githubusercontent.com/assets/7845997/12042692/184bbb40-aec9-11e5-8eab-cd6fad126d4d.png)

There's some reeeally minor (in my eyes) artifacts which are basically inherent to compression. The most obvious I can see there is the yellow square in the midst of the red vertical lines. There's actually one in the original too, just less obvious.

**Comment by starkgate** [comment]
It looks pretty damn good, thanks. Way better than before :).

**Comment by starkgate** [comment]
I'd consider it fixed now, I made some more tests and I can say the compression is about the same as in 718. If you want to improve it further though, here are more test files so you can see what remains to be fixed : http://filebin.ca/2RiYa3Lg96MR/MoreTest.7z

**Comment by KFreon** [comment]
I'll keep poking but I think I'm at my limit there.
Those test files are good though. Nice colour spread, diagonals, built in artifacts :P 
I'll close this now though.
