### ISSUE TITLE
rev723 Textures not recognized

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#116]
Similarly to #97, some textures don't seem to be recognized correctly by TPF/DDS anymore. This is what it looks like :
![capture](https://cloud.githubusercontent.com/assets/12874678/11764002/42e90c74-a120-11e5-8e3d-fa3eefd587a5.PNG)
And here are some testing files :
http://filebin.ca/2Pjh6Fq2J4gH/Recog.7z
Three cases for these testing files :
- No MIPS : the texture without any MIPS. Recognized by TPF/DDS as a normal texture.
- Texmod : the texture extracted through Texmod. Not recognized (see image)
- 718 : the texture autofixed through 718. Not recognized (see image)
  This happens for various textures, it's a mess.

**Comment by starkgate** [comment]
No change here either in 724, it's the exact same behaviour as in rev723, with the same test files.
This is what happens when I run autofix :
16:35:05:  Fixing: Normandy_Door02_Top_Diff
     FORMAT -> Current: .dds  Expected: DXT5
     MIPS -> Current: 0  Expected: 8

**Comment by starkgate** [comment]
Still the same in rev725.

**Comment by KFreon** [comment]
It'd be good if you could run this in VS and see what's actually breaking. I've been testing with those files for other bugs and they work fine for me.

**Comment by starkgate** [comment]
I'd love to, but as I said on me3ex forums, I can't build rev725 in VS :/.

**Comment by KFreon** [comment]
Ohh right. We need to get that sorted then. 
I haven't had a good explanation for it yet, so I'll see if I can make it work.
I say that above bit because I've never had this error.

**Comment by starkgate** [comment]
Otherwise you can just reproduce the error on your end with the test files linked above.

**Comment by KFreon** [comment]
![image](https://cloud.githubusercontent.com/assets/7845997/12042650/cdca5702-aec8-11e5-851b-c4c691b57bb4.png)

I can't reproduce it. I guess it might have to do with the fixes I've made recently. Pretty sure it isn't though.

**Comment by starkgate** [comment]
I don't remember if you implemented the fix we spoke about on the chat, about W7's missing library iirc. In any case, the problem remains the same with rev727. Here is the VS log :
'ME3Explorer.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'D:\Bibliothèques\P2P\ME3Explorer-r727\ME3Explorer\bin\Debug\ME3Explorer.exe'. Symbols loaded.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Cannot find or open the PDB file.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Cannot find or open the PDB file.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Cannot find or open the PDB file.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Cannot find or open the PDB file.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Cannot find or open the PDB file.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Cannot find or open the PDB file.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Cannot find or open the PDB file.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms.resources\v4.0_4.0.0.0_fr_b77a5c561934e089\System.Windows.Forms.resources.dll'. Module was built without symbols.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'D:\Bibliothèques\P2P\ME3Explorer-r727\ME3Explorer\bin\Debug\KFreonLib.dll'. Symbols loaded.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'D:\Bibliothèques\P2P\ME3Explorer-r727\ME3Explorer\bin\Debug\UsefulThings.dll'. Symbols loaded.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Cannot find or open the PDB file.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Cannot find or open the PDB file.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'D:\Bibliothèques\P2P\ME3Explorer-r727\ME3Explorer\bin\Debug\SaltTPF.dll'. Symbols loaded.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Cannot find or open the PDB file.
The thread 0x3dc has exited with code 259 (0x103).
The thread 0xacc has exited with code 259 (0x103).
The thread 0xa98 has exited with code 259 (0x103).
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'D:\Bibliothèques\P2P\ME3Explorer-r727\ME3Explorer\bin\Debug\CSharpImageLibrary.exe'. Symbols loaded.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_fr_b77a5c561934e089\mscorlib.resources.dll'. Module was built without symbols.
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\PresentationCore.resources\v4.0_4.0.0.0_fr_31bf3856ad364e35\PresentationCore.resources.dll'. Module was built without symbols.
A first chance exception of type 'System.NotSupportedException' occurred in PresentationCore.dll
A first chance exception of type 'System.NotSupportedException' occurred in PresentationCore.dll
System.NotSupportedException: Impossible de trouver un composant d'image adapté pour terminer l'opération. ---> System.Runtime.InteropServices.COMException: Exception de HRESULT : 0x88982F50
   --- Fin de la trace de la pile d'exception interne ---
   à System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   à System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   à System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   à System.Windows.Media.Imaging.BitmapImage.EndInit()
   à UsefulThings.WPF.Images.CreateWPFBitmap(Stream source, Int32 decodeWidth, Int32 decodeHeight, BitmapCacheOption cacheOption, Boolean DisposeStream) dans D:\Stuff\Other\Useful things\Code Repository\C#\UsefulThings\UsefulThings\WPF\WPF.cs:ligne 66
   à UsefulThings.WPF.Images.CreateWPFBitmap(Byte[] source, Int32 decodeWidth, Int32 decodeHeight) dans D:\Stuff\Other\Useful things\Code Repository\C#\UsefulThings\UsefulThings\WPF\WPF.cs:ligne 86
   à CSharpImageLibrary.General.Win8_10.AttemptUsingWindowsCodecs(Byte[] ImageFileData, Int32 decodeWidth, Int32 decodeHeight) dans D:\Stuff\Other\Useful things\Code Repository\C#\CSharpImageLibrary\CSharpImageLibrary\General\Win8_10.cs:ligne 159
A first chance exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll
A first chance exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll
A first chance exception of type 'System.AggregateException' occurred in mscorlib.dll
A first chance exception of type 'System.AggregateException' occurred in mscorlib.dll
A first chance exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll
A first chance exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll
A first chance exception of type 'System.AggregateException' occurred in mscorlib.dll
A first chance exception of type 'System.AggregateException' occurred in mscorlib.dll
'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing.resources\v4.0_4.0.0.0_fr_b03f5f7f11d50a3a\System.Drawing.resources.dll'. Module was built without symbols.
A first chance exception of type 'System.ArgumentException' occurred in System.Drawing.dll
A first chance exception of type 'System.ArgumentException' occurred in System.Drawing.dll
A first chance exception of type 'System.ArgumentException' occurred in System.Drawing.dll
A first chance exception of type 'System.ArgumentException' occurred in System.Drawing.dll
A first chance exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll
A first chance exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll
A first chance exception of type 'System.AggregateException' occurred in mscorlib.dll
A first chance exception of type 'System.AggregateException' occurred in mscorlib.dll
A first chance exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll
A first chance exception of type 'System.IO.EndOfStreamException' occurred in mscorlib.dll
A first chance exception of type 'System.AggregateException' occurred in mscorlib.dll
A first chance exception of type 'System.AggregateException' occurred in mscorlib.dll
The thread 0x17ac has exited with code 259 (0x103).
The thread 0x10b4 has exited with code 259 (0x103).
The thread 0x718 has exited with code 259 (0x103).
The thread 0xfc8 has exited with code 259 (0x103).
The thread 0x105c has exited with code 259 (0x103).

**Comment by KFreon** [comment]
Think this is fixed. I hope...

**Comment by starkgate** [comment]
Well, kinda^^. There is some amelioration at least : the previews aren't placeholders and the textures do get correctly detected.
![a1](https://cloud.githubusercontent.com/assets/12874678/12374082/3d85e1bc-bc91-11e5-8891-44d8eb5fe840.png)
![a2](https://cloud.githubusercontent.com/assets/12874678/12374083/3d86ad9a-bc91-11e5-9f96-b147d66780b2.png)

With that scaling problem, I can't click the analyse button and thus can't see how everything fares with that.

**Comment by starkgate** [comment]
Scratch that, I managed to access that analyse button by tapping 10 times the tab button. Yes, that's the exact number needed, and yes, it took some time to figure it out^^.
![a1](https://cloud.githubusercontent.com/assets/12874678/12374226/2bcadd48-bc95-11e5-90e5-19cf8fec2932.png)
