### ISSUE TITLE
Suggestion : Keep the previews in cache

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#117]
The title says it all, why not keep texture previews in cache ? That would avoid constant loading when doing comparisons between 2 textures and going back and forth between them. To avoid using to many RAM, you could just set a limit to the cache. It doesn't need to be very high (probably 256Mo is enough, as you just need to store 2-3 textures in cache at once). It also should be emptied when 'Clear all files' is clicked.

**Comment by starkgate** [comment]
Works in 725. It's so good to have this feature^^.

**Comment by KFreon** [comment]
Anytime :)
