### ISSUE TITLE
rev723 ModMaker previews

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#119]
Yet another problem with previews, this time with ModMaker.
![capture](https://cloud.githubusercontent.com/assets/12874678/11956072/bcd80f1e-a8b7-11e5-9486-f3afc2cc37ff.PNG)
![capture1](https://cloud.githubusercontent.com/assets/12874678/11956111/082022ae-a8b8-11e5-85a6-830d5f3ec068.PNG)

**Comment by starkgate** [comment]
You can test with whichever .mod you have, it happens with every single one of them for me.

**Comment by KFreon** [comment]
Some reeeeally old image code there...
Fixed now.

**Comment by starkgate** [comment]
Works in 725.
