### ISSUE TITLE
rev723 ModMaker failed to get PCCs

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#120]
When loading a mod and selecting one of the entries, I get an exception window with an error message in the debug log. This doesn't happen with the same mod in rev718. It is a texture-only mod.
Other facts : ModMaker doesn't ask for this specific mod to be updated. Other **updated** .mods don't trigger the error. Other **non-updated** trigger a non-related error about not finding the game corresponding to the .mod.

Here is a link to it : https://www.dropbox.com/s/e3mnhm58iu42rws/Holo%20Mod.mod?dl=0
Log : http://pastebin.ca/3297396
![capture2](https://cloud.githubusercontent.com/assets/12874678/11956333/bbc6f93a-a8b9-11e5-8c2e-fc48f273707c.PNG)

**Comment by KFreon** [comment]
Unfortunately, this doesn't happen to me :(
Do all non-updated mods trigger the non-related error?
Also non-updated = gave you a choice but said no, or doesn't require updating?

**Comment by starkgate** [comment]
The mod causing a problem is one not requiring updating (or at least, not asking for it). The non-updated ones are the ones where I specifically select not to update. Have you tried downloading the mod linked ?

**Comment by KFreon** [comment]
I did. And it doesn't break at all :( I even clicked on the one you had selected.
Curiously...the sizes are displayed differently. Yours just says 5mb, whereas mine has decimal places, and the one you have selected there is 680kb not just 68kb. Weirdness...

I'll look into it a bit more, but if I can't repeat it, I can't fix it :(

**Comment by KFreon** [comment]
We really need to sort out your VS build issues so bugs like this can be sussed out more.
Let me know when we can chat on the forums or something so we can work through it.

**Comment by starkgate** [comment]
I'll be on the chat this evening, at 8PM CET. I don't know what your timezone is, but you should be able to convert using this :http://www.timeanddate.com/worldclock/converter.html?p1=195

**Comment by KFreon** [comment]
Hey Creeper, if I you see this before we line up on chat, can I get you to go into VS -> Tools ->Nuget Package Manager -> For solution, and update the CSharpImageLibrary packages you have?
I made a fix in that package for Windows 7 and I figure this is a better way of testing than to have a new release.

Also that "path" to nuget is approximate. Naming might be different.

**Comment by starkgate** [comment]
That's gonna be complicated, holidays are almost finished here, and I don't have access to my Windows computer anymore, just the VM.

**Comment by KFreon** [comment]
Ahh...
Well I guess I'll make it a release then, or maybe just a temporary test.

**Comment by starkgate** [comment]
I can't say if this is fixed or not in rev727, the updating of the .mod just stalls. Log, VS is at the bottom :
17:26:43:  Message from MEExDirecs: Found installation path from registry. Using cooked directory: D:\Programmes\Mass Effect\ME2\BioGame\CookedPC
17:26:43:  Setting indicators...
17:26:43:  Path of file to check if game files present: D:\Programmes\Mass Effect\ME2\MassEffect2Launcher.exe
17:26:43:  BIOGame Path = D:\Programmes\Mass Effect\ME2\BioGame  found using: ME1Directory Class.
17:26:43:  Message from MEExDirecs: Found installation path from registry. Using cooked directory: D:\Programmes\Mass Effect\ME3\BIOGame\CookedPCConsole
17:26:43:  Setting indicators...
17:26:43:  Path of file to check if game files present: D:\Programmes\Mass Effect\ME3\BIOGame\PCConsoleTOC.bin
17:26:43:  BIOGame Path = D:\Programmes\Mass Effect\ME3\BIOGame  found using: ME2Directory Class.
17:29:52:  Loading file D:\Bibliothèques\P2P\Holo Mod.mod
17:29:52:  Current Version: 1.2.727.0    Mod built with version: 1.1.685.518
17:29:57:  Found 23 Jobs
17:29:57:  Add Job "Upscale (with MIP's): Bar_Text"
17:29:58:  Add Job "Upscale (with MIP's): ScanLines"
17:29:58:  Add Job "Upscale (with MIP's): MiraCore_B"
17:29:58:  Add Job "Upscale (with MIP's): MiraCore_X"
17:29:58:  Add Job "Upscale (with MIP's): MiraCore_Y"
17:29:58:  Add Job "Upscale (with MIP's): MiraCore"
17:29:58:  Add Job "Upscale (with MIP's): Circle"
17:29:58:  Add Job "Upscale (with MIP's): GalaxyGuiProxy"
17:29:58:  Add Job "Upscale (with MIP's): scanner_Line"
17:29:58:  Add Job "Upscale (with MIP's): Cab_Hologram"
17:29:58:  Add Job "Upscale (with MIP's): console01_Diffuse"
17:29:58:  Add Job "Upscale (with MIP's): console01_Emis"
17:29:58:  Add Job "Upscale (with MIP's): console01_Spec"
17:29:58:  Add Job "Upscale (with MIP's): HexBarrier"
17:29:58:  Add Job "Upscale (with MIP's): Gamble_01"
17:29:58:  Add Job "Upscale (with MIP's): Holomod_01_Tex"
17:29:58:  Add Job "Upscale (with MIP's): Bar_Text_01"
17:29:58:  Add Job "Upscale (with MIP's): Bar_Text_Bar"
17:29:58:  Add Job "Upscale (with MIP's): Bar_Text_Blocks"
17:29:58:  Add Job "Upscale (with MIP's): Bar_Text_Fade"
17:29:58:  Add Job "Upscale (with MIP's): Gamble_03"
17:29:58:  Add Job "Upscale (with MIP's): TUR_HIR_VSRa_Diff_Stack"
17:29:58:  Add Job "Upscale (with MIP's): TUR_HIR_VSRa_Norm_Stack"
17:29:58:  Loaded 23.
17:29:58:  Formatting jobs...
17:29:58:  Job: Upscale (with MIP's): Bar_Text  size:  22369748
17:29:58:  Getting further job info...
17:29:58:  Job: Upscale (with MIP's): Bar_Text  type: TEXTURE
17:29:58:  Job: Upscale (with MIP's): Bar_Text Detected game version: 1  Detected texname: Bar_Text
17:29:58:  Guessed gameversion: 1
17:29:58:  Got job details
17:29:58:  Generating thumbnail for: Upscale (with MIP's): Bar_Text
17:29:58:  Updating job: Upscale (with MIP's): Bar_Text
17:29:58:  Validating pccs
17:29:58:  ME1 COOKED: 
17:29:58:  About to begin validating

'ME3Explorer.exe' (CLR v4.0.30319: ME3Explorer.exe): Loaded 'D:\Bibliothèques\P2P\ME3Explorer-r727\ME3Explorer\bin\Debug\Gibbed.IO.dll'. Symbols loaded.
A first chance exception of type 'System.ArgumentNullException' occurred in System.Core.dll
The thread 0xeb4 has exited with code 259 (0x103).
The thread 0x1388 has exited with code 259 (0x103).

**Comment by KFreon** [comment]
So VS doesn't crash anywhere? Daaaamn. 
When it does freeze like this, can you click the little pause button and see if it's actually stuck somewhere?
You can ignore Main and the Debugger threads.

**Comment by starkgate** [comment]
I don't know what you're talking about exactly, but I'll try^^. I'll be on the chat this afternoon (at ~1 PM Paris time).

**Comment by KFreon** [comment]
Is this still a problem?

**Comment by starkgate** [comment]
The mod update is still stalling in rev730, so I can't say :/.

**Comment by KFreon** [comment]
Gonna need VS to sort this one out then :(
You have it on your remote machine?

**Comment by starkgate** [comment]
Yes, I have VS 2013.

**Comment by KFreon** [comment]
Ok so what needs to be done is to press the Pause button in VS when it stalls.

**Comment by starkgate** [comment]
Well I'd love to, if VS would deign to build me3explorer rev730. As said in the 730 forum post though, it doesn't :/.

**Comment by KFreon** [comment]
Ohhh right. I remember that.
Ok so see where it says MEdirectories.cs @ line 13? There'll be something like:
public static string etc = "" .
Just remove the equals and anything after it. You might need a ; sign too if it still doesn't like it.

**Comment by starkgate** [comment]
rev731 works with VS, which is great. So here is the log when I click on Yes to update :

> A first chance exception of type 'System.NotSupportedException' occurred in PresentationCore.dll
> A first chance exception of type 'System.NotSupportedException' occurred in PresentationCore.dll
> System.NotSupportedException: Impossible de trouver un composant d'image adapté pour terminer l'opération. ---> System.Runtime.InteropServices.COMException: Exception de HRESULT : 0x88982F50
>    --- Fin de la trace de la pile d'exception interne ---
>    à System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
>    à System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
>    à System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
>    à System.Windows.Media.Imaging.BitmapImage.EndInit()
>    à UsefulThings.WPF.Images.CreateWPFBitmap(Stream source, Int32 decodeWidth, Int32 decodeHeight, BitmapCacheOption cacheOption, Boolean DisposeStream) dans **D:\Stuff\Other\Useful things\Code Repository\C#\UsefulThings\UsefulThings\WPF\WPF.cs:ligne 66**
>    à UsefulThings.WPF.Images.CreateWPFBitmap(Byte[] source, Int32 decodeWidth, Int32 decodeHeight) dans **D:\Stuff\Other\Useful things\Code Repository\C#\UsefulThings\UsefulThings\WPF\WPF.cs:ligne 86**
>    à CSharpImageLibrary.General.Win8_10.AttemptUsingWindowsCodecs(Byte[] ImageFileData, Int32 decodeWidth, Int32 decodeHeight) dans D:\Stuff\Other\Useful things\Code Repository\C#\CSharpImageLibrary\CSharpImageLibrary\General\Win8_10.cs:ligne 159
> A first chance exception of type 'System.ArgumentNullException' occurred in System.Core.d

Could the problem come from the paths I highlighted, which refer to your own setup ?

**Comment by KFreon** [comment]
That is rather strange. It might be due to me forgetting to update the nuget package.
![image](https://cloud.githubusercontent.com/assets/7845997/12694011/f4eee96a-c769-11e5-968a-26bba1557e71.png)

Either way, I don't need the log, I'm trying to figure out where it's stuck. I suspect it isn't actually breaking, just getting stuck doing something somewhere.

Those errors up there are due to the ImageEngine trying to figure out whether it can use fancy codecs or not (win7 or win 8+)

EDIT: Forgot to mention what I was looking for.
The image up there shows the Pause button I was talking about. So when it gets stuck on updating, just whack that button and see where it is in the code.

**Comment by starkgate** [comment]
![capture](https://cloud.githubusercontent.com/assets/12874678/12695716/3349f186-c757-11e5-825b-727ce8204908.PNG)

**Comment by KFreon** [comment]
Hrm. I was hoping there'd be something more interesting there.

Maybe enabling this will show us something more.
![image](https://cloud.githubusercontent.com/assets/7845997/12698864/20780352-c7f4-11e5-9f17-5cb854039357.png)

**Comment by starkgate** [comment]
I don't have this option in VS 2013. I'll download the newer version in the night, we'll see tomorrow :).

**Comment by starkgate** [comment]
Actually, VS 2015 doesn't have it either. Is this an addon ?

**Comment by KFreon** [comment]
It's only while debugging? I've only got the free version of VS 2015 too.
So you have to run ME3Explorer through VS and pause it, then you'll be able to select this option.

**Comment by starkgate** [comment]
Ah, I must have forgotten to pause. I'll try it this week-end.

**Comment by starkgate** [comment]
Here you go, hope that helps :
![screenshot_2016-02-05_18-42-06](https://cloud.githubusercontent.com/assets/12874678/12854188/7ff8409c-cc38-11e5-81d3-a8daa64a9284.png)
![screenshot_2016-02-05_18-44-20](https://cloud.githubusercontent.com/assets/12874678/12854189/7ffabb10-cc38-11e5-831e-f52d73c0c72a.png)

**Comment by KFreon** [comment]
Interesting...I'm guessing you don't have one of the games installed?
Anyway [try this one.](https://dl.dropboxusercontent.com/u/37301843/ME3Explorer_TEST.7z)

**Comment by starkgate** [comment]
Sorry, my computer's network card seems to have died, so I won't be able to test until I come home in a week.

**Comment by starkgate** [comment]
Apparently the death was temporary. I can confirm your test version fixes the problem. No thumbnail problem, the updating went fine too. I had all 3 games installed with rev731 though, but it is possible that me3explorer didn't detect all 3.

**Comment by KFreon** [comment]
Eeexcellent. Ok so I'll add this to the next rev.

**Comment by starkgate** [comment]
Confirmed to work in rev733.
