### ISSUE TITLE
rev723 Another Index problem

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#121]
This time in ModMaker :
![capture3](https://cloud.githubusercontent.com/assets/12874678/11956389/3089c0fe-a8ba-11e5-85f7-75e8fa5ac052.PNG)
This happens when using the down arrow while already being at the bottom of the list. It doesn't happen when using the "Move Down" button. Also happens with rev718.

**Comment by KFreon** [comment]
Fixed.
Had the wrong boundary condition.

**Comment by starkgate** [comment]
Works in 725.
