### ISSUE TITLE
rev723 Installing BMP autofixed textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#122]
BMP autofix does work, but TPF/DDS seems to be unable to install the resulting DDS :
![capture](https://cloud.githubusercontent.com/assets/12874678/11959085/d1b75f70-a8cb-11e5-99f0-ef695e168607.PNG)
Test file : http://filebin.ca/2Qq9xa0Q5Lbf/MASSEFFECT3.EXE_0x07CE12D3.7z

**Comment by KFreon** [comment]
I think I just found out why your other report of the header being different happens. 
Firstly, the header is fine though. No stress there.
BUT, I believe I don't handle the lower mip levels (2x2, 1x1) correctly. So I've expanded that a little.
It's still wrong, but who can see things 2 pixels wide anyway?

**Comment by starkgate** [comment]
Works with 725. Does not crash 717/718 anymore. Can install with 725, but older revs can't install 725 autofixed textures :
12:48:47:  Now replacing textures in texture: HMM_ARM_CTHi_CLN_DIFF
12:48:47:  Unknown error with mod:  HMM_ARM_CTHi_CLN_DIFF, skipping.
12:48:47:  All mods were skipped.
You can do the test with the same file linked above. I'm not sure that's a problem since it works with 725, but compatibility would be pretty good to have.

**Comment by KFreon** [comment]
Closing this in accordance with the other thread.
