### ISSUE TITLE
SirCxyrtyx changes (all of r721) are ignored in 722+

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#123]
Bugfix was never merged into master, which is where apparently all the builds are coming from. As such none of his changes to ME1Explorer are there and they cannot be merged automatically because the code branches have forked. Before further edits are commited this should be resolved otherwise his work was pointless.

I attempted to manually merge them but I don't know enough about ME1Explorer and didn't want to screw it up so this one's on you KFreon.

**Comment by SirCxyrtyx** [comment]
I'm not able to do anything right now, but if this is unresolved by about the 27th, I can take care of it.

**Comment by KFreon** [comment]
I merged it all, hopefully correctly...
