### ISSUE TITLE
rev725 Autofixed DDS' not compatible with older revs

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#125]
Trying to load a 725 autofixed DDS in 718 works, but trying to install it systematically results in :
12:48:47:  Now replacing textures in texture: HMM_ARM_CTHi_CLN_DIFF
12:48:47:  Unknown error with mod:  HMM_ARM_CTHi_CLN_DIFF, skipping.
12:48:47:  All mods were skipped.
I'm not sure that's a problem since it works with 725, but compatibility would be pretty good to have.
http://filebin.ca/2Qq9xa0Q5Lbf/MASSEFFECT3.EXE_0x07CE12D3.7z
http://filebin.ca/2MJtF2tOD6Rs/BugReport.7z

Related to #108

**Comment by starkgate** [comment]
DDS Checker logs :
**rev718**
magic               : 0x20534444 - DDS 
dwSize          : 0x0000007C - 124
dwFlags         : 0x00021007 - [DDSD_CAPS] [DDSD_HEIGHT] [DDSD_WIDTH] [DDSD_PIXELFORMAT] [DDSD_MIPMAPCOUNT] 
dwHeight            : 0x00000100 - 256
dwWidth         : 0x00000100 - 256
dwPitchOrLinearSize : 0x00000000 - 0
dwDepth         : 0x00000000 - 0
dwMipMapCount       : 0x00000009 - 9
dwReserved1
                    00 = 0x00000000 - 00000000
                    01 = 0x00000000 - 00000000
                    02 = 0x00000000 - 00000000
                    03 = 0x00000000 - 00000000
                    04 = 0x00000000 - 00000000
                    05 = 0x00000000 - 00000000
                    06 = 0x00000000 - 00000000
                    07 = 0x00000000 - 00000000
                    08 = 0x00000000 - 00000000
                    09 = 0x00000000 - 00000000
                    10 = 0x00000000 - 00000000
ddspf.dwSize        : 0x00000020 - 32
ddspf.dwFlags       : 0x00000004 - [DDPF_FOURCC] 
ddspf.dwFourCC      : 0x31545844 - DXT1
ddspf.dwRGBBitCount : 0x00000000 - 0
ddspf.dwRBitMask        : 0x00000000 - 0
ddspf.dwGBitMask        : 0x00000000 - 0
ddspf.dwBBitMask        : 0x00000000 - 0
ddspf.dwABitMask        : 0x00000000 - 0
dwCaps          : 0x00401008 - [DDSCAPS_COMPLEX] [DDSCAPS_TEXTURE] [DDSCAPS_MIPMAP] 
dwCaps2         : 0x00000000 - 
dwCaps3         : 0x00000000 - 0
dwCaps4         : 0x00000000 - 0
dwReserved2         : 0x00000000 - 0

**rev725**
magic               : 0x20534444 - DDS 
dwSize          : 0x0000007C - 124
dwFlags         : 0x00021007 - [DDSD_CAPS] [DDSD_HEIGHT] [DDSD_WIDTH] [DDSD_PIXELFORMAT] [DDSD_MIPMAPCOUNT] 
dwHeight            : 0x00000100 - 256
dwWidth         : 0x00000100 - 256
dwPitchOrLinearSize : 0x00000000 - 0
dwDepth         : 0x00000000 - 0
dwMipMapCount       : 0x00000009 - 9
dwReserved1
                    00 = 0x00000000 - 00000000
                    01 = 0x00000000 - 00000000
                    02 = 0x00000000 - 00000000
                    03 = 0x00000000 - 00000000
                    04 = 0x00000000 - 00000000
                    05 = 0x00000000 - 00000000
                    06 = 0x00000000 - 00000000
                    07 = 0x00000000 - 00000000
                    08 = 0x00000000 - 00000000
                    09 = 0x00000000 - 00000000
                    10 = 0x00000000 - 00000000
ddspf.dwSize        : 0x00000020 - 32
ddspf.dwFlags       : 0x00000004 - [DDPF_FOURCC] 
ddspf.dwFourCC      : 0x31545844 - DXT1
ddspf.dwRGBBitCount : 0x00000000 - 0
ddspf.dwRBitMask        : 0x00000000 - 0
ddspf.dwGBitMask        : 0x00000000 - 0
ddspf.dwBBitMask        : 0x00000000 - 0
ddspf.dwABitMask        : 0x00000000 - 0
dwCaps          : 0x00001000 - [DDSCAPS_TEXTURE] 
dwCaps2         : 0x00000000 - 
dwCaps3         : 0x00000000 - 0
dwCaps4         : 0x00000000 - 0
dwReserved2         : 0x00000000 - 0

**Comment by KFreon** [comment]
I'd say this is because it's trying to load a slightly larger file than it expects (it expects wrong)
I don't see this as a problem. I'd more call this a fixed bug.
Imma close this, but feel free to reopen it if there's  a larger problem with this.
