### ISSUE TITLE
rev725 Spec textures preview

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#126]
Spec textures look different in the thumbnail and in the normal preview :
![capture](https://cloud.githubusercontent.com/assets/12874678/11994388/a3c7467a-aa3d-11e5-835a-f5e43956a129.PNG)
The "correct" one is the thumbnail.

**Comment by starkgate** [comment]
Same thing in Texplorer.

**Comment by KFreon** [comment]
This is due to handling the alpha channel. 
The thumbnail ignored it, whereas the preview didn't.
Now they both do.

**Comment by starkgate** [comment]
Fixed :)
