### ISSUE TITLE
rev725 G8 textures detected as G8_L8, autofix failing

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#127]
An image is worth a thousand words :
![g8_l8](https://cloud.githubusercontent.com/assets/12874678/11998423/8c1cdeec-aa9f-11e5-83ee-ba9857081790.PNG)
Debug log when trying to autofix in rev725 :
00:34:22:  Fixing: LD_Spec_03
     FORMAT -> Current: G8_L8  Expected: G8
     MIPS -> Current: 10  Expected: 8
00:34:22:  Error checking texture: Le flux de mémoire n'est pas extensible.
00:34:22:  Fixing: Spec_Tile_A
     FORMAT -> Current: G8_L8  Expected: G8
     MIPS -> Current: 10  Expected: 8

"Le flux de mémoire n'est pas extensible." is hard to translate. It would mean "The memory stream can't be extended".

**Comment by KFreon** [comment]
From the gist of your translation, I'd say it's more like "Can't read past end of memory stream" maybe?
Also you got a link for a test image?

**Comment by starkgate** [comment]
Yes, that could be it too. Here is a test file : http://filebin.ca/2RGeoh1WoImc/Test.7z

**Comment by KFreon** [comment]
Fixed. Was doing the format check the wrong way around.

**Comment by starkgate** [comment]
Fixed indeed !
