### ISSUE TITLE
rev725 Undefined bug :/

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#128]
This one I really can't see a pattern with.
![capture](https://cloud.githubusercontent.com/assets/12874678/11998458/45e3d9e8-aaa0-11e5-853f-126a895b4fb3.PNG)
As you can see, some V8U8, DXT5 and DXT1 textures are not recognized in 725 anymore. It doesn't happen for all of the V8U8/DXT1/DXT5, and these specific textures don't have anything in common that could explain it. They're all rectangles, but the WPN_PST_BARe_Spec is one too and doesn't pose any problem.
Test files : http://filebin.ca/2R6Xp4IExMqe/test.7z

**Comment by starkgate** [comment]
Also, you can see on picture that the preview doesn't correspond to the selected texture (KroInd_Pipe_01_Diff). It seems like the cached picture is displayed by default when no other is available.

**Comment by KFreon** [comment]
Fixed both of them I think.
First was due to trying to read a 0x1 mipmap it thought existed.
Second was just forgetting to reset the image before exiting the function. This one is untested though.

**Comment by starkgate** [comment]
I can confirm both are fixed, mostly. From the test files linked, KroInd_Pipe_01_Diff is the only one that still isn't recognized. Maybe another underlying bug ? A bug can hide another^^.
