### ISSUE TITLE
All revs Replacing 0 MIP textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#129]
There seems to be a problem in all revs with upscaling 0 MIP textures. Doing so simply crashes the game upon loading the save ; although TPF/DDS seems to install it properly (no need for autofix). Texplorer does throw out an error if I try to replace the texture. No problem with installation if I just "Add Bigger Image", but it still crashes ME3.
![capture](https://cloud.githubusercontent.com/assets/12874678/12017605/46f79f3e-ad59-11e5-9d21-2a02cb634f08.PNG)
Log : http://pastebin.ca/3306072
Test files : http://filebin.ca/2RUq7pOLK9Wf/Textures.7z

The original discoverer of the bug is LedGuardian, who gave me the permission to use his textures for ALOT, but had problems with this one texture. We tried just about everything, so I don't know where the problem lies. Maybe directly in me3explorer's code ?

This is what he told me before I did my own testing : there is no problem with loading the texture through Texmod. Replacing the upscaled texture with afore-extracted vanilla one still crashes the game. You can install the texture with 11 MIPS (as it should have), only 1 is kept by TPF/DDS (without a need for autofix) and it still crashes the game.

**Comment by KFreon** [comment]
Single image upscale has been a problem for a while. 
Replace in Texplorer is for images of the same size only. 
Dunno why it would be crashing the game, but I'll look into it.
Won't be a quick fix though :(

**Comment by starkgate** [comment]
> Replace in Texplorer is for images of the same size only.

Ooh I see, I wasn't aware of that.

**Comment by KFreon** [comment]
It's supposed to tell you that straight up, and I can't think of why it would crash like that...

**Comment by starkgate** [comment]
There is still a problem with "Add Bigger Image", if the thumbnails aren't generated it will throw an error about it. Trying to regenerate them also fails because apparently me3explorer can't find " 'D:\Bibliothèques\P2P\ME3Explorer-r727\ME3Explorer\bin\Debug\Exec\ThumbnailCaches\ME3ThumbnailCache\KroInd_MetalTrim_01_Emis_MSK_1980454538.jpg'." Why would it need the previous thumbnail to regenerate it ? Or does it try to delete it ?
Note that this is only a problem for those who switch between revs without transferring the thumbnails. Not sure if the thumbnails port over after a Version Switcher switch, would be interesting to know.

**Comment by KFreon** [comment]
Yeah It was trying to delete a file it couldn't find. 
Fixed now.
