### ISSUE TITLE
ModMaker Save/Extract Data, Incorrect Actions

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#131]
Rev726.

Two problems so far.
1. Selecting all 20 jobs in a mesh .mod file and using the Extract Data feature resulted in 2 DDS files being created in the specified save directory. I know this sounds impossible, but it's accurate. I created from the directory from scratch and it was empty. After the extract, I watched two DDS files appear. Note, that the .mod consisted of entirely new meshes. There were no textures included. I triple-checked and cross-referenced to the relevant PCC files.
2. Selecting a subset of 15 jobs from the same .mod and using the Save Selected to .mod resulted in a .mod file that contained a single job.

Seems perhaps features associated with selecting multiple jobs and then performing an operation are not working correctly. 

Actually running the mod with only the 15 selected seems to work. At least the tool said it was installing 15 mods.

**Comment by ghost** [comment]
Test file attached.

[ELE_hairstyles_me3.zip](https://github.com/ME3Explorer/ME3Explorer/files/79219/ELE_hairstyles_me3.zip)

**Comment by KFreon** [comment]
1. Fixed. Was due to the naming system only using the name of the pcc, so if multiple jobs being extracted worked on the same file, they'd overwrite each other.
2. Only had 1 job saving :D Whoops.

**Comment by ghost** [comment]
An update on this.

The files edited by this mod -- with 15/20 jobs selected -- is corrupt and cannot be read by the game. Not sure if this is an artifact of the multi-file selection or autofix.
[Corrupt_modded files.zip](https://github.com/ME3Explorer/ME3Explorer/files/80111/Corrupt_modded.files.zip)

Uploading them for examination in case it helps.

**Comment by ghost** [comment]
And, one more update.

Extracting all 15 jobs individually, and then manually inserting them via PCCEd2 works as expected. No problems. Which means there is nothing wrong with the contents of this particular .mod file, and it's ikely something with the script/autofix.

It might also be worth nothing that when I did this, I initially replaced one mesh as a test and then loaded it in game to be sure it would work. After verifying it did, I tried to replace additional meshes in the same file _without_ reloading it in PCCEd2. This resulted in PCCEd2 throwing a "zlib" error every time I clicked on any export below the replaced mesh. Once I reloaded the file, then I could replace additional meshes without a problem. No idea if ModMaker might be running into a similar error or not, but wanted to let you know in case it was related... or made you think of something that could be, lol.

**Comment by KFreon** [comment]
Oh deary me...
I came across this issue before as well, and just assumed that's sometimes what happened in mesh modding. 
I'll take a look then.

**Comment by KFreon** [comment]
Fixed. Was somehow using the wrong PCCObject.

**Comment by ghost** [comment]
Great. This works perfectly in r733 :)

**Comment by ghost** [comment]
@KFreon -- And, looks like we still have one other issue.

If you select multiple files for extraction and they are a mix of textures and other assets, they all get named as "BIN", rather than the textures getting saved as DDSes.

For example:
![mm_extractbug2png](https://cloud.githubusercontent.com/assets/13645804/13374085/683249b4-dd2f-11e5-97b1-55a7fc719eef.PNG)

This does NOT happen if you only select/extract one asset. In that case it works perfectly and textures are named as DDSes, and other assets are named as BINs.

**Comment by KFreon** [comment]
Should be fixed now.

**Comment by ghost** [comment]
Verified in rev742. Nice work, K.
