### ISSUE TITLE
ModMaker Extraction of DLC .mod files

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#133]
K, this is related to what we were talking about yesterday, but is a slightly different issue.

ModMaker currently attaches a ".mesh" extension to all jobs the user extracts. This is a problem, since, A-not every job will be a mesh, and B-if the user wants to install manually, most of the time a BIN extension will be what's necessary, since that's what's used to replace entire exports in PCCEd2. I've extracted these .mesh files, renamed them to BIN files, and BIN replacement inside PCCEd2 works as expected.

However, in the case of .mod files that will edit DLC, they have been designed to use full PCC replacement in SFARs. And, upon extracting _these_ jobs, they are also named ".mesh". BUT, renaming them to ".pcc" does _not_ work, despite the fact that they are indeed full PCC files. Opening them with PCCEd2 results in an error telling you that it _isn't_ a PCC file.

You can test this with Otte's "EDI From Ashes" mod, here: http://www.nexusmods.com/masseffect3/mods/273/?

I know this ties into the dilemma re currently have as to how this stuff needs to be changed. But, despite that, the extraction itself isn't working. It seems to corrupt the file upon extraction.

**Comment by KFreon** [comment]
I do believe that mod is one Ottemis fixed to work properly with DLC's that'd been extracted.
Modmaker doesn't do mods that replace entire PCC's. There'd be no need to use Modmaker for that.

**Comment by ghost** [comment]
Nope, it doesn't... not if I'm understanding you correctly. If you load it up, it replaces full PCCs. These .mod files are made with DLC Ed2, and were made back before SFARs were being extracted. WV actually created the ModMaking feature inside of DLCEd2 at my request for TM back in 2013. I've actually made .mod files myself that fully replace PCCs inside of SFARs. TM v1.0 was released with several of them.

So, in this case, these _are_ full PCC files (ModMaker even says so), but they aren't being extracted properly.

**Comment by KFreon** [comment]
Closing this, but for reference, DLCEd2 can do this, it's just not what was happening.

**Comment by ghost** [comment]
Verified working in r733. Extracted jobs are now saved with the bin suffix, so they should immediately be usable in PCCEd2 if the user wishes.
