### ISSUE TITLE
Crash when autofixing textures (version 110 R726 win 7 testing)

### ISSUE THREAD

**Issue by forgetti** [ME3Explorer/ME3Explorer#134]
when attempting to autofix incorrectly formatted textures me3 explorer will fully crash. 

I was attempting to autofix the texture linked here: https://mega.nz/#!fY00XCaD!C42LXHPaf_dj2WW3beDBMk7cMQ5T7iRC8thLX2ZLEiM and install it to me2. but instead of autofixing the textures as intended me3 explorer crashed. I've repeated the attempts with different texture files as well and its crashed when trying to autofix them as well

here is the windows error Dialogue if this will help fix the problem:

Problem Event Name: APPCRASH
Application Name:   ME3Explorer.exe
Application Version:    1.1.726.0
Application Timestamp:  5689a7b4
Fault Module Name:  StackHash_7e73
Fault Module Version:   6.1.7601.19045
Fault Module Timestamp: 56258e62
Exception Code: c0000374
Exception Offset:   000ced0b
OS Version: 6.1.7601.2.1.0.768.3
Locale ID:  1033
Additional Information 1:   7e73
Additional Information 2:   7e739d22820b05e2d7a169d0d8577e29
Additional Information 3:   dbaa
Additional Information 4:   dbaa6c36b520c025f2feced2181684a2

**Comment by starkgate** [comment]
I can't access the link you posted. Can you upload it to filebin.ca ? It would be more practical.

**Comment by forgetti** [comment]
ok. i uploaded the file to my mega repository and linked that instead

**Comment by KFreon** [comment]
EDIT: Scratch all that. Read the title properly this time :P 
So that's using the new version I posted on the forums?

**Comment by forgetti** [comment]
yeah. the one you wanted us windows 7 users to test. also to note autofix worked fine in the standard release of r726.

**Comment by KFreon** [comment]
Really? Worked before the fix, that's very interesting. It shouldn't have :P 
Unfortunately, I don't have Windows 7 anymore and even more unfortunately, looks like this testing is going to have to be done from inside Visual Studio. 
Need more debugging detail :(

**Comment by starkgate** [comment]
I couldn't reproduce the error on rev727 W7, I suppose it can be considered fixed.
