### ISSUE TITLE
Suggestion : Multicore support and optimization idea

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#135]
Just decided I'd write some ideas here, in case the next stable is indeed the last. It would be nice to have a performance boost with it :).

I was thinking about multicore support when I saw the time it takes to build a tree or install big mods, and the fact that my CPU was idle at 75%. Multicore would possibly divide the process time by 2-8 (depending on core number. Not sure if it works quite that way, but it would certainly shorten the process anyway). I don't know if it is easy to implement or not though.

Heff also told me about an optimization that would be possible to do for texture installation, before his absence. As I don't know if he will develop it himself, I'll just write the idea down here.
For example, if you have a big TPF with multiple textures belonging to the same PCC, you would open the PCC, install each of these textures into it, then only close it. The current process is to open, install one texture, close and repeat until done. I suppose this would also shorten the installation time by quite a bit.

**Comment by Mgamerz** [comment]
Multi core is a significant undertaking (air complex) Depending on if its
cpu or disk maxing out it may not improve performance by much. Would help
lots of things though.

**Comment by KFreon** [comment]
Strange it's idling like that...Mine is maxed out nearly the whole time.
Multicore support is already with all the texture stuff and modmaker.
I'd already added Heff's optimization to the WPF version I was writing ages ago. I just need to try and get it over to the main stuff.
Dunno if it's going to happen for the stable though :(

**Comment by starkgate** [comment]
So the threading option does indeed have an effect now ? It used to not work at all, I didn't know that changed :).

**Comment by KFreon** [comment]
Treescanning at least has a bunch of threading going on. 
Pretty sure installation does too.

**Comment by starkgate** [comment]
Does that require to activate an option ? Because I never experienced that threading. I'll test it out in the future to be sure.

**Comment by KFreon** [comment]
Do you have it turned off? It respects that threading option in the main window and/or Texplorer window. Not sure which is which.

**Comment by ghost** [comment]
@KFreon -- Can this issue be closed? Is the toolset already multi-threaded as Creeper asked?

**Comment by KFreon** [comment]
Mmm It needs more, and once I get to it in my rewrite, I might be able to merge it into this.
I suppose it probably won't make it into the stable though. 
Enhancement is good.

**Comment by KFreon** [comment]
Ok now I'm closing this. It doesn't belong here anymore.
As info though, the rewrite is multithreaded in any long running operation, and the UI and actual operations are separate at nearly all times.
