### ISSUE TITLE
rev727 | PCCED2 Error; Unuseable

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#136]
Welp, I'm getting this error with PCCEd2 on the new rev:
![pcced2](https://cloud.githubusercontent.com/assets/13645804/12222490/ae936830-b772-11e5-9111-6b18b07cda9c.PNG)
It's happening in all 3 files I've tried so far, and any object in the file I click on.

Error doesn't exist in rev726.

**Comment by Mgamerz** [comment]
This is my fault. Visual Studio seemed to blow up in the editor and remove a lot of random stuff. I am working on a fix. I know what the issue is (hb1 got blown up for some odd reason)
