### ISSUE TITLE
ModMaker PCC Compare not generating MOD file

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#138]
So, yeah.

The windows pop up asking you to choose the base file and the modded file to compare them, but no MOD file is generated. Nothing happens at all. No Debug output, no error.

**Comment by KFreon** [comment]
It won't create a MOD, it'll create mod jobs in the modmaker window.
I can't really test this too well since I don't know how to do mesh modding. 
I guess it'd work for textures too. I'll see what I can do test-wise, but I don't see anything weird in the code.

**Comment by ghost** [comment]
I'll double-check, but from memory, jobs didn't appear in the window, either -- I would have noticed that, lol.

**Comment by ghost** [comment]
Just re-verified. This definitely doesn't work. After selecting the unmodded and modded PCCs, nothing appears in MM's main window. It just lies empty. This should be easy for you to replicate, K.

No error or debug feedback at all. Simply nothing happens.

**Comment by ghost** [comment]
@Kfreon -- Can verity that this still doesn't work in r733. No error or debug output, nothing in the MM window. Nothing at all happens after selecting the files to compare.

**Comment by KFreon** [comment]
Whoops. Was refreshing the wrong thing :)

Now, I've just realised that there's a rather interesting difference that I apparently didn't think too much about.

This grabs the two PCC's, finds their differences, and creates a SINGLE job for the whole bunch.
That's right, multiple things happen in a single job.
I'm guessing this isn't particularly desirable. For now, it's staying that way, but I think it's going to need to change.

EDIT!!! Scratch all that. I found more problems that necessitate I fix it now...
So what's going to have to happen is the modified PCC MUST BE in its place. It can't be in some other folder, it HAS to be where it's supposed to be. This is so it can get the pathing correct.

**Comment by ghost** [comment]
@KFreon -- This seems a bit weird, since people used to use this feature before it was removed, and I don't remember lots of problems being reported. I'm... also not quite sure this solution works.

So, the modder has their vanilla (or whatever) PCC in the base game. Then they have their modded PCC (with the same name) somewhere else. So, they have to move the modded PCC in the base game, and then put the vanilla one... somewhere else? That seems... backwards.

Why does pathing matter when you're simply comparing two files? Esplain to the non-coder, plz, lol.

**Comment by KFreon** [comment]
I basically copied the code verbatim from the old version, so it should function the same. It's just I can't code properly :)

Here's how I see a mod like this happening.
You want to mod a file, so you copy it somewhere else so you have a backup.
You mod the file.
You want to make a mod to share, so you use PCC Compare with the modified file IN PLACE.

The modified has to be in the correct location because now we can mod DLC files. The script defaults to basegame, and this wasn't a problem in the past because we couldn't mod DLC.
It can be the other way around (vanilla in place) but it makes more sense to me to be the other way around.

**Comment by ghost** [comment]
@Kfreon -- Okay, this now works great in r735. BUT!

There needs to be better directions in the choose 1st/2nd PCC windows for the user. Nothing told me that the modded PCC _needs_ to be in the proper install location. I know this is what you told me, and I now see why -- b/c the script needs the proper path. 

The user won't know this, though, so we need text at the top of the "choose PCC" windows to say something that's a bit clearer:

> Select base PCC -- May be located inside or outside the game directory

I'd remove the "unmodified" part, b/c it actually isn't necessary. I could start with a modified PCC, as long as those same modifications are also in the other PCC -- along with the other changes that I'm actually trying to "record" into the mod file. In other words, the file doesn't actually have to be vanilla. It all depends on what changes the modder is trying to record.

The description of the modded file should look like this:

> Select modified PCC -- Must be located in the proper game directory

Other than that, awesome :)

**Comment by KFreon** [comment]
Made a new window to better display the situation.
![image](https://cloud.githubusercontent.com/assets/7845997/13167874/fdac006a-d722-11e5-934c-e10c85402527.png)

Nice and simple. I could go all out on progress, but that's too much effort. When it's done, the window just closes.

Also something rather interesting I noticed, this only works on ME3 right now. Should it be expanded or does that not work?

**Comment by ghost** [comment]
@KFreon -- Ha, that's perfect. I was going to suggest  a new box like that, but didn't want to create more work for you, lol.

As for your other question... hm. It can't hurt. The Package Editors for both prior games are pretty slim on features at the moment, so I don't think there's a great likelihood of it being used, BUT, I think all us modders hope Sir/Heff can find time to expand them. If that happens, then it very well might get used.

Deager and Fob both actually have some very simple mods out for ME2 right now that could always be implemented as a mod file rather than DLC mods as they've currently done. Options are good :)

**Comment by KFreon** [comment]
Hrm. I get that, but it is rather a bit more work to get the other games into it, cos you'd need a way of telling the tool which game the PCC's belonged to. 

That can just be a dropdown I guess. Should it be?

**Comment by ghost** [comment]
Sure, a dropdown works.

And, ME1 doesn't even have PCCs. I'm actually sort of surprised you can even implement it for ME1 since the file structure for the game is so different.

**Comment by KFreon** [comment]
Ha well maybe I can't :P 
For now, I'll leave it at ME3 anyway.

**Comment by ghost** [comment]
Can verify that the new box works perfectly in r738. New jobs are made and can be saved into a mod file. Even tested with the modded file located inside a DLC mod and job/mod generation still works great. 

One question -- do we even have mod files for ME1 and ME2? I know there's no mod creation tools available for either. Not in the Package or Sequence Editors. 

Installing textures with .mod files is deprecated at this point and something we aren't supporting. No more .mod generation inside TPF Tools.

So, if we aren't going to implement the PCC Compare Feature for either game, then it's probably safe to strip out all ME1/2 GUI features in MM and just say it's an ME3 tool. Leaving those features in gives users the impression that there _are_ mod files for ME1/2 -- or that they can be created.

**Comment by KFreon** [comment]
I don't know if there's mesh or anything for ME1 and 2 mod-wise.

I don't really want to do anything to Modmaker, and fortunately I don't have to.
It's already pretty game agnostic, just the game indicators (which don't affect anything) and the Game Version dropdown, which shouldn't be a problem. 

I can have it default to ME3 if you want, but unless there's actually an issue with it, I don't want to risk more issues :)

**Comment by ghost** [comment]
Okie doke. Pretty sure it defaults to ME3 already, so I think we're okay.

**Comment by ghost** [comment]
This issue is back in rev748.

![mm_pcccomp](https://cloud.githubusercontent.com/assets/13645804/14358575/766c10a4-fca2-11e5-84bf-a7825a160d62.PNG)

It's possible that the fix for #242 affected it.

**Comment by SirCxyrtyx** [comment]
I can't replicate this. Can you send me the files you are using?

**Comment by ghost** [comment]
@SirCxyrtyx -- Crap, I just realized I forgot to revert a file when I tested this. I compared two vanilla files to each other, lol. So, obviously no differences to create jobs!

If it's not too much work to toss in some debug output if this happens, it would probably be helpful :)

Feel free to re-close.

**Comment by SirCxyrtyx** [comment]
Wondered if that might be the problem. :wink:  I'll stick in something if there are no differences found

**Comment by ghost** [comment]
Something else I'll comment on here; and I'll actually stick it on the forums, as well, since it'll be a dev issue to discuss in the future.

Now that I was finally able to install .mods again, here's some more detailed info about how MM will handle DLC mods and .mod files:
- Installing to a DLC .mod works, as long as the .mod file was explicitly created for it. Finally just got to test this :)
- MM does add to the name list.
- MM does NOT add to the export list. In other words, it cannot insert cloned objects into the file. I think it's save to assume it cannot add to the import list, either.

It seems that PCC Compare should be able to tell if exports have been added, but my guess is that's a feature that will take a while to implement :)

**Comment by SirCxyrtyx** [comment]
Yeah, currently all it does is replace the data of an export and add names. It can't handle added exports, added imports, or even changed export metadata.

**Comment by ghost** [comment]
@SirCxyrtyx -- Oooh, metadata? Like what? Links and such? Like to new exports or new imports?

Oh... well, yeah, that would make sense. I didn't even think about that. That's... hugely problematic, actually.

I wouldn't say it's entirely useless for content modding, but if re-linking doesn't work that's a significant constraint.

So that means... new names and modded export properties, basically? That correct?

**Comment by SirCxyrtyx** [comment]
It won't change Class, link, name, Index, archetype, Superclass, or Flags. It only does a binary replace of the data that shows up in the Hex Editor tab of PCCEditor2.

**Comment by ghost** [comment]
That's very handy to know. I'll incorporate that into the wiki.

Thanks for the clarification :)
