### ISSUE TITLE
TPF Tools, V8U8 Normal MIP detection

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#141]
Seems to be a bug with the new image library, I think.

TPF Tools thinks that this Normal map (made by Otte) lacks mips. However, opening the extracted file in DirectX Texture Tool and GIMP ensures that it does have mips:

![tpft_normals_mipbug](https://cloud.githubusercontent.com/assets/13645804/12304704/c5b28bc0-b9e5-11e5-87cc-62809808892f.PNG)

Display of extracted normal is also wonky in GIMP and can't be opened in Pain.NET , but this isn't particularly unusual. All DDS files that aren't simple GUI diffs can be hit or miss.

**Comment by KFreon** [comment]
Seems to be fixed...Bit strange though.

**Comment by ghost** [comment]
And, as an addendum to this -- Texplorer thinks the same thing and refuses to let me insert the new texture manually.

Of course it uses the new library, so, makes sense.

**Comment by ghost** [comment]
One more follow up. This is indeed happening with every single normal. I've tried several TPFs and TPF Tools thinks the MIPs are wrong for every one.

**Comment by ghost** [comment]
FYI, retested this with r731, and the normals are indeed recognized properly. GIMP still opens the normal and it appears all black and white as in the screenshot, but I can't say if that's a problem with GIMP, the image library, or both.

Issue appears to be resolved.

**Comment by KFreon** [comment]
FYI Gift, it's just the way various things handle colour channels. 
Shouldn't matter. _touch wood_

**Comment by ghost** [comment]
Verified fixed, r733.
