### ISSUE TITLE
Texplorer, Add DLC to Tree broken

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#142]
A couple things with this:
1. The tool needs to be clearer as to which folder the user should select. The root DLC folder (DLC_CON_XXX) or the DLC's CookedPCConsole folder. Neither work, but I was confused as to which to pick.
2. Doesn't work. Debug output says the files are scanned, but there's no action in Texplorer's progress bar, and the tool seems to freeze. Neither the tree nor the thumbnail cache gets modified:

![tex_adddlc](https://cloud.githubusercontent.com/assets/13645804/12309146/f33775a2-b9fd-11e5-87b8-16988eee1ff6.PNG)

Submitting a separate issue that will technically be a feature request, but that should really be implemented along side this feature.

**Comment by KFreon** [comment]
Might be fixed, again can't really do much testing here.

**Comment by ghost** [comment]
There's a chance this is linked to the same issue I just reported with Texplorer not saving into DLC files properly when using the "Add Bigger Image". I'm not sure it's detecting DLC pathing correctly.

**Comment by starkgate** [comment]
I tried adding the recently updated EGM to my tree, it didn't work either. It started fine and scanned 80/86 entries correctly before stalling. Forgetti had no problems building a tree from scratch, so the problem must come from me3explorer.
I don't really have much more information to give, VS doesn't say anything, nor does the debug window.
http://me3explorer.freeforums.org/post22249.html#p22249

EDIT : Interestingly, I could close Texplorer without receiving a warning about a running process, and after rebooting it the new entries did appear. Maybe it is just a graphical glitch ?

**Comment by ghost** [comment]
Looks like this isn't taking into account whether a DLC is extracted. I purposefully tried to add an unextracted DLC and it told me it was successfully added. We probably don't need a new dialog window, K, but some debug output and some text by the lower left progress bar saying "Unextracted DLC can't be added" or something would be good.

---

Re-testing with an extracted DLC and the files seem to scan fine. But, when I clicked in the Search box to search for a new texture to ensure it really was scanned properly, I get this error:

![adddlc_error](https://cloud.githubusercontent.com/assets/13645804/14025708/a9985c4a-f1ac-11e5-92c2-def4f31a4edd.PNG)

Closing the tool and reopening solves the problem, and I can verify that the textures from the newly scanned files were indeed added properly.

**Comment by ghost** [comment]
1. Add DLC to Tree now knows if DLC is extracted. Fixed. Yay! @KFreon, keep this in mind and be very careful when fixing issue #266.
2. Error message fixed. 

Verified in r746.
