### ISSUE TITLE
Texplorer, new feature, "Choose Destination TFC"

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#143]
When it comes to DLC Mods, the new "Add DLC to tree" feature that's a WIP will be hugely helpful to both users and modders. However, modders really need another feature for this to be practical:

_Modders need to be able to specify the destination TFC for texture replacements. Namely, their DLC Mod's TFC._

Right now, all texture replacements by default dump into CustTextures0.tfc.This is fine for the base game and BW DLC, and it's initially fine for DLC mods. 

To quickly review, this is how modders create a custom DLC mod TFC:
1. Ensure no CustTex currently exists in the main cooked
2. Run a scan to build the mod to build into the tree
3. Replace all the desired textures via Texplorer to generate a CustTex
4. Cut/paste CustTex into the DLC mod
5. Rename CustTex for the DLC mod (Textures_DLC_CON_THANEMOD)
6. And, finally, repoint all affected PCC's by hex-editing the name list (changing CustTex to the new name)

All this works beautifully. The problem comes in when you need to add a new file and texture to your DLC mod. And, the problem is this:

**Even if you rescan the DLC into a new tree, any new texture replacements will go into CustTex, _not into the DLC mod's existing TFC._**

Modders need to be able to add new files and rescan (only) the DLC to add them to the tree. Then they need to be able to specify any texture replacements affecting those new files are built into their mod's existing TFC, and not into a new/existing CustTex. 

Currently, to add a new files and textures to their DLC mod, modders have to not only do a treescan from scratch, but they have to create a brand new TFC from scratch, as well. Which means any time _a_ new texture must be added, _every_ texture must be **re**added.

So, yeah. It's a pain. We do it, but it's a pain.

I'm guessing this would be a good bit of work since Texplorer by default dumps everything into CustTex, but it's a huge disadvantage for DLC mod creators.

I'm open to suggestions on how to achieve it, but it seems like we either need to allow modders to choose a destination TFC. Or, we have to make Texplorer smarter, so it recognizes a DLC mod, detects whether there's a TFC already present, and then knows whether to dump new textures into that TFC or not.

**Comment by KFreon** [comment]
An interesting idea.

Some things to consider:
- When you do an image replace in Texplorer, that texture can live across DLC's and basegame. At the moment, it copies the image data to CustTextures0.tfc and sets all relevant pcc's to reference that one location. How would you want it to behave now?
- If you had the tfc selectable, would it default to the most recently used one, or CustTextures0?

My biggest concern is that generally Texplorer doesn't care where the PCC is, and thus just dumps it in the big tfc. If it had to start thinking about which tfc to use, I can see that being a huuuge amount of work in the back end. 
I'm also not sure that's how we want it to work for users either. I mean, when a user gets BO or something, then installs some textures, then gets a BO update, BAM...texture updates gone.

**Comment by ghost** [comment]
Your first question:
Texplorer already provides the option to select only certain PCCs. That's the only option that's needed. The modder would only apply that new texture to the PCC in their DLC mod. All that's required is that this feature works properly.

Your second question:
It should probably default to CustTex. This is the safest way for users, so they don't inadvertently mess something up.

And, yeah. I'm pretty sure it will be a large amount of work. It would also be _enormously helpful_ to modders if you could do it.

I don't see it as a problem for users. They don't care where the textures are stored, they only care whether they are applied. As long as CustTex is the default, I think it would be ok. We could even put some warning box attached to the setting that says "this is for DLC Mod Creators only!" or something.

The problem I _do_ see is that a system like this makes the thumbnail irrelevant, but actually... we already have this problem. Textures can already be different in different PCCs, since we have the ability to select/deselect the,. Texplorer simply shows the most recent replacement, correct? There's no guarantee it's what every PCC uses.

Kinko might also have some ideas about this. He adds lots of new textures for Galaxy Map Mod, and has a complex system in place for how he manages all his DLC trees, etc.

**Comment by KFreon** [comment]
I've done this as far as I can tell. 
It should behave as the old cache does.

Changing the cache only works until the toolset is closed. Change cache setting is in Texplorer. Yet another new button...
The old toolset makes me sad :(

**Comment by ghost** [comment]
This works _beautifully_, @KFreon. Excellent work. Just tested the following workflow:

Add DLC to Tree > Change Custom TFC > Change texture in DLC mod > Save texture

This results in the texture change being saved to the newly integrated DLC mod's TFC, just as intended. Wewt.

One drawback of this method, is that if you re-add the DLC to the tree (b/c you need to build in a new PCC), and you've swapped out textures in the past, it results in multiple copies of those textures with the same name at different offsets. They all can be edited and directed to the new TFC, but modders will have to make sure they don't get confused about which one is currently being referenced.

**Comment by KFreon** [comment]
That would be because it's now a "different" texture. Can't think of a way around in unfortunately, not simply anyway.

**Comment by ghost** [comment]
@KFreon -- Yep, I realize that. It's no problem, just wanted to give folks a heads up :)
