### ISSUE TITLE
TPF Tools, TOC DLC Warning

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#145]
Similar to ModMaker, TPF Tools also gives an extraction warning on TOC, which is already past the point of no return, in my eyes. This warning should be given before the process begins, so the user can stop it _safely_.

In addition, it also warns that all DLC are about to be extracted and is not detecting when DLC are _already_ extracted, which is confusing to the user.

**Comment by KFreon** [comment]
As I noted in the other one, TPFTools now won't notify you at all.
It'll just update as it's told. If you don't have DLC's extracted, you've done something wrong.

**Comment by ghost** [comment]
That makes sense for TPF Tools. DLC must already be extracted, since TPF Tools can't work w/o a Texplorer tree. Texplorer would have already given the warning. ModMaker, on the other hand, doesn't require a Texplorer tree to function.

**Comment by ghost** [comment]
Verified removed in r733.
