### ISSUE TITLE
Suggestion, TPF Tools, "Texture Name" field

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#146]
TPF Tools would benefit from a "Texture Name" field on the right side that would be filled in when a texture is selected. Place right above "Image Format" would make the most sense.

Currently, selecting/deselecting PCCs for a texture removes the highlighting for the corresponding thumbnail on the left. Therefore, if there are a lot of PCCs and it takes you a while to figure out which ones you want to use, you may have _cough_ forgotten which texture you were working on, lol.

**Comment by KFreon** [comment]
Wow it does deselect it. 
It's supposed to keep the selection so you know which is which.
I really don't want to duplicate information, especially since that information can be semi-duplicated anyway when there's tree duplicates in there.
I'll try and make it keep the selection visible.

**Comment by ghost** [comment]
That would certainly work, too. Just some way to know which texture you've been working on and which is next.

**Comment by ghost** [comment]
Verified fixed in rev731.
