### ISSUE TITLE
TPF Tools Normals handling bug

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#147]
So, this is an interesting one.

This might be tied to the normals MIPs issue that I previously reported. 

Autofix can be used on these normals, and when it is, the tool will supposedly install them. I say supposedly, b/c after checking on an issue with some Ashley texture replacements, I eventually tracked this down:

![tpf_normsbugpng](https://cloud.githubusercontent.com/assets/13645804/12334307/32fd1d76-baae-11e5-9466-d558f5053d72.PNG)

Looking at the EDI files I already worked on, the same thing is happening. The tool is changing the texturegroup to Shadowmap, saying that it's installing the normal correctly, but it remains pointing to the vanilla TFC, rather than CustTex. Diffs and Specs are fine; Norms are the problem...as usual, it seems. Blarg.

I'm going to try editing the PCC by hand to point to the new tex file and see if that fixes the issue.

**Comment by ghost** [comment]
Okay, hand editing the exports to repoint to the correct TFC doesn't work. My best guess with that is b/c it's pointing the the wrong offset.

There's also a chance we've got two issues rolled into what I'm experiencing in game right now:
1. Autofix isn't fixing normals correctly. This would explain the unpleasant visual artifacts I'm seeing right now, lol.
2. installation post-autofix is wonky. This would explain the screenshot above and the infinite loads/freezes I'm getting when trying to load certain levels in game.

**Comment by ghost** [comment]
Something else that might be helpful.

When autofix is used on these normals and they are extracted and then reloaded into TPF Tools, they look like this:

![tpf_badautofix](https://cloud.githubusercontent.com/assets/13645804/12335301/57f69e0e-bab3-11e5-9c40-fd1adc61776f.PNG)

When the original TPF containing this normal is loaded in TPF Tool, it looks as it should.

**Comment by ghost** [comment]
K, just wanted to clarify something about my last post. 

After the autofix/extraction, that norm was immediately re-loaded in TPF Tool with the other two textures it's depicted with. It wasn't opened (or edited) by any other program.

**Comment by KFreon** [comment]
Think this is fixed, and I'm going to close it but I expect it to be reopened.

**Comment by starkgate** [comment]
I'm adding some information here, as I don't think it is necessary to open a new issue for it. Norm files do seem to be autofixed differently in 728. The first norm file in the picture below has been autofixed through 728 then loaded in 718. Same with some diff and spec, but those do not seem to pose problem.
![capture](https://cloud.githubusercontent.com/assets/12874678/12374428/449c5382-bc9b-11e5-89e3-db7c53e94165.PNG)
Test file : http://filebin.ca/2ThBFzJp0fSh

**Comment by ghost** [comment]
Verified working in r733. Yay!
