### ISSUE TITLE
rev728 Autofixing 0 MIPS textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#150]
Autofixing 0 MIPS textures results in a DDS containing only the alpha of the said texture, not the RGB layer (hence the problem .with the thumbnail I suppose, see #116 ).
Test files : http://filebin.ca/2TguJ3uVfZhx

**Comment by KFreon** [comment]
I assume by this you mean that black one?

**Comment by starkgate** [comment]
Yes, sorry for not being clear. I'm on the chat btw :)

**Comment by KFreon** [comment]
A curious thing this one, when I do it to that texture in Windows 7 and save to DXT1, the preview works fine and the top mip works fine, but the lower mips are alpha only.
That the same for you?

**Comment by KFreon** [comment]
OK I think I finally fixed this. Forgot that Windows 7 can still use WIC images. 
So basically, if it works in Windows 8/10, it works in Windows 7 except for native DDS loading.

**Comment by starkgate** [comment]
Yup, works indeed in 729. Only thing, the alpha is completely white, as opposed to the default file. I don't know if this is important, like if it will impact the render in game.
![sans titre](https://cloud.githubusercontent.com/assets/12874678/12376866/050121f8-bd09-11e5-95e6-9ae34149838b.png)

**Comment by KFreon** [comment]
Hrm that is bad, but I can't replicate it.
When I load that texture and save it back as DXT5, I still get the alpha.

**Comment by starkgate** [comment]
What happens if you try to simply autofix the 'No MIPS' DDS, then load the autofixed DDS in Photoshop or equivalent to see the alpha ? I tried it again with 731, the problem is definitely there for me.

**Comment by KFreon** [comment]
Just tried it in Photoshop and got back the alpha I expected :(

**Comment by KFreon** [comment]
Just tried this again and still couldn't repeat it on Windows 7 VM.
Maybe it's fixed cos of the new build.
When I get it out, let me know.

**Comment by starkgate** [comment]
Nope, still the same problem. Really strange. If somebody else could do some testing too, would be much appreciated !

**Comment by starkgate** [comment]
Still the same in rev743, this may be related to #245
