### ISSUE TITLE
rev728 Regenerating non-already existent thumbnail in Texplorer

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#151]
Trying to regenerate the thumbnail still results in a problem, which gets silently ignored : Texplorer shows a nice "Thumbnail Regenerated!", although VS outputs the log below, and no thumbnail actually gets generated.

Log : http://pastebin.ca/3335753

**Comment by KFreon** [comment]
Looks like that bottom bit says something like "Can't access because another thread is accessing file: blah"? 
Does that file exist?

**Comment by starkgate** [comment]
Nope, it's the same problem we had earlier, where Texplorer tries to delete the thumbnail before regenerating it, even if it does not already exist (or has been deleted). I changed the title, as I suppose 'normal' setups will have no problem regenerating thumbnails.

The bottom bit says "Impossible to find a part of the path 'D:\Bibliothèques\P2P\ME3Explorer-r728\ME3Explorer\bin\Debug\Exec\ThumbnailCaches\ME3ThumbnailCache\KroInd_MetalTrim_01_Emis_MSK_1980454538.jpg'". There's no allusion to another thread.

**Comment by starkgate** [comment]
Ok, so now the thumbnails do get created. Except the corresponding JPGs are broken, they can't be opened by anything (thus still no preview in Texplorer).
Test file : http://filebin.ca/2TkoNvrQoT7U

I also tried to click the "Regenerate thumbnails" button, which resulted in a slew of errors, from VS and me3explorer.
VS spams the following lines, probably one per thumbnail :
A first chance exception of type 'System.NullReferenceException' occurred in CSharpImageLibrary.exe
A first chance exception of type 'System.NullReferenceException' occurred in CSharpImageLibrary.exe
A first chance exception of type 'System.NullReferenceException' occurred in CSharpImageLibrary.exe
A first chance exception of type 'System.NullReferenceException' occurred in CSharpImageLibrary.exe
A first chance exception of type 'System.NullReferenceException' occurred in CSharpImageLibrary.exe
A first chance exception of type 'System.NullReferenceException' occurred in CSharpImageLibrary.exe
A first chance exception of type 'System.NullReferenceException' occurred in CSharpImageLibrary.exe

A part of me3explorer's log :
[log.txt](https://github.com/ME3Explorer/ME3Explorer/files/93278/log.txt)

Now, I don't know if it is worth it to take the effort and fix this. I personally don't take care about thumbnails as long as I can double click and get a preview. Most people won't even change versions, so it won't pose a problem generally.
The only thing I didn't (and can't, because it's broken, hint hint FemShep^^) test, is if Version Switcher removes these Thumbnails when it switches revision (which is likely, I think it removes them and the trees). That would be the only reason to fix this bug, as people will probably want to update through it, because it is easy.

**Comment by starkgate** [comment]
Worthy to note that all thumbnails aren't broken, when I look into the ThumbnailCache folder, there are quite a bit that are just fine. I can't see what they have in common though : some norms work, others don't, same goes with spec, diff etc. I can send you a bunch of them if needed.

**Comment by KFreon** [comment]
I don't know much about the norms not working, but the null errors are fixed, and with them, more than likely the thumbs will be fixed too.

**Comment by starkgate** [comment]
Ok, 'Regenerate all thumbnails' works nicely in rev730. Regenerating individual thumbnails still poses some problems : the thumbnail does get correctly generated in the Thumbnail folder (no corrupted jpg), but the thumbnail itself, in Texplorer, is all white (ie it goes from placeholder picture to white). Rebooting me3explorer and Texplorer doesn't change anything to it. Note that the thumbnails regenerated through 'Regenerate all thumbnails' are displayed correctly.

**Comment by KFreon** [comment]
Interesting...
Once again, this doesn't happen for me, so I can only guess.
But I think maybe it's fixed now?

**Comment by starkgate** [comment]
> But I think maybe it's fixed now?

I don't see any new rev, where would it be fixed ?

**Comment by KFreon** [comment]
[Should be here?](http://me3explorer.freeforums.org/rev-730-rc-t2235.html)

**Comment by starkgate** [comment]
Ehm. My message above explicitly says 'in rev730' ^^. You shouldn't do drugs K, they're bad^^.

**Comment by KFreon** [comment]
Oh man...The derp is real. 
But I'm sure I wrote this, then changed something.
Maybe I'm crazy...

**Comment by starkgate** [comment]
My statement from 730 is still valid for 731 : individually regenerated thumbnails appear all white, although they are correct when I view them from the thumbnail folder. Maybe an alpha problem ? Although I don't know why total thumbnail rebuild would work and individual wouldn't...

**Comment by KFreon** [comment]
Its most likely due to the image not being found or something so it gets a blank square.
I don't know why though...

**Comment by starkgate** [comment]
Do you use the same function for individual and general rebuilding ? I checked, names seems correct (ie same naming format for individual and general), permissions are set equally, so I really don't know what could go wrong.
Interestingly, individually regenerating the thumbnails of textures already regenerated by general rebuilding (if that makes sense^^) does work correctly. So...

**Comment by KFreon** [comment]
Is this still happening Creeper?

**Comment by starkgate** [comment]
Nope :). Sometimes the regenerated thumbnail can be displayed white shortly, but refreshing the page or regenerating another fixes it. So, yes, consider it to be fixed.

**Comment by KFreon** [comment]
Oh good :D
