### ISSUE TITLE
rev 729 TPF/DDS tools 3.0 not replacing normal maps 

### ISSUE THREAD

**Issue by forgetti** [ME3Explorer/ME3Explorer#152]
ok so the autofixing and that works fine now but TPF/DDS tools fails to replace Normal maps
![all textures say installed](https://cloud.githubusercontent.com/assets/16586137/12377102/dba06662-bd75-11e5-9ff9-39757922af54.JPG) sure it says all 10 texture files installed but when I go to check that they actually did install I am met with a texture that still has the stock normal map
![2016-01-17_00001](https://cloud.githubusercontent.com/assets/16586137/12377111/068c9b5c-bd76-11e5-8e8a-329bc1a626ce.jpg)

I've tested this with various other texture files as well but it never replaces the normal map. I've only tested this for mass effect 2 so I can't speak for if it happens on mass effect 3

here is the file where I initially uncovered the issue: https://mega.nz/#!fY00XCaD!C42LXHPaf_dj2WW3beDBMk7cMQ5T7iRC8thLX2ZLEiM

and finally the debug log:

12:05:48 AM:  -----New Execution of TPF/DDS Tools 3.0-----
12:05:48 AM:  Build Version: 1.2.729.0
12:05:48 AM:  Using file: DebugOutput.txt
12:05:48 AM:  Using debug file: DebugOutput.txt
12:05:48 AM:  Using ResIL dll at: C:\Users\Viking\Desktop\ME3Explorerplasma edition\ResIL.dll
12:05:48 AM:  In CheckGameState, checkin ur gamez.
12:05:48 AM:  Using ResIL dll at: C:\Users\Viking\Desktop\ME3Explorerplasma edition\ResIL.dll
12:05:48 AM:  Message from MEExDirecs: Found installation path from registry. Using cooked directory: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect\BioGame\CookedPC
12:05:48 AM:  Setting indicators...
12:05:48 AM:  Path of file to check if game files present: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect\MassEffectLauncher.exe
12:05:48 AM:  BIOGame Path = C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect\BioGame  found using: ME0Directory Class.
12:05:48 AM:  Message from MEExDirecs: Found installation path from registry. Using cooked directory: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC
12:05:48 AM:  Setting indicators...
12:05:48 AM:  Path of file to check if game files present: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\MassEffect2Launcher.exe
12:05:48 AM:  BIOGame Path = C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame  found using: ME1Directory Class.
12:05:48 AM:  Message from MEExDirecs: Found installation path from registry. Using cooked directory: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect 3\BIOGame\CookedPCConsole
12:05:48 AM:  Setting indicators...
12:05:48 AM:  Path of file to check if game files present: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect 3\BIOGame\PCConsoleTOC.bin
12:05:48 AM:  BIOGame Path = C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect 3\BIOGame  found using: ME2Directory Class.
12:05:48 AM:  Successfully deleted existing temp files.
12:05:48 AM:  Setting up tree: 1 using PathBIOGame: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect\BioGame
12:05:48 AM:  Tree: 1 is not null.
12:05:48 AM:  Setting up tree: 3 using PathBIOGame: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect 3\BIOGame
12:05:48 AM:  Tree: 3 is not null.
12:05:48 AM:  Couldn't find main game files for ME1.
12:05:48 AM:  Setting up tree: 2 using PathBIOGame: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame
12:05:48 AM:  Tree: 2 is not null.
12:05:48 AM:  Couldn't find main game files for ME3.
12:05:48 AM:  Found main gamefiles for ME2 at  C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame
12:05:48 AM:  ME1 tree not found.
12:05:48 AM:  ME3 tree not found.
12:05:48 AM:  Creating tree: 2. Found: 3570 scannable gamefiles.
12:05:48 AM:  Advanced ME2 Tree features detected.
12:05:49 AM:  ME2 tree found.
12:05:54 AM:  Matching hashes...
12:05:54 AM:  Tree Texes: 8166
12:05:54 AM:  Checking for File Duplicates...
12:05:54 AM:  Searching for Tree duplicates...
12:05:54 AM:  Finished searching for duplicates.
12:05:56 AM:  Textures loaded = 1
12:05:56 AM:  Num valid: 1
12:05:56 AM:  -----New Execution of Texplorer 2.0-----
12:05:56 AM:  Using: 4 threads.
12:05:56 AM:  Checking if games are present...
12:05:56 AM:  In CheckGameState, checkin ur gamez.
12:05:56 AM:  Using ResIL dll at: C:\Users\Viking\Desktop\ME3Explorerplasma edition\ResIL.dll
12:05:56 AM:  Message from MEExDirecs: Found installation path from registry. Using cooked directory: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect\BioGame\CookedPC
12:05:56 AM:  Setting indicators...
12:05:56 AM:  Path of file to check if game files present: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect\MassEffectLauncher.exe
12:05:56 AM:  BIOGame Path = C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect\BioGame  found using: ME0Directory Class.
12:05:56 AM:  Message from MEExDirecs: Found installation path from registry. Using cooked directory: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC
12:05:56 AM:  Setting indicators...
12:05:56 AM:  Path of file to check if game files present: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\MassEffect2Launcher.exe
12:05:56 AM:  BIOGame Path = C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame  found using: ME1Directory Class.
12:05:56 AM:  Message from MEExDirecs: Found installation path from registry. Using cooked directory: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect 3\BIOGame\CookedPCConsole
12:05:56 AM:  Setting indicators...
12:05:56 AM:  Path of file to check if game files present: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect 3\BIOGame\PCConsoleTOC.bin
12:05:56 AM:  BIOGame Path = C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect 3\BIOGame  found using: ME2Directory Class.
12:05:56 AM:  Found installation path from registry. Using cooked directory: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect\BioGame\CookedPC
12:05:56 AM:  Found installation path from registry. Using cooked directory: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC
12:05:56 AM:  Found installation path from registry. Using cooked directory: C:\Program Files (x86)\Mass Effect Trilogy\Mass Effect 3\BIOGame\CookedPCConsole
12:05:56 AM:  Installing mod:  HMF_MIR_LGTa_Norm | 1/1 mods completed.
12:05:56 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_END_Vixen_00.pcc
12:05:56 AM:  File already decompressed. Reading decompressed data.
12:05:56 AM:  Reading Names...
12:05:56 AM:  Reading Imports...
12:05:56 AM:  Reading Exports...
12:05:56 AM:  Prefetching Export Name Data...
12:05:56 AM:  Now replacing textures in texture: HMF_MIR_LGTa_Norm
12:05:56 AM:  Replacement complete. Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_END_Vixen_00.pcc
12:05:56 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_END_Vixen_00.pcc
Refreshing header to stream...
12:05:56 AM:  Opening filestream and writing to disk...
12:05:56 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_END_Vixen_01.pcc...
12:05:56 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_END_Vixen_01.pcc
12:05:56 AM:  File already decompressed. Reading decompressed data.
12:05:56 AM:  Reading Names...
12:05:56 AM:  Reading Imports...
12:05:56 AM:  Reading Exports...
12:05:56 AM:  Prefetching Export Name Data...
12:05:56 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_END_Vixen_01.pcc
Refreshing header to stream...
12:05:56 AM:  Opening filestream and writing to disk...
12:05:56 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioD_EndGm1_110ROMMirranda.pcc...
12:05:56 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioD_EndGm1_110ROMMirranda.pcc
12:05:56 AM:  File already decompressed. Reading decompressed data.
12:05:56 AM:  Reading Names...
12:05:56 AM:  Reading Imports...
12:05:56 AM:  Reading Exports...
12:05:56 AM:  Prefetching Export Name Data...
12:05:56 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioD_EndGm1_110ROMMirranda.pcc
Refreshing header to stream...
12:05:56 AM:  Opening filestream and writing to disk...
12:05:56 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_Vixen_00.pcc...
12:05:56 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_Vixen_00.pcc
12:05:56 AM:  File already decompressed. Reading decompressed data.
12:05:56 AM:  Reading Names...
12:05:56 AM:  Reading Imports...
12:05:56 AM:  Reading Exports...
12:05:56 AM:  Prefetching Export Name Data...
12:05:56 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_Vixen_00.pcc
Refreshing header to stream...
12:05:56 AM:  Opening filestream and writing to disk...
12:05:56 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_Vixen_01.pcc...
12:05:56 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_Vixen_01.pcc
12:05:56 AM:  File already decompressed. Reading decompressed data.
12:05:56 AM:  Reading Names...
12:05:56 AM:  Reading Imports...
12:05:56 AM:  Reading Exports...
12:05:56 AM:  Prefetching Export Name Data...
12:05:57 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioH_Vixen_01.pcc
Refreshing header to stream...
12:05:57 AM:  Opening filestream and writing to disk...
12:05:57 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_HEN_VT\CookedPC\BioA_ZyaVtl_100.pcc...
12:05:57 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_HEN_VT\CookedPC\BioA_ZyaVtl_100.pcc
12:05:57 AM:  File already decompressed. Reading decompressed data.
12:05:57 AM:  Reading Names...
12:05:57 AM:  Reading Imports...
12:05:57 AM:  Reading Exports...
12:05:57 AM:  Prefetching Export Name Data...
12:05:57 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_HEN_VT\CookedPC\BioA_ZyaVtl_100.pcc
Refreshing header to stream...
12:05:57 AM:  Opening filestream and writing to disk...
12:05:57 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioD_ProNor.pcc...
12:05:57 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioD_ProNor.pcc
12:05:57 AM:  File already decompressed. Reading decompressed data.
12:05:57 AM:  Reading Names...
12:05:57 AM:  Reading Imports...
12:05:57 AM:  Reading Exports...
12:05:57 AM:  Prefetching Export Name Data...
12:05:57 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioD_ProNor.pcc
Refreshing header to stream...
12:05:57 AM:  Opening filestream and writing to disk...
12:05:58 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioP_ProCer.pcc...
12:05:58 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioP_ProCer.pcc
12:05:58 AM:  File already decompressed. Reading decompressed data.
12:05:58 AM:  Reading Names...
12:05:58 AM:  Reading Imports...
12:05:58 AM:  Reading Exports...
12:05:58 AM:  Prefetching Export Name Data...
12:05:58 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\CookedPC\BioP_ProCer.pcc
Refreshing header to stream...
12:05:58 AM:  Opening filestream and writing to disk...
12:05:58 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_CON_Pack02\CookedPC\BioH_END_Vixen_02.pcc...
12:05:58 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_CON_Pack02\CookedPC\BioH_END_Vixen_02.pcc
12:05:58 AM:  File already decompressed. Reading decompressed data.
12:05:58 AM:  Reading Names...
12:05:58 AM:  Reading Imports...
12:05:58 AM:  Reading Exports...
12:05:58 AM:  Prefetching Export Name Data...
12:05:58 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_CON_Pack02\CookedPC\BioH_END_Vixen_02.pcc
Refreshing header to stream...
12:05:58 AM:  Opening filestream and writing to disk...
12:05:58 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_CON_Pack02\CookedPC\BioH_Vixen_02.pcc...
12:05:58 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_CON_Pack02\CookedPC\BioH_Vixen_02.pcc
12:05:58 AM:  File already decompressed. Reading decompressed data.
12:05:58 AM:  Reading Names...
12:05:58 AM:  Reading Imports...
12:05:58 AM:  Reading Exports...
12:05:58 AM:  Prefetching Export Name Data...
12:05:58 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_CON_Pack02\CookedPC\BioH_Vixen_02.pcc
Refreshing header to stream...
12:05:58 AM:  Opening filestream and writing to disk...
12:05:58 AM:  Now saving pcc: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_DHME1\CookedPC\BioD_ProNor.pcc...
12:05:58 AM:  Load file : C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_DHME1\CookedPC\BioD_ProNor.pcc
12:05:59 AM:  File already decompressed. Reading decompressed data.
12:05:59 AM:  Reading Names...
12:05:59 AM:  Reading Imports...
12:05:59 AM:  Reading Exports...
12:05:59 AM:  Prefetching Export Name Data...
12:05:59 AM:  Writing pcc to: C:\Program Files (x86)\Mass Effect 2 Ultimate Edition\BioGame\DLC\DLC_DHME1\CookedPC\BioD_ProNor.pcc
Refreshing header to stream...
12:05:59 AM:  Opening filestream and writing to disk...
12:05:59 AM:  All PCC updates finished. 
12:05:59 AM:  Updating Basegame...
12:05:59 AM:  Updating Basegame...
12:06:00 AM:  -----New Execution of DLC Editor 2-----
12:06:01 AM:  Basegame updated.

**Comment by KFreon** [comment]
Hmm nothing unusual in the log. 
I'll have to test it out.

**Comment by forgetti** [comment]
I had my avast anitvirus disabled because that seems to deny the ability for me3 explorer to even install any form of textures.

but if you test it on me2 and all the textures including the normal maps install then it may be a problem that only I or other windows 7 users seem to have

**Comment by KFreon** [comment]
When I downloaded that file, it needed autofixing but I can't see any of that in your log.
It's important for me to know because:
A) It'd be weird if I needed autofix and you didn't.
B) Creeper has been right all along about the sizing thing with my ImageEngine, and autofixed textures don't like ME1 and 2. I'll need to fix it.

**Comment by forgetti** [comment]
oh whoops. sorry I uploaded the stock TPF to my mega. the one I ran through was one that  had ran though autofix then recompiled into a me3explorer TPF. though the same problem still occurs if I run the stock one through TPF tools. I'd guess it would be scenario B

**Comment by KFreon** [comment]
I think I fixed this finally. It'll need some testing, but it seems to pass.

**Comment by forgetti** [comment]
cheers man that's awesome to hear. if it does prove to work texmod can be marked as redundant, well for me anyway
