### ISSUE TITLE
All revs Extract All doesn't append a hash

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#153]
I'm giving this information from what I recall, I can't access me3explorer right now to check if everything is exactly true. Should be :).

So, let's take a texture named 'HMM_ARM_whatever.dds' by the mod author, and packed in a TPF. Everything below depends on whether or not the mod author included the texture's hash in the name.
- Individually extracting this texture in TPF/DDS Tools (by selecting and clicking 'Extract'), results in a DDS file with the hash appended at the end : 'HMM_ARM_whatever0x00000000.dds'. Note that there is no underscore between the texture name and the hash (iirc). This means you can't install the texture afterwards in TPF/DDS, as it won't recognize the hash.
- Using the 'Extract All' button results in a DDS file named after the original : 'HMM_ARM_whatever.dds'. No hash whatsoever.

What would be nice is to have a standardized naming process, like 'MASSEFFECT3.EXE_0x00000000.dds'. It's cleaner, and doesn't require any manual fixing afterwards.

**Comment by KFreon** [comment]
That's what the output is supposed to be. 
Looks like I missed a few cases. 
Pretty sure it's fixed now.

**Comment by starkgate** [comment]
rev730 : Yay, it works !

**Comment by starkgate** [comment]
Tiny tiny nitpick : your method adds a 0x00000000 hash at the end of each texmod.log ^^.

**Comment by KFreon** [comment]
Roger that. Fixed in the next one :)
