### ISSUE TITLE
rev730 me3explorer windows scaled down

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#154]
All the tool's windows are scaled down in size in 730, compared to previous versions. It wouldn't be too much of a problem if me3explorer remembered changed window's sizes upon closing tools, but as it isn't the case, it becomes quickly tedious to resize the window every time I launch the tool.
2 solutions : Either make it so me3explorer can remember window sizes and positions upon closing it, or rollback to the previous sizes.
![capture](https://cloud.githubusercontent.com/assets/12874678/12530792/8bb05698-c1ea-11e5-8132-81b6a55cb4f2.PNG)

**Comment by KFreon** [comment]
I didn't realise getting a new screen would cause such frustration.
There's not much I can do about this anymore. 
I can fiddle, but I'm only guessing. It all looks different for me.
Ideally someone with only 1080 monitors would fix it in there and update Master.

Apologies all around.

EDIT: Actually, does resizing it show the buttons?

**Comment by starkgate** [comment]
To your question : no, it doesn't sadly :/. I have a 3840x1080 monitor or a 1366x768, so yeah. Would forcing your resolution to 1080p work ?
Also, are the positions of the buttons relative to each other and to the window, or absolute ? The problem might lie there, absolute positions would be problematic with different screen resolutions, as opposed to relative coordinates (percentages).

**Comment by KFreon** [comment]
I should clarify: The resolution itself doesn't matter, just the DPI.
So the 1366 monitor will probably suffice.
As for the forcing to 1080, it actually would. I may or may not have forgotten about that...

WinForms is notorious for having issues with different resolutions. Especially in the hands of a novice such as myself. I'll see if I can find something.

**Comment by KFreon** [comment]
See #158
