### ISSUE TITLE
Suggestion : Extract all TPFs from a folder

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#155]
The idea is simple : add an option in TPF/DDS to bulk extract all TPFs from a given folder in specific folders. This is especially useful to avoid overwriting textures present in multiple TPFs when extracting in a single folder.

**Comment by KFreon** [comment]
Added for the next rev.

**Comment by starkgate** [comment]
Ehm, where is the button to bulk extract ?^^ I see only the normal menu, no change. Or is it among the buttons hidden below like Analyse and Install Valid ?

**Comment by KFreon** [comment]
Its at the end of the menu bar? Resize maybe?

**Comment by starkgate** [comment]
Ah yes, you're right, I didn't see it. And it works, awesome !

**Comment by CreeperLava** [comment]
Hmm, I tested it with a larger batch of files, it stalled with an Out of Range exception after running for a while. When opening the folder where the extracted TPFs should be saved, about 25% of them had been extracted before the error.

**Comment by starkgate** [comment]
I did some more testing with a larger batch of file. It went relatively good, but it regularly stalled when it came to extracting some specific TPFs. Apparently it didn't like some of them, although extracting them manually posed no problem. It's a minor issue, I think the problem doesn't come directly from me3explorer, but from the TPFs' formats themselves.

**Comment by KFreon** [comment]
Interesting...Wonder why it was stalling.
