### ISSUE TITLE
PCCEd2 Still Broken; unfixed from Issue 136

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#156]
Still broken. Same exact issue and error as reported in #136 

@HeffU, can you please take a look at this? Whatever fix was merged when this ticket was closed didn't do the trick.

**Comment by KFreon** [comment]
I just tried this and it seems to work for me.

**Comment by ghost** [comment]
Yep, your right. My error. Sorry about that.

I must have double-clicked the wrong shortcut and opened rev727 instead of the current rev. Just to make sure, I've opened vanilla, modded, and modded PCCs with cloned objects, and everything seems fine. No errors thrown like previously.

Issue can be closed.
