### ISSUE TITLE
rev731 MIPS generation

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#157]
This isn't really a bug report, it's just a comparison between MIPS generation in rev717, 731 and Photoshop, showing what could be improved before the next stable. If you have time and motivation :).
Here you have an autofixed texture's MIP (the first MIP) in rev717, pretty bad :
![717](https://cloud.githubusercontent.com/assets/12874678/12821046/09ada0a2-cb62-11e5-9c20-cfc93f034175.PNG)
It gets better in rev731 :
![731](https://cloud.githubusercontent.com/assets/12874678/12821047/09c47ade-cb62-11e5-97c7-a3b9776cfb26.PNG)
Photoshop is still better quality-wise though :
![ps](https://cloud.githubusercontent.com/assets/12874678/12821048/09ea7180-cb62-11e5-9ee4-d00fd003bf2e.PNG)

This problem was brought to my attention with [this](https://www.youtube.com/watch?v=6UBYXIHDSNU) video, which shows how bad MIPS generation/transition can alter the graphics. The video was taken with textures autofixed using 718/717, so I don't know what it would look like with rev731.
Testing files : http://filebin.ca/2Vp5ndmNCGdG

**Comment by KFreon** [comment]
I don't think there's really anything I can do here. 
It already uses the highest quality resize method as far as I know. I can check I guess.

**Comment by KFreon** [comment]
I might change the resize filter and see which you like better.
I'll do this on the weekend and post a bunch of them.

**Comment by KFreon** [comment]
Hrm...turns out I can't. Personally, I don't mind the quality in that.
Bit of a quality thing, but even so, apparently it's using the highest quality resize anyway.

**Comment by starkgate** [comment]
Well, it's not perfect, but it's pretty good nonetheless, so I suppose that's fine.

**Comment by KFreon** [comment]
When I get the new rev out, let me know if this still a problem.

**Comment by starkgate** [comment]
Can't test it right now, as I don't have a working me3 tree.

**Comment by KFreon** [comment]
You got a tree yet?

**Comment by starkgate** [comment]
Forgot to test it, will do asap.

**Comment by starkgate** [comment]
Well, as much as I'd like to, I can't test it right now. See #210

**Comment by KFreon** [comment]
Try with rev 739. Hopefully it works now.

**Comment by starkgate** [comment]
I think it does, but I still can't actually see the MIPs. Screenshots available in #210.

**Comment by KFreon** [comment]
You'll just have to use the ImageEngine viewer or The Compressonator or something unfortunately :(

**Comment by starkgate** [comment]
You can consider this closed, I couldn't tell the difference between Photoshop and 743 :).

**Comment by KFreon** [comment]
Excellent :)
