### ISSUE TITLE
rev731, TPF Tools doesn't extract MIPs from AutoFixed Normals

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#159]
Discovered this while researching the fixes to #141.

Good news is that autofix seems to work on normals again. They look proper when viewed in GIMP after extraction. They're rendered in gray rather than the more common blue/purple hue of normals, but my understanding is that this doesn't matter.

The catch is that apparently only the largest MIP is taken. I have no idea if this is intended, so I'm reporting it. Non-autofixed normals have their MIPs extracted properly (but they still look wonky, at least in GIMP).

**Comment by KFreon** [comment]
I'm assuming you mean TPFTools, since modmaker doesn't do anything with the image if it's wrong.
Found a logic derp. Told it to make mips if it had enough already...

**Comment by ghost** [comment]
@KFreon -- Doh, TPF Tools, correct. 

Cool. Will retest upon next rev.

FYI, I'm retesting all old issues I submit to make sure that the fixes are indeed working. Then I've been posting comments to those closed threads verifying the fix.

**Comment by ghost** [comment]
Reopening issue.

Not fixed in r733. Autofixed normal still only extracts with 1 mip.

**Comment by KFreon** [comment]
Maybe fixed? Can't seem to replicate it.
Feel free to reopen again as necessary.
