### ISSUE TITLE
r731, TPF Tools/Texplorer replacing all textures inside vanilla TFC

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#160]
This is directly related to issue #147.

Whereas before the issue seemed to be the pointer not changing correctly to the new CustTex, NOW the tool _is actually replacing inside the vanilla CharTextures.tfc_:

![tpftools_normals_vantfc](https://cloud.githubusercontent.com/assets/13645804/12892440/05f14838-ce41-11e5-9bcd-e44e7b72972a.PNG)

Obviously, this is very... not good. Good thing I keep lots of back ups :/

**Comment by KFreon** [comment]
Whaaaaaaat.
Texplorer wtf.

**Comment by ghost** [comment]
And, it's not just normals and not just TPF Tools. 

Both Texplorer and TPF Tools are replacing inside the CharTextures.tfc, for everything. Normals, diffs, etc.

**Comment by ghost** [comment]
What I want to know, btw, is how no other testers noticed this! Grrr.

**Comment by KFreon** [comment]
Ahh I see. I broke this when I added alternate named caches.
Seems to be fixed now.

**Comment by ghost** [comment]
yaaaaaay, lol.

Closing.

**Comment by ghost** [comment]
Verified fixed in r733.
