### ISSUE TITLE
rev731, TPF Tools executing DLCEd2 unnecessarily?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#161]
Related to #145.

Unsure if this is intended, so reporting to be certain.

When modding a base game PCC, TPF Tools is still executing DLC Editor during the TOC process, resulting in a delay of about 1 minute. It does _not_ TOC any DLC, but I was wondering why it was executing the tool in the background (resulting in the delay), when it doesn't need to.

![tpftools_dlced2_again](https://cloud.githubusercontent.com/assets/13645804/12892771/86a110b6-ce42-11e5-82ef-504895cd2a25.PNG)

**Comment by KFreon** [comment]
It was just being initialized before checking whether it needed to. Wasn't actually doing anything.
Moved inside the check, doesn't happen anymore.

**Comment by ghost** [comment]
Got it. Thanks for the clarification.

**Comment by ghost** [comment]
Verified fixed in r733.
