### ISSUE TITLE
r731, Changes to Version Switcher needed before stable 

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#163]
We have two issues that need to be addressed if Version Switcher is going to be retained in the stable release:

**1. Broken Revs.** It's not really practical to test every rev, but if the rule is that Version Switcher won't work when the root toolset folder is "Debug" and not "ME3Explorer", then those revs need to be removed from the equation. We don't want users trying to switch and then ending up confused b/c it's not working. 

I doubt re-uploading all those revs with the correct file structure is feasible. If it is, then that would be the optimal solution. If not, then all revs that don't follow the correct file structure should be removed from the dropdown list inside the tool. That way, users can't select the broken revs.

**2. Trees & Thumbnails.** The practicality of the tool is _severely_ hindered by not retaining the user's tree.bins and Thumbnail cache files. A majority of our users use it to modify textures. Probably 90%. Not retaining those across rev switches -- and not even informing the user of this before deleting their existing install -- is highly problematic.

In addition, there's one other complication. Sometimes trees from one rev won't work in another rev. Which means that retaining them could also be problematic in itself.

I'm not sure about the best way to deal with this. At the bare-minimum, the user's existing trees and Thumbnails should be backed up before Version Switcher deletes their old directory. If we're going to provide an "automated" tool for updating, then that needs to be automated, as well. Ideally, the tool should also be able to copy them into the new directory, assuming they are compatible. If they aren't going to be compatible, then we might need the tool to warn the user _prior to the switch_ that their existing tree structure isn't compatible with the rev they want to switch to.

---

Both of these issues are significant. If they can't be corrected, then we need to seriously consider removing Version Switcher from the stable and having folks handle updates manually. 

With the new Nexus page, the clearer versioning on Git (compared to SF), the wiki, and something else Heff and I have in the works, updating manually is easier than ever. It might be that in this particular instance, trying to automate this does more harm than good.

**Comment by starkgate** [comment]
I second this. See #148, some of these issues and others are shown there.

**Comment by ghost** [comment]
Bah, thanks for inserting that, Creep. I meant to link it at the beginning.

**Comment by KFreon** [comment]
Being from the old days, I think VersionSwitcher is a dangerous crutch. _You kids get of my lawn!_

Usefully now, I'm not sure what to do. I haven't looked into the code to see about fixing it regarding trees and thumbnails. 
I've been keeping the base directory naming the same for a number of revs now, so if the last few work, all is well in directory land and either the old ones need fixing, or the tool needs to be able to fix it itself.

**Comment by ghost** [comment]
@Kfreon -- Well, that's not entirely true about the directory naming. rev727 has a Debug folder for instance. That's a very recent rev. 720 does as well from what I can tell. Those are just a few that I happened to check.

VersionSwitcher is actually pretty new, but it's a reincarnation of the old SVNUpdater, which also had no mechanism for backing up trees/thumbs.

If you want to look into the code for a backup mechanism that's fine, but it also doesn't solve the problem of "what if version X isn't compatible with the tree created with version Y". That I think is a much larger problem.

As far as the complications I outlined above, combined with the issues we're already trying to solve, it might be smartest to remove it. Keep the code around somewhere, though. If it can be fixed in the future, then we can always re-implement it.

**Comment by starkgate** [comment]
I think it is not K's job to fix it in any case. FemShep published it, and as such is the one responsible for supporting it. I would leave it in anyways, just put a warning with the known issues.

**Comment by ghost** [comment]
No, it's not K's job to fix it, but it also can't be left it in as is. It must be addressed.

This will likely be the final stable release. That means everything left in the toolset has to be fully functional. The only way we can leave it in without fixing it is if Version Switcher is totally disabled, similar to the Texture Tool.

Also, if the criteria for support was based upon who published the tool, not a single tool in the toolset would be maintained right now except for TPF Tools. ModMaker and Texplorer are both Salt's tools; K didn't create them. Once a tool is placed in the toolset and a bug arises, it becomes the responsibility of the core toolset team to fix it. This is exactly why not just "anything" should be pushed into the main branch of the toolset. Especially at this point since we have so few devs.

**Comment by SirCxyrtyx** [comment]
If this is going to be the (probable) final stable release, there doesn't seem to be a whole lot of point to leaving version switcher in, especially if keeping it would require extra work.

Any further updates to the toolset after the final stable will almost certainly be to mod-authoring tools, and not mod-installing tools (hopefully). I don't think it's too much of an imposition on mod-authors to require that they actually manually download a new revision. For mod-users, everything will be simple because they'll just download the final stable from the nexus and not have to worry about updating or any further releases on Github. Having a tool in the stable release to easily switch to a development release doesn't seem like the best idea.

**Comment by ghost** [comment]
@SirCxyrtyx -- Yeah, those are all good points and I agree.

We might want to also consider pulling (or at least removing from the menu), the Texture Tool, and any other tool that has a little pop up that says "disabled/broken".

Something else that would be helpful is if you and @HeffU could fix some of the lingering bugs that are a bit less complicated than others. I'm thinking of issues like #66 , #59 , #37 , #29 , #22 / #31 . There are some others I can probably think of that haven't been submitted, but those are good ones that address functionalities that need fixing. It would be nice to include them in the stable, but K has more than enough on his plate.

**Comment by KFreon** [comment]
Removed VersionSwitcher from the menus.
All code is unchanged, so someone can rebuild it later if they wish.

**Comment by ghost** [comment]
Okay, closing issue.

Might as well also close all other Version Switcher related issues, since the tool has been removed, at least for the foreseeable future. I'll retab them with "wontfix".
