### ISSUE TITLE
Feature: Add links to Git and Nexusmods in the "About" menu

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#164]
We should add links to the download areas, for easy user access:

"GitHub" should lead to http://github.com/ME3Explorer/ME3Explorer/releases
"Nexusmods should lead to http://www.nexusmods.com/masseffect3/mods/409/?

Re-alphabetize "About" options as such:
-About
-Forums
-GitHub
-Nexusmods
-Wiki

**Comment by KFreon** [comment]
Done.

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
Verified in rev742.
