### ISSUE TITLE
r731, Add DLC to Tree partly functional

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#165]
This _almost_ works. I think it's very close.

I tried using the CE OnlinePass as a test, and it ended up hanging partly through the scan:

![adddlctotreehang731](https://cloud.githubusercontent.com/assets/13645804/12898168/34ddc36e-ce60-11e5-9c3f-22a6c20d19e0.PNG)

So, it definitely appears to be working, but these are 100% unmodded files, so it shouldn't be hanging. I also tried Sir's Ken and Gabby mod which only has maybe a half dozen files in it and Texplorer hanged again. No errors and nothing in the Debug window.

Really close, though. Hope you can get this fixed, K :)

**Comment by starkgate** [comment]
I think this is just a graphical glitch, see how it stalls at exactly 40/45 ? I reported it in #142, it stalled for me at exactly 80/86, also a round number. If you close and reopen Texplorer, it should display the textures without problems.

**Comment by ghost** [comment]
It might be, b/c it also updates the tree.bin file. But, either way, there's a problem that needs to be fixed.

Also, probably not the best idea to add new information to closed issues unless it's just to verify that the fix works properly. I'm not sure K is going back to check for new bug reports added to old issues. If he's not, then he's going to miss some of the info you've been attaching to closed reports.

**Comment by starkgate** [comment]
He is receiving notifications to all posts we do here, and he reopens issues when problems arise anew after a bugfix that should have fixed them (ie after a new rev).

**Comment by ghost** [comment]
@CreeperLava -- Ah, okay. That's helpful to know. Then I won't open new issues anymore. Thx.

**Comment by KFreon** [comment]
I don't actually look at the notifications :P 
I get too many.
But I do check the closed section. I'm guessing users can't reopen issues?

Also this should definitely not be happening, but if it updates the tree, I guess it finished...

**Comment by ghost** [comment]
@Kfreon -- No, users cannot reopen issues. So, what do you prefer? Do want me to post too issues, or add to old ones that are closed? My concern is there's a greater chance to miss the new information if it's appended to a closed issue.

Well, let's not assume it's finished if the tree is updated. Take a looksy. Should be very easy for you to replicate and figure out what's happening :)

**Comment by ghost** [comment]
And, I lied... users can reopen issues :D

(accidentally hit "close and comment" right now, lol)

**Comment by ghost** [comment]
Ok, further clarification. We can only open issues that we, personally, close. Looking at the previous issues I've submitted and that you have closed, K, I cannot reopen those.

**Comment by SirCxyrtyx** [comment]
Giftfish , I added you as a contributor to this repository (because you are) with write access. I think that should allow you to reopen issues.

**Comment by ghost** [comment]
@SirCxyrtyx -- Uh... okay. That works :) 

Also, if I see lingering open issues that I know have been addressed, I'll go ahead and close them for you guys.

**Comment by KFreon** [comment]
I think I fixed this...
Next release will show I suppose.

**Comment by ghost** [comment]
Okay, closing both related issues; will reopen if not fixed.

**Comment by KFreon** [comment]
Best to leave things open until the next rev so I can find them to make note of them.
I close them after posting the new rev.

**Comment by ghost** [comment]
@KFreon -- Okie doke. I just won't close things then. I was trying to help your work flow, but I think I just messed with it. Sorry bout that.

**Comment by ghost** [comment]
@KFreon -- Ha! It works!

I haven't tried replacing a texture yet, but the progress bar on the bottom now says, "DLC Added to Tree", and the tree file is updated, AND if I locate a texture I know is referred to in one of the new DLC PCCs, it's present in Texplorer's PCC List.

Yay! Nice work, K!
