### ISSUE TITLE
r731, Change Custom TFC issues

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#166]
A couple issues here:
1. There's no confirmation in Texplorer's bottom window that the new TFC has been specified. Some simple debug output to verify it's been changed would be helpful.
2. I'm getting an error when trying to change a texture in AVPen's MiriArmor mod. This is a good one to test, since it's a small mod with its own TFC. Using "Add Bigger Image" in Texplorer results in this error:

![newtfcerror](https://cloud.githubusercontent.com/assets/13645804/12899403/0a5beea8-ce66-11e5-8dea-ba1f5d989215.PNG)

Seems like it's partially working and worth pursuing, but it's not there, yet.

EDIT: Oh, and to be clear, the files weren't at all modified.

**Comment by KFreon** [comment]
Interesting...Is that reproducible?
As in does it happen every time with every texture?
I suspect it only happens for the second texture, is why I'm asking.

**Comment by ghost** [comment]
I can try more; I just have a limited amount of DLC with custom TFC files that I can test on.

Can you be more specific on exactly what you want me to try?

**Comment by KFreon** [comment]
As in when you add a single new texture, does this happen? And if so, does it happen on the first or second PCC that it's installing to?

**Comment by ghost** [comment]
@KFreon -- Well, what I did above _was_ adding single new texture. Select thumb > Add bigger > Navigate to new DDS. To my knowledge, there's no way to replace multiple textures at once in Texplorer... that's what TPF Tools is for >.>

As far as which PCC, I don't think I can answer that, b/c it never got to the save point. The error pop ups after using "Add bigger" and before clicking "Save Changes".

**Comment by KFreon** [comment]
Hrm...might have been fixed by some of my other changes, cos I can't get it to break.
Next rev will show I suppose.

**Comment by ghost** [comment]
@KFreon -- Ha! This now works, too! Holy crap, this is fucking fantastic. I can't wait to post on the forums, lol.
