### ISSUE TITLE
r731, Texplorer Saving Prematurely

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#167]
In trying to verify that issue #144 was fixed, I've also found that not only is Texplorer modifying vanilla TFCs, it's doing so prematurely, as soon as a texture is replaced, BEFORE the user clicks on "Save Changes":

![texplorer_prelimsav](https://cloud.githubusercontent.com/assets/13645804/12900295/700ec1d6-ce6a-11e5-8cc2-dad92bf6ae5c.PNG)

To my knowledge, when it saves into CustTex0 as it should, it doesn't build _anything_ into the game files at all until "Save Changes" is clicked. Up until now, I've always been able to safely exit Texplorer knowing none of my files would get modified _unless_ I clicked Save Changes. This is also what I explain in the wiki.

What's particularly interesting with this bug is the PCCs aren't modified at all, it's just the CharTextures.tfc that's getting baked with the changes prematurely.

I can't finish testing the issue reported in #144 until this is fixed, since right now Texplorer is saving into the wrong TFC.

**Comment by KFreon** [comment]
Incorrect I'm afraid. 
The data is saved to the tfc immediately so as to be able to set a...actually I don't know why it's like this, and I don't have enough coffee right now to think of a reason.
I suppose it's just easier.

FYI saving saves the changes to the PCC's, where the game can pick up the changes. Junk data in the TFC's just makes it bloated. Doesn't change or affect anything.

**Comment by ghost** [comment]
@KFreon -- Well, that's pretty weird. I am 100% certain that in the past I have done "Add Larger Image" in Texplorer and absolutely _nothing_ was altered until I hit "Save Changes". I know this b/c I've exited out of Texplorer without saving and the CustTex0 wasn't altered.

So... can we make that happen again?

**Comment by KFreon** [comment]
I'm quite certain that this has always been the way, at least since I took over from Salt. 
His function is unchanged since he wrote it and it has this line:
`ChooseCache(etc)`
which moves the data into the custom cache.

If you can find a rev that doesn't do this, I'd be interested to see how it worked.
It can work the way you're suggesting, but not without a considerable rewrite.

**Comment by ghost** [comment]
@KFreon -- Hrm. Talk about a needle in a haystack. I can poke around a bit.

**Comment by ghost** [comment]
@KFreon -- Okay, you're right, I surrender :) The two other versions I've worked most with are revs653 (stable) and rev722. Both alter the TFC immediately. I'll need to correct that on the wiki.

Issue can be closed.
