### ISSUE TITLE
rev731 Set game path for ME3

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#168]
Using the 'Set Custom Path' option (under Options in the main menu) for ME3, then browsing for the exe, results in a wrong path being saved.
eg if my ME3.exe is in C:/ME3/Binaries/MassEffect3.exe, the path saved for the gamepath will be C:/ instead of C:/ME3, C:/BioGame/CookedPCConsole instead of C:/ME3/BioGame/CookedPCConsole, etc. The only way I found to circumvent the problem is to manually enter the path in TPF/DDS Tools using 'Change Game Paths'.

**Comment by ghost** [comment]
Well, that's interesting. I wonder when it broke.

**Comment by KFreon** [comment]
This is because for the standard installation, the path is like: C:\Program Files\Mass Effect 3\Binaries\**Win32**\MassEffect3.exe, note the extra folder in mine. 
I assume this is the standard install across the board, so I don't know why yours is different.

**Comment by starkgate** [comment]
Ah alright, that might be why. I made a 'fake' ME3 install to test (would be funny to install ME3 on the school's computers, but I'm not sure how they would react^^). Guess I forgot that folder. You can close the issue :).
