### ISSUE TITLE
R733 TPF/DDS tools 3.0 Issues with installing textures to mass effect 2 (again)

### ISSUE THREAD

**Issue by forgetti** [ME3Explorer/ME3Explorer#169]
ok. looks like we've still got a problem with me2 texture modding via me3 explorer

when you install textures most of the time all layers will end up being visible in game I.e glowing blue spec map. here is a direct screencap: 
![masseffect2 2016-02-13 01-03-34](https://cloud.githubusercontent.com/assets/16586137/13006547/7a90a084-d1ee-11e5-9cbf-96c2ba214a76.png)

the TPF I was using: http://www.mediafire.com/download/d2ikntl2hj7px2y

and here is the log (it was too long to post raw, Open with notepad++)
[logginbn.txt](https://github.com/ME3Explorer/ME3Explorer/files/127959/logginbn.txt)

**Comment by ghost** [comment]
@forgetti -- Any way you can also test an ME1 texture, just to verify? I very much have ME3 on my radar, right now, so it's important that we know things aren't going haywire for ME2 _and_ ME1.

**Comment by forgetti** [comment]
I'll see what I can do

**Comment by KFreon** [comment]
Forgetti: That download is protected.
Also looks like an alpha issue maybe.

**Comment by forgetti** [comment]
oh dammit. I'll switch it to a mediafire link: http://www.mediafire.com/download/d2ikntl2hj7px2y

**Comment by starkgate** [comment]
Have you tried other textures ? I think this is a problem with the mod itself, not me3explorer. Miranda's outfit doesn't have an alpha, I'm not entirely sure how texture rendering works but that's probably the cause of the problem. Her alternate outfit does have an alpha, and thus should be displayed properly.
I've had a similar issue with a blood texture that lacked an alpha, and also displayed purple (in ME3).

**Comment by forgetti** [comment]
yeah. with most other textures other layers will be visible as well like the M8 avenger will also have it's specmap overlapping with the diff map

**Comment by starkgate** [comment]
Hmm, sounds like norm and spec maps are displayed as diffs, which makes no sense.

**Comment by forgetti** [comment]
some textures like the default squad uniforms are displayed properly but it's usually the alternate loyalty ones that are plagued by the problems

**Comment by KFreon** [comment]
Does this still happen? I'm hoping it's one of those that fixes itself :)

If it does, can you run the autofix ONLY, then zip up the autofixed textures and send them to me? 
Maybe the Image Engine is doing weird things for you like it sometimes does with Creeper.

FYI Autofixed stuff is at exec\TPFTEMP\autofixed    (something like that)

**Comment by forgetti** [comment]
sure man. I'll do that as soon as I get home

On Fri, Feb 26, 2016 at 11:29 AM, Kael <notifications@github.com> wrote:

> Does this still happen? I'm hoping it's one of those that fixes itself :)
>
> If it does, can you run the autofix ONLY, then zip up the autofixed
> textures and send them to me?
> Maybe the Image Engine is doing weird things for you like it sometimes
> does with Creeper.
>
> FYI Autofixed stuff is at exec\TPFTEMP\autofixed (something like that)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ME3Explorer/ME3Explorer/issues/169#issuecomment-189013153>
> .
>



-- 
RUDIMENTARY CREATURES OF BLOOD AND

**Comment by forgetti** [comment]
sure man I'll do it as soon as I get home. also tested with the latest rev and auto fixed textures and it still failed on me

**Comment by forgetti** [comment]
ok. got the files for ya mate: http://www.mediafire.com/download/cwko3i8m9lp8q2c/textures_for_testing.zip

**Comment by KFreon** [comment]
Excellent, thanks for the quick turn around. 
I'll do some testing this weekend and see how I go.

**Comment by forgetti** [comment]
no worries mate. Hopefully we can get the issue fixed :D

**Comment by KFreon** [comment]
I don't suppose I can convince you to do a bit more testing to narrow down this issue? 
Like install one texture, check, install the next texture, etc

**Comment by starkgate** [comment]
From what I've seen with ALOT for ME2, this isn't due to to ME3Explorer, but to the mod itself. It must have a bad alpha on the spec map (happened to me quite a few times). To fix it, open the modded and the vanilla texture in Photoshop, remove the modded alpha. Duplicate the vanilla alpha channel to a new 'object', upscale it then duplicate it again to the modded one. Save, install.

**Comment by forgetti** [comment]
ok, I'll give that one a shot. wait... you are making an ALOT for me2? ok. I may actually want to wait until you release it, cause I do not have photoshop....

**Comment by forgetti** [comment]
@KFreon  sure I can give that a try.

**Comment by starkgate** [comment]
It's already released, actually^^. Look on nexus.

**Comment by forgetti** [comment]
Keelah I'm blind. I'll go look right now

**Comment by KFreon** [comment]
This is likely related to #245  which is fixed. Hopefully this is too.
