### ISSUE TITLE
rev733 Bulk extract

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#172]
Well, now each time I try to bulk extract I get an index out of range error. You can try it for any TPF. I'm going to see with VS how it goes and will update here.
Edit : ![capture](https://cloud.githubusercontent.com/assets/12874678/13026847/1374ca3a-d237-11e5-995a-d4b46b2a5c1d.PNG)

**Comment by KFreon** [comment]
Fixed.

**Comment by starkgate** [comment]
Confirmed to work in rev735. Bulk extract is rock solid, went through 113 TPFs mixed with a .rar and a .mod without problems.
