### ISSUE TITLE
rev733 TPF/DDS Previews of identically named textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#173]
If two different textures, but with the same name, are loaded in TPF/DDS, the preview for both is identical. Only the name matters, they can have different sizes, MIPS, etc, as long as their names are identical, their previews will be the same.

**Comment by KFreon** [comment]
If they have the same hash, there's a problem...
EDIT: Same hash is likely still a problem, but otherwise it was a caching problem. Since my test images had the same name and no hash, they had the same cache key.

**Comment by starkgate** [comment]
They can be from 2 different mods, I often use me3explorer as a display to compare mods. The caching feature is very useful for that.

**Comment by KFreon** [comment]
I've added some more properties to the key to make it more unique. 
Should be fine.

**Comment by starkgate** [comment]
Confirmed to work in rev735.
