### ISSUE TITLE
rev733 Autofix reformats alpha

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#174]
I don't know if this is a bug with me3explorer or just a limitation in the DXT algorithms, but I'll report it anyways.
What I tried to do is autofix a texture from DXT5 to DXT1 using rev733. The alpha from DXT5 was formatted as black and white only (1 bit alpha) and thus should be present in the resulting DXT1. But when I checked it in Photoshop, the alpha was simply completely white. I'm not sure how that alters the render in-game, but it is undesired behaviour in any case.

The files : http://filebin.ca/2WpjeUYWhMBs

**Comment by KFreon** [comment]
Same as #150

**Comment by KFreon** [comment]
#150
