### ISSUE TITLE
rev733 General autofix report

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#175]
I autofixed around 50 ME2 textures using rev733, here is what seems important to note :
- I verified the process is indeed multitasked, all 4 cores were used at 80-100%
- The total size of the 49 files is 213 042 976 octets (=bytes), compared to the 213 032 800 octets from 718 (about 207.7 more bytes per texture in 733 vs 718). So, not identical, but I could load them with no problems in 717/718, so not a big deal.
- A good point for 733, which supports PNGs whereas 718 doesn't. The autofix of a wrongly dimensioned texture also went fine in 733.

Now to the bad points :
- TGA isn't supported by 733 (nor by 718 btw). If it's not too complicated, you might want to add compatibility for it.
- Mask, Strp and Tint conversions are really bad, a lot of compression artifacts show up. Even when comparing to 718, 733 is worse on that matter.
  Quite interestingly, even a simple MIPS generation without format conversion results in artifacts too.
  (click to enlarge, the 730 in the first picture is a typo)
  ![capture](https://cloud.githubusercontent.com/assets/12874678/13028882/9ea07ba0-d27c-11e5-9e49-07e5a8a7284f.PNG)
  ![capture2](https://cloud.githubusercontent.com/assets/12874678/13028883/9eb88808-d27c-11e5-8992-fe926c443eab.PNG)
  ![capture3](https://cloud.githubusercontent.com/assets/12874678/13028919/f33fd45c-d27d-11e5-8151-6476aa5844cc.PNG)
  ![capture4](https://cloud.githubusercontent.com/assets/12874678/13029051/6c9504b4-d281-11e5-87c5-75d398857891.PNG)

The 733 autofixed files : http://filebin.ca/2WqhmNKXSRUj

Additional note : just did a 300 textures autofix, not a single stall. Pretty impressive !

**Comment by ghost** [comment]
This is awesome information, @CreeperLava . Those compression artifacts are actually pretty terrible. Yikes.

Thanks a ton :)

**Comment by KFreon** [comment]
Don't think I'll be supporting TGA for now.
There was some limited support for TGA in Salt's code, but it wasn't complete as far as I could tell. 
At any rate, I'll read up and see if it's easy.

Also it took me about 10 minutes to figure out that the ones you linked are the autofixed ones.
If you have the unfixed ones, they'd be more useful :)

**Comment by starkgate** [comment]
Sorry, I didn't think you would need them. Here you go : http://filebin.ca/2X3qzAXr9aiR

**Comment by KFreon** [comment]
Should be better now.

**Comment by starkgate** [comment]
Pretty much perfect, yes. No artifacts remain from what I can see.
