### ISSUE TITLE
rev733 Autofix flags not removed for duplicates

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#176]
An image is worth a thousand words, this is what it looks like after autofix :
![capture](https://cloud.githubusercontent.com/assets/12874678/13029824/0fecf5a8-d297-11e5-9de2-5359cbdfb9f2.PNG)

**Comment by KFreon** [comment]
Interesting...
Gonna need a test image unfortunately.

**Comment by starkgate** [comment]
http://filebin.ca/2Ws90ZCorjVZ
I checked, it only happens with non DDS textures. No problem if I try the same with just MIPS flags.

**Comment by KFreon** [comment]
Fixed.

**Comment by starkgate** [comment]
Please feel free to ignore this if you think it is related to the '1 or 2 issues that could cause everything'.
Loading the BMPs results in this message being displayed in the debug log :

> 10:49:58:  Error checking texture: Impossible de définir une propriété sur l'objet >'System.Windows.Media.Imaging.WriteableBitmap' parce que son état est en lecture seule

It is complaining about read-only state, although the files aren't read-only and I launched me3explorer as administrator.
Clicking on Analyse results in VS displaying this :
![capture](https://cloud.githubusercontent.com/assets/12874678/13072819/9b36151c-d49b-11e5-9f08-9d68b522fbf0.PNG)

**Comment by KFreon** [comment]
No, that's a new one. Somehow that bmp doesn't have a Thumbnail, so when I try to copy the thumbnail, it fails.

**Comment by starkgate** [comment]
Are thumbnails part of the BMP file normally ? Never heard of it, interesting.

**Comment by KFreon** [comment]
No they aren't, but they are part of the TPFTools object I create. 
Here's what seems to have happened (5 minute look):
- One of the textures broke when trying to generate a thumbnail.
- When the duplicate checks happened, it tried to copy this texture for the duplicate, but was unable to copy something that didn't exist (thumbnail), so it died.

I've added a check to make sure the thumbnail exists before copying it, but I'm rather interested now as to why the thumbnail wasn't there.

**Comment by starkgate** [comment]
Confirmed to work in rev738.
