### ISSUE TITLE
Add float convertion to PCCEd2 (like Interp Editor)

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#177]
This one is for @SirCxyrtyx .

You've built a fantastic feature into Interp Editor that needs to be added to PCCEd2. You automatically convert the hex floats to their standard decimal values. So, instead of seeing:

-9775040527, as in PCCEd2

you see...

-6013.29, in Interp Editor

And, even better... Interp Editor actually identifies the X/Y/Z for each value.

Can this code be put into PCCEd2, so it does the same thing? AND, can we have an editable field for it? AND, can it work for all floats? AND can it work for and identify XYZ values like above, but also RGBA values for colors??

This would literally save my life.

Well, almost.

Please?

**Comment by SirCxyrtyx** [comment]
Maybe? The way I was able to do this in the InterpEditor is that I hardcoded in every single property of every single class. (That's also how it can show the default values for properties that aren't baked into the game files) Doing that is not an option for PCCEd2. Just defining the small subset of classes that are InterpTracks took ~4000 lines of code and days of work.The PCCEd2 just has basic rules for types of properties, and I'm not sure if there's a way to programatically determine what's a float, what's a color, etc.

I'll look into it though, because I agree, it would be hugely helpful.

**Comment by ghost** [comment]
@SirCxyrtyx -- Ack. Well, that sucks. Please do what you can :)

**Comment by SirCxyrtyx** [comment]
Looks like PCCEditor2 already handles floats properly, if they're on their own. The problem seems to be if they're part of a struct property. PCCEditor2 does not handle StructProperties well at all. just displays an integer array, which is pretty much always wrong as far as I can tell. I think I can make a solution for Vector, Rotator, and Color structprops, but it will have to be specific to each one. So if there are any other struct props you'd like special handling for, let me know (with a pcc and export number so I can find one)

**Comment by ghost** [comment]
@SirCxyrtyx -- Okay. Let me also pop up a post on the TM forums; JohnP, Kinko, and AVPen might have some suggestions. Location, angles/rotation, color are the main ones I can think of.

**Comment by SirCxyrtyx** [comment]
So far I've got it added to the Interpreter, which is the simple part, but I have a question. The rotation values are in a strange format where 65536 is one rotation, so I added a degrees conversion next to them
 ![](http://i.imgur.com/99UH1sW.png)

Is it clear that the degrees is a conversion, and that 35840 is the actual value?

Also, I've added LinearColor to my list of structs to do special handling on.

These are the ones I'm doing:
- Vector
- Rotator
- Color
- LinearColor

**Comment by ghost** [comment]
Give me a bit to research this. I remember something about this in the online UDK documentation...

**Comment by ghost** [comment]
Here we go. Look at this:

https://wiki.beyondunreal.com/Rotator

Also, I've found contradicting information online about how the axes are oriented, just FYI.

I'd say that if it's possible to just do the conversion behind the scenes so a player can just type in "196.875", then that would be ideal. Having to research and understand this weird UDK standard of 65536 Unreal Units = 360 degrees is a little ridiculous. The math works out right, though, in your example above:

65536UU/360deg = 182.04UU per degree

182.044UU/deg \* 196.875deg = 35839.9UU

But, like I said, it would be nice of all that math would stay hidden. Just display the 196.875 instead. That's what most folks will understand.

EDIT: Same thing with the colors. It's easy to locate a color via a web tool or GIMP/PS and get R/G/B values like 134-0-179. Then use a website [like this](http://www.easyrgb.com/index.php?X=CALC#Result) to get the decimal values, which are converted into the hex floats. But, what would be nice is if all that math happened behind the scenes and the user could just put in the RGB values, and if those were displayed.

**Comment by SirCxyrtyx** [comment]
Commit 72fadc46fc5dcd6cc42fb0b69e30b5a868c38ea4 resolves this for Vector, Color, Rotator, and LinearColor props. I'll leave this open for now in case more requests are made for other struct props.

**Comment by ghost** [comment]
This looks awesome so far, thanks! :)

One huge is missing, though, from my original request: there's no way to edit in the interpreter.

We really need an edit box for these values -- especially if the conversions are going to be done behind the scenes. Otherwise, the player will have to do all the math anyway -- except in reverse -- to convert the degrees back into unreal units back to floats and then to hex. And, they'll have no idea _how_ to do that. 

I also noticed that there's sort of a big with the edit box itself.

If an editable property (with the box) is clicked on, and then one of these vector/color properties are clicked on, the editable box stays present on the top, containing the number from the previous selected property. If a non-editable property was previously selected, then _those options_ will stay in the menu bar up top. Basically, this bar is not changing for these particular values.

So, how much work are we talking to add an edit box for this stuff?

**Comment by SirCxyrtyx** [comment]
Edit in Interpreter added by 56eea7a670b4048566df34865612683cb31e4bc3, [release 736](https://github.com/ME3Explorer/ME3Explorer/releases/tag/r736)

**Comment by ghost** [comment]
![kelly_scalars](https://cloud.githubusercontent.com/assets/13645804/13787278/91441e92-ea98-11e5-9149-df5ccc2d9c30.PNG)

@SirCxyrtyx -- I can't tell you how much awesome this is. I can't wait to start tinkering with Bailey and Aethyta. This will make things INFINITELY easier.

---

Verified in rev742.
