### ISSUE TITLE
Soundplorer requests AFC file for every file opened, even if you just opened it

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#178]
Soundplorer has several issues:
1. Say you have an unpacked DLC. You open a pcc, say SFXPawn_Scion.pcc, and try to play a wav in it. IT asks you to open the .afc file it references, OK. Now I click on anotehr WAV. it asks me again for the AFC, the same one. Soundplorer should cache this into a variable and use it, perhaps with a way to "purge" cache. 
2. Soundplorer stops working (in fact, ME3Explorer entirely does) once you seem to play 1 or 2 wav's, or perhaps a file that isn't meant to be played.

**Comment by SirCxyrtyx** [comment]
For the crashing after playing wavs thing, do you have a specific file and wav that it happens on? I can't replicate it.

**Comment by mjperez-usgs** [comment]
I unpacked MP4 and was using SFXPawn_Scion. Windows 10 x64. I think I was on rev729 or something, but since nothing has changed I don't think it had changed.

**Comment by mjperez-usgs** [comment]
I'll make a screencast if you can't reproduce it.

**Comment by mjperez-usgs** [comment]
Also, what I mean by "stops working" is not a crash. It's like an invisible modal dialog comes up (the dibg noise doesn't sound or title bar flash) but it just completely stops reacting to inputs. Windows still seems to think its responding.

**Comment by SirCxyrtyx** [comment]
Well, I tried playing everything in that pcc, but everything worked fine.

**Comment by Mgamerz** [comment]
https://www.youtube.com/watch?v=2mPEhwWk5sM

Additionally when in the vid I say a tooltip it's because most times in the toolset when you select a "dlc" item it opens the SFAR open dialog. Since these both want just a straight up pcc file, I don't know if there's a difference.

**Comment by SirCxyrtyx** [comment]
Well, I followed the exact steps you did, including moving my dlc folder to the same place, and still no hang. Only thing I can think of at this point is to open it in VS and step through the code yourself.

You do make a good point about the open pcc buttons though. There didn't really need to be two options, so I've consolidated it to just "open pcc" in my next commit.

**Comment by Mgamerz** [comment]
I'll get to it when I can. Working on other stuff (pcc decompression, oh how fun) for now.

**Comment by Mgamerz** [comment]
I'll try to look into this today or tomorrow.

**Comment by Mgamerz** [comment]
Can't seem to reproduce this issue anymore, closing it.
