### ISSUE TITLE
rev733 Rebuild TPF with Texmod

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#182]
There are a few issues with this.
- The rebuild doesn't work. If I load MASSEFFECT3.EXE_0x51AEDCC7.dds, MASSEFFECT3.EXE_0x13790734.dds and MASSEFFECT3.EXE_0xD83C233B.dds in TPF/DDS Tools and click on the Rebuild with Texmod button, it will generate a MEResults.log that will look like this :

> 0x51AEDCC7|MASSEFFECT3.EXE_0x51AEDCC7.dds
> 0x13790734|MASSEFFECT3.EXE_0x13790734.dds
> 0xD83C233B|MASSEFFECT3.EXE_0xD83C233B.dds

It will also move these 3 files _and rename_ them to Tropical_Fish_Weeds_0x51AEDCC7.dds, Tropical_Fish_Weeds2_0x13790734.dds and Tropical_Fish_Weeds3_0xD83C233B.dds.

This means that Texmod won't be able to generate the TPF as it can't find the textures. A solution would be to keep the original texture name when extracting it. It's what was done before, I don't know why it changed (possibly when you implemented the bulk extract function ?).
The MEResults.log should look like this :

> 0x51AEDCC7|Tropical_Fish_Weeds_0x51AEDCC7.dds
> 0x13790734|Tropical_Fish_Weeds2_0x13790734.dds
> 0xD83C233B|Tropical_Fish_Weeds3_0xD83C233B.dds
- The permission properties of the directory \ME3Explorer_r733\ME3Explorer\exec\TPFToolsTemp\TexmodRebuild are extremely messed up after a successful rebuild. I cannot access the folder, view its content or even delete it even though I am the admin. I don't even have the rights to change permissions. No success using Powershell either.
  Any suggestion as to how to delete that directory would be most welcome btw^^.
- Another problem, not necessarily with Rebuild only, is that extracting textures from Texplorer renames them as eg Rubble01_Diff0x7EF9FB2D.dds. It would be nicer to have an underscore between the texture name and the hash, although TPF/DDS surprisingly did recognize the hash anyways.

**Comment by KFreon** [comment]
- Yup was due to the naming conventions in Bulk Extract. 
  Fixed as you specified.
- I have not seen this problem before...
  All it does is extract stuff to the directory. Unless Texmod is holding it? 
  Is it only AFTER a successful rebuild? What about during? Cancelled?
- Fixed.

**Comment by starkgate** [comment]
The undeletable folder went away after a reboot I think (or after a chkdsk I had to run, I'm not sure). You want me to do more testing ?

**Comment by KFreon** [comment]
I don't think there's much that can be done about that issue.
Random Windows fun :P

**Comment by starkgate** [comment]
Confirmed to work in rev738. Not sure if I like the fact that TPF/DDS renames the texture from 'whatever_hash' to 'textureName_hash' though, but that's your choice :).
