### ISSUE TITLE
rev733 ARGB textures detected with 1 MIP

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#183]
ARGB textures are incorrectly detected as 1 MIP textures in rev733 (they're correct in rev718). Autofixing does work. I extracted the autofixed textures and put them back into TPF/DDS, they were recognized as correct. Even more interestingly, autofixed and non-autofixed textures have the exact same size. My bet is on a badly managed header property, dunno what would explain it otherwise.
Testing files : http://filebin.ca/2Wyg110ouUmJ

**Comment by KFreon** [comment]
Fixed.
Something weird with the estimation of mip counts. I'm 1 off and I don't know why...

**Comment by starkgate** [comment]
Confirmed to work in rev735.
