### ISSUE TITLE
Suggestion : Extract only valid textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#184]
In TPF/DDS, there is an 'Extract All' and an 'Extract Invalids' option, so why not an 'Extract Valids' too ? For now if I want only the valid textures I have to either extract them individually or extract invalids then differentiate with the entire folder of textures, which is tedious.

**Comment by KFreon** [comment]
Done. 
I like these "bugs".

**Comment by starkgate** [comment]
Confirmed to work in rev735.
