### ISSUE TITLE
rev733 Some textures incorrectly regarded as valid

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#185]
Everything is in the title, some textures are NFIT, are flagged as such, but are displayed as valid by me3explorer. Extracting all valid textures does extract these as well. This doesn't happen for all textures.

Testing files : http://filebin.ca/2X4S8OxemlOf
These are all valid in ME3, but only 2 of them should be valid in ME2 (same hashes). TPF/DDS doesn't care though and marks them all as valid while still displaying the flag NFIT. I tried renaming the files from MASSEFFECT3.EXE_hash to MASSEFFECT2.EXE_hash, it didn't change anything.

**Comment by KFreon** [comment]
![image](https://cloud.githubusercontent.com/assets/7845997/13066286/1b2b6042-d4b0-11e5-892e-56153c829a86.png)
Uh oh...

**Comment by starkgate** [comment]
What do you mean ?^^

**Comment by KFreon** [comment]
Isn't what's in my screenshot correct? As in I can't replicate the issue?

**Comment by starkgate** [comment]
No, you get the exact same issue as I do. You get a bunch of NFIT, but if you look below near the green bar, all of them are considered valid nonetheless. If you try to install them, TPF/DDS will attempt to install even the NFIT.

**Comment by KFreon** [comment]
Ohhhhh I see.
Fixed.

**Comment by starkgate** [comment]
Confirmed to work in rev738.
