### ISSUE TITLE
rev733 Display issues in Texplorer

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#186]
Still alpha issues :
![capture](https://cloud.githubusercontent.com/assets/12874678/13055399/5c3ae70c-d40f-11e5-85ab-e78c74fee078.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12874678/13055400/5c3b445e-d40f-11e5-9a4c-782b3f7113b6.PNG)
![capture3](https://cloud.githubusercontent.com/assets/12874678/13055401/5c3da15e-d40f-11e5-8032-55de9cea3c56.PNG)
![capture4](https://cloud.githubusercontent.com/assets/12874678/13055396/5bdce814-d40f-11e5-95f4-05b834499376.PNG)
![capture5](https://cloud.githubusercontent.com/assets/12874678/13055397/5bdf6300-d40f-11e5-8916-514c915a9bc4.PNG)
I wrote 718 but it's 717 obviously, sorry^^.

**Comment by ghost** [comment]
Damn, those are pretty screencaps, @CreeperLava :)

**Comment by KFreon** [comment]
Fixed.

**Comment by starkgate** [comment]
Confirmed to work in rev735.
