### ISSUE TITLE
rev735 Unrecognized textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#187]
Some textures seem to not be recognized in recent revs :
![sans titre](https://cloud.githubusercontent.com/assets/12874678/13155758/8cfb0b8e-d67f-11e5-9f3f-cfdc99723cc8.png)
Quite interestingly, when loaded with fewer textures, the GethPod one is not flagged anymore.
![sans titre3](https://cloud.githubusercontent.com/assets/12874678/13155757/8cf8bdfc-d67f-11e5-8505-4fc7ebd1d555.png)
The size of the textures ( size ratio of 1x4) probably isn't the cause of the problem, as other similarly sized ones don't bug. Here are the files :
http://filebin.ca/2XQKo81ieXM0/invalid735.7z

**Comment by KFreon** [comment]
Also couldn't replicate this one.
VS?

**Comment by KFreon** [comment]
Does this still happen?

**Comment by starkgate** [comment]
I'll test this one soon.

**Comment by starkgate** [comment]
![bug11](https://cloud.githubusercontent.com/assets/12874678/13393748/a54a4634-dee3-11e5-9ff0-0ef9845deeb8.PNG)
![bug12](https://cloud.githubusercontent.com/assets/12874678/13393749/a54b1276-dee3-11e5-8f3a-6707a03417c2.PNG)
![bug13](https://cloud.githubusercontent.com/assets/12874678/13393750/a54c542e-dee3-11e5-9658-2f623177f346.PNG)
![bug14](https://cloud.githubusercontent.com/assets/12874678/13393747/a54a0fca-dee3-11e5-90b9-bd75a6a1dc2d.PNG)

**Comment by KFreon** [comment]
Hrm...it's failing in ReadCompressedMipMap.
In that first image, see where it says "Locate file DDSGeneral.dds" (or something like that), click that and go ME3Explorer\Packages\CSharpImageLibrary\DDSGeneral.dds (or something like that), so it shows the exact location of the error.
Try to get the Locals and Autos windows in the screenshot too please :)

Much thanks for the testing Creeper. It's nearly super stable.

**Comment by starkgate** [comment]
I searched for that DDSGeneral.cs in windows explorer, without success. Maybe it's simply missing ?

**Comment by KFreon** [comment]
In the github download (the one you use for VS), e.g.
D:\ME3Explorer\Packages\CSharpImageEngine\src\General\DDSGeneral.cs

If it isn't there...we have some very weird issues.

**Comment by starkgate** [comment]
![capture](https://cloud.githubusercontent.com/assets/12874678/13568185/e049a32a-e45f-11e5-8d38-2f79da5292f2.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12874678/13568194/e8d607cc-e45f-11e5-89b9-887553b274d8.PNG)

**Comment by KFreon** [comment]
Ahh finally I've managed to reproduce this.
It was hiding behind another exception.

I'll see what I can do.
