### ISSUE TITLE
rev735 No thumbnails for 1 MIP textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#188]
1 MIP textures do not get a thumbnail when loaded in TPF/DDS. It's sad, really :/.
![sans titre2](https://cloud.githubusercontent.com/assets/12874678/13156116/311c2d3c-d681-11e5-8c67-44c8c64fe6ad.png)
![sans titre4](https://cloud.githubusercontent.com/assets/12874678/13156115/311c05c8-d681-11e5-92e5-f28e3af8dfc2.png)
Files : http://filebin.ca/2XQOF3r2mR2a

**Comment by KFreon** [comment]
Couldn't replicate this one. 
What happens if you run in VS?

**Comment by KFreon** [comment]
Does this still happen?

**Comment by starkgate** [comment]
No, strangely^^.

**Comment by KFreon** [comment]
Oh good.
