### ISSUE TITLE
rev735 Problems with METPFs

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#189]
METPFs created by rev735 have a different size than those of rev718, possibly due to a difference in naming (MASSEFFECT3.EXE_hash.dds in 718 vs TextureName_hash.dds in 735). More importantly, they pose problems in earlier revs.
See for yourself : http://filebin.ca/2XQbhvrMyIpU
The 735 metpf causes a NFIT error in 718. ~~The METPFs created with rev735, used for ALOT 4.0 also caused stalls for people.~~ Scratch that, it's probably caused by an error on my side.

**Comment by KFreon** [comment]
You'll find this is 100% dependent on the naming of the files.
It resulted in the log getting sorted to somewhere except the end where it belongs.

Fixed.

**Comment by starkgate** [comment]
Works in rev738, generally. I have found a few ways to break it though : 
- Rebuilding a TPF with a texture named 'whatever.dds' outputs an empty METPF, with an empty MEResults.log inside.
- Rebuilding a TPF with a texture named 'whatever_0x12345678.dds', where the hash 0x12345678 is NFIT, outputs a METPF with the texture and a MEResults.log '0x12345678|_0x12345678.dds'

I think both issues are linked, sounds like a naming problem. You were right K, changing that did bring more issues.
Files : http://filebin.ca/2XeE1etHvMk7

**Comment by KFreon** [comment]
Nice find. 
Looks like this is now fixed.
