### ISSUE TITLE
DXT5 to DXT1 conversion

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#19]
Similar to the quality loss bug report #18. In this case autofix seems to convert from DXT5 to DXT1 with alphas, which results in a black file. It should convert from DXT5 to DXT1 without alphas. Now this one isn't systematic, so I'm kinda puzzled. But DXT5 to DXT1 seems to be a real problem for the actual toolset.
![tumblr_nsgyt0fzmk1uvtk4po1_540](https://cloud.githubusercontent.com/assets/12874678/9047801/99741136-3a34-11e5-9982-21c5f63309c4.png)
This happens with these mods : http://social.bioware.com/project/8437/ http://social.bioware.com/project/8266/

**Comment by HeffU** [comment]
Unsure about how this manifests, the new conversions _might_ fix it, but we'll have to do in-game testing.

**Comment by HeffU** [comment]
Possibly fixed in e9cca0d71a80c802f9dbd8b98551718a14cb3a37, needs verification.

**Comment by HeffU** [comment]
Seems to be working well enough.
