### ISSUE TITLE
rev738 Old ME3Tree.bin not recognized

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#191]
Now I don't know if this is specific to my setup or not. I have had a few problems with my computer, had a HDD die on me and ran chkdsk multiple times. Plus I am using a fake ME3 install for now, so the problem may very well come from me. The tree I am using is exactly the same as in older revs though. Basically, this is what happens when I put my me3tree.bin in rev738, in Texplorer :
![sans titre](https://cloud.githubusercontent.com/assets/12874678/13198531/7b6547c6-d80b-11e5-8d20-af0c8e7075a6.png)
No problems with the ME1 or ME2 trees.

**Comment by KFreon** [comment]
Nothing has changed on the tree end that I can think of. 
Good thing is, that message is inside a Catch statement, meaning it'll be real obvious in VS.

**Comment by ghost** [comment]
FYI, mine works fine in Texplorer. It loads the tree structure just fine. Mine was built with rev 722, I think.

**Comment by starkgate** [comment]
Maybe it has something to do with the fact that I added EGM to the tree, then rollbacked to the old tree in rev738. If it happens again, I'll reopen this issue, but in the meantime I think we can consider it closed.
