### ISSUE TITLE
rev738 Loading certain textures stalls TPF/DDS

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#192]
I'm sorry K :/.
Loading a texture with an incomplete hash (ie 0x123456 instead of 0x12345678) stalls TPF/DDS. Of course the texture isn't valid anyways, but I thought I'd report it anyways.

**Comment by KFreon** [comment]
Think this is fixed.

**Comment by starkgate** [comment]
Confirmed to work in rev743.
