### ISSUE TITLE
Remove Camera Tool?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#194]
@SirCxyrtyx -- WV added this tool at my request, before you released Interp Viewer.

For the most part, functions seem to overlap. They might very well overlap entirely. Can you take a look? If they do overlap entirely, then Camera Tool should be removed. If they don't overlap entirely, then maybe any content that Camera Tool visualizes can be added to Interp Viewer, since obviously it's the stronger of the two tools.

**Comment by ghost** [comment]
@SirCxyrtyx -- Thought about this at all, and whether it can be removed?

**Comment by SirCxyrtyx** [comment]
Removed in 2.0.11
