### ISSUE TITLE
Interp Viewer, name change = new icons

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#196]
[Here's the link.](https://drive.google.com/open?id=0B6dpXB1BUPrvb0V5UFRNenQ0dm8)

Should be downloadable and contain everything needed. Let me know, otherwise.

**Comment by SirCxyrtyx** [comment]
Thanks! I'm traveling right now, so I won't be able to do anything development-wise until the weekend unfortunately.

**Comment by ghost** [comment]
All good. If the new stable is released before that _gasp_, then I'm sure K can get to it :)

Thanks for the heads up!

**Comment by SirCxyrtyx** [comment]
Changed Icons in 5e00ec2e089cbe7d9593cac445a06a92dc005300

**Comment by ghost** [comment]
Verified in rev742.

Looks great.
