### ISSUE TITLE
DLC Tools needs name change

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#197]
This change would compliment the change already made to the SFAR TOCbin Updater.

With the advent of DLC mods, saying "DLC Tools" is no longer descriptive enough. People are becoming accustomed to "DLC" no longer being synonymous with "SFAR". Therefore, these dev tools and menu options need to be changed to properly reflect their usage:

DLC Tools (menu) > changed to SFAR Tools
DLC Basic Editor > menu and tool name changed to SFAR Basic Editor
DLC Editor 2 > menu and tool name changed to SFAR Editor 2

I have one more suggestion to go along with this, but it should be in its own issue.

**Comment by KFreon** [comment]
Done.

**Comment by ghost** [comment]
Crap... that means I need to make icons.

Will do tomorrow and upload a download link.

**Comment by ghost** [comment]
@KFreon -- And, [linky](https://drive.google.com/open?id=0B6dpXB1BUPrvWnlWeDMzcXpxNHc) for the new icons.

**Comment by KFreon** [comment]
Hrm. I can't access that. Just errors out.

**Comment by ghost** [comment]
@KFreon -- Did you click the download icon in the top center of the page? Works for me and I'm not logged into my Google account right now.

**Comment by KFreon** [comment]
![image](https://cloud.githubusercontent.com/assets/7845997/13425254/56e6f0b4-dff1-11e5-9b03-6c0eb7229efd.png)
When I click download, I get a 415k zip file that's corrupted. The icon appears to be suitable, but the png is broken. 
Can't remember if the png is used though...

**Comment by ghost** [comment]
Wtf. Okay, that sucks; I've been trying to keep this all on the toolset's Google account I set up.

Let me try my personal Mediafire. That link I'm going to have to PM you, K.

**Comment by ghost** [comment]
Looks like this change isn't fully implemented in rev741.

Issues that remain include:
- DLC Basic Editor menu/tool name needs to be changed to SFAR Basic Editor
- New taskbar icons have to be implemented for both SFAR Tools

**Comment by KFreon** [comment]
How strange. 
![image](https://cloud.githubusercontent.com/assets/7845997/13741387/b10b69b4-ea21-11e5-8821-ec293130e2e2.png)

I wonder if I uploaded the wrong version somehow, except the other bugs are fixed.

**Comment by ghost** [comment]
@KFreon -- Yep, that's what mine looks like, too. Seems like only SFAR Editor 2 was changed. And, like I said, the taskbar icons weren't changed for either (both are still the old "DLC" ones).

**Comment by KFreon** [comment]
I think this might have to do with the translation thing again. Not sure why that would affect the icons.
I'll have a look once I get home.

**Comment by ghost** [comment]
Verified in rev744.
