### ISSUE TITLE
Add "TOC all extracted DLC" option to AutoTOC, or...

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#198]
I realize this can be accomplished by using the "Unpack All DLC" option in DLC Ed 2, but hear me out.

Use of DLC mods and extracting BW DLC is now commonplace. With r738 we've made extraction trigger upon toolset open. The basic fact is that at this point, all toolset users and devs should have their DLC extracted.

The intention of the division between User Tools and Developer Tools is that the typical user shouldn't be using any Dev Tools. However, the typical user _will_ now need to autotoc all their DLC -- frequently. Forcing them to use what's basically a fake extraction via DLC Ed2 is a bit silly. We need the ability to do this in the AutoTOC tool.

In fact, it seems like having autotoc always toc _everything_ and not just generate single TOC file would be ideal. It's simpler and will prevent issues with users forgetting to TOC one DLC but not another.

The only complication I see is if the user bypassed the extract upon opening the toolset and DLC aren't extracted. So, I'm guessing we'd need some type of check to make sure they are. Either that or, we make AutoTOC extract them -- just like DLCEd2.

One final thing. We just implemented a check for DLC extraction by using presence of a TOC.bin file in the DLC root directory. This is perfect for BW DLC and for users with DLC mods installed. However, DLC mod creators still need the option to generate this file for the first time, so the "Create TOC" with the ability to generate single TOC files will still need to be retained.

**Comment by SirCxyrtyx** [comment]
Well, now that you say it, that does seem like a pretty obvious feature.

**Comment by SirCxyrtyx** [comment]
Does "Generate all TOCs" sound like a good name for the button?

Having non-extracted DLC isn't a problem. AutoTOC just wont toc those folders.

**Comment by ghost** [comment]
@SirCxyrtyx -- Sounds like a fine name :)

**Comment by ghost** [comment]
Verified in rev742.

This works _great_. Like the new completion message, as well.
