### ISSUE TITLE
rev 738 - TPF/DDS tools 3 - Preview cache not updating when deleting textures

### ISSUE THREAD

**Issue by alvarome** [ME3Explorer/ME3Explorer#199]
Looks like while the Main Page textures list is always updated, the preview cache is not refreshed after deleting textures. 

Here you got the TPF/DDS tools window. Selected texture "Painting_03" in the left "Main page" pane shows a preview in the rigth "Preview" one. That´s ok!

<img src="https://farm2.staticflickr.com/1626/24630742104_395ecef85a_o.png">

Once more... now selected texture is "Ribbon_tex"...

<img src=https://farm2.staticflickr.com/1448/24634576423_2abb715a24_o.png>

Using the left pane "Delete Page" tab I removed Painting_03" texture...

But now, in the Main Page, if I select "Ribbon_tex" texture preview shows the next "Wall01_Diff" texture one!

<img src=https://farm2.staticflickr.com/1629/24893688869_93d5a3e010_o.png>

This behaviour is accumulative... beign more and more noticeable -and, perhaps, confusing- if you delete a few textures and select a texture that was well below in the list: here, after deleting six textures, selecting "Kassa02" texture returns "Crate_Weak_01_M_diff" preview-.

<img src=https://farm2.staticflickr.com/1481/24893688179_41081a1d6b_o.png>

HTH!
Alvaro

**Comment by KFreon** [comment]
Much thanks :D 
Tis fixed now.
