### ISSUE TITLE
r738, DLC Extraction needs pathing check

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#200]
EDIT: While the issue below was my fault and is not a bug, it does lead to an important check we need to add to this procedure:

---

Found a pretty major bug with this; glad I only reverted one DLC to test, lol.

Good news is the extraction window pops up as it should. Window itself could use a little tidying; it looks a bit lopsided on my machine; guessing this needs still improvements for the recently rectified scaling issues:

![r738_dlcextraction](https://cloud.githubusercontent.com/assets/13645804/13360407/f948369c-dc6d-11e5-9c65-6d5f54ffb14e.PNG)

Now, the problem. The extraction is handling the directories all wrong. There are 3 separate issues:
- Unpacked files are saved the the wrong directory
- Two TOCs are made; both of which are in the wrong directory
- The vanilla directory is borked, with the Default.sfar relocated to the DLC's root folder.

Here's a series of screencaps covering all 3 issues. Has nobody else experienced this?

![newdlextractionbug](https://cloud.githubusercontent.com/assets/13645804/13360631/fcf93dee-dc6e-11e5-82d0-6f9021b3f136.PNG)
![newdlextractionbug2](https://cloud.githubusercontent.com/assets/13645804/13360632/fe3b36a8-dc6e-11e5-9254-40a0a912a96a.PNG)
![newdlextractionbug3](https://cloud.githubusercontent.com/assets/13645804/13360634/0033c826-dc6f-11e5-86db-7733ba39f0fd.PNG)

I can verify that the toolset is seeing my game paths correctly, as well. At least from the Options > Known Paths dialogue. So, path detected doesn't seem to be the problem. I've actually never had a problem with toolset pathing; it's always detected my directories properly.

However, that brings me to an issue we might need to address as part of this new process.

Part of the ME3Explorer initial setup process is to verify it's detecting the game directories properly. Now that we've placed extraction before this, we need to give the player time to verify this prior to the extraction. if they don't -- and if the directories are borked -- then I'm guessing the extraction will be borked, as well.

So, I think prior to the DLC extraction window, we need a different window, called "ME3Explorer Initial Setup" or something. It displays the various paths for each game, and asks the user to verify them as correct or change therm to reflect their system. Then it moves onto the extraction... which I'm pretty sure should technically be called "unpacking", as the files are completely removed from the SFAR.

**Comment by starkgate** [comment]
I haven't experienced any of these errors with my tree building (I extracted DLCs the same way you did, through this little popup), extracted DLCs are where they should be, with the Default.sfar in their respective Cooked folders. No TOC.bin in the DLC folder either. Could these misplaced files be from an older install ?

**Comment by ghost** [comment]
@CreeperLava -- Doh.

Definitely not from previous installs, Creeper. I'm much more careful than that; I keep my directories clean, I don't have more than one install for any of my games, and I've never had to uninstall any of the 3 games. Plus, all file dates and times match each other and match the time of the extraction. So, they were absolutely created simultaneously.

HOWEVER.

I did make a mistake. From what I can tell, I copied the Default.sfar into the DLC's root folder, rather than its CookedPCC. So, that caused the problem. After re-doing the extraction, and ensuring I placed the SFAR into the DLC's CookedPCC and it works perfectly.

BUT.

It's good I made this mistake. My comments about pathing remain, and are actually verified by what happened. We definitely need to implement a pathing verification dialogue before unpacking, or it will indeed be borked if paths are off.

Thanks for saying something that make me re-check, Creep. I knew the unpacking was responsible, but it didn't occur to me that I made a simple copy/paste error :/

**Comment by KFreon** [comment]
Added some checking.
Now if the sfar isn't in a folder called "CookedPCConsole" it'll skip it and notify the user that there was a problem.

**Comment by ghost** [comment]
That's an interesting approach. Will it give the user some direction as to the problem?

**Comment by KFreon** [comment]
I'm not at my pc right now, but it says something about the pathing and the path it tried to use to the sfar is printed in the debug window. I think I mention checking there too.

**Comment by ghost** [comment]
Okie, will test once the next rev is released.

**Comment by ghost** [comment]
I think we need a little bit more work on this new feature.

Here's what the new pathing check looks like inside the DLC extraction dialogue:

![extractdlc](https://cloud.githubusercontent.com/assets/13645804/13792673/44b12508-eab0-11e5-8231-32f759afebcc.PNG)

The wiki link is a very good idea -- nice call. However, there are 3 issues:
1. There is no statement at the top of the window to say "Please verify proper pathing prior to extraction." We can put the pathing information there, but we have to prompt users to look at it, otherwise, they'll ignore it.
2. There's no way to edit the paths if there actually is a problem.
3. The entire extraction check is easily bypassed by clicking past the window to the toolset below. It does not currently force the user to make a choice. Without this, it's much too easy to bypass. At the very _least_, we have to force users to click "yes" or "no".

I also purposefully tried to fool the pathing check and had success two different ways:
1. If I totally delete the CookedPCC from a DLC, this happens upon opening the toolset:
   ![pathingproblem](https://cloud.githubusercontent.com/assets/13645804/13792860/4337bdda-eab1-11e5-846d-6338ed08e59f.PNG)
   2.If I place a Default.sfar into the DLC root and not its Cooked, the toolset doesn't realize there's a problem at all. However, I know from experience that the extraction will not work properly.

@KFreon -- What are you using for a check, btw? We had talked about using the presence of the PCConsoleTOC.bin in the DLC's root, but removing this file from a DLC doesn't trigger the check. 

Presence of PCCs inside the DLC Cooked isn't an adequate indicator of _proper_ extraction, b/c all users of the current stable who have their DLC extracted will still have TOC.bins in their SFARs. The version of Texplorer in the stable leaves the TOCs in the SFAR, which is what created all the TOCing problems in the first place. I have no idea if a simple autotoc will fix that or not. Presumably, I guess, if the tools don't attempt to TOC that still remains inside the SFAR. There also might be a problem with having a TOC both inside and outside; my guess is we really don't want to find out.

---

While I realize we can't account for every potential problem, we do need to make this a bit more foolproof to _prevent_ new problems when we release the stable. Here's what I see as the best solution:
1. Change the instructions at the top of the window to provide even more information. This is a very, _very_ important thing, which is why we're trying to get people to do it:

> Extraction will allow for proper modding of DLC. Failure to do this will prevent mods (like textures and meshes) from affecting DLC files. To prevent problems with extraction, verify your game paths below before you begin. Extraction of all DLC can take up to 3 hours. See the Getting Started Guide on the wiki for a complete explanation of these details.
1. Implement a "Browse to" feature for each game path. Without this present inside the dialog, users with bad pathing end up _more_ confused. This is b/c to change the pathing, they will have to exit out of the extraction (without extracting), manually enter into the "Set Custom Paths" dialogue, define the new paths, then close and re-open the toolset. They won't even know _how_ to do any of that without consulting the wiki directly.
2. Acknowledgement of the extraction check (yes or no) _must_ be mandatory before the toolset can be used. We're allowing people to say "no" with the red "x". We're even allowing them to turn the check off permanently if they want to. However, _when the check is triggered_, answering it _must_ be mandatory. There's room for too many problems if we don't require this.
3. If it's possible to make the pathing check more foolproof, we should. The issue with the error needs to be addressed, possibly with a dialog that clues the user into the potential problem. We also have to keep in mind users of the current stable who have all of their DLC extracted improperly. These folks need the TOC.bin files removed from the SFAR and placed in the DLC's root folder, which can only happen by failing the initial extraction check. 

I've got a couple more related things, but they belong with ModMaker :)

**Comment by KFreon** [comment]
The first error is occuring because it can't find an .sfar to look at.

There seems to be some confusion about how all this works, so here's what happens:
- Toolset opens
- Does some stuff like cmd line, THEN starts DLC Check
- If ME3 Path not found, show message and exit the DLC Check. This could be a slight issue I guess.
- Look through the ME3 DLC path for anything that ends in ".bin". These are considered "extracted", other folders that don't have ".bin" are "unextracted".
- Look through unextracted folders for anything ending in ".sfar" and get it's size.

At this point, it hasn't done any checking pathing checking or anything in regards to sfars in the wrong place or anything.

**Extract Button**
- Have Fob's function in DLCEditor2 extract all the DLC. This is where incorrectly placed sfars are detected and skipped with a note in the log.
- If any such errors occured, after extraction a message is shown.

**Cancel Button**
- Nothing particularly interesting

**NEW BUTTON for fixing pathing**
- I didn't want to implement yet another place where paths can be changed which would bring that number to about 5. 
- This button closes the DLC window and opens the path changing window.
- If the user cancels the path changing window, it cancels the DLC check.
- If the user OK's the paths, the DLC check is reopened.

**Comment by ghost** [comment]
@KFreon -- I'm sure you're frustrated with this. I know it's a pain to get right, but I do think we're almost there. Sorry, if I'm being a total pain in the ass about this; I'm just trying to do the best thing for the toolset and its users <3
1. If it's only searching for "BIN" does that mean it can pick up Coalesced.bin, as well, and not just the TOC? Folks upgrading from the stable will have to build new trees anyway, so now that I think about it, that's slightly less of a big deal.
2. Thanks for clarifying the sequence of some of the above events. That explains why it didn't realize the SFAR was in the wrong spot immediately. Got it.
3. Pathing. So, here's the thing. It really doesn't need to be in 5 spots, and I agree that's silly. We're implementing a pathing check immediately upon toolset open, which is when it should be occur; similar to when a program is installed. We also have accessible via the main menu in case it needs to be modified later on. Pathing modifications from either of these locations should apply to _all tools_, so I don't see why a paths dialogue needs to be inside specific tools. Having additional pathing checks and modification options inside Texplorer, TPF Tools, and Mod Maker seems redundant and unnecessary at this point. So... why not remove them? Cuts code and makes things simpler, right?

**Comment by KFreon** [comment]
It will pick up coalesced.bin, but there isn't one in the DLC folder is there?
Good point though, I'll make it more specific.
1. This is where things get messy. 
   The way I wanted to do things was different and incompatible with the way everyone else wanted to do things pathing-wise.
   I store all settings in a single project (KFreonLib) but the settings for other tools are spread out over the ME1, 2, and 3 projects. 
   It would be a gigantic pain to update all the other tools to point to the same place for settings.

I agree that it makes more sense to put the pathing edit there, but it makes me sad to have all this stuff to change paths and not be able to use it :P 
I'll think on it some more. Maybe there's an easy way of doing it.

**Comment by ghost** [comment]
@KFreon -- 
1. The Coalesced.bin for each DLC lies inside its CookedPCC. So, if you're checking for "BIN" inside "DLC root", then you're fine. If you're checking for "BIN" anywhere inside a DLC, then it could be problematic.
2. Well, I certainly understand the frustration if it creates more work or nullifies previous work. But, I think we should always do what's smartest and most efficient. At this point, the startup and main menu pathing seems to be the way to go. I think it's also useful to look at it in the context of the (possible) forthcoming GUI overhaul. It presents an opportunity for us to really improve on things and streamline how the toolset works. A chance to remedy some of the pitfalls that go along with the "tacked on" nature of now it evolved and instead make the program _as a whole_ work better :)

**Comment by ghost** [comment]
Something that might be relevant to this. Not sure, but I'm placing a breadcrumb here in case.

A false-positive for the warning message inside ModMaker, as it relates to extraction. See issue #140 .

**Comment by ghost** [comment]
@KFreon -- Just testing this.
1. The message is definitely clearer, with the pathing notification in red letters (also like the blinking green checkmark, lol). 
2. The "Cancel to change paths" button is good, but this isn't opening the Set Custom Paths dialogue in the main menu -- at least not on my machine.
3. I purposefully put an SFAR in the wrong place and hit the "continue" button to extract, and it kicked a pop up window at me telling me something wasn't extracted and to check the debug output. Last time I tested it, it extracted it anyway to the Binaries folder; this time it simply ignored it. Worked like a charm. Great :)

**Comment by KFreon** [comment]
"Cancel to change Paths" button removed for a in-house "Change" button which launches the old TPFTools/Texplorer pathing option, which is also now the main window -> Change Paths -> All at once option.

**Comment by ghost** [comment]
Beautiful. Verified in r745.
