### ISSUE TITLE
r738, ModMaker Help Menu

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#202]
@KFreon -- ModMaker's "Help" menu option can probably be removed, now that we have one for the entire toolset.

If you want to keep it, the link needs to be changed to the ModMaker page on the wiki, which is at:

http://me3explorer.wikia.com/wiki/ModMaker

**Comment by KFreon** [comment]
Done.

**Comment by ghost** [comment]
Verified in rev742.
