### ISSUE TITLE
New idea for Tree.bin?

### ISSUE THREAD

**Issue by knightaries** [ME3Explorer/ME3Explorer#203]
I've ran update database to rebuild my tree several times now and it keeps telling me a file or two wasn't scanned. This was on a Vanilla copy freshly loaded (Origin DL) and on backup copy of Vanilla ME3.
  I'm less concerned about the file(s) being missed but more wanting to give an idea (if Possible)
When I get the list of file(s) not scanned and it gives the option to save; is there any way to point it to the file to attempt scanning it again? I know there's an option to add DLC's but didn't know if there was a way to expand that down to an individual file for the occasions it's needed.

**Comment by KFreon** [comment]
Not at this time, unfortunately. 
It got removed due to some weird issues, and likely won't be returning any time soon.

The debug window might tell you why something was skipped.
