### ISSUE TITLE
DLC Editor 2, mod making functionalities

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#204]
Bear with the explanation. This feature in the toolset is not widely known.

DLC Editor 2's mod making functionalities were implemented back in 2013 by WV (sort of) at my request for ThaneMOD.

To jog your collective memories, this was way, way back, pre-SFAR extraction. At this time Texplorer used a TexplorerDLCache it created during treescanning, where it extracted copies of all SFAR textures. When replacing them, it first modded the texture in the DLC cache, then inserted the new texture into the SFAR, and rebuilt it during the DLC TOC to stay under the 2GB limit (which still didn't always work).

Anyway, MEHEM and CEM were the only other large mods out at that point. The VPatch method that Fob/wavion used for MEHEM was beyond my comprehension, so WV came up with a method of full-PCC replacement inside of SFARs. He did this by implementing modmaking inside DLCEd2, so I could record the PCC replacements inside it, when using the tool. This is how ThaneMOD v1.0 was distributed. The MOD files I created for the EC edited the SFAR in this manner.

Fast forward 2 years and now we're fully extracting DLC and have DLC mods. MOD files created via DLCEd2 are no longer useable by ModMaker.; they aren't even fixable. They cannot be used; 100% incompatible.

So, uh... we should probably remove this feature from the tool, eh?

**Comment by KFreon** [comment]
So what do you suggest doing?
There's not really anything to remove from Modmaker since all it does is call functions.
I can disable the function so that it doesn't do anything, but there'll be no feedback. The job just won't have an effect.

**Comment by ghost** [comment]
This isn't a job installing thing. This is a MOD creation thing.

I'm suggesting we remove the creation feature/menu option from DLC Ed 2, as ModMaker will no longer install full-PCC replacement MODs to DLC -- which is exactly what the feature in DLC Ed 2 is for.

**Comment by KFreon** [comment]
Oooooohhhh right. That's nice and easy then.

**Comment by ghost** [comment]
Verified removed in rev742.
