### ISSUE TITLE
Image Engine GUI Suggestions

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#205]
@KFreon -- Normally, this is the thing I did in the Wiki forum section, but now that we've moved to GIt, I can do it here :)

Very cool little tool you have here, btw. It's very nice for users who might need to fix textures and who don't want to dive into GIMP/PS, which can be really intimidating. Paint.NET works well and is simple, but... it's not bundled with the toolset :D

There are only two things I see that could use some improvement. One is easy, the other perhaps less so. Screenshot for reference:

![iamgeenginegui](https://cloud.githubusercontent.com/assets/13645804/13380147/a207ed4e-ddf0-11e5-88a3-5a9a6e6d4c16.PNG)

**1. The Default Button in the middle.**
Creeper astutely pointed out in the initial draft of the article, that this was to affect mipmips in the converted texture. However, there's no label to indicate this, and none of the dropdowns mention mips either. There's literally no way for the user to know what this button does without doing an actual conversion. I'd suggest a "Mipmaps" label, either above it or to the right, similar to the "Format" label.

**2. Format Names.**
My primary concern with the list of format names is consistency with what's displayed in TPF Tools and Texplorer. There's one difference, and since this stuff is confusing enough, I think it needs to be changed simply to avoid confusion:
- DDS_ARGB >> DDS_A8R8G8B8 (matches TPF Tools/Texplorer)

Also, I wanted to ask about the DDS_RGB format. This is uncompressed, I take it?

**Comment by starkgate** [comment]
ARGB seems less confusing than A8R8G8B8, or is it just me ?^^ I suppose it would make sense to have consistency, but in that case wouldn't replacing A8R8G8B8 by ARGB be more logical ?

**Comment by ghost** [comment]
@CreeperLava -- Yeah, that's logical. The thing is that in the technical documentation it's always called "A8R8G8B8" and that's also what all other image programs I've used called it (Comrpessonator, GIMP, PS, Nvidia Texture Tools, more). 

Due to that, I don't think we want to change what Texplorer displays to something less descriptive. That could potentially confuse _more_ experienced users who are familiar with the format and are used to noting this format in Texplorer, extracting the texture, editing it, and then ensuring the _exact_ same format is used upon saving in GIMP/PS.

As long as it matches TPF Tools/Texplorer I don't think A8R8G8B8 is any more confusing. The important thing is that it matches, so it's clear to the user.

**Comment by ghost** [comment]
Btw, damn that missing red channel, lol.

**Comment by KFreon** [comment]
![image](https://cloud.githubusercontent.com/assets/7845997/13491994/4e0812ca-e181-11e5-98e0-3cdd5208d1df.png)

Added explanation to the Mips setting.
Also fixed the red channel thing :)

Much too lazy to fix the ARGB thing btw.  It's just something they're going to have to figure out on their own. There's nothing else that looks like ARGB, and the effort required to change it is actually a bit.
Just note in the article that ARGB = ARGB8's etc.

FYI ARGB is entirely uncompressed. Just the exact ARGB values one after the other for every pixel.
The reason the other tools specify the 8's is because they can handle the other ARGB bit sizes. Mine probably can too, but I haven't tested, and I don't know what'd happen.
It's a bit harder to get them though, so I don't consider it an issue.

**Comment by ghost** [comment]
@KFreon -- Yeah, I knew A8R8G8B8 was uncompressed; I was wondering about RGB. I'm understanding this stuff more now, so I get now that it is, too.

Yay for the return of the red channel!

I'll be sure the wiki articles use A8R8G8B8/ARGB. I know I already use it in a table, but I'll check a couple other locations to be certain. Novices will absolutely need this info; this is not something they are going to be able to figure out on their own. All these format/compressions are very confusing.

Also, if you want, you really don't need that much text next to the MIPs button. The wiki article explains the difference, and the long string of text looks pretty awkward. "Mipmaps"/ "Mipmap Settings" or something works well. Up to you, though.

**Comment by KFreon** [comment]
I like the descriptions. It helps me remember what it all does :) 
Also, hopefully users will never need to know anything about formats and mips. 
Everything should just work in the stable.

**Comment by ghost** [comment]
Verified in rev742.
