### ISSUE TITLE
TPF Tools Help link

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#206]
@KFreon -- Just like ModMaker, this needs to be updated to the wiki article, which is now in progress!

Link: http://me3explorer.wikia.com/wiki/TPF_Tools

**Comment by KFreon** [comment]
Yaay!
Done.

**Comment by ghost** [comment]
New link works great, but I have one suggestion, K :)

The mechanic you have in place right now when clicking Help is this:

1.Click 1 = show tooltips
2.Click 2 = open wiki

What's missing is a way to _turn off_ the tooltips.

Right now, literally the only way to remove them is to click Help a 2nd time to open the wiki. Then, they will go away. What's really funny, though, is that if you move the toolset window when the tooltips are displayed, _they don't move with it_. They stay stuck to the desktop in the window's initial location, lol. So, let's fix that anchoring issue, can we?

I think the only way to solve the other problem is to implement a new Show/Hide Tooltips button that's separate from the Help button. I'm guessing you really don't want to (more GUI stuff), but they are two different features and one shouldn't depend on the other.

**Comment by ghost** [comment]
@KFreon -- Along with the above, same deal for Texplorer. There's no way to turn off the tooltips without having to open the webpage to the wiki.

**Comment by ghost** [comment]
@KFreon -- One other small bug associated with this now. The menu name still changes from "Help" to "Further instructions online" when clicked in Texplorer. It's not a huge deal, but it should be removed since it's not needed (and you removed it in ModMaker and Texplorer).

**Comment by ghost** [comment]
Verified in rev746.
