### ISSUE TITLE
Suggestion : Add more information to the DLC Extraction popup

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#209]
![f948369c-dc6d-11e5-9c65-6d5f54ffb14e](https://cloud.githubusercontent.com/assets/12874678/13381762/44fe2ba8-de64-11e5-981f-205906e3d873.PNG)
Since this window is the first thing the users will see, it would probably be good to add an explanation as to what the DLC Extraction is and why they need it^^. That and a link to the [Getting Started](http://me3explorer.wikia.com/wiki/Getting_Started) article. That way we make sure that :
1. People build their modding setup correctly
2. They have all the information they could need at disposition with the wiki

**Comment by KFreon** [comment]
A reasonable request.
Done. If the text isn't suitable let me know.
