### ISSUE TITLE
rev738 Buggy MIP creation

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#210]
It took me a while to understand what was going wrong here. Basically, MIPS created by 738 seem to be stored in the .dds file (ie the file size goes up), but they are not recognized by any tool I have access too, not even by ME3Explorer itself. Which means, if you autofix-extract-load again, me3explorer will ask you to autofix the file you just autofixed. This has been tested for ME2, it may be different for ME3.
Test files : http://filebin.ca/2YdJhOivTQw9

Quite the interesting debug output too (it is a 'duplicate' texture) :
13:07:05:  Fixing: HMM_HGR_SHP_FBDi_Diff
     FORMAT -> Current: DXT1  Expected: DXT1
     MIPS -> Current: 1  Expected: 10
13:07:06:  Fixing: HMF_ARM_HGR_FBDi_Diff
     FORMAT -> Current: DXT1  Expected: DXT1
     MIPS -> Current: 12  Expected: 10

No debug from VS.

**Comment by starkgate** [comment]
Other test files, this time not a duplicate texture : http://filebin.ca/2YdP9Wusnko5

**Comment by KFreon** [comment]
Fixed I think.
I hadn't actually finished implementing the Default setting.

**Comment by starkgate** [comment]
So it is the same function for Image Engine and TPF/DDS ? I forgot to mention it, but this was experienced in TPF/DDS.

**Comment by KFreon** [comment]
Yeah when the toolset/user selects Default as the mipmap option, the tool wasn't doing the generating part of Default. 
It saw Default and a single mip and forgot to make more, but flagged the low mip fixer to do it's thing.
That's the bit that makes sure the sub 4x4 mips are the right sizes.

So I reminded it to make mips when necessary.

**Comment by starkgate** [comment]
Confirmed to work in rev743. Well, ish. The MIPs are recognized by ME3Explorer rev743, but not by GIMP. ie I can't see how the MIPs look in GIMP, whereas I can with other revisions.
![717](https://cloud.githubusercontent.com/assets/12874678/13899245/b7d47d14-ede9-11e5-8abd-46501c010fbd.PNG)
![743](https://cloud.githubusercontent.com/assets/12874678/13899246/b7d51364-ede9-11e5-8a4b-ccecb19f82c1.PNG)

**Comment by KFreon** [comment]
I can't figure out why this would be.
Every other tool opens them fine, mips and all.

The Compressonator and dxtex.exe (part of the DirectX tools) open them and display mips fine, so maybe just have to use those. 

Sorry :(

**Comment by starkgate** [comment]
Image Engine can definitely open these, indeed. Maybe you forgot to set some weird DDS flag ?
I made a comparison of 717, 743 and PS DDS' with DDS Checker, here are the results : http://pastebin.ca/3406295
The only differences between the 3 are : DDSD_LINEARSIZE (absent in 743), dwPitchOrLinearSize (also absent in 743, probably linked to the LinearSize).
The more important difference seems to be this line :
743 -- dwCaps  : 0x00001000 - [DDSCAPS_TEXTURE]
717 and PS -- dwCaps  : 0x00401008 - [DDSCAPS_COMPLEX] [DDSCAPS_TEXTURE] [DDSCAPS_MIPMAP]

**Comment by KFreon** [comment]
Ughghgh that's the one alright. Fixed now.
