### ISSUE TITLE
r738, TPF Tools, Cannot select multiple textures in Main Page

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#211]
@KFreon -- This is a weird one. You recently fixed an issue where selecting a PCC on the right would de-select the texture on the left. This has been fixed.

However, now, I cannot select multiple textures in the Main Page. I can't Shift+Click, Ctrl+Click, or drag and highlight. There is no way for me to select more than a single texture at a time. Shouldn't there be a way to do this? What if I wanted to "Save Selected to TPF"?

Creeper insists he can select more than one thumb at once. Creeper, are you certain? With r738?

**Comment by starkgate** [comment]
Oooh you meant on the main page... That's why I didn't understand, I thought you were having problems with the delete page. I think multi-selection has never been available for the main page. It would definitely be something to think about if the delete page is to be removed, but for now I don't see much use for it. If you wanted to save specific textures as a TPF, you'd just drag&drop the right DDS' from Windows Explorer.

**Comment by ghost** [comment]
> If you wanted to save specific textures as a TPF, you'd just drag&drop the right DDS' from Windows Explorer.

Well, sure... but what if you want to save selected textures from a TPF into a new one? This feature is available in ModMaker (Save selected to .mod). Is this actually not doable in TPF Tools? You'd have to extract the ones you want, clear the files, reload the DDSes you just extracted, and then re-save to a new TPF? That seems... strange.

**Comment by ghost** [comment]
And, to clarify, this CAN be done in the current stable. You can Shift+Click and Ctrl+Click:

![tpftools_selectsome](https://cloud.githubusercontent.com/assets/13645804/13403923/3dd9cd74-decc-11e5-868d-6f0854352d68.PNG)

So, yeah... "Save Selected to TPF"/"Extract Selected"/Install Selected", please!! :D

**Comment by KFreon** [comment]
I've done away with the tabs and just have one page again.
There's now checkboxes next to each texture and I've changed the context panel to operate (mostly) on checked textures.

![image](https://cloud.githubusercontent.com/assets/7845997/13491914/dd6e5d4e-e180-11e5-8361-938c215baa50.png)

I'm pretty happy with it.

**Comment by starkgate** [comment]
Looks good ! Hopefully it won't break too many things^^. I'll do some testing once the new rev is out.

**Comment by ghost** [comment]
Looks great!

Right away I looked for the check/uncheck all buttons. Very nice :)  Ooooh, and I see you implemented the "extract/build selected" feature. Wewt!!

**Comment by ghost** [comment]
This works perfectly. Really nice job, @KFreon , especially with the new spacebar-select thing.

Verified in r747.
