### ISSUE TITLE
r738, TPF Tools Replace feature needs additional checks

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#212]
@KFreon -- It's possible to bork things a bit using this feature. 

I was able to do the following:
1. Load a PNG for a codex image that was 512x256 (vanilla size)
2. Autofix that PNG into a DDS/DXT1. No mips added. Good.
3. Use Replace to replace it with a 512x512 PNG of the cabin photo.
4. Autofix that into a DDS/DXT1... that remained 512x512.

So, at step 3, the toolset should have thrown an error, saying "improper size" or something. We shouldn't allow users to replace a texture that has different _proportions_ from vanilla.

**Comment by starkgate** [comment]
Is it really useful to keep the replace function anyways ? I never used it, no idea what use you could find for it.

**Comment by ghost** [comment]
I can see it being useful.

Say you load a TPF with a dozen textures and like all but one or two. If you happen to have others you'd rather use, then you can just quickly replace them. Basically, for mixing and matching textures in different TPFs it could definitely be handy.

**Comment by KFreon** [comment]
I tossed up whether to add it back when I did. Still don't know if it's worth it, but anyway. 
Added the dimension check for replacement.

**Comment by ghost** [comment]
@KFreon  -- I think this works. It now gives me a <---- DIMENSIONS ----> flag and sees the replacement texture as invalid. I'm not going to try to install it, but the flag should prevent it.

Nice. Verified in r747.

**Comment by ghost** [comment]
FYI, this is broken again in rev749. New issue created to keep things clean with the stable.
