### ISSUE TITLE
r738, TPF Tools, Remove "Save valid to MOD"?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#213]
It seems like we need to ditch this feature. 

MODs have been deprecated for textures since TPF Tools was made. We've specifically telling folks not to use texture MODs, so if that's the case, it seems counter-intuitive to retain this feature in TPF Tools, that allows folks to create them.

In addition, related to issues #207 and #211, the space for this in the GUI could be used for "Save selected to TPF" or something of the sort.

**Comment by KFreon** [comment]
EDIT: Wrong thread.

This button is removed.

**Comment by ghost** [comment]
Verified in rev742.
