### ISSUE TITLE
Better zooming in Sequence Editor

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Explorer/ME3Explorer#215]
Right-click and drag is not intuitive in the least. Mousewheel zooming and/or a zoom level button would be great.

This is basically a note to myself, I know, but maybe making this an issue will get me to finally fix this.

**Comment by ghost** [comment]
Oh god, yes, please.

**Comment by SirCxyrtyx** [comment]
Now I remember why I didn't do this a couple years ago. This was a huge pain. But it's done now and should be commited soonish.

**Comment by Mgamerz** [comment]
Thank you. Zooming on a touchpad was near impossible. Especially on a Mac.

**Comment by Mgamerz** [comment]
Also, can you make sure you have both (or maybe a ctrl +/-  keyboard shortcut to zoom like browsers)? Without a wheel, zooming would still be pretty difficult on a touchpad.
