### ISSUE TITLE
DoDLCCheck() is called before command line options have parsed (breaks command line)

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#216]
I have tools that automate ME3Explorer from the command line, such as TOC editor updates and stuff. The DoDLCCheck() is run in the Form1() constructor, which runs asynchronously it appears. This causes a GUI to try to appear from command line, which breaks command line access. 

This can be fixed by moving DoDLCCheck() to Form1_Load after the if statements for command line access. Once command line programs have finished loading, the program exits, so it never even loads the frame. For users there would be no noticeable change.

**Comment by KFreon** [comment]
A fair point.
Mods from cmd line have been disabled for now though due to lack of the DLC check.

Something you might have to note to your users is that this could cause problems down the line if they're doing anything affecting DLC.

**Comment by Mgamerz** [comment]
What do you mean doing anything affecting the DLC? (and mods disabled due to lack of DLC check?)

It's not that big of a deal, once you reach stable I will probably fork the code and make a few minor tweaks and distribute it to my users as an update. Trying to keep my versions as close to vanilla as possible.

**Comment by KFreon** [comment]
Well the reason we did this in the first place is to stop the weird issues where mods would affect dlc but the dlc wasnt extracted, and the weird things happened. 
Also toc'ing from my tools works on the premise that all dlc is extracted.

if you don't use/rely on those, then i guess there's no issue.

**Comment by Mgamerz** [comment]
I don't. The command line tools take paths to files. My tools don't typically work on a  mod that is installed, it does it externally from me3. There isn't many, only autotoc, toceditorupdate, dlcfileadd, dlcfileextract, dlcunpack (unpack specific dlc) and dlcinject if I recall.

**Comment by Mgamerz** [comment]
I don't have an issue with the dodlccheck screen (besides being unable to turn it off). For command line though, I think one can assume they know what they are doing. Plus the UI never pops up and it can't really install mods in the sense like texture mods and such.

**Comment by Mgamerz** [comment]
Wrong click. Sorry.

**Comment by Mgamerz** [comment]
Fixed by 8c2aac1

Thanks for fixing this KFreon.
