### ISSUE TITLE
Suggestion: tree.bin plain text report / export

### ISSUE THREAD

**Issue by alvarome** [ME3Explorer/ME3Explorer#217]
Hi:

Knowing that every tree.bin file created by Texplorer contains exact and detailed info of every texture included in an scanned vanilla game, I´m just wondering if there is any way to get that info -or part of it- in simple plain text -.csv file, in example-.

I was thinking in some kind or report or export to editable text file including texture info already stored at the tree and shown at the properties pane in Texplorer:

Texture name / Format / Width / Height / Texmod Hash / LODGroup

I think it would become useful to find reusable or portable textures among games, in example. Matching hashes is the quickest way to identify those... and then you could move on and continue comparing formats, sizes...

-Sometimes you find textures in different games sharing hash but with different sizes, i.e.-

LODGroup could be useful as a simple way to determine if texture belongs to characters, environment, effects...

Having all that info in simple text comma or tab separated values could be then imported into Excel / Access or the like for game trees comparisons.

HTH!
Alvaro

PS Beign every tree.bin file a database file by its own, perhaps there is an easier workaround to this using an ODBC to open it -?-. 

EDIT --> Please, discard the lastest ODBC idea -even if possible- for the high risk of altering (damaging!) the tree.bin.

**Comment by KFreon** [comment]
Unfortunately I don't store the LODGroup or the texture dimensions.
I can do so for the WPF version, whenever it comes out.

**Comment by alvarome** [comment]
Kf, I have no idea about what´s stored -or not- at tree.bin. I just took as example info available trought Texplorer properties pane.

Anyway, for the suggested purpose, to have a report of scanned textures including name, format and hash is much, much  more than we have now! ;)

As always, thanks you for you help here!
Alvaro

**Comment by starkgate** [comment]
I don't think it is necessary to get the LOD or texture sizes for what we plan to do. Having the names and hashes would be enough.
Subsidiary request here : Would it be possible to extract all textures of the tree at once ? Or even better, if you have time, to extract the textures that correspond to a list in a .txt file ? I know this is a very specific request, I would totally accept it if you don't want to develop it^^.

**Comment by KFreon** [comment]
Bit specific there Creeper for any kind of menu.
All the groundwork is there though. 
It'd be a good intro to the toolset though... _wink wink_

**Comment by starkgate** [comment]
A very good point, I'll try to look into it^^. You have to know though that for now I am learning Java with javas'cool (very bad pun) and the extent of my knowledge only goes up to [turtles](https://en.wikipedia.org/wiki/Logo_%28programming_language%29 turtles). I should have a turtle do it for me.

**Comment by KFreon** [comment]
Great news then!
Java and C# are very similar.
C# is just better.
_shots fired_

**Comment by starkgate** [comment]
I actually agree with you, java seems very messy when compared to the C++ I did before, out of school. So the toolset is written in C# ? I suppose it isn't too different from C++. Hopefully I won't destroy it^^.

**Comment by KFreon** [comment]
Ooo C# is much closer to Java than to c++.
C++ looks messy to me, but each to their own. 
Have fun! :D

**Comment by SirCxyrtyx** [comment]
When I started working on the toolset, I'd hardly even heard of C# before. My prior programming experience was C++, Ecmascript, and Actionscript 2. You'll do just fine. C# is lots of fun.

**Comment by KFreon** [comment]
Gonna close this for now guys. 
Jump on chat or the forums for interesting coding chats :D
