### ISSUE TITLE
Intepreter2: Taskbar Item / Status bar indiciation of what is being viewed

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#218]
I don't know how feasible this request is, but making Interpreter2 part of the taskbar would be very useful... it is very easy to lose when you have multiple parts of ME3Explorer that you are switching back and forth from. I don't know if it is strongly tied to the spawning task.

Additionally, I think there should be some indiciation of what you are viewing in Interpeter 2. For example, what am I looking at in the following pic?

![image](https://cloud.githubusercontent.com/assets/2738836/13560394/db4e659c-e3db-11e5-85a3-0e57e4407174.png)

PCCEditor2 has a pretty good example of this.
![image](https://cloud.githubusercontent.com/assets/2738836/13560428/2a172d58-e3dc-11e5-8d09-ef4593b301a9.png)

(Pic is from my xbox me3explorer fork but still applies)

I don't think it is too much work to list what export is being interpeted, because the scanner uses this code to start the scan.
`readerpos = PropertyReader.detectStart(pcc, memory, pcc.Exports[Index].ObjectFlags);`

I assume one could read the name of the export and list that or something. I don't know how KFreon's interpreter works though, I've never looked into it.

**Comment by SirCxyrtyx** [comment]
Not sure if I can make it part of the taskbar, I remember having trouble doing that for opening the PCCEditor when opened from the InterpEditor. I'll look into it.

I can definitely do the second request though.

**Comment by SirCxyrtyx** [comment]
Say, @giftfish, I don't suppose I could trouble you to whip up an Interpreter icon? Adding it to the taskbar is easy enough, but it'll need an icon.

**Comment by SirCxyrtyx** [comment]
How does this look? I've got the Class name, index, and file name.
![image](https://cloud.githubusercontent.com/assets/5533111/13627386/e97aec36-e57e-11e5-94b8-dde098202696.png)

**Comment by Mgamerz** [comment]
Can one interpet anything besides an export? Might want to list it as export index 746 if so. Otherwise looks pretty good.

**Comment by ghost** [comment]
Sorry @SirCxyrtyx , just saw this now and yes, I can whip up an icon tomorrow. I'll add it and then reopen the issue once I do.
