### ISSUE TITLE
rev739: Texplorer - missing game indicators and toogle button

### ISSUE THREAD

**Issue by alvarome** [ME3Explorer/ME3Explorer#219]
Hi:

Texplorer not showing neither game indicators nor toogle button at top right, no matter the window size.

This issue is related to Texplorer only and not to TPF/DDS Tools -that is showing those properly-

Here you got a screenshot comparing Texplorer to rev738:

<a data-flickr-embed="true"  href="https://www.flickr.com/photos/120029478@N08/25053569094/in/dateposted-public/" title="rev739_texplorer_window_01"><img src="https://farm2.staticflickr.com/1546/25053569094_945d7f84dc_o.png" width="659" height="675" alt="rev739_texplorer_window_01"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

Suggestion here: in any case that behaviour could be related in any way to the newly introduced  "export tree as csv" option at the main menu, perhaps it could be moved as a submenu of the already present "Tree I/O" menu. In fact, is a tree output operation, isn´t it?

Then, "Tree I/O" menú would include two submenu items: 

--> "import/export/ tree -action automaticaly triggered when choosing that menu item now- 

--> "export tree as csv" 

HTH!
Alvaro

**Comment by KFreon** [comment]
Done.
This scaling is really getting ridiculous.
