### ISSUE TITLE
r741, Texplorer, ME2 Game Path/Tree indicators swapped?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#220]
Pretty sure this is what's happening. I just copied my ME3 tree and thumbnail cache into the folder for the new rev. The debug window output seems to be correct: The ME2 path is detected and there is not a ME2 tree. 

But, the indicators say the reverse:

![icon_mixup](https://cloud.githubusercontent.com/assets/13645804/13724345/3a745324-e837-11e5-9f81-65df2e00c171.PNG)

This had otherwise been working perfectly in recent revs.

@KFreon -- Btw, am I remembering some recent change you made to how the thumbnail cache works? I've gotten used to copying over my cache along with my trees. Will this still work? 

Also... what's the "0" that's under "Modding ME3" and is getting cut off?

**Comment by starkgate** [comment]
The 0 corresponds to the number of textures that the search function found. If you don't search anything, it defaults to 0.

**Comment by ghost** [comment]
Ah, okay.

Looks like K needs to tweak it's location, lol.

**Comment by KFreon** [comment]
That 0 is supposed to be hidden under the search bar. Minor thing that I'll get to if I can be bothered beating my head against the winforms wall.

So...where it says Trees is actually the game indicators? Deary me...

There's no changes to the thumbnail cache that I can think of. Just the way it's created. It shouldn't trigger any game or tree detection either, just fyi.

**Comment by KFreon** [comment]
Whoops. The order was: Tree1 Game2 Tree3, Game1 Tree2 Game3. 
Fixed now :)

**Comment by ghost** [comment]
@KFreon -- Ha ha. Thanks :)

Man, I really can't wait to work on a GUI overhaul. I have so many ideas. Plus, it would be the perfect chance to use the new Toolset Dev section to put up mock ups of various design ideas.

**Comment by ghost** [comment]
Verified in r742.
