### ISSUE TITLE
r741, Texplorer completion message

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#221]
Any way that you could move this to trigger upon completion of TOCing, @KFreon? 

Right now it triggers upon replacing the texture, but the program is still TOCs everything in the background for a good 15-30s. I clicked to close the tool and it told me background tasks were still running, which upon looking at the debug window, I discovered was the TOCing.

Basically, if we're going to give folks a heads up that "it's done!", then it should really be done.

Btw, didn't it used to provide TOCing status on the progress bar? That would be good to put back in. That way it's reflecting what's really going on. I think you removed it when we were working through all the DLC and TOCing changes.

**Comment by KFreon** [comment]
Really? How strange...it definitely should be waiting before it says "Finished".
I'll get on that.

Also all it used to say was "TOCing. Please Wait..." or something like that. Getting actual progress isn't really feasible.

**Comment by ghost** [comment]
@KFreon -- Yeah, it's the "TOCing, please wait" that it used to do. That would be perfect :)

**Comment by ghost** [comment]
Verified fixed in r745.
