### ISSUE TITLE
r741, Manage TLKs not sticking; window priority

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#222]
@SirCxyrtyx -- I want to say this is a new issue; I think I specifically tested this on first release of the TLK Manager and they stuck fine, but now they don't.

In r741, the contents of the TLK manager reset every time the tool is closed. So, suggestions:
1. Have them stick across tool sessions.
2. Have them be cross tool?

I've been trying to think of a situation in which I wouldn't want the same TLK list to be used across different tools, and so far I can't come up with one. I can't see any advantage to the Dialogue Editor and Sequence Editor not using the same list, for example. So, if it's possible to set up the list inside one tool and have it be used across tools, I think that would be ideal.

Another thing I'm experiencing is the TLK window wants to hide behind the main toolset window. Each time I navigate to select another TLK and the tool pops me back out, the window gets buried and I have to reselect it.

Btw, I'll create an icon for this, as well since it's using the little generic icon. Give me a few.

**Comment by ghost** [comment]
@SirCxyrtyx -- Here's the download for the [TLKManager and Interpreter icons](https://drive.google.com/open?id=0B6dpXB1BUPrvMk9pRVhrN1Zfa3M). Let me know if you have any problems with the link :)

**Comment by SirCxyrtyx** [comment]
Funnily enough, making the loaded tlks be cross tool results in much simpler code. Should have done it this way in the first place.

**Comment by ghost** [comment]
Ah, glad it was a good idea, then. 

I sat for a bit and had a think about why you made them separate in the first place, as to what advantage there might be to having different tools use different lists (and therefore be capable of following different priorities). I still can't come up with anything, so hopefully nobody else does either... now that you are indeed changing the code, lol.

**Comment by ghost** [comment]
@SirCxyrtyx -- This is working beautifully; the shared TLK, retained across sessions, and the window priority.

One more idea. What do you think about implementing a taskbar icon? It would help in the case the window does get buried.

Also, interpreter icon looks great.

---

Verified in rev742.
