### ISSUE TITLE
Remove redundant Taskbar Icon Text 

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#223]
@SirCxyrtyx , guessing this suggestion would be up your alley.

@HeffU and I talked about doing this back when I _started_ making icons for everything, but we needed to hold off until every tool was finished. Now that they are, there's really no reason for taskbar icons to continue to be accompanied by text; this text was there _solely_ b/c not every tool had an icon. Removing the text will allow users to fit more icons on the taskbar at once. Yay.

Let's remove the text :)

![taskbar_text](https://cloud.githubusercontent.com/assets/13645804/13730489/034455d4-e90e-11e5-8d8e-97169fe414e4.PNG)

**Comment by Mgamerz** [comment]
On high DPI monitors, if the user has not set up windows scaling it will be very difficult to read due to the aliased text on the image. At least have tooltips on the taskbar buttons to indicate what they are if the text is removed.

**Comment by ghost** [comment]
@SirCxyrtyx -- This is AWESOME. Did you add blue highlighting, too? I don't remember that.

Verified in r742.
