### ISSUE TITLE
r741, Image Engine wrong/lacking icons

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#224]
@KFreon -- Just need to implement the following:
- Upper left icon inside the tool
- Taskbar icon

Icon in the main menu is fine.

**Comment by ghost** [comment]
@KFreon -- Oh, and I should be clear, I made the Image Engine icons a while back, so you should already have them. If not, the link is probably in our PM thread on the ThaneMOD forum; let me know if you need me to pop it up here for convenience.

**Comment by KFreon** [comment]
I don't think ImageEngine uses the taskbar as it's a pop out tool.
I guess it can if you want.
Also, I'd rather not change the icon in the top left since it doesn't belong to the toolset, it's just used there.
Happy to change the menu icon though.

EDIT: Oh it already was.

**Comment by ghost** [comment]
@KFreon  -- FYI, Texplorer and TPF Tools are "pop out" style as well, but they still have taskbar icons.

Not sure what you mean about it "not being a part of the toolset". I get that you created it so it may also exist outside of the toolset, but when bundled with the toolset it becomes a part of the toolset. As such, it's icon should coordinate with the rest of the tools. If we treated every tool individually, things turn into a mess... aka, what the current stable looks like.

**Comment by KFreon** [comment]
Orly? I can add the taskbar icon then. For some reason I didn't before.

I wrote the ImageEngine outside of the toolset for various reasons. The toolset doesn't own texmod, it doesn't own the .NET framework.
If we bring in other tools from other projects, we can change everything related to them in the menus, but the tool itself has it's own icon.

The icon is updated in the taskbar and the menus, just not the top left of the actual window.

**Comment by ghost** [comment]
@KFreon -- Sure, it doesn't own Texmod or NET Framework, but we also don't use either one as _tools themselves_. That's a big difference. Image Engine is used as a full, independent tool inside the toolset. It's not run inside anything else -- it's not like Texmod.exe, which is just an executable run from inside TPF Tools so it can generate TPFs. When inside ME3Exp, Image Engine is a toolset tool. Just like PCCEd2, Sequence Editor, Texplorer, BIK Extractor, or any of the 50 other tools.

My only point is that by your logic, anyone who makes a tool for the toolset can say, "I don't want my icon changed.". At that point, the toolset loses a certain amount of GUI cohesiveness. It's one thing to have that be the case for an OS; of course any Android app will have its own icon. But, it's something else, when it's all a part of the same program. Despite the toolset's modular nature, all tools are still run under the "ME3Explorer" program umbrella.

I get if you want the icon for Image Engine to remain in its current state when outside of the toolset. It's your program, you built it, and that's totally understandable. But, it seems like for the EXE inside the toolset, it wouldn't be that big of a deal to simply recompile it with the toolset-specific icon. If I understand correctly, this literally takes about two seconds using a program like Resource Hacker. I'm sure it's similar for VS or whatnot.

**Comment by KFreon** [comment]
The way I see it, PCCEd2 can't run by itself outside the toolset. It needs all that stuff.
It is exactly an executable like texmod, run from inside. It just has it's own menu entry as well.

As for your second point, what I'm saying is ImageEngine ISN'T part of the toolset. It's more akin to that android app. It's just getting used on the OS.

I get why you want it this way, and it would normally be as simple as recompiling it if was part of the toolset. However it's a nuget package, which means anyone, anywhere can use it as they want. I'd have to make a SECOND nuget package just for the toolset, which defies the purpose of nuget packages.

That little icon up top is hard to see anyway, and I feel the menu and toolbar icons are the important ones.

**Comment by SirCxyrtyx** [comment]
Given that it's a nuget package, and that it _is_ just the tiny little icon in the upper left corner, I think it's fine the way it is.

I would suggest re-ordering the User Tools > Textures menu to be 
- TPF Tools
- Texplorer
- Image Engine

as that is in order of most  to least used (I think)

**Comment by ghost** [comment]
Okay, I surrender, keep the bloody icon in the upper left the way it is, lol. Nobody can accuse me of not arguing my point to my greatest ability, ha. 

/offers K a beer

I would suggest that we leave the submenu alphabetized, though, like all other submenus. Seems weird to just change one to be like that. Plus, if we do overhaul the GUI, that will change, anyway, as Image Engine will be relocated to "Utilities", since that's what it really is :)

**Comment by SirCxyrtyx** [comment]
Oh, I had no idea the submenus were alphabetized. Shows how much I pay attention. Well in that case, I'll close this, since the taskbar icon part has been done.

**Comment by ghost** [comment]
@SirCxyrtyx -- Yeah, that was actually the first part of "tidying up" the GUI as the new wiki got started and I began to make icons for everything :)

**Comment by ghost** [comment]
Verified in rev744.
