### ISSUE TITLE
Cannot build project due to references

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#225]
It looks like somewhere after 738 things such as PLayer and UMD came up in some of the tools code, as what looks like part of a refactoring. It looks like the references in the csproj are using full paths rather than relative paths. You think the developers of visual studio would figure it out someday...

Edit: It appears the piccolo reference points one folder off from what it needs to be.

**Comment by SirCxyrtyx** [comment]
Looks like I referenced Piccolo as a dll in the output folder instead of as a project in the solution.
