### ISSUE TITLE
DLC Extractor window is not the correct size at 96dpi

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#226]
![image](https://cloud.githubusercontent.com/assets/2738836/13766917/9420eebe-ea2b-11e5-95d2-9a9c985cf450.png)

Don't think this is how the dialog is supposed to look. The buttons are out of the frame size.

I am unsure of how window sizing in C# works, but I know in java you don't have to specify the size of the frame, and it will automatically pack it to the correct size. Is that possible for this window in C#? This has no forms or anything complex in it.

**Comment by Mgamerz** [comment]
Hate to be that guy but building the latest copy (I think this is post 742) at 96dpi now does this.
![image](https://cloud.githubusercontent.com/assets/2738836/13799882/34635174-eae9-11e5-9d23-c6d4c465a82f.png)

**Comment by KFreon** [comment]
Oh WPF, don't do this to me.
I will burn Redmond to the ground over this DPI rubbish.

**Comment by KFreon** [comment]
Ok so apparently setting things to Auto isn't how it's done.
Setting "SizeToContent = WidthAndHeight" is the way to go.

**Comment by Mgamerz** [comment]
I'll check it out when I get home today.

**Comment by KFreon** [comment]
It's not actually on the server yet. Haven't synced.

**Comment by Mgamerz** [comment]
Looks good, back to normal.
