### ISSUE TITLE
Image Engine, Mipmaps slider tweak?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#230]
Just tossing this up as a thought/suggestion, K.

The mipmaps slider on the right side of the initial window is fun, but I'm not sure it has any real use. 

If it actually showed accurate pictures of the mipmaps as you switched between each one, that would be useful -- similar to how the layers of mips look in GIMP/PS.The problem is that accuracy is lost due to scaling the mip to fill the screen. It's also impractical, b/c it actually hinders the viewer from seeing anything useful. They just see a progressively worse blur.

So, I guess there would be 2 ways to change it:
1. Totally remove it. Just display the numbers of mips present.
2. Remove the scaling feature so the player sees the mip at the _actual_ size. This is more accurate, as the player then sees how big the mip really is. 

Functionally, the second approach would look identical to viewing the image dialogue in PS/GIMP and progressively hiding each layer until the smallest is reached. Each mip would be anchored to the upper left corner.

**Comment by starkgate** [comment]
I agree with the 2nd option, I see no reason to actually remove this feature. What would be interesting though is to add the possibility to zoom in on the displayed picture. Useful to check for MIPs or compression artefacts.

**Comment by KFreon** [comment]
I too don't want this removed.
I'd like zoom as well and I'll look into it, but no promises.

To elucidate:
- This tool shouldn't be needed to be used by users; It's basically a developer tool.
- It's supposed to be for displaying Mips for the precise reason of seeing how many/what condition they're in.
- It loads a smaller mip first so you aren't waiting around for the larger one. I added this because on slower machines, it could take something like 10 seconds to load a 4k image. 
  Absolutely unacceptable, so now it loads a small one so you can tell what you're looking at, while loading the bigger one in the background.
- It should switch to the full size when available. This isn't happening?
- Scaling is necessary for most as how are you going to see anything useful in a 4x4 mipmap? I realise this isn't a useful size, but it helps to be able to see pixels/quality.

**Comment by ghost** [comment]
@KFreon -- Well, it is a User Tool, though. Not only b/c we've put it in that section of the toolset, but b/c if users have problems with autofix or something else, we recommend Image Engine to them.

I'm not saying the feature needs to be removed, but I just don't see how this is useful:

![imgengineslider](https://cloud.githubusercontent.com/assets/13645804/13835561/47120554-ebb6-11e5-9d80-be3818b3563c.PNG)

Especially when there is no way to zoom out on that texture (without switching to the next mip). But, if you're saying that's what it's supposed to look like, and you are saying that is somehow useful for texture editing, then.... well, okay. I'm not the world's authority on making textures, that's for sure, but I've had to make some, and seeing that above, just doesn't seem helpful. Not in this sense. If I'd be doing some handpainting or something -- then yeah, sometimes I need to see individual pixels. But, for this purpose, I'm not sure why it's needed.

Like I originally said, it was just a thought/suggestion. Maybe it's just my inexperience talking.

**Comment by KFreon** [comment]
The tool belongs to the original project it comes from which is a general image viewer and converter, thus it needs to display all useful image information, not just ME3Explorer useful information.

I included it in the toolset to enable manual conversions to replace DDS Converter, not expecting it to ever get used, except maybe for viewing something weird.

Seeing mips/images at their real size is often annoying to me, but in this case, the point is to show what the image looks like. The people who use it for things other than converting will know the dimensions and how that works and stuff. 

If we want to move it to Developer Tools or something, I can do that, I just don't think it's necessary.

**Comment by ghost** [comment]
@KFreon -- I think it's better suited where it is if only b/c that's where all the texture-related stuff is, so that's where folks will look for it. I definitely don't think we should move it.

I guess other than that, we can just agree to disagree on this one. If you want to leave it as is that's entirely up to you. I just figured it was worth a brief discussion :)

**Comment by KFreon** [comment]
Righto, well I'll close this for now.
If people are using it and somehow get super confused or something, we can reopen the discussion.
