### ISSUE TITLE
ModMaker, Change Extract Destination Window

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#233]
This is a **huge** pet peeve of mine, b/c it's just so unnecessary.

A select few "Save As/Open" windows in the toolset have this, more dated, _much_ less useful format:

![modmaker_extractwindow](https://cloud.githubusercontent.com/assets/13645804/13791193/23f53306-eaa9-11e5-8062-f6bb97b22adc.PNG)

I would give you my first born to never see this type of window again. It is a royal pain to have to repeatedly navigate through drives and folders.

Instead, it should look like this:

![modmaker_openwindow](https://cloud.githubusercontent.com/assets/13645804/13791230/51708bc8-eaa9-11e5-9e60-97fa1e508b5f.PNG)

This window has the nice sidebar of shortcuts & Favorites that retain their open/closed structure, so you don't have to _repeatedly_ spend 10 minutes expanding dropdowns to locate your destination. In addition, it allows for the nice single-line instructions in the upper left.

Note that ModMaker uses both window types. The bad for _Extract Data_, and the good for _Load/Save Selected to .mod_. Can we please, please, _please,_ only use the latter type? <3

**Comment by Mgamerz** [comment]
The top one is a folder chooser, the bottom one is a file chooser. One could probably hack the file chooser to only accept folders, but it may not be as intuitive as one would expect (would have to prevent going into empty folders)

**Comment by Mgamerz** [comment]
@KFreon 

Here's some research if you want to look into this. http://stackoverflow.com/questions/31059/how-do-you-configure-an-openfiledialog-to-select-folders

On my fork I looked at the Windows API Code Pack and it is available as NUGET but it seems really dated, though it was easy to make the file chooser (accept folders only) work well.

**Comment by KFreon** [comment]
Femshep is correct. The old school crappy folder dialog is the only real way of choosing a folder.
I've been meaning to look into an alternative for a while, so I guess I will now.
Reeeally don't want to have to write my own though.

**Comment by ghost** [comment]
So much yay here.

Verified in rev744.
