### ISSUE TITLE
Interpreter2: Incorrect display of 1-element arrays

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#238]
I'm having trouble reproducing this reliably, but 1 element arrays seem to semi-break the display of Interpreter. 

![image](https://cloud.githubusercontent.com/assets/2738836/13801301/35ceb1ae-eaf6-11e5-9ff5-59559b5423d4.png)
(Size is 8 because 4 byte element + 4 byte array header data)

I've profiled the code and it seems to be that 1 element arrays are generated differently than > 1 element arrays. I am unsure if this was done because you don't need a tree for a singular item or because of special storage of 1 item arrays (can't find any documentation on this, or a native 1-item array).

**Comment by SirCxyrtyx** [comment]
This is a bug with detection of properties in arrays. I think it only happens when a 1 element integer array is followed by a bool property. Weird thing is, I remember fixing this, but my fix is nowhere to be found in the code. It'll be easy enough to put back in.

**Comment by Mgamerz** [comment]
Good to know it wasn't my code then, had no idea what was causing this.
