### ISSUE TITLE
r742, Texplorer, "Replace" Broken; probably should be removed

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#239]
@KFreon -- I know we've talked about this feature before, and I don't think it's ever actually worked. Right now, it's totally broken.

I think the goal of this feature is to be able to pick a mip level, and replace only that mip level. But, there's one major problem with this:

_Why would you want to replace only a single mip level? That would technically mean you could replace that mip with a texture that doesn't match any others._

**A texture with mipmaps is a "package deal".** It really shouldn't be possible to change any individual mip; it doesn't make sense to. A feature to "Replace Largest Mip" would make more sense, but even then, you end up with the same problem of it being possible to have mismatched mips comprising the same texture group.

Here's what happens when you use the tool right now:

![texplorer_replace](https://cloud.githubusercontent.com/assets/13645804/13825114/4ff0bf6e-eb6e-11e5-8be6-9fcc3d64b850.png)
1. The tool tells you the operation is to "Replace mip level with another image"
2. It brings up a window to choose the desired mip level. You pick ONLY one. Thus, the replacement image _should not_ have mipmaps. It should only be a single mip.
3. Navigate to the replacement image that corresponds to the selected size.
4. Upon selecting the replacement image, it throws an error. Why? _For lack of mipmaps, LOL._

So, yeah. Two options I see for this:
- If we want to keep this feature, then the operation probably needs to be changed to "Replace largest Mip." That also means the dialog to choose the mip level can be removed. Don't forget to change the tooltip.
- The operation can be disabled entirely, and the tooltip changed accordingly. Note that "Add Bigger Image" actually already works fine for replacing vanilla textures with one of an identical size.

---

As a side note, "Add Bigger Image" really isn't a proper description of the function. It makes it sound like you are just adding a mip to upscale the texture. This isn't the case. Functionally, it's a _full replacement_, since the new texture must have all the proper mips for Texplorer to use it.

Imo, the current "Replace" feature (linked to a single mip) should be removed, and the "Add Bigger Image" button text should be changed to "Replace Texture", as any texture replacement needs to involve all mip levels, regardless of whether the resolution differs.

Upscale/Downscale (not currently used) can stay in place, as that's an operation that would take place solely inside Texplorer.

**Comment by ghost** [comment]
One more thing to add onto this.

Textures without mipmaps -- like GUI codex textures -- will throw the same mipmap error, despite not having or needing mipmaps.

**Comment by KFreon** [comment]
I thought i changed these buttons ages ago.
Either way, I will now.

So there'll just be a button "Change" or something which does the texture modification.

I'll look into the mips thing too.

**Comment by ghost** [comment]
Nice job with this, K. I haven't been able to verify scanning and texture replacements on ME1 and ME2 yet due to the pathing bug, but things are working properly now for ME3 -- both GUI textures and ones with mips like the above.

Verified in rev745.
