### ISSUE TITLE
Texplorer, Import Tree

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#241]
@KFreon -- Does this also import all associated thumbnails? If not, should it? Otherwise, you'd just have to rebuild the thumbnail cache, anyway.

I could try it to see, of course, but I don't really want to copy 10K tiny files unnecessarily. Ick.

**Comment by starkgate** [comment]
You can only import a tree.bin, it's basically the same as copying it manually into the exec folder.

**Comment by ghost** [comment]
@CreeperLava -- Okay, we'll see what K says then. Copying in a tree doesn't do much good without thumbnails with it. Seems like they should both be done together.

**Comment by starkgate** [comment]
I guess so. Although it could pose a bunch of problems, eg how do you react when there are no thumbnails ? Or if the naming convention/format of the thumbnails changed (happened before with bugfixes).
Plus thumbnails take a lot of space, and the user may not be aware of it. For compatibility's sake, a good option could be to have a message in the import dialog, that tells the user to use the rebuild thumbnail option of Texplorer.

**Comment by ghost** [comment]
@CreeperLava -- Message would be doable, yes. But, I wonder how the tree import even works without them. I guess maybe just placeholders are used?

The thumbs really don't take up a lot of space; only 100MB on disk for ME1 and ME2. What's a bit more annoying is just the amount; 20K thumbs between those two games. Constantly copying and deleting that many files... lots of fragmentation. Ick.

**Comment by KFreon** [comment]
I don't know how this feature is actually used.
It wouldn't be too painful i guess. 

It would work as such:
- User selects tree file (naming = whatever)
- Tree is read to find what game version it is.
- Search containing folder for a folder called "ME(game version)Thumbnails"
- If exists, just blanket copy.
- If doesn't exist, use placeholders.

I don't want a dialog box. I hate those things, but I can make the progress bar red and have a message there if you really think it's necessary. 
I figure if they don't have thumbnails with the tree to start with, they don't want them/need them.
They aren't necessary, they just look pretty :)

**Comment by ghost** [comment]
@KFreon -- I think it's pretty unlikely that they wouldn't have thumbnails, if they have a tree to import. After, all, the thumbnails are generated during the tree-building process.

I would argue that the thumbnails are one of the most necessary features of Texplorer. 

Have you gone back to the stable and tried to use Texplorer, with all its placeholder icons? It's.... a bit horrible. You scroll through the folder tree seeing nothing but a bunch of identical placeholders, and then to see a texture, have to right-click on it and then click the Preview option. Being able to quickly scroll through the Texplorer tree and easily see all textures at a glance is what makes it such a useful tool.

**Comment by KFreon** [comment]
I know, but why don't users just copy the tree out and stick it back in?
I guess that's what the Import/Export feature is for.

**Comment by ghost** [comment]
@KFreon -- That's exactly what I do; I copy it by hand, just b/c to me it's easier. But, it's a nice feature to have in the tool for folks who are less technically-inclined :)

**Comment by KFreon** [comment]
Should ExportTree export thumbnails?

**Comment by starkgate** [comment]
It shouldn't be named Export Tree anymore, if you were to change it. You could have something like 'Export Modding Setup (Thumbnails and Tree)' instead.

**Comment by KFreon** [comment]
What I'm asking though, is should that be a thing? Is it useful at all?

**Comment by ghost** [comment]
I'd keep it in, K.

If you're going to keep the ability to import, then I'd keep the ability to export. I can see folks wanting to back up (export) their trees to a specific location on their HDD, and then import them when they update the toolset. This is what I do manually, with both trees and thumbs. Then I name the folder by the rev.

**Comment by KFreon** [comment]
Oh boy...these imports and exports just got about 20000 times slower with the thumbnails.

**Comment by ghost** [comment]
@KFreon -- A couple issues with this; it isn't quite working like I expected.
1. Import Tree isn't importing any thumbnails.
2. Export Tree is exporting all the thumbs, but not in the existing folder structure. How I (wrongly) assumed it would work is the toolset would simply copy ..\ThumbnailCaches OR ..ThumbnailCaches\ME#ThumbnailCache to the specified destination, along with the me#tree.bin. Instead, it copies each thumbnail itself, rather than the directory.

I'm assuming fixing problem 1 isn't an issue, but any way we can also fix problem 2?

**Comment by ghost** [comment]
@KFreon -- This is now working perfectly for both import and export. It's also about 20 times faster, which seems to come from retaining the folder structure for the thumbs.

Verified in rev746.
