### ISSUE TITLE
r742, Extracted Textures saved to ME3Exp root folder?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#243]
Just noticed this, which seems very weird:

![extractsaved](https://cloud.githubusercontent.com/assets/13645804/13832298/43fc4d48-eb98-11e5-8d94-ea9b6209a01c.PNG)

All of these textures I extracted for test purposes, but I extracted them to a different location. I can verify that they are not only there, but in the ME3Exp root directory as well, which seems unintended and entirely unnecessary, lol.

**Comment by KFreon** [comment]
I wonder why it's doing that....

**Comment by ghost** [comment]
@KFreon -- Ha ha, you tell me!

**Comment by starkgate** [comment]
I also noticed that a bunch of DDS files were randomly sitting in my ME3Explorer folder, this may be an explanation^^.

**Comment by Mgamerz** [comment]
Looks good, back to normal.

**Comment by ghost** [comment]
Verified in rev745.
