### ISSUE TITLE
r730 -> r743 TPF/DDS tools 3.0 - Autofix doesn't work for TGA format

### ISSUE THREAD

**Issue by mkta** [ME3Explorer/ME3Explorer#244]
While adding a .tfp file with textures .tga or another format other than DSS, the "Analyse with Texplorer" will display an error "Not DDS format". After pressing "Run Autofix" nothing will happen. And it will remain stuck at this process. 

Debug console message: 
Fixing: HMM_HGR_SHP_FBDf_DIFF
     FORMAT -> Current: .tga  Expected: DXT1
     MIPS -> Current: 0  Expected: 10

Tested with all rev from r730 to r743
r712 doesn't say invalid DDS format and recognize them as .tga texture

**Comment by starkgate** [comment]
.TGA textures are not supported by ME3Explorer. The stall is definitely a bug though, it should display something like _Autofix failed_ instead.
Not sure why rev712 would recognize them, is it able to autofix too ?

**Comment by mkta** [comment]
r712 recognize them as valid textures and try to install them. Autofix only fixes some MIPS in the textures. Although r712 freezes at installing.

**Comment by starkgate** [comment]
Well there you go, TGA has probably never been compatible. I guess it could be useful to add compatibility for it, but iirc KFreon said it would take too much time. You can still manually convert these textures with Compressonator or Photoshop though.

**Comment by mkta** [comment]
I see. Thank you for the reply, I will manually convert them. 
Although as a note, with the stable version I managed to install those textures from that .tpf
The only reason I tried a new version is because the stable one stopped installing any .tpf. It just stalls. Then I encountered this issue with the new revision and I thought to let you guys know.

**Comment by KFreon** [comment]
TGA isn't supported yet. JPG, bmp, and png should be though.
If you have a test file, I can try replicate the stall though.

**Comment by mkta** [comment]
I understand, thank you.
Here is the file I tested with
[N7 Terminus Armor-356-.zip](https://github.com/ME3Explorer/ME3Explorer/files/181197/N7.Terminus.Armor-356-.zip)

The thing is I managed to install it once in the stable version. Now any .tpf I try to install it just stalls.
Then I tried with newer versions and I encounter the issue above.

**Comment by KFreon** [comment]
I've implemented TGA loading but saving isn't supported.
As for the errors, I can only assume it's because all those images are TGA.

I'll close this for now, but if there's still an issue, reopen it and let me know.
