### ISSUE TITLE
rev743 White Alpha

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#245]
This is a pretty serious issue with autofix. For now, I only tested DXT1 to DXT5, but it could very well happen for other conversions (edit : same with BMP to DXT5). Basically, the converted texture has an entirely white alpha. Which means it is opaque in-game. In the case of a diff texture, it's not too bad, but for specs it looks like this :
![jguphb3](https://cloud.githubusercontent.com/assets/12874678/13898729/7af5b740-eddb-11e5-9873-a482b64b8547.jpg)
A bunch of textures had this issue in ALOT for ME2, and I wasn't sure what caused it. I suppose that's why.
Test files : http://filebin.ca/2amxSizmvjuh
![capture2](https://cloud.githubusercontent.com/assets/12874678/13898712/b714e1fc-edda-11e5-8554-faf55c1e5c00.PNG)
![capture](https://cloud.githubusercontent.com/assets/12874678/13898711/b713dfaa-edda-11e5-84b5-dbab7074e027.PNG)

**Comment by Mgamerz** [comment]
Why Miranda you're positively glowing!

**Comment by starkgate** [comment]
Confirmed to work in rev744, although see #251.
