### ISSUE TITLE
rev743 Suggestion : Extracted files keep their name

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#247]
If you think this would cause too many potential issues, feel free to ignore :).
For now, if I load a texture named 'MASSEFFECT3.EXE_0x12345678.dds', it will be extracted as eg 'HMM_abc_whatever0x12345678.dds', which can be quite annoying when you try to keep naming conventions. What I suggest is to simply keep the name of the texture, and change the extension if needed.

Note that this could pose problems with textures in TPF or MOD files, since those do not necessarily have a hash appended afaik. So definitely make a check for hashes.

**Comment by alvarome** [comment]
Well, I find the current nametexture_hash format useful... but not complete. 

Another option here for the extracted .dds filename:

Just add a game suffix (ME1, ME2, ME3) -to match the game tree you are extracting the texture from-, followed by texture name and texture hash (or vice-versa).

i.e.: ME1_whateverthenamehere_0x12345678.dds

This way, even extracting textures with same hash and name from different games those cannot be overwritten by mistake not to mention that the name would be quite descriptive.

And this would give us a quite normalised naming convention, I think, so no need for further renaming. 

@CreeperLava, just a matter of renaming older .dds files not matching that format. but that can be solved with a .batch file easily! ;)

HTH!
Alvaro

**Comment by KFreon** [comment]
If this is TPFTools, the original name is kept if extracted before Tree Analysis.
After Tree Analysis, the filename is changed to the texture name.

I can change it I guess, but I don't want to :P

**Comment by starkgate** [comment]
As Alvaro said, it's relatively easy to fix using a bulk rename tool, it would just be better to have it already done. You can close the issue then :).

**Comment by KFreon** [comment]
Maybe one day there'll be an option to keep the old names. 
Not today though I'm afraid :(
