### ISSUE TITLE
rev743 Suggestions : Remove Change Game Paths

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#249]
This option should only be available once in the whole toolset, ideally in the main menu. So why keep it in TPF/DDS Tools too ? It's redundant and takes valuable space^^.

**Comment by KFreon** [comment]
It's under debate atm. Can't find the Issue, but it's here somewhere.

**Comment by SirCxyrtyx** [comment]
fixed by 1311926337d92f8d6f7d391509ead95917d3a032

**Comment by starkgate** [comment]
Very nice, confirmed to work in 746.
