### ISSUE TITLE
rev744 Texplorer buttons are gone

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#250]
![capture](https://cloud.githubusercontent.com/assets/12874678/13903714/3c88d940-ee87-11e5-9970-0a0ab9ebce60.PNG)
As you can see, something is missing in the top right.

**Comment by KFreon** [comment]
Someone didn't read the whole thing.
**tsk tsk** :P

**Comment by starkgate** [comment]
Sorry :)
