### ISSUE TITLE
rev744 Alpha issues (again :/)

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#251]
TPF/DDS seems to generate an alpha when autofixing, even when the original texture doesn't have/need an alpha.
![capture](https://cloud.githubusercontent.com/assets/12874678/13903754/3d739452-ee88-11e5-8d3f-581f4ae9e5f1.PNG)
![capture2](https://cloud.githubusercontent.com/assets/12874678/13903755/3d73c1e8-ee88-11e5-89f0-1d23e062e049.PNG)
http://filebin.ca/2asyglV7Wfwc

Note : this happens ONLY for textures that did not originally have an alpha, the others keep their alpha as intended. This means, no more white alpha bug apart from this specific case.

**Comment by KFreon** [comment]
This should only happen when converting to a format that supports alpha EXCEPT for DXT1. 
DXT1 should only get alpha if the original had alpha.

**Comment by starkgate** [comment]
Well, this specific texture is a DXT1, so...

**Comment by KFreon** [comment]
Oh...
So it's a non-dds being converted to DXT1 or a DXT1 being reconverted to DXT1?

**Comment by starkgate** [comment]
Yes, it is a DXT1 that lacked MIPs.

**Comment by KFreon** [comment]
Ah this is a strange thing, but excellently, not my fault :)
The Photoshop plugin shows the alpha channel there if you load Mipmaps. 
It's not present just loading the image. This isn't different behaviour.
The original just doesn't have any mips.

**Comment by starkgate** [comment]
I don't understand what you are saying, do you mean that tpf/dds can't generate MIPs for the alpha ?

**Comment by KFreon** [comment]
I mean it's how Photoshop displays mipmaps. So it loads all the mips, joins them all together, and masks everything with the alpha channel. 
So to be clear, there isn't any alpha, photoshop just uses an "alpha" mask to help display with mipmaps.

**Comment by starkgate** [comment]
Still odd that ut would show an alpha if there isn't one, but I'll trust you^^.

**Comment by KFreon** [comment]
Try it in another program or don't load the mips in Photoshop and see what happens :)

**Comment by starkgate** [comment]
Their behaviour is also strange and inconsistent. Gimp shows a white alpha in both cases. The only tool I found to be correct is Image Engine, you can be proud of your work K :).
