### ISSUE TITLE
rev744 Suggestion : Add visual indication of dropdown menus in Texplorer

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#252]
In Texplorer, the dropdown menu for 'Tree IO' and 'Rebuild Database' should get an arrow to show they are dropdown menus and not normal buttons.

**Comment by KFreon** [comment]
I'll see what I can do.

**Comment by KFreon** [comment]
Ok so that's not so simple cos of the type of menu bar I used.
So I don't think I'll be doing it :(

I don't think it's a big deal though since most menus in Windows are this style.

**Comment by starkgate** [comment]
It's pretty unintuitive, especially for the rebuild databse button. Rebuild database sounds scary, so people probably won't click it just to see what it does, thus won't see that you can rebuild by folder. Not a huge deal I suppose if it can save you time for more important stuff :).

**Comment by KFreon** [comment]
As I said, I would if I could, but it doesn't seem to be that easy.

**Comment by KFreon** [comment]
Added a 'v' to the end of these as kind of an arrow. 
Obviously imperfect, but looks ok.
![image](https://cloud.githubusercontent.com/assets/7845997/14070069/414067fa-f4e5-11e5-8c08-78e1fb366067.png)

**Comment by starkgate** [comment]
Haha, I love your way of fixing things^^. Can you insert special characters in these buttons ? There's probably a lot of different characters in Unicode that could help represent an arrow better than a v.

**Comment by KFreon** [comment]
I had a quick look and couldn't figure out how to insert the unicode code point.
I'll try again this afternoon.

**Comment by starkgate** [comment]
Better than nothing I suppose^^. Confirmed to work in rev748.
