### ISSUE TITLE
Bug:  Level Explorer default move speed

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#254]
Level explorer is a surpassed by ME3Creators level view in most ways, but it does one thing that nothing else does - it shows volumes (that block, trigger etc).   The problem is that it defaults to a movement speed of 10,000 per click and for some reason is very hard to change (a change of the drop down menu works about 1 time in 15).  For comparison the entire length of the Normandy is about 8,000.

For the limited use of Level explorer the easiest minimal fix would be to set the default speed to 100 or 200.   Then it would be at least useable.

**Comment by Mgamerz** [comment]
There's a level explorer!?
