### ISSUE TITLE
Suggestion: Skel Mesh imports (ME3Creator)

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#255]
ME3Creator's import works perfectly with Static meshes.  Mesh explorer imports skel meshes from UDK, but requires identical numbers of bones.   ME3Creator also works with Skeleton Meshes but requires a bit of hex editing to fix the bone names.   If this could be automated it would be very useful.

Detail:   The skel mesh binary hex contains a list of bone names at the end.   It takes the form of  

name (16 bit reference)  bone number (1 byte integer starts at 0).

To manually fix you need to do this when copying a skel mesh from pcc X to pcc Y:

(1) Import object via ME3Creator.  Find name table at the end of the binary hex.
(2) Convert name reference from pcc X & lookup name.
(3) Lookup name reference in pcc Y.  Add if it is not already in the table.
(4) Run a search and replace in the object in pcc Y.   Usually the name reference appears twice - one in the LOD data and secondly in the bone name table.
(5) Repeat for the next 109 bones.

I have copied skel meshes across pccs and even from ME2 to ME3 successfully doing this, but it is quite a hassle, and any automation would be very handy.

**Comment by SirCxyrtyx** [comment]
Thanks for the detailed instruction on how to achieve this. Sounds very doable, but might take me a bit.

**Comment by ghost** [comment]
Hm. @Kinkojiro, would this also make importing animations easier?

**Comment by Kinkojiro** [comment]
Maybe.   I am not sure about the structure of animation binary data.

**Comment by SirCxyrtyx** [comment]
Looks like in the properties, the LODInfo array has a TriangleSorting Array that is an array of Names. I could auto-detect name arrays based on each entry being 8 bytes long, and then either find or add the names in it and modify that array to point to the names in the pcc that it's being imported to. That would make all manner of object imports easier.

It would screw up any arrays that had an entry length of 8 that weren't name arrays, but I don't think there are any of those.

**Comment by Kinkojiro** [comment]
I have done this with 5 or 6 meshes and never had any problems with 8 byte name arrays being duplicated in the binary data.

**Comment by SirCxyrtyx** [comment]
Oh, sorry if my last comment wasn't particularly clear. I was talking about name arrays in the properties _before_ the binary data, like this:
![image](https://cloud.githubusercontent.com/assets/5533111/14023000/9969f0e8-f19f-11e5-99b7-9f726f81b53f.png)
I can detect those, and change all the names to point to ones in the new pcc.

**Comment by Mgamerz** [comment]
Are there arrays of 64-bit integers?

**Comment by SirCxyrtyx** [comment]
I certainly hope not. If you know of any though, It'd be good to hear about them before I release this and screw up the importing of them.

I really ought to just write something that will scan through all the game files, find all the classes, and generate definitions for them so the code doesn't have to guess at what stuff is.

**Comment by ghost** [comment]
> I really ought to just write something that will scan through all the game files, find all the classes, and generate definitions for them so the code doesn't have to guess at what stuff is.

Now, that sounds handy, @SirCxyrtyx.

**Comment by Kinkojiro** [comment]
So just a quick update re Bones and animations, I reminded myself.   They use a different system.  The bones for the animations are numbered.   The numbered lists are then related to the model bones in a seperate BioAnimSetData export object.   Importing this type of object where the names are imported correctly would be handy in future, but I guess would be seperate from the skel mesh imports as it is unreal code rather than binary.

**Comment by ghost** [comment]
@Kinkojiro -- Ah, okay that makes some sense. Thanks for pointing that out.

**Comment by SirCxyrtyx** [comment]
This is done, and will be in the first post-stable build.

**Comment by Kinkojiro** [comment]
Sir you are legend.

**Comment by SirCxyrtyx** [comment]
Sorry about how long this request is taking to get out. We did a feature freeze to make it easier to get the stable out. Assuming all goes well with the stable release, this feature should be out before May. If you need this feature for modding you're trying to do right now though, I can send you a special build that has it in it.

**Comment by Kinkojiro** [comment]
Would be very useful.  I keep multiple copies of me3exp working so please send me the files if it is possible.  I will test out the skel mesh feature.
