### ISSUE TITLE
r744, ModMaker, Base game TOC upon mod install fail

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#258]
When testing installation of a .mod file with a single job affecting a BW DLC, and this fails (reported in a different issue), MM continues to TOC the base game, rather than aborting entirely.

We've already fixed this for DLC; it doesn't TOC unless a DLC is edited (yay). Looks like we need to do this for the base game, as well, though.

**Comment by KFreon** [comment]
I thought we were TOC'ing all the time?
But yeah, if basegame isn't modified it shouldn't be TOC'd. I'll see what I can do.

**Comment by ghost** [comment]
@KFreon -- Sort of. 

What we decided is that we're TOCing _all_ DLC whenever _any_ DLC are modified. If only base game files are modified, then only the base game should get TOCed. And, no TOCing should happen at all if no changes are made.

Like I said, the DLC TOCing didn't happen, so it seems to be fine. It's only the base game TOCing that misbehaved :)

**Comment by KFreon** [comment]
It's surprisingly difficult to make that happen with the way I've implemented functions. 
I'd need to change a lot of functions just to feedback that a mod failed to install.

To me, it's a lot of work to stop something not bad from happening. The basegame TOC doesn't take that long.

**Comment by ghost** [comment]
@KFreon -- You're right, it doesn't take that long. It is unexpected though -- again I tried closing the tool and the tool said "You shall not pass!". Mostly, it's just illogical that it would TOC _anything_ in the case of nothing being installed.

If you'd rather not mess with it for the stable, I understand, but we should keep the issue open so it can be addressed later.

**Comment by ghost** [comment]
@KFreon , @SirCxyrtyx -- If we want to make things simple, we might want to change ModMaker to use the Generate All TOCs via autotoc, to match the change to Texplorer and TPF Tools. The situation is slightly different for this particular issue as it's TOCing upon mod install _failure_ (not desirable), but this seemed to be a good issue to bring it up.

**Comment by SirCxyrtyx** [comment]
Modmaker uses Texplorer's UpdateTOCs function actually, so that's already done :)

**Comment by ghost** [comment]
Well, sweet :dancer:

**Comment by KFreon** [comment]
Was this fixed by Sir's changes?

**Comment by SirCxyrtyx** [comment]
Nope. Sort of makes it worse actually, since it now TOCs basegame + DLC. But It's not a huge deal, since it only takes a couple of seconds.

**Comment by ghost** [comment]
Not sure, since I haven't been able to test. But, I'm not 100% certain that Sir's fix will alleviate the TOCing upon install failure part. Maybe @SirCxyrtyx can chime in to clarify?

EDIT: I just cross-posted with Sir. I should clarify, then, is the goal to TOC, even if a MOD file fails to install? That's what this original issue was for.

**Comment by KFreon** [comment]
I still consider the time required to fix that, disproportionate to the time it takes to do the TOCing.

**Comment by ghost** [comment]
@KFreon -- Okie doke. If we don't want to fix it for the stable, then I can put a note about it in the wiki. It's not logical, but then again, neither is TOCing everything, lol. I think at this point we need to go with foolproof, simple solutions... as much as we can.

If you want to keep it as it is right now, go ahead and close when ready, K.

**Comment by KFreon** [comment]
It is messy, but it's also easy :)

**Comment by ghost** [comment]
Hm. I'm going to re-open this, since there's one more problem with this that I noticed.

@KFreon -- After TOCing, ModMaker gives a message next to the progress bar of "All Mods Installed!". So, there seems to be an assumption in the tool that TOCing = successful install. This is no longer the case if we're going to allow TOCing even upon mod failure.

This is a User Tool, so I don't think we want to be giving folks the impression their mods have installed, when they actually have not. Yes, you'd think the error messages that trigger for each job would be enough, but some folks will think that just means _part_ of the mod didn't install right, since the tool is also explicitly telling them, "All mods installed!".

**Comment by SirCxyrtyx** [comment]
Now says "Some Mods Did Not Install! See Debug Output For Details." if any of the mods failed in any way.

**Comment by ghost** [comment]
Wewt! Thanks :D

**Comment by ghost** [comment]
Reopening due to the second issue in this thread, not the one in the title.

@SirCxyrtyx -- We're almost there with this. The new message on the bottom is great, BUT, there's no indication in the debug output as to which jobs didn't install. Here's what it looks like when every mod job fails to install:

![mm_installfaildebug](https://cloud.githubusercontent.com/assets/13645804/14356999/c1d1eb38-fc9b-11e5-817f-15c6f48c08f9.PNG)

Can we improve this further, so users know which jobs were problematic?

EDIT: A bit more info on this. If I run a .mod that attempts to install to an unextracted DLC and it fails, I get this message, so it seems that there is some debug output present, sometimes:

![mm_installfaildebugb](https://cloud.githubusercontent.com/assets/13645804/14360717/8d992028-fcac-11e5-97a9-7139ee9b4406.PNG)

**Comment by SirCxyrtyx** [comment]
You may have found a flaw with my error detection. It only works for .mods that were created with this rev, or were updated with this rev. There is debug output when a job fails to install, so the fact that there is none in the first picture might indicate that those jobs did install, but since it's using an old script, Modmaker thinks it didn't.

I could change it so that it reports all mods installed for old .mods. But then there'd be false positives instead of false negatives.

**Comment by ghost** [comment]
@SirCxyrtyx -- Oooh, that would do it. The first example was an old mod, as I was trying to test .mod install to a DLC mod at the same time (and I had already "discovered" the issue with PCC Compare). Second example was a new .mod.

Okay, well, if there's no way to fix it being rev-dependent then feel free to re-close :)

**Comment by SirCxyrtyx** [comment]
I may not be able to fix it, but I can point people in the right direction. I can detect that it's using an old script and print this to the DebugOutput when it reports a mod installation failure:

```
It looks like these mods were created with an old version of ME3Explorer
Try selecting each job and clicking "Update Job" in the lower bar, then run it again.
```

So for mods that actually did install correctly, the user can update the jobs, run it again, and this time it will report success. I don't believe their are any issues with running a job on a pcc twice.

**Comment by ghost** [comment]
Sounds good, Sir. And, no, if anything running a job more than once seems to be a good thing, lol.
