### ISSUE TITLE
Issues with the path changer

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Explorer/ME3Explorer#259]
When selecting the executable of any of the 3 games, the path changer will display the game path followed by BIOGame, like this:
`C:\Program Files (x86)\Origin Games\Mass Effect\BIOGame`
There's two problems with this. First, the folder is BioGame in ME1 and 2, not BIOGame. Second, when these values are used to set the paths, the code will strip out the BIOGame part, making it pontless to have put it in in the first place. Except for the the ME1 path, which doesn't strip it out because  it's trying to strip out 'BioGame', not 'BIOGame', and it doesn't ignore case like the ME2Directory class does, leaving the ME1 path broken.

To fix this, I would suggest changing this function in PathChanger.cs:

```
string GetBIOGame(string path, int whichGame)
{
    string BIOGame = Path.GetDirectoryName(Path.GetDirectoryName(path));

    if (whichGame == 3)
        BIOGame = Path.GetDirectoryName(BIOGame);
    return Path.Combine(BIOGame, "BIOGame");
}
```

to this 

```
string GetGamePath(string path, int whichGame)
{
    string gamePath= Path.GetDirectoryName(Path.GetDirectoryName(path));

    if (whichGame == 3)
        gamePath= Path.GetDirectoryName(BIOGame);
    return gamePath;
}
```

**Comment by KFreon** [comment]
I dunno why I do these things.
Fixed. Doesn't seem to cause any problems.

**Comment by ghost** [comment]
Verified all paths issues fixed in rev747.
