### ISSUE TITLE
TPF Tools game existence check

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Explorer/ME3Explorer#260]
TPF tools seems to think I don't have ME1 and ME2 installed, judging by the indicator in the upper right, even though I do. The debug log says that it's looking for the presence of a "MassEffectLauncher.exe" and "MassEffect2Launcher.exe". I have the games through Origin, and neither of those programs exist. Is that a Steam thing? 

It seems like looking for MassEffect.exe, and ME2Game.exe would be better existence checks.

**Comment by KFreon** [comment]
I can't remember why I did it this way. They should exist though. I have the old school disk version.
Might have been laziness, but it might have been related to this:
- You mention ME2Game.exe, which I don't have. Mines called MassEffect2.exe.

**Comment by SirCxyrtyx** [comment]
I have MassEffect2.exe and ME2Game.exe actually. In my install, ME2Game.exe is the one that actually runs the game, while MassEffect2.exe seems to act like an invisible launcher.

**Comment by KFreon** [comment]
As long as it's there then.

**Comment by ghost** [comment]
@SirCxyrtyx , @KFreon -- That ME2Game.exe thing must be unique to Steam. I also have the old school ME2 Collectors Ed on disk and that EXE doesn't exist on my system. Very interesting.
