### ISSUE TITLE
Texplorer still extracts DLC on first time setup

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Explorer/ME3Explorer#261]
I hear it's not supposed to do this anymore.

**Comment by KFreon** [comment]
Whoops.

**Comment by ghost** [comment]
LOL!

I love how @SirCxyrtyx is so concise about this. @KFreon , you know it would have taken me about 2 paragraphs to say the same thing.

I'm working on that. Really, I am. I can elaborate if you want ;)
