### ISSUE TITLE
rev745 - All Kfreon's tools, Game Indicators for ME1 & ME2 Broken

### ISSUE THREAD

**Issue by alvarome** [ME3Explorer/ME3Explorer#262]
Hi:

Rev 745 Texplorer game indicator shows (in my case) no ME2 game present while usual info displayed upon opening Texplorer shows correct ME2 game path.

Same applies for rev 745 TPF/DDS Tools.

Debug log confirms ME2 game present in both cases.

ME3Explorer "Options" --> "Show known paths" shows all game paths correctly.

I have all three games installed but deceiving (red) indicator is just for ME2 game.

HTH!
Alvaro

**Comment by ghost** [comment]
We had a glitch with this indicator a couple revs ago where the tree and game indicators were accidentally swapped. 

Just to check, is it also telling you there's an ME2 tree present when there really isn't?

**Comment by ghost** [comment]
@KFreon -- Just updated the title for this bug, as it affects all of your tools, for both ME1 and ME2. Guessing something else needs to be updated in relation to fixes for #259. 

In case it's helpful:
![ktools_pathingbug](https://cloud.githubusercontent.com/assets/13645804/14021692/d7a073f6-f199-11e5-97c0-c70a777bc862.PNG)

**Comment by ghost** [comment]
Weird. Just lost an edit to my above post. Let's try again.

More info that might be helpful and related to this, as it pertains to ModMaker. The tool is hanging upon checking for paths, and it won't allow mods to be loaded. PCC Compare actually works, oddly enough, but mods can't be loaded or installed. If you try to close the tool, it tells you "background tasks running". Debug:

![mm_hangerror](https://cloud.githubusercontent.com/assets/13645804/14022281/5920b614-f19c-11e5-8fde-952c8bb513f5.PNG)

**Comment by ghost** [comment]
Might as well post Texplorer debug output while I'm at it, lol.

![texhangpath](https://cloud.githubusercontent.com/assets/13645804/14022881/126602f8-f19f-11e5-889e-fde790e8a62a.PNG)

**Comment by alvarome** [comment]
@giftfish [...] Just to check, is it also telling you there's an ME2 tree present when there really isn't? [...]

Negative. ME2 game tree indicator seems to be working ok.

HTH!
Alvaro

**Comment by KFreon** [comment]
Absolute rookie error with pathing.
My bad.

**Comment by ghost** [comment]
@KFreon -- Lol. Okay, well, please push a new rev when you can. I know you just did, but like I said in a different issue it makes ModMaker at least impossible to use (and test). I haven't tried using TPF Tools/Texplorer with ME1/ME2, as I figured it would just be better to wait.

**Comment by ghost** [comment]
Verified in r746.
