### ISSUE TITLE
r745, Texplorer, FirstTimeSetup GUI

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#264]
@KFreon -- A couple questions/comments with this.

In the dialogue below, what is the "Backup" checkbox on the right mean? There's no clear explanation, and it's only there when the DLC isn't extracted -- or if there happens to be no PCCs inside the DLC (as in the last case).

![tex_question](https://cloud.githubusercontent.com/assets/13645804/14023438/97b9e63e-f1a1-11e5-91dc-ec997bd499ec.PNG)

It almost seems like the tool is _asking_ if you want to back up a DLC, but I don't think that can be right, as I've never experienced it. It also seems to calculate a number when the DLC is checked versus unchecked. That particular part seems to be a remnant of when extraction was inside Texplorer.

I realize that you very likely _don't_ want to mess with this before the stable, as it's a GUI thing, but it seems like the entire right panel of this dialog is now unnecessary. Texplorer no longer needs to calculate hard drive space, as it doesn't extract. All it needs to do is show a list of DLC and allow the user to tick/untick them. You could even gray out ones that are still packaged in SFARs, if you wanted, and make them untickable.

**Comment by ghost** [comment]
@KFreon -- What you've implemented is a good solution for now. 

After the stable, I'd recommend actually removing the right-hand panel altogether and making the window size correspond to the size of the left panel. Then, remove the Disk Space amount next to the progress bar, as well. Thumbnails really don't take a lot of space. 100MB, basically. If folks don't have that much spare room on their HDD, they certainly aren't going to have room to install textures. CustTextures0.tfc alone easily gets over 100MB just by installing a few texture mods.

I'm going to reopen, but re-tag with "enhancement", just so it's not forgotten about :) If you want to implement the above changes prior to the stable, that's entirely up to you.

---

Verified in rev746.

**Comment by KFreon** [comment]
I...did remove the right panel?

**Comment by ghost** [comment]
@KFreon -- Oh, I see... it's technically gone, but the window isn't resized to compensate:

![texgui](https://cloud.githubusercontent.com/assets/13645804/14054370/f4cf5f58-f295-11e5-924e-7e49fe9ec46d.PNG)

Sorry about that -- I didn't catch the change in color (the panels were different colors, now it's uniform). Can we get the window sized down and the space computation next to the progress bar removed, then? Basically, the window could be half it's size, if not a bit less. It's cosmetic at this point, though, so like I said, it can wait until after the stable if you want.

**Comment by KFreon** [comment]
Done.

**Comment by ghost** [comment]
Yay! THis looks much better. Nice work.

![yayguitex](https://cloud.githubusercontent.com/assets/13645804/14066550/435ffa3a-f401-11e5-8d82-c879ab9b0e4b.PNG)

Verified in r747.
