### ISSUE TITLE
r745, Texplorer, Some PCC-Stored Textures not marked as such

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#265]
@KFreon -- I've reported this bug to you several times before, but the same textures still have problems. The selected textures in both screenshots below are PCC-stored, but only the bottom of them is marked as such:

![pccstored_buga](https://cloud.githubusercontent.com/assets/13645804/14024637/5a947bc4-f1a7-11e5-842e-d4772057eb39.PNG)
![pccstored_bugb](https://cloud.githubusercontent.com/assets/13645804/14024638/5deb28c2-f1a7-11e5-94b5-f9d59d79cd78.PNG)

How does Texplorer determine what is PCC-Stored and what isn't? Whatever method it's using is letting a lot of textures through the cracks.

For example, all codex textures are inside a single texture-centric game PCC, such as, SFXImages_Codex_1.pcc. These are the ones it doesn't realize are PCC-stored.

Other textures -- like those for model ship notifications or the bottom texture above -- are in a variety of game PCC's associated with specific levels (e.g., BioD_Nor.pcc).

From what I can tell, literally _every_ GUI image in the game is PCC-stored. That's simply how it works; Texturegroup_UI = PCC-stored. I know this b/c I've made new PCCs with new GUI images, and placed new GUI textures into existing PCCs. This also suggests that the only textures that are in TFCs are those with mips.

@Kinkojiro would be a good person to correct me if I'm wrong :)

**Comment by Kinkojiro** [comment]
AFIK every texture has at least one mip level stored in the pcc.   For GUI textures that is the only mip level.   For non-gui textures that are extremely small (e.g. 64x64) all the mip levels are stored in the pcc (typically these are default black or white textures for materials or gradients etc).   

However most GUI textures and all mip textures that have at least one mip outside the pcc have a tfc reference.    Even in the case that this reference is never used.   In my experience  Texplorer correctly ignores the tfc reference for GUI textures.    What you are picking up above is that difference - both are pcc stored, single mip textures.   It is just one has a (redundant) tfc reference.  

I would ignore this.   We don't know if there is some obscure reason that unreal needs a tfc reference if the GUI texture is above a certain size.   It doesn't seem worthwhile KFreon modifying the tree just to correctly state whether that texture has 1 mip level (hence GUI) or not.  You cannot replace GUI textures with mipped textures in any case.

**Comment by KFreon** [comment]
Unfortunately, there are a lot of ways to check.
At the moment, it was using the Texture ArcName property which usually contains the name of the TFC it belongs to.
I might have to use the StorageType property though.

**Comment by ghost** [comment]
@KFreon -- Sounds good. Kinko's explanation was (predictably) much more thorough than mine, so use your best judgement based on that info :)

**Comment by ghost** [comment]
Nice. This is indeed fixed :)

Verified in rev746.
