### ISSUE TITLE
rev745, Texplorer, Update TOCs broken

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#266]
Not sure if this has something to do with the neglect of TOCing DLC in Texplorer, but this is totally broken. When clicked, the window it brings up is entirely unpopulated:

![tex_tocbug](https://cloud.githubusercontent.com/assets/13645804/14026961/9cb5dc86-f1b2-11e5-963a-6697c8c08503.PNG)

**Comment by ghost** [comment]
Not quite fixed.

All DLC now appear in the window (yay), but Texplorer thinks they aren't extracted. It will TOC the base game, but not any of the DLC. In debug it says "No DLC extracted. Not TOCing."

This seems to be the same issue ModMaker is having, so again I'm wondering how these checks are coded differently from the initial check when opening the toolset -- which works fine.

**Comment by SirCxyrtyx** [comment]
So, for this update TOCs thing, is there any reason not to have it just run AutoTOC's "generate all TOCs" function? The current way it deals with TOCs is pretty complicated, and relies on a lot of outdated functionality. The way I see it, just calling "generate all TOCs" whenever the Update TOC's button is clicked is dead simple and pretty much guaranteed to not cause problems.

This would also fix #272, and #180 
If no one objects, I can just commit a fix to do this.

**Comment by ghost** [comment]
@SirCxyrtyx -- _Ideally_, DLC are only TOCed when edited and the base game is only TOCed when edited. This is logical. BUT, if that's too complicated and labor intensive to implement due to outdated code, then your solution might work.

The only potential issue I see is that it _might_ trigger a bug that K already fixed, which was that ModMaker -- I can't remember if Texplorer did this or not -- would extract DLC just to TOC it. As in, the DLC was still packed and not even edited by the tool, but TOCing required unpacking, so it unpacked it. That was very problematic.

If this can no longer happen, either due to the recent changes to the tools, or due to the Generate All TOCs function, then it sounds like a great solution to the problem.

**Comment by SirCxyrtyx** [comment]
The reason it was extracting DLC is that it was using DLCEditor's Extract All DLC function to TOC DLC. My intention here is to just have all TOCing be done via AutoTOC's "generate all TOCs". It takes about 3 seconds on my computer (which does not have an SSD) with all Bioware DLC installed and extracted. 

Always TOCing everything is still pretty fast, and unlikely to ever have any bugs. The benefits of granular TOCing are, IMO, not worth the added complexity.

**Comment by ghost** [comment]
@SirCxyrtyx -- Got it. Sounds great :)

**Comment by ghost** [comment]
@SirCxyrtyx , @KFreon -- This now works perfectly. Everything is TOC'd, and TOCing doesn't extract DLC, lol. Yay.

One question, though. 

How hard would it be to implement a message on the Progress bar for this? I only ask b/c there's no visual confirmation in the tool window at all that the TOC has worked. There is Debug Output, but it's very easy to miss. I actually spammed the button wondering why it wasn't working, lol.

**Comment by SirCxyrtyx** [comment]
Not hard at all :)

done in a639560

**Comment by ghost** [comment]
Verified in rev748. Perfect :)
