### ISSUE TITLE
r745, Texplorer, All Games, A8R8G8B8 Changed to G8/L8

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#267]
Guessing this happened when the new image library was implemented. 

We've got a bug with what used to be identified as A8R8G8B8 and is now G8/L8. This is a comparison of rev727 and rev 745:
![formaterrortex](https://cloud.githubusercontent.com/assets/13645804/14028214/a588ff0e-f1b8-11e5-9aba-de41583fedc9.PNG)

A similar difference exists for the "planetring" textures in the same folder.

I'll dig around for a bit and see if I find any others. I'll have to consult a slightly earlier rev for ME1/2 since I can't build trees due to the pathing bug.

EDIT: So far I haven't found any other messed up formats, but there are plenty of the ARGB textures that were newly-miscategorized as G8/L8.

To be clear, everything that was _originally_ G8/L8 continues to identified as such and still works. I'm also seeing several textures that didn't change format at all, over the past 20 revs, but that are now displayed differently (and properly) due to the new image library. Despite this glitch, looks like moving to the library has been a very positive change.

**Comment by ghost** [comment]
Did find one other format issue for ME3. Both are identified as DXT5, but the left is rev727 and the right is rev745.

![formaterrortex2](https://cloud.githubusercontent.com/assets/13645804/14028935/8686af26-f1bc-11e5-963e-65816890a391.PNG)

Not sure what's going on with this one. Generally Texplorer recognizes textures much better after the new library.

**Comment by ghost** [comment]
Just changed the title on this, b/c it looks like it's happened in all games. Just finished treebuilding for ME1, and it has the same problem. EDIT: And, finally got to ME2, and it indeed is the same. Somehow we lost ARGB format.

Maybe this happened with the new enums, @Kfreon?

**Comment by KFreon** [comment]
Having a lot of trouble with this one. It's because of the way I detect the format in the string that comes out of PCC's. 
Getting there.

**Comment by ghost** [comment]
Okie doke. Thanks for the update :)

**Comment by KFreon** [comment]
Ugh. I hate my solution. Feels dirty. 
Seems to work though.

**Comment by ghost** [comment]
It does seem to work, @KFreon. Nice job :)

In addition, take a look at this. Some textures that used to be considered G8_L8, are now ARGB, and from what I can tell, this is actually correct and not a bug. Check it out:

![argb_1](https://cloud.githubusercontent.com/assets/13645804/14066685/415746b8-f405-11e5-93c0-65795d3c4873.PNG)
![argb_2](https://cloud.githubusercontent.com/assets/13645804/14066686/42d513da-f405-11e5-8076-87b564f73746.PNG)

I can also verify that textures that are indeed G8_L8, are still detected properly:

![argb_3](https://cloud.githubusercontent.com/assets/13645804/14066692/805227de-f405-11e5-8ba0-6a2cfe08308b.PNG)

All the work that's gone into this is really paying off, @KFreon. Texplorer has _never_ been so accurate at rendering textures.

Verified in r747.

**Comment by KFreon** [comment]
All my testing shows that those images are supposed to be ARGB.
I guess they were just wrong in 746.

**Comment by ghost** [comment]
@KFreon -- Indeed they are, and I think I see something that might give us a clue. 

Back in rev720 (I keep lots of old revs) the door_console texture was identified as A8R8G8B8/L8. That was before the change to the new image library, though, I'm almost certain. So, it seems like at some point between then and now, certain A8R8G8B8/L8 texture were reassigned as G8/L8. 

Maybe it was even with the new enums, and whatever change you just made, you fixed it :)
