### ISSUE TITLE
r745, Texplorer, Tree construction variation

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#268]
Not sure this is a bug, but it is a bit strange so I wanted to check on it.

There seems to be some variation in how Texplorer can construct a tree. I just built a tree 3 times with the same files and the placement of at least one group of textures changes:

![textree_var](https://cloud.githubusercontent.com/assets/13645804/14030322/43bec086-f1c4-11e5-8105-58f12e42e0f0.PNG)

At first, I thought Texplorer was skipping the file, but I dumped the debug and did a search for the file and it was there. Then, I did a search for the texture in the tree, and indeed it was, but it was inside a different folder within the tree.

@KFreon -- Any idea why this happens? It's not a problem as long as replacement still works fine, but the variation seems... odd. It's possible it's always done this, and I simply didn't notice until now.

**Comment by KFreon** [comment]
I do not know why that's happening...
That group might exist in multiple places though.
As in there's a SHPO folder, and a BIOG_HGR\SHPO group folder. Pretty sure that's a thing that happens.

**Comment by ghost** [comment]
@KFreon -- There's only ever one folder at a time. There's _either_ a SHP_O subfolder, or the SHP_O exists by itself, as on the left. It's never both, at least in the 3 tests I did.

You can close the issue if you want, I just thought I'd bring your attention to it, since it seemed weird.

**Comment by KFreon** [comment]
Huh...I don't know why that would happen. As long as the same PCC's are there.

**Comment by ghost** [comment]
@KFreon -- Yep, they indeed are. Vanilla base game files and no changes between tree scans. Quite odd, indeed.

**Comment by KFreon** [comment]
Ok this has become an issue. Textures are missing, whole folders of textures are missing or have the wrong names.
I really hate the toolset some days.

**Comment by ghost** [comment]
@KFreon -- Are you doing a search for texture names or hashes, just to be sure? I saw a few other folders today as I was testing that also migrated to different locations. 

Also, make sure you have the correct game selected. I couldn't find a couple, and then realized I was on ME2 and not ME3, lol.

**Comment by KFreon** [comment]
My scan has no Avina textures, and is missing everything I checked in the "Textures" folder.

**Comment by ghost** [comment]
@KFreon -- For ME1, she's in two folders for me: VI and AVINA. I search for "avi" ... in case that helps >.<

**Comment by KFreon** [comment]
I know, I searched for the texture name in your screenshot and got nothing back. Must be something going on during scanning :(

Shame scanning takes so damn long.
Actually, since yours worked, what PCC is that Avina texture in?

**Comment by ghost** [comment]
@KFreon -- Two.

Startup_INT.upk -- This is in the Cooked root and used to be the one TPF Tools really, really didn't like to install into.

BIOG_HMF_ARM_NKD_R.upk -- This is inside Packages > GameObjects>Characters>Humanoids>HumanFemales.

And yeah, scanning for ME1 takes a good bit. Must be the UPK packaging?

**Comment by KFreon** [comment]
**cough**
Um you know a few back when you said "Check the game"?
Yeah...

**Comment by ghost** [comment]
LOLOLOL, @KFreon ....

**Comment by KFreon** [comment]
Ok scratch this one again. Things are there, I just had the wrong game selected :)
