### ISSUE TITLE
Menu and Tool Name Changes

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#27]
Transferring these and expanding on them from the Wiki thread, here: http://me3explorer.freeforums.org/next-svn-requested-toolset-changes-t1651.html

Now that we have a better issues/bug system, I'll just make any new requests this way. 

To preface these changes, obviously the goal is to have congruency between menu names and tool names. We also want the names to properly reflect the functionality of the tools. Names for User Tools should be especially explicit since some users may be quite non-technical. Finally, structure should be logical and match what's already been discussed and established on the wiki.
#### Menu Name Changes and/or Relocations

_Tools that need their name changed in the main toolset menu, or that need their menu link relocated. Old name on the left, new name on the right._
- GUID Editor >> GUID Cache Editor
- Interp Editor -- relocate to Dialog submenu
- Language Select  >> Language Selector
- ME3Explorer Version Switcher >> Version Switcher (it's in the toolset, the "ME3Exp" is superfluous; also alphabetize with rest of menu).
- TLK Editor -- relocate to Dialog submenu
- Tools >> User Tools (top menu)
#### Tool Name Changes

_Tools that need their name changed to match the main toolset menu. Old name on the left, new name on the right._
- Operator >> Coalesced Operator
- PlotVarDB >> Plot Database
- PropDump >> Property Dumper
#### Menu and Tool Name Changes

_Tools that need their name and corresponding name in the main menu both changed. Be sure to re-alphabetize in the context of the other menu options. Old name on the left, new name on the right._
- AFC to WAV/AFCExtract >> Audio Extractor
- Conditionals >> Conditionals Editor
- DLC Editor/DLC Explorer >> DLC Basic Editor
- Movies.tfctoBIK/BIKExtract >> BIK Movie Extractor
- Vanilla Maker >> ME3 Backup Tool
- WWiseBank Viewer/Wwise Viewer >> WwiseBank Editor
- TOC.bin Editor/TOCEditor >> TOC Editor
- TOC.bin Editor (AK86)/tool's name >> TOC Editor (AK86)
#### The New "About" | Toolset Credits and Authorship

Credits/authorship for the toolset should be adjusted to only those present on the **About Us** page the wiki. Just b/c people had _access_ to the code on SF, doesn't mean they _contributed_ code (see WV's recent forum post where he lists these different groups of people). From my research on the forum when I wrote the wiki article, only those people I have listed had definitely contributed code. WV has now also said some of Feckless's material was used. I'm currently unclear on Eliot's role.

A better way to structure the names on the new About would be:

**Toolset Authors:**
    Amarok86
    Aquadran
    Ashley66444
    BCSWowbagger
    Erik JS
    Eudaimonium
    FemShep
    Fog.Gene
    Heff
    JohnP
    Kfreon
    MrFob
    Saltisgood
    SirCxyrtyx
    Warrantyvoider

**Thanks also to:**
Feckless
gibbed
gildor

To my knowledge, none of the people listed below have contributed code to the toolset, either directly or indirectly. I'm totally unfamiliar with Azulath, Bracketh, and Morpheus839; they should be removed until we know if they contributed code. Ottemis, Renimiri, and myself have not contributed our own code. TankMaster also has not contributed code; his tools are currently his own (so far), he simply has a dev thread on the forums.

Therefore, the following names should be removed:

Azulath
Bracketh
Giftfish
Morfeus839
Ottemis
Renmiri
TankMaster

**Comment by Mgamerz** [comment]
Heff can you assign me this. I can't do it on the mobile site.

**Comment by Mgamerz** [comment]
giftfish, don't know if you're on a really old version but a number of the items you list are up to date already or don't exist. I can't even find TLK Editor, and things like Coalesced Operator are already named this in the last couple of versions. Working on the rest still.

Edit: NVM, I see you're talking about the title of the window boxes. What you see in ME3Explorer is the toolstrip at the bottom while in the code editor it looks like a window. Fixing them now.

I put WarrantyVoider at the top of the list because he's simply the top one to credit.

Also I really don't think TLK Editor should be named Dialog Editor. Not all strings in the game are dialog.  In fact lots of them aren't. Perhaps Strings Editor. Or Localization Editor. User's won't know that Dialog and other strings are actually the same thing.

**Comment by HeffU** [comment]
The names posted here was decided on in the forums afaik, so we should use those provided, further discussion can happen later.

The menu items are edited if you check in visual studio, but for a lot of users the old names are still whats visible when you actually run the tool, did you run it to verify that things are actually visible?

**Comment by HeffU** [comment]
Some of the edits are indeed still only visible in the designer view, but not when running. It's most likely related to the language selection feature, I'll look around for a file.

**Comment by HeffU** [comment]
Turns out the language file overwrites designer text, which is not surprising. It can be found in resources/exec/languages.xml.
Not all items are in the translation though, so its mightily confusing, we should refactor later.

I fixed all items on the list now, mostly the items in the user tools menu that were being problematic.
Also you had forgot to link the buttons for the relocated interp and tlk tools, but that's fixed now.

Otherwise looks good to me.

**Comment by Mgamerz** [comment]
Weird. I checked at runtime but it didn't appear off. Maybe I have a
different language?

**Comment by HeffU** [comment]
There are only english and german, so I doubt it. In any case everyone else got the wrong results in runtime, but it's fixed now so this issue will close once I merge it to master.

**Comment by ghost** [comment]
FYI, I didn't say to rename the TLK Editor to Dialogue Editor, I said this:

"TLK Editor -- relocate to Dialog submenu"

Just like with the Interp Editor.

Please revert that incorrect name change if it's been implemented, and proceed with the relocation.

**Comment by HeffU** [comment]
Fairly sure I doublechecked that before closing this, both the relocations are done but no name change was done to them. I'll as for you to doublecheck once r716 is out that includes these changes.

**Comment by ghost** [comment]
Coolio. Gracias :)

**Comment by Mgamerz** [comment]
Must have misread it or something.
