### ISSUE TITLE
r746, ME1 Textures Improper Install; Mips? Alpha?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#273]
First, this is a monumental achievement. I just perma-replaced my very first texture for ME1 with 100% success. Yay! Sort of. There's some type of issue with alpha.

I used CDAMJC's Avina body textures. Both the diff and VFX texture. Here's what it should look like; this is with Texmod:
![masseffect 2016-03-25 12-40-20-35](https://cloud.githubusercontent.com/assets/13645804/14052435/8efc7cfa-f287-11e5-845b-13275586e5e1.png)
Here is what the exact same two textures look like, installed with Texplorer:
![masseffect 2016-03-25 11-56-51-51](https://cloud.githubusercontent.com/assets/13645804/14051676/08dbaf1a-f282-11e5-90b3-8fcf6f9a691e.png)

Obviously there's a problem. Her body is almost invisible; her head almost as much. 

Since the texture works properly in Texmod, that leads me to think the following:
1. Improper alpha in the texture
2. Bad alpha handling in Texplorer
3. Bad Texturegroup re-assignment
4. Bad texture replacement
5. Incorrect INI setting
6. ?

Here's what the alpha channel for both new textures look like in GIMP:
![alphaproblem](https://cloud.githubusercontent.com/assets/13645804/14052656/04157be4-f289-11e5-86d3-d83bd0ecfd94.PNG)

I understand the black/white concept of alpha, but I don't understand the discrepancy between the alpha layer thumbnail (white/opaque) and the alpha layer on the actual image (black/transparent), as displayed in GIMP. Presumably, CDAMJC knows what he's doing and the alpha is correct, but I don't know this for certain. Upon extracting the vanilla textures, their alpha is identical to each other and to the modded textures.

Here's a side-by-side:
![avina_compare](https://cloud.githubusercontent.com/assets/13645804/14052509/20de9cc0-f288-11e5-8a78-48acc3d90a4d.PNG)

The left one is a DIFF, the right a SPEC. The Texturegroup changes from this to LightandShadowmap
![lod group changed](https://cloud.githubusercontent.com/assets/13645804/14052624/d3e9f74c-f288-11e5-917d-d27696d102cc.PNG)

So... any idea what the problem is?

**Comment by starkgate** [comment]
What does the vanilla alpha look like ? I don't think it is a bug with MEUITM either, but you never know.

**Comment by ghost** [comment]
@CreeperLava -- 

> Upon extracting the vanilla textures, their alpha is identical to each other and to the modded textures.

In short, black in the image, white in the alpha thumbnail. Modded and vanilla alpha are identical.

**Comment by ghost** [comment]
Thought I'd post something that installed perfectly... just because.

Here's Kasumi looking perfect in ME2 with JeanLuc's texture that I made a couple tweaks to. The diff, norm, spec, and spwr have been edited:
![masseffect2 2016-03-25 15-16-03-97](https://cloud.githubusercontent.com/assets/13645804/14055188/f1bbecb2-f29c-11e5-9829-f132828487ba.png)

If there is an alpha issue, I'm guessing none of these are affected.

**Comment by KFreon** [comment]
That's suuper weird.
I'll see what I can find but one there looks greener than the other. Which is which there?

**Comment by ghost** [comment]
@KFreon -- Top is vanilla, bottom is modded. I also noticed it was more green, but that shouldn't be affecting the alpha, which is what _seems_ to be the problem.

One thing I should also point out is that CDAMJC has this perma-modded into his EXE version of MEUITM, and I know from our PMs he's made most of it based on the current stable. That suggests we've implemented something that has changed how alpha is handled -- at least in some instances.

Kasumi aside, this indicates we need folks to do additional testing on alpha-sensitive textures. Facial textures would be a good example.

**Comment by KFreon** [comment]
It'd be good to narrow it down to just that extra green diff. 
If you just change the spec, does it behave as expected?

To be clear, I have no idea what could possibly be causing this, but that extra greenness raises my eyebrows.

**Comment by ghost** [comment]
Uh, I can do the replace quick just with the spec. Gimme sec.

**Comment by ghost** [comment]
@KFreon -- Nope. Slightly different results, but same basic issue:
![masseffect 2016-03-26 18-17-16-30](https://cloud.githubusercontent.com/assets/13645804/14063281/619a1cb0-f37f-11e5-896e-b0959e012295.png)
![masseffect 2016-03-26 18-17-38-23](https://cloud.githubusercontent.com/assets/13645804/14063282/632f04e6-f37f-11e5-9520-9afc59602edf.png)

What's really strange is that it's affecting her head, as well, but her head is a totally different texture set. Just look at the ME1 textures for her head and you'll see what I mean. You can see it in the comparison in the OP, too. I am _only_ replacing the two body textures, but that replacement is changing her head, as well.

So, are you convinced the textures themselves are formatted properly alpha-wise, based on my screenshots?

**Comment by KFreon** [comment]
Yeah. The textures themselves look fine.
I don't know what the heck is going on there.

It's possible that that spec is used for her head as well? 

Also, so the spec only makes a mess, does the diff only make a mess too?

**Comment by ghost** [comment]
Yeah, it's like installing it basically makes it disappear. I'm wondering if the texture simply isn't being installed properly, period. I haven't had the chance to test anything else for ME1, yet; I wonder if it's just this one or if there's issues with alpha, period.

**Comment by ghost** [comment]
Hrm. K... the VFX texture is a DXT1... what about the 80%/20% thing we were talking about in the other thread?

Let me try to replace just the diff and see what happens...

**Comment by KFreon** [comment]
That's why I want to know what happens with the diff only.
Cos that did occur to me too.

**Comment by ghost** [comment]
Sorry, I missed that originally.

So, diff is a problem, too:

![masseffect 2016-03-26 18-52-21-34](https://cloud.githubusercontent.com/assets/13645804/14063399/3733b30a-f384-11e5-9d8d-3ea04d3a7ba6.png)

This result is surprising. I am 100% sure I vanilla'd files in between, and replacing the diff also prevents the VFX texture from being shown. It's like she's barely there.

**Comment by KFreon** [comment]
Yeah...this looks weird alright.
I dunno what to say about it.

**Comment by ghost** [comment]
What I want to know is how CDAMJC got it installed into his game, and if anyone else has had the same problem.

One thing I haven't tried is installing it via TPF Tools rather than Texplorer. I'll post the issue today in the Stable Thread on the forums and see if anyone else has had the same problem.

If nobody responds, I'll try PMing CDAMJC on Nexus and see what he has to say.

**Comment by ghost** [comment]
Tried with TPF Tools and same basic results. This time I did try installing the new head diff as well, though. Here's what happened:

![masseffect 2016-03-27 08-36-44-48](https://cloud.githubusercontent.com/assets/13645804/14066144/4e29a1f0-f3f7-11e5-919f-94ed99a6258f.png)

**Comment by ghost** [comment]
There's an issue with the EngineFonts that I'm wondering if it has to do with this. Check out how it looks in r746 and something like... r720, I think:

![formaterrortex2](https://cloud.githubusercontent.com/assets/13645804/14066599/1312fba0-f403-11e5-9a8c-f3ed3160cdc1.PNG)

**Comment by starkgate** [comment]
Did you rebuild the thumbnails, by any chance ? There is a minor issue with rebuild thumbnails per folder, where the thumbnail would appear white until you reload Texplorer.
Edit : Forget it, there's definitely an issue. Even double-clicking shows up entirely white on my side.

**Comment by ghost** [comment]
@CreeperLava -- Yep, and I did rebuild the thumbs, anyway.

**Comment by KFreon** [comment]
WTF. I swear I checked those cos I noticed they were white in someone elses screenshot.

**Comment by KFreon** [comment]
HAHAHAHAHAAAAA
Ok, so it's not broken. Its just that there's no RGB; The text is all in the alpha channel...which is white.
So it's white on white. Much amusement.

Bad news is...I dunno how to fix that while still having everything else working.
The reason it worked before is because I used to merge the alpha down instead of stripping it out.
We changed it to remove alpha so that other textures were visible though.

**Comment by ghost** [comment]
@KFreon -- Okay, so some new info. I finally got around to testing a different set of textures for ME1. We definitely, _definitely_ have a problem for texture replacement in ME1. A problem that does not occur in ME2 or ME3.

Here's CDAMJC's Elcor texture under Texmod:
![masseffect 2016-03-28 08-31-07-40](https://cloud.githubusercontent.com/assets/13645804/14081642/94cebfd6-f4c0-11e5-822a-4f3b0ebc30cd.png)

And, here it is permamodded via TPF Tools:
![masseffect 2016-03-28 08-37-17-09](https://cloud.githubusercontent.com/assets/13645804/14081657/a9a9957a-f4c0-11e5-9098-710c9bd69eba.png)

Pretty much like Avina's body, but more opaque -- which makes sense -- as Avina is mostly transparent, anyway.

And, here's another piece of the puzzle that's interesting. This was happening to Avina, too, but with her VFX, I wasn't 100% sure it was relevant:
![masseffect 2016-03-28 08-36-54-09](https://cloud.githubusercontent.com/assets/13645804/14081681/c5b18804-f4c0-11e5-961d-e46af14b6708.png)

So, maybe this "alpha" issue, is actually a mips issue. If distance affects the problem, that certainly suggests mips.

I should also be clear that **these textures have not been autofixed**. They are properly formatted, installed without error, and these are the results. 

It would also be very, very handy if someone else can replicate these issues on their ME1 install. I'm aware there are various INI settings for ME1 to handle larger textures and some of these are 2K and 4K textures. We also need to be sure that isn't the problem. I wouldn't think so, as I'd think the toolset should be modifying the INI that if something like that is required for proper installation, but... who knows.

@Kfreon, @SirCxyrtyx , would looking at the modded files with ME1's Package Editor point us in some direction? There's a UPK and 3 SFMs for the Elcor. For Avina, there's 2 UPKs. I can zip them up and toss up a link.

_EDIT: I double-checked my INI and here's what I have set up for the modded LOD group:_

`TEXTUREGROUP_LightAndShadowMap=(MinLODSize=256,MaxLODSize=4096,LODBias=0)`

_Not sure if any other INI setting that I might have changed would affect the rendering in game. This seems to be the logical one_

**Comment by KFreon** [comment]
Hrm....
Lets summarise:
- Avina is more transparent than normal, but that fixes itself with distance.
- Elcor is black up close, but normal at a distance.
- All textures fully formatted. No autofix.

Interesting...that gives us a place to start anyway.

What happens if you remove that ini line? Or change the MaxLODSize to 2048?

**Comment by ghost** [comment]
@KFreon -- I definitely wouldn't suggest removing the INI line. My INI is lightly-modded, and that line is vanilla; if BW put it there, it should stay there. The INI was my first thought, but I've verified that line against a vanilla INI; it's not the problem. 

If we _really_ want me to make sure it isn't modded INI's, then I should back them up and just let the game create new ones upon re-launch. However, the thing is, is that my INIs, if anything, should improve the situation. I modded them long ago for MEUITM, to make sure they would maximize texture quality with higher rez textures. The exact sort that I've installed for Avina and the Elcor.

Avina. It's not just that she's transparent, but you can tell on her body that the texture is basically not there, or barely there. She is a solid blue shadow. My _guess_ is that if she were more  "solid" (less transparent) like the Elcor, she'd probably look solid black like him.

**Comment by KFreon** [comment]
I'm fairly sure there's code that adds that line to the ini, and I make the point because there was an issue ages ago related to the lod settings in the ini.

I'll look into it, but more relations between the textures would be good, like size, format, etc

**Comment by ghost** [comment]
@KFreon -- FYI, Just changed the Issue title to more accurately describe the problem.

I haven't rolled INI's back to vanilla yet -- I'll do that momentarily, but K, I know for certain that line is not added by the toolset. Despite not rolling back yet, I know that b/c the various sites I use to tweak the INI, always quote the vanilla INI settings and then comment on how to change them, such as:

http://forum.bioware.com/topic/215916-making-the-most-of-your-me1-pc-experience-maximizing-graphics-and-sound/

and

http://www.tweakguides.com/ME_8.html

Both mention the exact same line and quote the same vanilla setting I pasted above. But, I'll be sure to double-check it when I allow the game to re-generate the vanilla INIs. I'll also zip those up so you can take a look -- assuming you don't have them. Do you have ME1 installed?

Btw, do you want me to maybe PM CDAMJC on Nexus and see if he might have some ideas? Or not quite yet?

**Comment by ghost** [comment]
Tested ME1 with new INIs I forced it to generate upon launch. Same results, but with the elcor, it's a little harder to tell since I can't use flycam (requires modded INI).

Btw, here's a picture of Avina looking fine, further away, just like the elcor:
![masseffect 2016-03-29 07-24-46-56](https://cloud.githubusercontent.com/assets/13645804/14111568/1a820bdc-f580-11e5-89c3-e82d566a1955.png)

Here's another pic the elcor at a distance where the texture is about half and half. There is a small difference with this. Standing at the same distance with flycam in the modded INI, it's solid black; in the vanilla INI it's only _mostly_ black:
![masseffect 2016-03-29 07-25-39-21](https://cloud.githubusercontent.com/assets/13645804/14111614/3719e8b4-f580-11e5-9fb9-182763c596fd.png)

Here's here's the vanilla settings for LOD groups (modded textures are assigned to LightAndShaowMap):
`[TextureLODSettings]
//TEXTUREGROUP_Character=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
//TEXTUREGROUP_CharacterNormalMap=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
//TEXTUREGROUP_Effects=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
TEXTUREGROUP_LightAndShadowMap=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
TEXTUREGROUP_RenderTarget=(MinLODSize=1,MaxLODSize=4096,LODBias=0)
//TEXTUREGROUP_Skybox=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
//TEXTUREGROUP_UI=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
//TEXTUREGROUP_Vehicle=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
//TEXTUREGROUP_VehicleNormalMap=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
//TEXTUREGROUP_Weapon=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
//TEXTUREGROUP_WeaponNormalMap=(MinLODSize=256,MaxLODSize=4096,LODBias=0)
TEXTUREGROUP_World=(MinLODSize=16,MaxLODSize=4096,LODBias=2)
TEXTUREGROUP_WorldNormalMap=(MinLODSize=16,MaxLODSize=4096,LODBias=2)
TEXTUREGROUP_AmbientLightMap=(MinLODSize=32,MaxLODSize=512,LODBias=0)
TEXTUREGROUP_Character_Diff=(MinLODSize=32,MaxLODSize=512,LODBias=0)
TEXTUREGROUP_Character_Norm=(MinLODSize=32,MaxLODSize=512,LODBias=0)
TEXTUREGROUP_Character_Spec=(MinLODSize=32,MaxLODSize=256,LODBias=0)
TEXTUREGROUP_Environment_512=(MinLODSize=32,MaxLODSize=512,LODBias=0)
TEXTUREGROUP_Environment_256=(MinLODSize=32,MaxLODSize=256,LODBias=0)
TEXTUREGROUP_Environment_128=(MinLODSize=32,MaxLODSize=128,LODBias=0)
TEXTUREGROUP_Environment_64=(MinLODSize=32,MaxLODSize=64,LODBias=0)
TEXTUREGROUP_VFX_512=(MinLODSize=8,MaxLODSize=512,LODBias=0)
TEXTUREGROUP_VFX_256=(MinLODSize=8,MaxLODSize=256,LODBias=0)
TEXTUREGROUP_VFX_128=(MinLODSize=8,MaxLODSize=128,LODBias=0)
TEXTUREGROUP_VFX_64=(MinLODSize=8,MaxLODSize=64,LODBias=0)
TEXTUREGROUP_GUI=(MinLODSize=8,MaxLODSize=1024,LODBias=0)
TEXTUREGROUP_Environment_1024=(MinLODSize=32,MaxLODSize=1024,LODBias=0)
TEXTUREGROUP_VFX_1024=(MinLODSize=8,MaxLODSize=1024,LODBias=0)
TEXTUREGROUP_APL_128=(MinLODSize=32,MaxLODSize=128,LODBias=0)
TEXTUREGROUP_APL_256=(MinLODSize=32,MaxLODSize=256,LODBias=0)
TEXTUREGROUP_APL_512=(MinLODSize=32,MaxLODSize=512,LODBias=0)
TEXTUREGROUP_APL_1024=(MinLODSize=32,MaxLODSize=1024,LODBias=0)
TEXTUREGROUP_Character_1024=(MinLODSize=32,MaxLODSize=1024,LODBias=0)
TEXTUREGROUP_Promotional=(MinLODSize=32,MaxLODSize=2048,LODBias=0)`

Sorry about the formatting; not sure what Git is doing there. @KFreon , let me know if you want me to zip up all those vanilla INIs for you.

**Comment by ghost** [comment]
@KFreon -- Here's a thought... and I will really laugh if this is all (sort of) my fault. 

Is the toolset supposed to modify an INI? If so which one(s) and which setting(s)? I just remembered that I keep mine set to "Read Only" to dodge the ME1 bug where it just randomly decides to regenerate and replace your INIs, undoing all previous edits. After having this happen to me more times than I'd like to count (and me not always keeping a backup of my _current_ version) I finally set them to read-only so the game couldn't screw me anymore. But, if the toolset is supposed to modify a setting, that means that it probably can't do it.

If this is the problem (I sort of hope it is, b/c then the issue is solved), I'll need to talk about it on the wiki. I'm almost certain I got the read-only idea somewhere on the BW forums, so there's a very good chance that other folks modding ME1 have done the same thing and will experience the same problem.

**Comment by ghost** [comment]
@KFreon -- Finally got some confirmation that this isn't just me. Deager gets the same results.

Currently waiting to hear whether his INIs are modded at all, and what the situation is there. I'll edit this with an update when I find out.

**Comment by HuntersRun1** [comment]
Heh Deager beat me to it. New user and I was browsing the me3explorer website when I saw you wanted confirmation on this issue. so as I was already in the middle of a mass effect playthrough did some testing and got the same results.  I am unable to register there(cannot see code) so I am posting this here.

Some notes from testing (unsure what might be useful): Win 10-64 bit. I got the same issue as others whether tpftools or texplorer. I was using meutim but I reinstalled my backups. After testing I reinstalled meutim and I noticed that the textures were still vanilla. I  deleted  the shader cache using the configuration.exe and the meutim textures reappeared. I did not delete the cache during testing so I am unsure if that makes a difference or not.  Also my ini's were set to uncheck read only.

**Comment by ghost** [comment]
@HuntersRun1 -- Thanks for all that info, actually... the shader cache is another good thought. I'm running the shader cache fix, and I'd be surprised if Deager wasn't. I wonder if that could be involved.

Have you tried backing up your modded shader cache files (assuming these are the ones CDAMJC provides) and trying vanilla ones?

**Comment by ghost** [comment]
FYI, I've verified that reverting shaders to vanilla doesn't help, nor does deleting the shader cache.

This indeed seems like a toolset issue. We now have replication in triplicate and I'm out of ideas on what else it could be.

**Comment by ghost** [comment]
@KFreon -- Any thoughts on this, btw, now that we're certain it's a toolset issue?

Also, like I said previously, I know from speaking directly with CDAMJC that he has used mostly the current stable to build the EXE version of MEUITM. This version installs all ME1 files, with the textures already permamodded in. So, whatever problem we have now, it does not exist in the current stable.

Not like there aren't a bajillion changes between r653 and r747, but between that and the issue with mips/alpha that we're seeing, maybe that gives you some ideas?

I'll try re-building my ME1 tree again today, just to double-check on debug output. Be sure nothing looks wonky.

**Comment by KFreon** [comment]
I haven't had a chance to look into this, but there was a similar issue ages ago with null mips on top. Salt implemented a top null removal feature, a button I removed not long ago due to it being inconsistent, and that I thought the problem had gone away. 

That's where I plan on starting, then I'll compare the "stable" with the latest rev and see if anything in the texture or PCC handling has changed.

**Comment by ghost** [comment]
@KFreon -- Does that problem only affect ME1, though? That should really be the largest clue -- something that affects ME1 and not ME2/3. Texture handling for ME2/3 basically seems to be perfect, short the few issues Creeper has been tracking with alpha, autofixing, conversions, and stuff.

**Comment by KFreon** [comment]
Yeah back in the day it was me1 specific.

**Comment by KFreon** [comment]
I don't suppose you have a save I can use? I don't want to have to get all the way to the citadel to test this one.

**Comment by ghost** [comment]
Of course I do :)

Sending to you on Skype.

**Comment by KFreon** [comment]
After an entire day of testing, SUCCESS!!
It was all down to how Texplorer does installation to multiple PCC's.

**What I was doing:**
- Load pcc
- Load texture2D
- Modify texture2D
- Save pcc
- Copy changes of texture2D to all remaining pcc's

**What I should have been doing:**
- Load pcc
- Load texture2D
- Modify texture2D
- Save pcc
- _REFRESH PCC and TEXTURE2D so changes are propagated through the remaining pccs._
- Copy changes of texture2D to all remaining pcc's

Apparently the former wasn't good enough for ME1. At this stage, I'm too lazy to find out exactly what this changes, by which I mean why does the object have to be regenerated? It's changed enough for the first pcc, why not the rest? 
Curious, but no time or patience for that level of debugging.

EDIT: This may explode some things come to think of it as I also allowed external textures to be directly modified...I may need to revert that. I'll put a rev up here for some intermediate testing to see.
[Check it](https://dl.dropboxusercontent.com/u/37301843/ME3Explorer_ME1TESTING.7z)

**Comment by ghost** [comment]
Looking forward to testing this.

One question, though. Does TPF Tools use the same method of replacement? Presumably so? Just pointing out at the problem was discovered with Texplorer, but isn't isolated to it.

Will test today, and see if I can wrangle up some others to test :D

**Comment by KFreon** [comment]
I didn't test Texplorer actually, just TPFTools, but they use the same methods.

**Comment by HuntersRun1** [comment]
So I ran a quick test. Note the texplorer gui has scaling issues so I couldn't change the game. I had to import the me1 tree from a previous rev. I ran the avina and elcor textures through tpftools and it seemed to have worked. I didn't notice any adverse effects, but I was only in the game for a minute.

**Comment by ghost** [comment]
Yep, it's definitely working :D

**Comment by ghost** [comment]
@KFreon -- Hmmm are you certain this change was pushed into the rev?

I just installed CDAMJC's Avina's body DIFF via Texplorer, and she's disappearing again. This was indeed fixed in the most recent text rev you posted on the forums, but I'm pretty certain I tested it via TPF Tools, in case that matters.

---

EDIT: On a whim, re-tested this via TPF Tools and the TPF. Installation via that method worked perfectly. So, it seems that Texplorer and TPF Tools use different install methods? That seems... problematic >.>

**Comment by alvarome** [comment]
Hi:

I have just ran some ME game textures install test. FWIW, all went ok here. 

I installed all three CDAMJC´s Avina textures separately -cheking in game after every single install- and all seemed to work here.

I also installed the Avina.tpf file and it worked too.

![avina](https://cloud.githubusercontent.com/assets/17484308/14367920/7959fd06-fd12-11e5-8118-7a04d7ee8595.PNG)

And I also installed all Elcor .dds files and no LOD problems so far.

I deleted shaders cache previously -and after- every install just in case that would have any side effect.

HTH!
Alvaro

EDIT --> I used TPF/DDS tools for those test!

**Comment by ghost** [comment]
@alvarome -- Yep, it's definitely just Texplorer that's the problem. Thanks for the verification :)

**Comment by KFreon** [comment]
Fixed. Same issue as before, since again for some reason there's multiple installation methods, even though they do basically the same thing.
I'm hankering for a rewrite again.

**Comment by ghost** [comment]
I'm also hankering.

K, can you put up a test version of this, so I can test prior to the next rev?

**Comment by KFreon** [comment]
Will do.
EDIT: Test build.
[ME3Explorer_Stable Prep.zip](https://github.com/ME3Explorer/ME3Explorer/files/210981/ME3Explorer_Stable.Prep.zip)

**Comment by ghost** [comment]
@KFreon -- Does this have all the changes for all the issues you just closed? That way, Creeper and I could give everything a preliminary test. Assuming everything's fixed, then the official rev could be the the final testbuild for the stable.

**Comment by KFreon** [comment]
Yes it does. Test away :)

**Comment by starkgate** [comment]
On my side of the world I'm already gone from home, so I won't be able to test for a week or 2.

**Comment by ghost** [comment]
And, fixed in the prebuild for r749 :)
