### ISSUE TITLE
r746, Texplorer, GUI Texture Scaling

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#274]
So this one is pretty funny, lol.

Testing texture replacement in ME2, and there's a problem with upscaling. It's _entirely_ possible this is an engine limitation and GUI textures simply cannot be upscaled -- or that an INI setting adjustment is required.I wanted to post it just in case it did have something to do with Texplorer. @Kinkojiro, I'd be interested to know what you think, especially.

Here's what happens when I replace the hanar codex image (512x256) with a different texture that's 1024x512:
![masseffect2 2016-03-25 13-54-50-01](https://cloud.githubusercontent.com/assets/13645804/14053931/3aae5f50-f292-11e5-97ee-f00267abafbb.png)

I should be clear that in ME3, upscaling GUI textures isn't a problem at all. All the new war asset and codex images I've made are 2x vanilla size and no additional game setting modification is required for it to render properly in game.

**Comment by starkgate** [comment]
Some ALOT users also reported this sort of error with a galaxy GUI texture, also in the codices iirc. I think this is a game problem, not related to ME3Explorer.
[Screenshot](http://imgur.com/M3KVmjx)

**Comment by ghost** [comment]
@CreeperLava -- Yeah, it's either that or some scaling mojo that Texplorer does for ME3 that it doesn't for ME2... or the mojo for ME2 needs to work differently.

**Comment by KFreon** [comment]
I'm not familiar with these kinds of textures.
What's wrong with that screenshot?

**Comment by starkgate** [comment]
The texture is not contained in the box, as it should, instead it goes beyond the borders, which it shouldn't^^.

**Comment by KFreon** [comment]
Ohhhhh I see now.
This seems to be an engine thing since the "size" of a displayed image isn't due to Texplorer-y things.
Right?...

**Comment by ghost** [comment]
@KFreon -- 

> This seems to be an engine thing since the "size" of a displayed image isn't due to Texplorer-y things.

Well, that's sort of what I wasn't sure about. I mean, why is it that a 4K texture can be used for armor, but apparently can't for GUI texture replacements? I had no idea what mojo Texplorer does under its hood, lol. I thought it was entirely possible you hadn't incorporated some type of code for GUI textures, as they are a bit of the exception to the rule.

**Comment by starkgate** [comment]
When you think about it, it does make sense that you can't upscale GUI textures. There is no use to upscaling them, since they would be downscaled anyways to fit in the box and you won't ever be able to zoom in on them, like you would with armor.

**Comment by ghost** [comment]
@CreeperLava -- Well, part of my point though, is that they scale without problems in ME3. I can also tell that they do scale dynamically in ME2 and ME1, at least to a certain extent. I know this b/c the texture that appears on my monitor isn't actually 512x256. If I screencap it and open it next to the actual texture in GIMP, it's smaller. So, it's not rendering at 100% size in the game engine -- and I'm pretty certain that 1920x1080 is the max resolution for ME2.

No, you can't zoom in on GUI textures like armor, but you also shouldn't _be able_ to zoom in on armor in any of the games. ME does not allow zooming. The only way you're going to see high detail on armor outside of a cutscene is if you mod the coalesced and insert flycam capabilities. BW doesn't count on players modding in flycam anymore than they count on players modding in new textures. The point is that they didn't actively insert scaling into the game engine to allow _us_ to do these things.

To me, it makes sense that GUI textures would be scaleable b/c it will keep them sharp at higher monitor resolutions, just like with anything else. If there is a difference b/n ME2 and ME3, then with ME3 as a new game, it's likely BW implemented it just for that reason -- the higher monitor resolutions that were becoming available.

**Comment by KFreon** [comment]
The more I read, the more I'm sure this isn't Texplorer's fault. It just replaces image data, nothing to do with mapping etc.
I suspect the following, with background info:
- Armor etc gets UV mapped. An image of any size is confined to a certain physical region.
- UI images may be directly linked to the resolution being used.
- UI images may not be scaled by the engine at all since they were a known size to the developers. Saved coding.
- SO, there might be a mapping variable or some way of confining the UI to a certain space.

**Comment by ghost** [comment]
@KFreon -- Ahhh, UV mapping. This is something I only understand a little about, but that makes sense. UV-mapping is what defines how the texture is wrapped to the 3D mesh. So it apparently helps control scaling.

UI textures probably don't even have a mesh. They are flat and 2D, so wouldn't need to have UV mapping. So, like you say, it might just be that ME2 doesn't support it, and ME3 for whatever reason, does.

Okay, I'd say if you're comfortable with it, the issue can't be closed, K. When I update the wiki again for the stable, I'll be sure to include some information about it :) If we ever want to look into it more later on, we can.

**Comment by KFreon** [comment]
Technically the UV mapping was done by the artists, but what I mean is that the engine takes a texture, not matter how big, and sticks it on a mesh of a known physical size.
The UI just grabs a texture and sticks it on the screen, not caring about the size because the artists just made it the right size.

Sounds good though. It's unfortunate, but no time to fiddle now :)
