### ISSUE TITLE
rev746 ModMaker append hash

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#275]
Extracting textures in ModMaker doesn't append a hash to it, like it does in TPF/DDS Tools. You only end up with the name of the texture itself, eg HMM_ARM_whatever.dds
Here a picture of what the analyzed/non analyzed textures look like in TPF/DDS Tools, you can see that the hashes are indeed there.
![capture](https://cloud.githubusercontent.com/assets/12874678/14054416/59e6b538-f2d9-11e5-9074-2f1794116aa7.PNG)
[Testing file](https://mega.nz/#!9hchQDLC!raymNMTQxGSEgGUOLC9X4DgN1EfINM4iw1U5fF3R_5Q)

**Comment by KFreon** [comment]
Correct. This is due to modmaker doing other things besides textures.
It doesn't check trees or anything.
If you want to extract stuff in this way, try loading it into TPFTools. It does mods.

**Comment by starkgate** [comment]
The screenshot is from TPF Tools. If this is intended behaviour, I will close the issue.

**Comment by KFreon** [comment]
Oh wait. Really? That's not the expected behaviour then.

**Comment by starkgate** [comment]
I think you may have misunderstood what I just said :
- Extracting textures in ModMaker doesn't append a hash
- Loading textures in TPF/DDS does show the hashes, as you can see in the screenshot
- Extracting textures in TPF Tools **does** append a hash

**Comment by KFreon** [comment]
Ohhhhhhh good.
So it is just modmaker that doesn't extract with hashes. Ok that is intended.
TPFTools should extract with hashes no matter the source (dds, tpf, mod)

**Comment by ghost** [comment]
@KFreon -- Have you changed something with this in rev748?

If you use Extract All or Extract Selected with multiple files, ModMaker names them automatically. However, if you Extract Selected with only a single file, the user has to name it manually. 

This didn't used to be the case; can we return to the old behavior where any extraction is automatically named?

**Comment by KFreon** [comment]
So when you extract a single job, the save window has no text?

**Comment by ghost** [comment]
Correct.

Extract 1:
![mm_saveone](https://cloud.githubusercontent.com/assets/13645804/14371868/870aa88c-fcf0-11e5-888a-65f3abc5637c.PNG)

This might have to do with when you implemented the new folder dialog hack, not sure.

Sorry for the gigantic screencap, btw. The new folder choosing dialog (which is awesome) doesn't allow you to resize the window. It's automatically full-screen and non-scaleable. I... haven't submitted an issue about that, lol.

**Comment by KFreon** [comment]
I'm not sure why yours doesn't allow resize...
![image](https://cloud.githubusercontent.com/assets/7845997/14376644/25af9110-fdae-11e5-9142-7def4355963b.png)

Fixed either way.

**Comment by ghost** [comment]
@KFreon -- My guess was that it was related to the scaling issue.

**Comment by ghost** [comment]
@KFreon -- The file name issue is is fixed in the rev749 prebuild.

The fixed window issue remains, though. The right bottom corner gives the impression the window should be re-sizable, but it isn't. Not a huge deal. Guessing it'll work itself out with the transition to WPF.

**Comment by KFreon** [comment]
Well what's weird is:
A) Mine isn't any different to any other dialog window.
B) It is resizable.

I might sound silly, but is yours maximised?
There's no settings for that dialog that I can find to control the sizing.

**Comment by SirCxyrtyx** [comment]
I think this is a system setting actually.. For some reason, yours is set to open the dialog maximized. If you right click on the title bar, you can choose "Restore", and that will make it normal again. This should persist the next time you open the dialog.

**Comment by ghost** [comment]
@SirCxyrtyx -- Ha, that worked.

It wasn't happening in any other program, though, only in the toolset. It coincided with the folder window change, so I figured it was that. Not sure how it got changed; I wasn't even aware of the setting. Must have been some type of weird mis-click.

Mystery solved! Thanks :)
