### ISSUE TITLE
rev746 minor:  Export function defined level items not showing in PCCEditor

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#278]
Bioware uses pcc held functions (i.e. not imported from engine/sfxgame) for certain placeables in the levels (things like SFXMedKit or SFXMedstation.  Also ammo, turrets etc).

PCCEditor / Interpreter cannot interpret these because there is binary code at the start of the object (the usual level interfacing item headers).   For some reason if the object is a typical imported object (interpactor for example), then the header is understood.  But not if it is locally defined function.

I am guessing PCCEd looks at a table of items for "level placeables" and doesn't include functions defined in the pcc.   The best solution would be to instead look at the Flags.

**Solution:**
02 flag is needed if the export header if the object is included in the level.   All these items should have the binary level interface header items.  This should define whether pcced2 reads from the start or after the header.

This is a minor thing only needed for high end modding.

**Comment by SirCxyrtyx** [comment]
Do you have an example file and object where this occurs?

**Comment by Kinkojiro** [comment]
BioD_CerJcb_450Evacuate.pcc as it has lots of different examples:
Objects:
2379 SFXPlaceable_Generator
2381 SFXPlaceable_ShieldGenerator
2358 SFXMedkit

Also BiOD_GthN7a_200Patrols:
9217 SFXPlaceable_GethTripMine

BioD_KroGar_600WalkA.pcc
9883 SFXAmmoContainer
9987 SFXMedkit

**Comment by SirCxyrtyx** [comment]
Interesting. The Interpreter is already using that flag detection method, so _it_ works. For some reason the PCCEd property view is just checking to see if the first 4 bytes are a negative integer? I guess that's an import list reference, which would explain why locally defined classes don't work. Making it use the same function as the interpreter is simple enough.

edit: This incorrect method is used all over the toolset actually. Refactor incoming.

**Comment by Kinkojiro** [comment]
Thanks.
