### ISSUE TITLE
r746, Image Engine, Header Field Unreadable

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#279]
@KFreon -- I'm not sure if this is supposed to be there or not (it's new), but it's entirely too small to be readable:
![imgengine](https://cloud.githubusercontent.com/assets/13645804/14060794/7d986a82-f32c-11e5-87b1-5d57072cd228.PNG)

**Comment by KFreon** [comment]
It's meant to be small since it's info almost no one would need, but is handy for seeing stuff.
I toyed with making it bigger, or having a different area to show it in, but it was easier this way.

Maybe I'll make it a button though.

**Comment by ghost** [comment]
Yeah, I'd make a "Properties Button" or something; maybe above the alpha challen tickbox. Users shouldn't need to scale their entire UI just to read it, and at 1920x1080, it's unreadable, as you can see.

**Comment by KFreon** [comment]
Done.

**Comment by ghost** [comment]
@Kfreon -- The tickbox is a good solution, but the text is still very, very small. And, with it being almost the same color as the background, it is hardly legible:

![dds_header](https://cloud.githubusercontent.com/assets/13645804/14066086/cc2c0478-f3f5-11e5-8502-f119eacba6db.PNG)

If you really, _really_ don't want to make it bigger (which I think is a mistake), at the very least, make the text black. If people can't read it -- or if it's simply too difficult to read -- they aren't going to use it.

Sitting at a 18" laptop with 1920x1080 resolution, I can _barely_ read it with my glasses on.

**Comment by KFreon** [comment]
Made it black and a bit bigger.

**Comment by ghost** [comment]
Wewt!

**Comment by ghost** [comment]
Verified in rev748.
