### ISSUE TITLE
Texture Tool broken in 653+

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#28]
Tool is currently completely broken. Last known working functionality is in rev653 (current SF).

Texture replacement functions should be updated and at some point, as it uses outdated methods 

This tool is especially useful for non-technical, inexperienced users, as it replaces a specific texture with a single click. Created by saltisgood, right now it only affects the cabin photo, and was meant to be expanded to include especially commonly modded textures like: Shep's dress, Shep's hoodie, and a few more.

If functions are not expanded to include additional textures, then we may want to consider removing the tool from the toolset.

**Comment by ghost** [comment]
Just had a thought. We should temporarily modify this tool to trigger a pop up like the broken DDS Converter.

Namely, clicking on the tool name shouldn't open it. Instead, it should open a window that tells users the tool is currently broken and will be fixed or removed in a future release.

**Comment by HeffU** [comment]
Went ahead and disabled/added a popup for now:
b3815ba34ad8a5f4178967f826be4b2ec479aaf8

**Comment by ghost** [comment]
Great, thanks Heff.

**Comment by ghost** [comment]
We should retain the code but comment this out (or however that works) for the new stable. Remove it from the menu basically, so the user doesn't know it's there.

**Comment by KFreon** [comment]
Done.

**Comment by ghost** [comment]
Verified in rev742.
