### ISSUE TITLE
r746, ME3Exp Memory Error

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#280]
So, this time it gave me an error before it crashed:

![memory error](https://cloud.githubusercontent.com/assets/13645804/14061537/6f39d468-f33f-11e5-9fb7-cf665193732b.PNG)

Have we recently changed anything to do with memory management for the toolset? Like I said in #271, I haven't had issues with treebuilding in a very long time and I've never had a message like this. It's always when Texplorer is open, and often when I go to open another tool or soon after opening another tool. This time loading a texture in Image Engine triggered it.

In the Event Viewer there's another NET framework error for the toolset right before this happens. I wasn't doing any intensive tasks at the time. Texplorer was open to browse, that's it.

EDIT: Hm... could the fix for issue #117 or something similar be causing this?

**Comment by KFreon** [comment]
No this is somehow breaking when loading images in ImageEngine.
I've never seen it and can't really think there it could be happening.
I'll take a look around.

**Comment by ghost** [comment]
Yeah, I'd say you can close this for now, @KFreon. This feels like a different issue than #271, but I haven't been able to duplicate it. I can always reopen :)

**Comment by ghost** [comment]
@KFreon -- I'm going to say this is verified in rev748. No weird errors since this one. Maybe it was also just the NET update.
