### ISSUE TITLE
rev746 Suggestion : Keep TPF/DDS Tools checkboxes selected after autofix

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#281]
For now, autofixing selected textures resets the selection. What would be nice is to keep the selection whatever the action taken on the textures.

**Comment by ghost** [comment]
Doh. Yeah, that seems like a bug.

**Comment by starkgate** [comment]
I talked about it with KFreon this morning, and as it is something that would take time to fix, we agreed to make that a suggestion rather than a bug.

**Comment by ghost** [comment]
It's certainly a bit of both; added the enhancement tag. If K wants to change it, he can.

**Comment by KFreon** [comment]
I just want to explain why it isn't a bug.

When the textures are checked against the tree, there can be tree duplicates: Textures with the same information but maybe in a different folder or something (can't remember exactly).

These then get added to the texture list, so if I just remembered that textures 2,5,8 were checked and check them after autofix, we can't guarantee that 2,5,8 are the same textures anymore.

**Comment by ghost** [comment]
Ahhh, okay. That makes some sense then :)

**Comment by starkgate** [comment]
Confirmed to work in rev748. I tried to break it, but I couldn't.
