### ISSUE TITLE
Toolset needs a listed license

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#283]
The toolset should have a listed license so users who want to use the code can do so properly. I'm not sure what license license-less code is considered.

I would assume GPL for this project would work well, but MIT and BSD seem to be good choices as well for less restrictive.

**Comment by SirCxyrtyx** [comment]
Well, based on the half-hour I just spent reading up on licenses, license-less code is the copyright of whoever wrote it, and they can revoke their permission for its use whenever they want.

MIT license sounds good to me.

**Comment by Mgamerz** [comment]
https://tldrlegal.com/license/mit-license

**Comment by SirCxyrtyx** [comment]
So if we use the MIT license, the first line is:
Copyright (c) -year-  -copyright holders-

Who exactly do we put as the the copyright holders? A big list of everyone who's contributed code or graphics? Or just "ME3Explorer Team"?

**Comment by Mgamerz** [comment]
I would put me3explorer team. Perhaps add a link to the repo, and in readme.md put a list of code and image contributors. The team is also in the about window.
