### ISSUE TITLE
r747, TPF Tools, "Checked: Autofix" Does Nothing

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#284]
Yep, basically that.

![select_autofixbad](https://cloud.githubusercontent.com/assets/13645804/14066863/82b40b96-f40a-11e5-81b0-2515636d0456.PNG)

"Run Autofix" on the top menu works fine, but that will obviously autofix every texture loaded and not just the selected ones.

_EDIT: This related to #281, maybe?_

**Comment by starkgate** [comment]
Definitely works for me, I'm starting to think we don't use the same rev747^^.

**Comment by ghost** [comment]
@CreeperLava -- Well, just for you,Creeper, I tried it for a 5th time, and (unsurprisingly) it doesn't work.

Did you use my exact example? A GUI texture that's not square, converting from PNG to DXT1?

Btw, if you remember correctly, the scaling issues were never replicable on different machines, and you and I _always_ had different results. That's the entire reason K couldn't actually fix the problem.

**Comment by starkgate** [comment]
No, I just used a normal unfixed texture, since you didn't say it was specific to GUI textures. That could be why, indeed. I don't have any GUI textures to test with, sadly.
A good practice with these bug reports is to post a link to the testing files, which helps people who want to test and will help you when you have to check if the bug is fixed :).

**Comment by ghost** [comment]
@CreeperLava -- Well, I didn't know whether it was specific to GUI textures. The first one I happened to test didn't work. I stopped there. It happened to be a GUI texture, and it happened to be a PNG. 

What did you test, btw? What size and format was your "normal" texture before autofixing? (That you also didn't upload, btw :P). If it is unique to GUI textures, PNGs, lack of mips, or a specific size, yes, we should know.

Locating GUI textures is easy, btw. Search for "codex" in Texplorer, extract any, convert to PNG (or whatever non-game format you want).

**Comment by ghost** [comment]
LOLOL.

@CreeperLava -- You'll love this. Epic fail on my part.

I had started to get used to clicking = ticking the box. So, it was highlighted blue, but unticked. And, of course that's why it didn't work. 

Okay, closing. False alarm :)

**Comment by starkgate** [comment]
Nice work gift, if only all issues could be closed this fast :D.

**Comment by ghost** [comment]
@CreeperLava -- Ha ha. Well, I should also have been a bit more patient and tried a couple more textures.

Had I done that, I might have caught it before I reported it! Ah well.

**Comment by KFreon** [comment]
SEE!!! That's why I did it that way :P 
I wish all issues were like this too.

**Comment by ghost** [comment]
LOL, @KFreon.

Yeah, I get it, but it does work sooo much better without it. It really did bork the entire concept of arrowing through the list unfortunately.

Yay for issues that get closed without needing more work :D
