### ISSUE TITLE
Plot DB tool overhaul

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#287]
I've been looking at Plot DB to see how it stores it's data. It's simply a binary value which is fairly simple. But I played with the tool a bit and this tool is very archaic. You have to modify something like a CSV and then it doesn't display very well. 

I've been working on overhauling it so its a tabular version. 
![image](https://cloud.githubusercontent.com/assets/2738836/14162247/587d0bd0-f6a7-11e5-9362-43e61e947635.png)

You simply click on a row and enter data like excel. It's way easier and has validation for fields. It will also cut some a couple of classes because we don't need a new window for editing anymore. It's not done yet, I just wanted to announce it so someone else doesn't start working on it. This should make it much more modern-feeling. The saving and loading is all still the exact same, but maybe I will make it so you can export to formats like XML or something, so if you wanted to use a text editor you could do that too.

**Comment by Mgamerz** [comment]
@giftfish 
Can you test this out? I posted a build in https://github.com/ME3Explorer/ME3Explorer/pull/288

I know you are the biggest Plot DB user.

**Comment by ghost** [comment]
Sure, I can test it; the validation aspect is very nice.

See the rest of my post in the original issue I submitted for it (#231). I'd like to keep this all confined to the same issue, but doesn't look like I can merge them.

**Comment by Mgamerz** [comment]
Merged with #231
