### ISSUE TITLE
Asset Explorer, remove edit features

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#29]
Editing features of this tool are highly deprecated and should be removed. If the tool is retained in the toolset it should be a true "explorer" and not an editor. 

Asset Explorer's GUI is much more user-friendly for non-technical folks compared to PCCEd2. The tool itself can still be valuable for this type of user, as they begin to explore the structure of the game files.

**Comment by ghost** [comment]
Heff, can we implement a notification message like for the broken tools for now, until the edit features are removed? 

Just say something like: 

"Asset Explorer should be used as a basic file exploration tool, ONLY. Its editing are deprecated and should not be used. They'll be removed in a future update."

This sound okay?

**Comment by ghost** [comment]
"Asset Explorer should be used as a basic file exploration tool, ONLY. Its editing feature are deprecated and should not be used. They'll be removed in a future update."

Inadvertently dropped the work "features" in my last post.

**Comment by HeffU** [comment]
Added a pop-up in 5db2419033dffdc61c05e5292645bfb1a1ac1d6e.

**Comment by ghost** [comment]
wewt! thx

**Comment by SirCxyrtyx** [comment]
Didn't actually remove the editing code, just disabled and hid any menu options that would let you do it. Seemed safer. I also removed the deprecation message HeffU added.

**Comment by ghost** [comment]
Verified in rev742. Uh, sorry with the delay there, lol.
