### ISSUE TITLE
Non-upscaleable texture warning

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#290]
There are some un-upscaleable textures in ME2 and ME3, that can only be upscaled with Texmod (eg the Aquarium textures). Heff didn't find the cause of it, and thus just implemented a warning when the user tried to install one of them. The problem is that the warning doesn't recognize all the buggy textures, only those I had found at the time. I have a found a few more since, namely :
- 0x5D2725D5, 0xE5100929, 0x171B6F9A, 0x4A1283F8, 0x8BF84879, 0x4096496D, 0x96EFFAEE, 0x2D64D01B, 0xD1A76025, 0x47D3B364 (Normandy Consoles), 0xA12623F4, 0xCF8B7094 (Tuchanka Pipes, don't ask), 0xC24409CC, 0x5DEBFB67 (Visors) for ME2
- 0x5D2725D5, 0x2D64D01B, 0xCC543DC1, 0x47D3B364, 0x8BF84879, 0xEB24C657 (Normandy Consoles) for ME3

Replacing these with ME3Explorer looks like this :
If you're far enough, MIPs are the same size as the vanilla texture and thus are displayed correctly :
![24723525384_3a88c9efb4_o](https://cloud.githubusercontent.com/assets/12874678/14287322/9ca5c96e-fb52-11e5-930f-5b05f8685f50.png)
When you get closer :
![25327944756_2a00897664_o](https://cloud.githubusercontent.com/assets/12874678/14287319/9ca4c712-fb52-11e5-92f6-5889fbd3b83a.png)
![25232922430_e8c04a4ec7_o](https://cloud.githubusercontent.com/assets/12874678/14287320/9ca55646-fb52-11e5-9ade-1ce3a526c275.png)
![25528531445_6b5ac97b7d_o](https://cloud.githubusercontent.com/assets/12874678/14287321/9ca5c5a4-fb52-11e5-8d33-5f89cd983b39.png)
I don't know if there's anything to be done about that problem, but just adding these hashes to the list would be helpful. The list is somewhere in the TPF Tools code iirc.

**Comment by ghost** [comment]
Do these all have some type of VFX applied? 

Wasn't that the issue with the aquarium and visor textures?

**Comment by starkgate** [comment]
If VFX=animation, then yes, that was the cause of the problems. I should have said "Heff didn't manage to fix the issue" instead :).

**Comment by ghost** [comment]
Yep, that's what I mean :)

We do already have that tidbit of info on the wiki, along with a help link within TPF Tools. I'm not sure how viable it is to incorporate a list like that into the tool itself. 

Plus, if we start listing hashes, then folks are going to start to take things more literally. I think it's much safer to say, "If a texture has an associated animation/VFX in game, then replacing it is unlikely to work". It's a good general rule to follow, and then we don't have to try to keep track of every hash. Considering the thousands of textures we're talking about in all 3 games, I don't think this is a good option.

**Comment by starkgate** [comment]
Found the code :

```
// Heff: List for prompting the user that these most likely will not install correctly,
        // due to the shadowmap texturegroup being too large for distorted textures to handle.
        // Needs more research, thanks to creeperlarva for the list.
        private List<uint> DistortionHashList = new List<uint>() {
            // Aquarium plants
            0x51AEDCC7,
            0x13790734,
            0xD83C233B,
            // Fish 
            0x9665E158,
            0x9D05DD80,
            0xF255F044,
            0x44332271,
            0x8E893D1F,
            0x3C2AD501,
            0xDFCE4655,
            0xD9BC5722,
            0xF0174EE2,
            // Animated Visors
            0x49DDF790,
            0xAE7A040D,
            0xCF0810CD,
            0x904BD94E,
            0x0B6D3FCE,
            0x00B10251,
        };
```

There aren't that many textures that pose problem, and even less have been modded, so we might as well have a list of them. It can't hurt, and I'm not sure VFX is the only cause now that I reread Heff's comment. I don't understand Heff's explanation, since I don't even know what the shadowmap group is supposed to be, but he definitely doesn't speak of VFX.

**Comment by ghost** [comment]
> There aren't that many textures that pose problem.

_That we know about._

Heff's list above is restricted to aquarium plants, fish, and visors. This is easy enough to explain in the wiki. I still think modifying the toolset to explain this in any way is both unnecessary and untenable in the long term, as the list will inevitably _grow_.

@KFreon -- We've already put a feature freeze in before the stable. Imo, this potential new feature can wait. Replacement issues with these textures is a known problem and cannot be fixed. In addition, if TPF Tools has a list, Texplorer must also, as both are used for texture replacement. If we're saying this information is important enough to insert into the toolset, then both texture replacing tools must notify the user.

FYI, I interpret Heff's explanation as such:

> The visor/aquarium VFX distorts the texture itself, and there is something incompatible between that and the properties of the shadowmap texture group. Since all replaced textures must be assigned to this group (that's a whole 'nother story), textures subject to this type of VFX distortion cannot be properly modded.
