### ISSUE TITLE
rev747 Installing 8k textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#291]
Note that this is definitely not an urgent issue, but there's still a problem somewhere so I thought I'd report it anyways. Maybe the engine just doesn't work with 8k textures, but I don't know how I can check that.
I wanted to see if ME3 would support 8k textures, and ran into some problems with ME3Explorer. Installing the texture seems to go fine, no errors, TOC Bin is updated. But the texture doesn't seem to actually be replaced, it doesn't appear in game and Texplorer still shows the old vanilla one.

Also, autofixing an 8k texture from DXT1 to V8U8 stalls ME3Explorer.

Test files : https://mega.nz/#!4gkEUBIS!Q4pbuM7IZ_W-uQ8Psc4V0IE-iHHfJ9f4GjYSlhBlaDk

**Comment by SirCxyrtyx** [comment]
Well, someone in [this thread](https://forums.epicgames.com/threads/601466-what-is-the-maximum-texture-resolution-for-unreal-engine-3) seems confident that UE3 works with 8k textures. Not sure what the point would be though. That's just ludicrously huge.

**Comment by starkgate** [comment]
I was just curious to see how 8k textures would go, I'm definitely not planning on using them^^. You can't see pixellation on a good 4k texture, so no reason to go beyond.

**Comment by KFreon** [comment]
It should work as far as I know. Definitely not really on the cards to fix.
I'm curious at the stall though.

**Comment by starkgate** [comment]
I tried installing in Texplorer directly, got this error message :
![capture](https://cloud.githubusercontent.com/assets/12874678/14309741/a7c43bdc-fbde-11e5-95c4-49659176877f.PNG)
