### ISSUE TITLE
rev748, TPF Tools, 2x1 Textures check - Path issue

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#293]
Something I noticed when clicking the analyse button, in the debug log :

```
14:48:02:  Reading Names...
14:48:02:  Reading Imports...
14:48:02:  Reading Exports...
14:48:02:  Prefetching Export Name Data...
14:48:02:  Failed to get dimensions of original texture: Could not find a part of the path 'E:\ME\ME2\CookedPC'.
14:48:02:  Load file : E:\ME\ME2\BIOGame\CookedPC\BioD_Nor_000Cabin.pcc
14:48:02:  File already decompressed. Reading decompressed data.
```

Looks like the path is wrong, it should be searching in E:\ME\ME2\ **BioGame** \CookedPC, not E:\ME\ME2\CookedPC

No error message for ME3 though. I also noticed that the analysing was taking much longer (about 6-7 seconds for 50 textures) in rev748, as opposed to rev747 where it would be almost instantaneous. I suppose this is caused by the checks for size. I'm not sure if it's really worth it. What do you think ?

**Comment by ghost** [comment]
There is a pathing issue I'm trying to locate that might be involved with this, but there's pathing discussions in so many issues it's becoming hard to remember. 

It was something that @SirCxyrtyx helped with, though, so that might help help narrow things down... maybe? Sir, you happen to remember?

**Comment by ghost** [comment]
Hm, there might be something weird going on with this, Creeper.

I'm building an ME2 tree right now with no problems. I'd expect if there was a problem with pathing, that it would show during treebuilding.

Did you experience this with a tree built with this rev, or an old tree? Also, did you check pathing in the main menu?

**Comment by starkgate** [comment]
I used an old tree. Paths are fine, I don't think the problem comes from there. I think it's just a little coding mistake, like swap pathBIOGame and pathCooked. Couldn't find it in the code of TPF Tools though, so I may be wrong.

**Comment by starkgate** [comment]
What about the speed of the check ? Can anything be done about it ?

**Comment by SirCxyrtyx** [comment]
Should be 2-3x faster now, and I'm pretty sure I didn't break anything.

**Comment by ghost** [comment]
I can't replicate this one to check the fix for the rev749 prebuild, so someone else will need to.
