### ISSUE TITLE
rev 748, Texplorer, Can't enlarge non-square thumbs

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#297]
I have a feeling this is linked to some of the dimension-check stuff we've been working on. Still, it's a pretty damn wonky bug:

![tex_dimenprob](https://cloud.githubusercontent.com/assets/13645804/14358644/c194e920-fca2-11e5-808e-bbaa429c96b1.PNG)

I haven't tried replacing it; I simply double-clicked on it to enlarge the thumb and it throws the above error. Doesn't happen with the square thumbs.

**Comment by starkgate** [comment]
I can confirm this happens to me as well.

**Comment by ghost** [comment]
Verified in r749 prebuild.
