### ISSUE TITLE
Fork or branch?

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#3]
You should fork the project (I think?) instead of creating a branch... right...? That way people keep their own copies of the work separate from the main repo?

**Comment by KFreon** [comment]
To me, forking was for when you weren't planning on merging changes back in.
Branches are for development work. So you'd have a branch, I'd have a branch, then we'd merge our branches into the master.
That way, I can pull in a change you've made, and you could pull a change I've made without affecting the master. 
We also then keep an entire copy of the repo. Forking is effectively a new repo right?

**Comment by Mgamerz** [comment]
Yeah. I just prefer forking myself because I feel it'd be harder to blow up the repo by accident.

**Comment by KFreon** [comment]
Git was made for branching and since the branch doesn't affect the master, I don't see anything blowing up. 
Each to their own though. Maybe down the track we'll find out which is better :P
