### ISSUE TITLE
ModMaker, functionalities removed/broken in rev653+

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#30]
Rev 653 and lower of ModMaker has functionalities inadvertently removed in revs 654+. ModMaker can no longer make mods from inside itself, it can only install them.

"Create New" and "PCC Comparison" functionalities need to be restored.

See details in post here:

http://me3explorer.freeforums.org/post17772.html#p17772

**Comment by KFreon** [comment]
This is now done. 
Only I didn't bother to re-add the "Create New" because it was ultra manual. 
I figured PCC Comparison was ok. 
I guess I can add the other one if reeeally necessary.
