### ISSUE TITLE
Texplorer, Export as CSV needs additional fields

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#300]
This can wait post-stable, but is the goal of this feature to export a complete list of information that Texplorer shows about the texture?

If so, then the following fields need to be added:
- Mipmaps
- Dimensions
- LOD group
- Location (as opposed to Cache File, as not all textures are stored in a TFC)

**Comment by alvarome** [comment]
Hi @giftfish 

IIRC, KF exported to csv the info available at tree.bin file. All that aditional data displayed at Texplorer window -from what I understood from his explanation then- was not stored at the tree.bin file, but I may be wrong here.

HTH!
Alvaro

EDIT --> I also agree with you that to have any aditional texture info would be highly welcomed I think.

**Comment by KFreon** [comment]
Alvarome is correct. I only exported information stored in the tree. 
After the stable i.e. the rewrite, more info can be stored in the tree and thus exported.

**Comment by ghost** [comment]
Got it.

Thanks for the clarification, K :)
