### ISSUE TITLE
Texplorer, TPF Mode Clarification

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#301]
This can also wait until post-stable, as I suspect it's going to be difficult to change.

This process begins with this message is a little bit confusing:

![tpfmodemessage](https://cloud.githubusercontent.com/assets/13645804/14367599/bca6e942-fccd-11e5-84be-e94de73ea7d6.PNG)

Once the user "replaces" a texture, TPF Tools launches which is fine. But, when the user returns to Texplorer, either to add another texture or to exit out, the message next to the progress bar says:

![tpfmodemessage2](https://cloud.githubusercontent.com/assets/13645804/14367703/6df0ab70-fcce-11e5-8997-2fbc4c55367c.PNG)

And, then before you exit out of Texplorer, it does this:

![tpfmodemessage3](https://cloud.githubusercontent.com/assets/13645804/14367700/68ade470-fcce-11e5-8134-a57c4e32acba.PNG)

To be clear, the TPF-building process itself works beautifully. However, the messages are a bit misleading. At the beginning the tool goes out of its way to explain your game files are not affected during this process. This is great. But, from there it seems to indicate that the files ARE either modified (Replacement Complete!), or that it WANTS you to save the changes (uh oh! are you sure you want to exit w/o saving?). The former is especially problematic, as the _exact_ same message is displayed when a texture is indeed replaced. It led me to double-check my files to make sure they weren't actually modified.

Just needs a bit of clarification is all :)

**Comment by KFreon** [comment]
Which way do we want it? 
It doesn't need to alter the game files, and I didn't think it did, but it actually does...Or it would if you clicked "Save Changes".

It's probably not too painful to change that.

**Comment by ghost** [comment]
@KFreon -- It doesn't alter them as far as I can tell, which is _definitely_ the way we want it.

In regular (non-TPF mode), when the texture is replaced the CustTex is immediately created, but the changes aren't saved into the PCC until "Save Changes".

I'm not sure what would happen if the user clicked "Save Changes" in TPF Mode. Swapping out the textures _doesn't_ generate a CustTex in that mode, so we definitely don't want them to be clicking on "Save Changes". Nor do we want to be giving the impression with a prompt that they _should_ be.

At minimim, I think we'd want to do the following:
- Change  "Replacement complete and job added to TPF Tools!" to "Replacement/Job added to TPF Tools!"
- Remove the "Save Changes" prompt entirely.

My fear about making even these two changes, is that both are _clearly_ also a part of the regular, non-TPF mode process. Any time you try to exit Texplorer w/o saving changes the same save prompt is given. It needs to be retained, just not when in TPF mode. Same with the "Replacement complete" which is also used when making a legitimate replacement outside of TPF Mode.

I see a lot of ways to improve this entire process and make it clearer and easier to use, but that's a post-stable discussion. I have been wondering something, though. There is a "Start TPF Mode", but not a "Stop TPF Mode". Is there a way to stop the mode, or does the tool need to be closed and re-opened to force this?

**Comment by KFreon** [comment]
According to the code, changes to the files should definitely be made. All it does is add the job to TPFTools, everything else happens as normal. 
Simple enough to change though.

I'll disbale the "Save Changes" button while TPFMode is active.

**Comment by ghost** [comment]
Nice changes here.
1. Progress bar now says "Job added to TPF Tools!"
2. _Save Changes_ is grayed out when popping back to Texplorer.
3. _Start TPF Mod_ had changed to _Stop TPF Mode_. I don't remember this being present.
4. Clicking _Stop TPF Mode_ re-activates _Save Changes_.
5. No "You didn't save!" warning is given upon closing Texplorer.

Really nice job with this K :dancer: 

---

Verified in v749 pretest build.
