### ISSUE TITLE
rev748, DXT1 Alpha threshold

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#302]
This directly relates to #277, but since that's actually two issues rolled into one, I figured it'd be less confusing to create a new issue.

Issue is clearly described here: http://me3explorer.freeforums.org/rev-748-t2346-10.html#p23146

Screenshots of extracted vanilla texture in GIMP:

![alpha_level1](https://cloud.githubusercontent.com/assets/13645804/14372910/c3239b90-fcf9-11e5-972d-6e6a691a92cb.PNG)
![alpha_level2](https://cloud.githubusercontent.com/assets/13645804/14372911/c462060e-fcf9-11e5-9223-2df444411a11.PNG)
- This is a DXT1 alpha threshold problem.
- It occurs when viewing the extracted vanilla and modded textures in GIMP, and when viewing the modded texture installed by the toolset in game.
- The vanilla texture and modded texture via Texmod have perfect appearance in game.

**Comment by ghost** [comment]
Btw, I've decided that DXT1 sucks.

It's very unfortunate that probably 2/3 of game textures are of this type :/

**Comment by KFreon** [comment]
DXT1 is smaller which is why they're used more.
This isn't really a bug, since the threshold is working properly. 
This is an example of "need to do it manually".

**Comment by ghost** [comment]
@KFreon -- Yeah, I know DXT1 is smaller and that's why they use it. Really, this is all the fault of consoles. Stupid space-limited consoles.

Also, this is the vanilla texture, just to be clear. 

Looks like the current stable does the same thing, though. So, seems like it's always worked this way, which is too bad.

Feel free to close. At least it's been posted and addressed in case other folks end up with questions :)
