### ISSUE TITLE
Allow replacing textures with a different format

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Explorer/ME3Explorer#303]
So that we may never be cursed with DXT1 again.

**Comment by ghost** [comment]
LOLOLOL. 

I second this motion. :D

**Comment by starkgate** [comment]
That would be awesome !

**Comment by ghost** [comment]
...Still have to deal with the built in Unreal3-customized-for-BW texture constraints, though. There's a reason why we only see DDS in DXT1, DXT5, V8U8, BC5, ARGB, and G8 formats in Texplorer :/
