### ISSUE TITLE
rev748 ARGB and RGB troubles

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#304]
Related to #296.
I built a new tree, the green background has disappeared, but information is inconsistent between Texplorer and TPF Tools. Texplorer claims the texture is ARGB (which is true, there is an alpha), while TPF Tools thinks it is RGB and wants to autofix it as such. If I do autofix, I get a texture without alpha that can only be opened in ME3Explorer, Photoshop throws an error.

Comparison of both before and after tree rebuild autofixes :
![capture](https://cloud.githubusercontent.com/assets/12874678/14383500/cc7c1928-fd95-11e5-9ae8-9bc83af86bf3.PNG)

Files : http://filebin.ca/2d36z161JpW5

**Comment by ghost** [comment]
That seems... strange. 

I thought the new enums (still no idea what those actually _are_) took care of this, and should be used by all tools that install textures (TPF Tools, MM, Texplorer).

**Comment by KFreon** [comment]
@giftfish This seems to be a case of my bad. You can see the new one isn't setting any of the masks at the bottom while the old one is.
No idea why it's happening though...

**Comment by KFreon** [comment]
OK so it wasn't the masks. I dunno why it was crashing your Photoshop, but it was just wrong format detection.

**Comment by ghost** [comment]
Verified in r749 prebuild.

**Comment by starkgate** [comment]
Awesome, thanks !
