### ISSUE TITLE
PCCEd2 PropertyView ObjectProperty labels unclear

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#306]
We haven't had a bug in the name list in a while, but this doesn't look right:

![namelist_bug](https://cloud.githubusercontent.com/assets/13645804/14405489/c6252a60-fe44-11e5-9e78-2365cfdb8a87.PNG)

The displayed name is correct, but this certainly doesn't correspond to -10 in the name list (which can't be negative). It's actually, 1623.

Note, this is a file I'm actively modding. I've used ModMaker, TPF Tools, Sequence Editor, and PCCEd2 so far. Only TPF Tools has added to the name list in order to mod in new textures.

Any ideas, @SirCxyrtyx?

**Comment by SirCxyrtyx** [comment]
If it's an object property, that means it's referring to either an import or export, not a name. The name and nameindex labels there don't make that obvious though.

**Comment by SirCxyrtyx** [comment]
![image](https://cloud.githubusercontent.com/assets/5533111/14413927/a19a91ea-ff3d-11e5-9e2c-6a93b66a9b82.png)

How are these as labels?

**Comment by ghost** [comment]
Those look great :D

**Comment by ghost** [comment]
@SirCxyrtyx -- I'm guessing you didn't push this change yet, correct? K mentioned something about "all your changes" being in the prebuild I'm testing, but this change isn't there.

Just making sure :)

**Comment by SirCxyrtyx** [comment]
Yeah, "all changes" would be changes I have pushed to github, which, ever since the feature freeze have only included bugfixes. I guess sometimes the line between bugfix and enhancement can be a little murky, but since this didn't seem like something that was actually broken, just unclear, it seemed like an enhancement to me.

**Comment by ghost** [comment]
Okie doke. No problem.
