### ISSUE TITLE
ME3Creator: When selecting name for link/name auto-select "New Name" if typing into text field

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#307]
When typing into the Name Selection part of ME3Creator, one can type in a "New Name" and easily forget to check the item. When text is input into that field it should automatically choose that option because it's real easy to miss.
![image](https://cloud.githubusercontent.com/assets/2738836/14405757/32f3e296-fe52-11e5-8e48-4704af4ead2d.png)

**Comment by SirCxyrtyx** [comment]
This is also an issue with the Object Selection dialog. They're both also strangely unresponsive at times and don't seem to focus properly. Additionally, "Abort" should be changed to "Cancel" to be standard.
