### ISSUE TITLE
ME3Creator: Save As feature

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#309]
Lots of the tools have Save As, but ME3Creator doesn't. Seems logical to have one. The "Save" feature seems like it would be maybe a save-as (or at least a save confirmation), but nope, it straight up saves, and could easily lose people's work if they didn't now that's how it worked.

**Comment by Kinkojiro** [comment]
The save feature is great, it just automatically saves the file without having to change the name (unlike pcced2), but a "save as" seperately would be useful.
