### ISSUE TITLE
New Tool: Replace existing Coalesced Editor with TankMaster's

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#31]
it's a well-known issue that gibbed's code (and therefore ME3Exp) doesn't handle type 3/4 parameters correctly, which makes it unuseable for DLC BINs.

TankMaster's tool resolves this and ideally, we can incorporate all of this tools into the toolset at some point.  

Until that happens, though, there should be some warning that pops up when a user opens the existing editor. It's a bug in the current code, and if we're going to keep the editor in the toolset, then the user needs to know about it. Maybe the popup could direct them with a link to TankMaster's thread or something?

**Comment by ghost** [comment]
Oops, I just noticed FemShep's report on this, but he doesn't mention my idea about inserting a pop up window for the tool. So, merge these if you like, of course :]

**Comment by HeffU** [comment]
Yeap, same idea as #22, we'll keep both and implement the temporary fix for this particular issue to being with.

**Comment by Mgamerz** [comment]
Tankmaster source code does not have an sln file so I don't know how projects are linked.

**Comment by HeffU** [comment]
We can either ask him for a project file, or set up our own. I'd guess that he has some kind of makefile to make things structured for portability, which generates the project files.

**Comment by HeffU** [comment]
Added a pop-up asking if the user wants to visit Tankmasters thread, otherwise the tool starts as usual:
f4ffa1471d8b6820eb2115626fad58a3d93a3072

**Comment by ghost** [comment]
Thanks, Heff!

**Comment by ghost** [comment]
We should really try to address this before the new stable.  What we have in place now is a band-aid, similar to the Texture Tool.

Ideally, we'd integrate TankMaster's code into the toolset, but we don't have permission yet, and he's not been around much. His code also uses XMLs, which isn't like anything else in the toolset (to my knowledge), so I don't even know how that would work. It would certainly be nice to have a more user-friendly coalesced editor in the toolset.

The easier strategy would be to modify the existing toolset code to fix Gibbed's errors, using what TankMaster has discovered. I think he's itemized things pretty clearly in his research threads.

This, however doesn't solve the other problem that TankMaster's editor does: the ability to add new INIs. The toolset can't do this and DLC mod authors need this ability. With XMLs and TankMaster's "compiler" approach, it's simple; with the toolset, it's impossible.

@SirCxyrtyx , @HeffU , any ideas?

**Comment by SirCxyrtyx** [comment]
I very much would like to just incorporate TankMaster's tools, but he hasn't been on the forum since August which makes it difficult to get permission.

If we can't contact him, or he doesn't give permission, then I think fixing Gibbed's errors but keeping the popup recommending his tools would be the correct thing to do. Can you link the thread where TankMaster goes over this?

**Comment by ghost** [comment]
@SirCxyrtyx -- Well, here's something handy...

His gmail is attached to his forum account. As admins we can see it, so we could try to just toss him an email. This would be ideal, b/c it would also be great if we could swap out the current TLK editor for his (doesn't use positions). It would need one other tweak that I can think of, but we can hold off on that until we find out.

It would also means we could attempt to incorporate his Plot Editor -- if it's not too much work. It's already used by several modders and adds a huge amount of functionality to the toolset -- and it would allow us to remove the existing Codex Editor that can only edit the base game.

WV asked him a while back if he was going to incorporate all 3 into the toolset and he responded positively, but that assumes he hasn't changed his mind.

Here's his dev/research threads:
[Plot Research](http://me3explorer.freeforums.org/done-research-plot-manager-native-objects-t1318.html)
[Tool Dev thread](http://me3explorer.freeforums.org/additional-tools-t1524.html)

[This post](http://me3explorer.freeforums.org/additional-tools-t1524-20.html#p12740) is where he starts explaining the issues with DLC coalesced's and their differing structure. Remember, we'd also need to be able to add new INIs and not just edit existing ones. If that can't also be done, then it's moot, b/c modders will end up having to use his tool anyway.

**Comment by SirCxyrtyx** [comment]
Well, I've sent him an e-mail, so we'll just have to wait and see if he gets back to us.

**Comment by ghost** [comment]
@SirCxyrtyx -- Cool, thanks. I think we have a bit of time; still getting the texture and ModMaker stuff sorted out.

**Comment by SirCxyrtyx** [comment]
This is going to have to wait until after the stable.

**Comment by ghost** [comment]
Okie doke, @SirCxyrtyx .

I actually _just_ posted on the forums about this, so feel free to (sort of) disregard that. We'll just work on it after the stable, instead :)

Thanks for the heads up.

**Comment by ghost** [comment]
@SirCxyrtyx  -- FYI, [this ](https://github.com/MatthewGenerous/MassEffect-ModTools)is TankMaster's Git Page, I think.

I'll make separate issues for porting the TLK and Plot Editors.

**Comment by SirCxyrtyx** [comment]
Almost got this integrated without too much trouble, but I will need an icon.

**Comment by SirCxyrtyx** [comment]
Or I suppose I could just use the existing Coalesced Editor icon. Not sure why I didn't think of that.
Nevermind!

**Comment by ghost** [comment]
Ha ha.

Yayyy. I'm pretty excited about this. What are you doing about GUI?

**Comment by SirCxyrtyx** [comment]
TankMaster's repository has a GUI for it. I'm just using that. I made some behind the scenes changes so that it actually does the conversion itself instead of calling the command-line tool, but I haven't changed his GUI.

**Comment by ghost** [comment]
Ooh, that's interesting. I don't think I've seen the GUI then.

**Comment by SirCxyrtyx** [comment]
This is done now. Any problems that crop up with the tool can be their own issues.
