### ISSUE TITLE
Texplorer - does not respect output filename when extracting a texture to file

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#313]
I am seeing this in 747, i have like 10000 copies of me3explorer and I can't find my 748. I am using texplorer, and am extracting a GUI texture to a file. It asks for a name, with the texture_hash.dds format. I chop out the _hash part in the save-as dialog, but it still saves with this hash in the filename, which isn't what I told it to do. Not sure if the result is being used from the save-as dialog.

**Comment by KFreon** [comment]
At this stage it does force the hash to be appended.
I'd prefer to keep it that way, but I'm open to reasoning.

**Comment by starkgate** [comment]
What it does is check if the hash is present, and if not, adds it anyways. It would be nice if there was a way to modify the hash part, indeed.
When I was trying to extract textures from ME3 Texplorer, I wanted to append the ME2 hash of the texture (for textures present in ME2 and ME3) instead of the ME3 one. I ended up with something like texture_name_ME2hash_ME3hash.dds, which wasn't really what I tried to obtain^^.

**Comment by Mgamerz** [comment]
If the hash must be appended then it should be a folder chooser dialog,
since you can't choose the filename, no? The default value already includes
the hash when the dialog comes up.

**Comment by starkgate** [comment]
You can choose what comes before the hash though, which is important.

**Comment by Mgamerz** [comment]
That seems really confusing to the end user, the way it is implemented then. The hash being part of the default save name that is editable is misleading if you can't actually remove that part of the hash from the filename, even though you can in the save window.

**Comment by KFreon** [comment]
Fair enough. I just remembered why it's like this, for the tpf rebuild, since they use the same extraction.
I figured it wasn't bad to force the hash.
I can change that though.
Everyone agree?

**Comment by starkgate** [comment]
I agree, yes.

**Comment by ghost** [comment]
Verified in v749 prebuild 4.
