### ISSUE TITLE
Better debug output in Script Tab of PCCEditor2

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#315]
I've built in my custom versions of ME3Explorer (and my gui dumping tool) a much easier to read (and to use for hex editing code) version of the script, which shows the name of the bytecode being run, it's offset and bytecode value, as well as the current items on the stack being evaluated. 

Here's an example:

```
...
Childindex : 8096
Unknown1 : 8099
Unknown2 : 172
Script Size : 120
Flags ( Defined Event Public  )
Native Index: 0
Script:
20 : oNoteData = GetNotificationData('CodexChange');
35 : If (!(Len(srTitle) > 0 && Len(srDescription) > 0)) Goto(0xA9);
57 : oNoteData.srSubTitle = srTitle;
6D : oNoteData.srBody = srDescription;
83 : AddNotificationOneParameter(oNoteData,0)
95 : Return ();
97 : \\End of Script

Debug print:

0 :                        EX_Let[0x0F]         0x20     oNoteData = GetNotificationData('CodexChange');
1 :              EX_LocalVariable[0x00]         0x21     oNoteData
2 :              EX_FinalFunction[0x1C]         0x26     GetNotificationData('CodexChange')
3 :                  EX_NameConst[0x21]         0x2B     'CodexChange'
4 :           EX_EndFunctionParms[0x16]         0x34          
5 :                  EX_JumpIfNot[0x07]         0x35     If (!(Len(srTitle) > 0 && Len(srDescription) > 0)) Goto(0xA9);
6 :        NATIVE_AndAnd_BoolBool[0x82]         0x38     Len(srTitle) > 0 && Len(srDescription) > 0
7 :         NATIVE_Greater_IntInt[0x97]         0x39     Len(srTitle) > 0
8 :                 UNKNOWN(0x72)[0x72]         0x3A     Len(srTitle)
9 :              EX_PrimitiveCast[0x38]         0x3C     srTitle
10 :              EX_LocalVariable[0x00]         0x3E     srTitle
11 :           EX_EndFunctionParms[0x16]         0x43          
12 :                    EX_IntZero[0x25]         0x44     0    
13 :           EX_EndFunctionParms[0x16]         0x45          
14 :                       EX_Skip[0x18]         0x46     Len(srDescription) > 0
15 :         NATIVE_Greater_IntInt[0x97]         0x49     Len(srDescription) > 0
16 :                 UNKNOWN(0x72)[0x72]         0x4A     Len(srDescription)
17 :              EX_PrimitiveCast[0x38]         0x4C     srDescription
18 :              EX_LocalVariable[0x00]         0x4E     srDescription
19 :           EX_EndFunctionParms[0x16]         0x53          
20 :                    EX_IntZero[0x25]         0x54     0    
21 :           EX_EndFunctionParms[0x16]         0x55          
22 :           EX_EndFunctionParms[0x16]         0x56          
23 :                        EX_Let[0x0F]         0x57     oNoteData.srSubTitle = srTitle;
24 :               EX_StructMember[0x35]         0x58     oNoteData.srSubTitle
25 :              EX_LocalVariable[0x00]         0x63     oNoteData
26 :              EX_LocalVariable[0x00]         0x68     srTitle
27 :                        EX_Let[0x0F]         0x6D     oNoteData.srBody = srDescription;
28 :               EX_StructMember[0x35]         0x6E     oNoteData.srBody
29 :              EX_LocalVariable[0x00]         0x79     oNoteData
30 :              EX_LocalVariable[0x00]         0x7E     srDescription
31 :                      EX_Unkn6[0x65]         0x83     AddNotificationOneParameter(oNoteData,0)
32 :              EX_LocalVariable[0x00]         0x8E     oNoteData
33 :                    EX_IntZero[0x25]         0x93     0    
34 :           EX_EndFunctionParms[0x16]         0x94          
35 :                     EX_Return[0x04]         0x95     Return ();
36 :                    EX_Nothing[0x0B]         0x96          
37 :                EX_EndOfScript[0x53]         0x97     \\End of Script
```

..and of course github butchered it. Here's a screenshot of it in my text editor.
![image](https://cloud.githubusercontent.com/assets/2738836/14518437/108018c0-01d5-11e6-94b2-a2b3dd9a94ac.png)

Curious if anyone would want this to be added, not sure how many people edit scripts. But doing it with me3explorer's text is pretty hard especially without the listed bytecode op.

**Comment by SirCxyrtyx** [comment]
Can't say I know anything about Script modding, but that certainly looks prettier.Why don't you submit a pull request to the Beta branch, as that is now where active development is occurring.

**Comment by Mgamerz** [comment]
Will when I get a chance, but I need my current pull request looked at,
cause I can't make other edits without then being put in that. I'd have to
rebase and such. Or figure out how to use more git commands... Hmm...

**Comment by Mgamerz** [comment]
I will look into this once 2.0.3 is published. This significantly alters the PCCObject class as it has to change a lot of the way tokens are converted to text. I will need to backport the current PCCObject to my version (734 IIRC) I think and then I will commit it rather than forward port my copy to the current one.

**Comment by SirCxyrtyx** [comment]
Can you post your altered PCCObject class somewhere that I can take a look at it? I'm not sure why it would need to be altered. The current script view doesn't seem to require anything special handling in PCCObject.

**Comment by Mgamerz** [comment]
I'm a derp, I meant to write bytecode.cs not PCCObject. It's located here https://github.com/Mgamerz/ME3-GUI-Transplanter/blob/master/ME3%20GUI%20Transplanter/TransplanterLib/Bytecode.cs

**Comment by SirCxyrtyx** [comment]
@Mgamerz, are you still interested in merging this? A _lot_ has changed since April, so It could be difficult to set up the pull request. If it's not going to happen though, I'd like to close the issue.

**Comment by Mgamerz** [comment]
Not really anymore. I have dumped the entire game using this method, and I just distribute the game dump. It's much easier to search and has offsets for everything so you rarely need to open ME3Explorer to modify stuff. Since you can't add new script data its easier with a hex editor like hxd as you can directly jump to stuff.
