### ISSUE TITLE
AddArrayElement of Interpreter2 does not hide after value is added (and cannot add another)

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#316]
At least in the me3explorer me3 interpreter2, once you click 'add array leaf' it reloads the list. This causes the add array leaf button to normally become unselectable because the array is no longer selected. However, this is not triggered, which may lead people to think they are adding values still even though its not.

Additionally, the setvalue button does not seem to work on the last element in an array, likely because of a < check rather than <=.

**Comment by SirCxyrtyx** [comment]
I'm doing a major overhaul of the interpreter's editing functionality so that hex-editing of properties will never be necessary again, to be released post-stable. This will be fixed by that.
