### ISSUE TITLE
TPF Tools, Error in TPF Building freezes toolset

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#318]
@KFreon -- This should NOT be fixed for the stable. I've been meaning to start an issue for this for a few weeks now and keep forgetting.

I've experienced this problem a few times when building Texmod-compatible (regular) TPF. Basically what happens is if the build process stalls inside of Texmod, the toolset doesn't know what to do. It just freezes. The user has to hard quit both utilities via Task Manager, then re-open and try again after they've figured out the problem.

What would be better is if some type of error debug could be thrown at them that would provide information about the problem, and them give them a chance to exit the tool (not the toolset).

Something to keep in mind for the re-write.

**Comment by KFreon** [comment]
Roger, wont' fix before the stable.
Problem with this is that there's no communication back to the toolset from texmod, so it can't know when it's done, or when there's an error.
The only way I can think of to fix this is to use a generic timer. So say if the build takes longer than 30 minutes, it's considered failed. 

I might actually look into uMod and see if they've gotten texmod compatible TPF creation working, then just use their code so we don't need the fiddly external stuff.

**Comment by ghost** [comment]
@KFreon -- uMod sounds like that could be a good idea :)
