### ISSUE TITLE
Texplorer, Import Tree functionality

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#319]
@KFreon -- I'm assuming changing the text in a dialog message is something that's "safe" for us to change before the stable, correct?

The message Texplorer triggers here is a bit weird and I don't think it's accurate anymore:

![importtree_trigger](https://cloud.githubusercontent.com/assets/13645804/14576059/e6ac3dde-031a-11e6-93c5-3fd93550fd70.PNG)

In issue #241 we changed how this works. Importing a tree does indeed save it to disk. Both the me#tree.bin and the thuumbnails are imported into the proper toolset directory. They stay there after the session has ended and the toolset closes, so as far as I can tell, this debug message isn't accurate.

To keep it simple, let's just change the text to something like:

> This procedure will import the tree and thumbnails (if present) from the specified location. Be sure the game currently selected in the tool matches the tree you are about to import. Do you wish to proceed?

If all that sounds okay, I'll label this for a stable change, since it's only altering some text and not any tool functionality.

**Comment by ghost** [comment]
@KFreon -- FYI, remember to get the new text for this message into the stable.

**Comment by KFreon** [comment]
Interesting...
I mustn't have synced with the serve for a while. 
I've made these changes on my end, so It'll be in the stable.
