### ISSUE TITLE
DDS Converter broken

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#32]
This tool is totally broken and currently disabled in the toolset. A popup window is triggered if the menu option is clicked on.

Just submitting this ticket to make things easier to keep track of.

**Comment by KFreon** [comment]
Tool redirected to the ImageEngine version of it. 
Works good now :)

**Comment by ghost** [comment]
Rev742 update. Image Engine (Old DDS Converter) functioning and fully tested at this point.
