### ISSUE TITLE
r749, ModMaker, PCC Compare bad scripts?

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#323]
This is a strange issue and I'm still trying to figure out what's going on. It's complicated, so apologies for the long post.

I can extract and save jobs from ELE's Ashley Legacy .mod and varren .mod without a problem. However, if I try the same thing on new mods I generate via PCC-Compare, I cannot extract. 

Instead, the tool throws this error:

![mm_noextract](https://cloud.githubusercontent.com/assets/13645804/14582399/bfb922de-03b8-11e6-87c4-d83571bc4bb0.PNG)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

```
************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at KFreonLib.Scripting.ModMaker.ModJob.get_ObjectName() in D:\My Documents\ME3Explorer\KFreonLib\Scripting\ModMakerHelper.cs:line 146
   at ME3Explorer.ModMaker.ExtractDataButton_Click(Object sender, EventArgs e) in D:\My Documents\ME3Explorer\ME3Explorer\ModMaker.cs:line 1406
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ME3Explorer
    Assembly Version: 1.2.749.0
    Win32 Version: 1.2.749.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/ME3Explorer.exe
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
KFreonLib
    Assembly Version: 1.2.749.0
    Win32 Version: 1.2.749.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/KFreonLib.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 4.0.8.0
    Win32 Version: 4.0.8.14612
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/Newtonsoft.Json.DLL
----------------------------------------
UsefulThings
    Assembly Version: 1.5.6.0
    Win32 Version: 1.5.6.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/UsefulThings.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
PresentationFramework.Aero
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
CSharpImageLibrary
    Assembly Version: 3.1.6.0
    Win32 Version: 3.1.6.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/CSharpImageLibrary.EXE
----------------------------------------
AmaroK86.ImageFormat
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/AmaroK86.ImageFormat.DLL
----------------------------------------
Gibbed.IO
    Assembly Version: 1.0.5890.23746
    Win32 Version: 1.0.0.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/Gibbed.IO.DLL
----------------------------------------
AmaroK86.MassEffect3.ZlibBlock
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/AmaroK86.MassEffect3.ZlibBlock.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 0.86.0.518
    Win32 Version: 0.86.0.518
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/ICSharpCode.SharpZipLib.DLL
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
Be.Windows.Forms.HexBox
    Assembly Version: 1.4.7.28573
    Win32 Version: 1.4.7.28573
    CodeBase: file:///J:/Modding/ME3Explorer%20Dev/Testbuilds/ME3Explorer_r749/Debug/Be.Windows.Forms.HexBox.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

At first I thought it was due to having references to a cloned export in the mod jobs. By that, I mean a vanilla export that was modded to reference a cloned export. PCC Compare will still work when cloned exports are present, it just ignores them. But, if a vanilla export is modified to reference another that is cloned in, I thought this might trigger the problem.

To omit this possibility I made a new .mod for something very simple: swapping Shepard's cabin music. All this changes are some hex references in the in the vanilla WwiseStream objects. As far as I know, this should be perfectly doable with ModMaker. ...I think. Yet, this threw the same error.

Next, I decided it might be due to both of these being in DLC mods. So, to omit that, I dropped the modded Cabin Music file into the base Cooked and then did a PCC-Compare to create jobs and saved that .mod. Then, I re-loaded it and tried extracting jobs (just in case they needed to be saved into the .mod first). Again, this failed.

At this point, there seemed to be two explanations: either the modifications I'm testing are incompatible with ModMaker, or PCC Compare is generating improper scripts. 

To investigate the latter further, I compared ELE's varren and Ashley Legacy for CE .mods, with two versions of the cabin music .mods (base game and DLC mod). The former I've tested and I know they install correctly and jobs can be extracted properly.

Here's comparison screenshots:

ELE varren (base game):
![mm_varren](https://cloud.githubusercontent.com/assets/13645804/14582539/e4106422-03bc-11e6-9aac-e80951cac9e0.PNG)

ELE Ashley Legacy for Collectors Edition DLC
![mm_ash_ce](https://cloud.githubusercontent.com/assets/13645804/14582540/e74b1902-03bc-11e6-813c-a32abb9cea65.PNG)

Cabin Music (Base Game):
![mm_musicbase](https://cloud.githubusercontent.com/assets/13645804/14582541/e8e1f88a-03bc-11e6-9d19-3d1f746cd1bc.PNG)

Cabin Music (DLC mod):
![mm_musicmymods](https://cloud.githubusercontent.com/assets/13645804/14582542/ea4b0450-03bc-11e6-8ea5-37b4d1384d03.PNG)

Things in the base game version of the music mod definitely aren't lining up with ELE's varren .mod. The pathing info is incomplete. What's strange is the pathing info in the DLC version of the cabin music .mod _does_ seem complete and correct, but something with it must still be wrong, as it's not allowing extraction of the jobs.

I haven't actually tried testing installation, but my guess is installation won't work if pathing is borked. If that's the case, that means not only is extraction a problem, but the .mods generated by PCC Compare can't actually be installed. This is definitely something that would need to be fixed for the stable. I don't think it warrants another rev, as it's isolated to ModMaker, and I should be able to quickly test any edits via testbuilds.

That said, it's also entirely possible I'm testing edits that are not compatible with the tool and that is the problem itself.

[I've zipped up](http://www.mediafire.com/download/to4xgfe2w5gtgd2/PCC+Compare+Testing.zip) everything I think would be needed for testing; @SirCxyrtyx, maybe you could take a look?

**Comment by ghost** [comment]
One quick follow up to this issue.
1. I can verify that .mod installation for both the varren mod and the Ashley CE DLC .mod work fine.
2. [I had forgotten an important point](http://me3explorer.freeforums.org/kfreon-modmaker-t2216.html#p22257):

> ModMaker doesn't have the ability to see DLC mods or replace inside of them. It remembers a static collection of files, only the base game and BW DLC.

I had forgotten this. From a practicality standpoint, comparing a base game file to a DLC mod file is is a very easy way to test PCC Compare, so that's what I've been doing. In addition, it works -- it   generates jobs that are Saved to .mod files without a problem. No errors are thrown, so I forgot that it isn't _supposed_ to be possible.

I'm not sure why Extraction of jobs from those .mod files would be where things go haywire, but that could explain some of the results above. 

What it _wouldn't_ explain however, is the problem with the base game cabin music .mod. So, it does still seem like there's an issue present.

**Comment by SirCxyrtyx** [comment]
Not at my coding computer at the moment, but I'm pretty sure that _installation_ of pcc-compare generated .mod files works fine. I remember testing that.

**Comment by ghost** [comment]
@SirCxyrtyx -- That's interesting. 

I thought I had tested this as well, but at this point I've done so much testing I can't remember. I tried to re-trace my steps a bit by re-looking at various issues, but wasn't able to find anything (doesn't mean I didn't miss it).

If this is working for you, that might mean that the cabin music edits are incompatible with Mod Maker. What this changes, Sir, are the offset and length hex data associated with each WwiseStream object. They aren't normal Properties, per se. Is that something ModMaker will work with?

I just had an idea of one more test I can try that should be able to help better discern what's going on. Give me a few :)

**Comment by SirCxyrtyx** [comment]
Modmaker should work with that. Didn't you say you hadn't actually tested installation?

**Comment by ghost** [comment]
@SirCxyrtyx -- I hadn't tested installation with that particular .mod, no. I tested with the varren mod and part of the Ashley Legacy mod. Those installed fine.

But, some new info. The varren mesh edit is super easy to test, and I already know it works for the base game via ELE's mod. So, here's what I just did:
- Ran ELE's varren .mod to edit BioD_Nor500.pcc in the main Cooked. All this edits is a single export.
- Verified the mesh swap in game.
- Took this modded BioD_Nor500.pcc and dropped it inside my new DLC_CON_URZ.
- Put a vanilla BioD_Nor500.pcc back into the main Cooked.
- Used a PCC Compare to compare these two files to generate a .mod file specific to DLC_CON_URZ.
- Reloaded the new .mod in ModMaker. Tried to extract the single job. Throws the same error.
- Replaced the modded Nor500 in DLC_CON_URZ with a vanilla file.
- Ran the .mod file.
- It successfully installs the changes inside DLC_CON_URZ modding the vanilla PCC (!!!).
- Verified the mesh swap in game.

So, this means three things:
- Installation for DLC mods works fine -- as long as the .mod is made to affect them.
- Extracting from mods made with PCC Compare in rev749 isn't working.
- There still something wrong with the cabin music mod when generated via the main Cooked.

**Comment by KFreon** [comment]
Modmaker should work on non BW dlcs. It's just that the mod has to be built for it.

Also, that bug was due to getting the name for the save dialog...I can't keep things consistent can I.
EDIT: Haven't looked at cabin music yet.
EDIT2: What's actually wrong with the Cabin music mod? Does it not install or is it just that the path looks wrong?

**Comment by ghost** [comment]
@KFreon -- Ha, I just discovered that about installation for DLC mods. It totally works.

There is still a problem with the cabin music .mod file, though. When generating the compare, the modded file is in the base game, and the vanilla file is in a totally separate drive on my PC, outside of all game content. Is this a problem?

I included the .mod file for it so you should be able to look at the script and see what's going on with the pathing.

**Comment by ghost** [comment]
@SirCxyrtyx -- Btw, nice changes to the Debug output upon .mod install fail :)

**Comment by ghost** [comment]
@KFreon -- 

> EDIT2: What's actually wrong with the Cabin music mod? Does it not install or is it just that the path looks wrong?

It's that the path looks wrong. I didn't even bother to test installation, since I thought if extraction didn't work and the pathing looked wrong, installation wouldn't work either.

Testing momentarily...

**Comment by ghost** [comment]
Ah ha, now we have more data...

For the cabin music .mod, install does fail:

![pccompare_fail](https://cloud.githubusercontent.com/assets/13645804/14583938/56f8cdfc-03e6-11e6-8be7-b13dcde42a05.PNG)

PCC Compare isn't using the correct path for base game .mods, which is kind of weird considering it's working just fine for those affecting DLC mods.

**Comment by KFreon** [comment]
[Try this one out.](https://github.com/ME3Explorer/ME3Explorer/files/222440/Modmaker.test.zip)
You'll have to regenerate that .mod, but hopefully it'll work now.

**Comment by ghost** [comment]
Progress :)

The pathing now looks as it should, like in ELE's varren mod. Also, extraction works. Yay!

But, now we're back to script errors...

![installfail1](https://cloud.githubusercontent.com/assets/13645804/14584139/3b61e040-03ed-11e6-803d-9c598cb48d7d.PNG)

You've got the necessary modded file for this in the download I linked, earlier, K, so you should be able to do the PCC Compare yourself and test the script generation/installation to replicate the error.

**Comment by KFreon** [comment]
Whoops. Put that in the wrong place.
Pathing looks right now though. Did you want another test build?

**Comment by ghost** [comment]
Yes, please. I may not get to it tonight, but I should confirm :) QC/A and all that business.

**Comment by KFreon** [comment]
[Test number 2](https://github.com/ME3Explorer/ME3Explorer/files/222447/Modmaker.test.2.zip)

**Comment by ghost** [comment]
@KFreon -- Success :D

I'd really like to avoid having to re-test the entire tool due to this change, so K, is there anything else that could have _possibly_ gotten messed up due to these three fixes? 

To recap, there were fixes for:
- Extraction not working for new PCC Compare .mods (the initial problem I reported when opening this issue)
- Pathing bug preventing proper script generation for jobs applied to the base game (DLC jobs worked fine)
- Script fix for "Unrecognized escape sequence"

If there's nothing else you want me to re-test, then we'll consider MM ready for the stable. So, speak now or forever hold your peace...

**Comment by KFreon** [comment]
Nothing I can think of, no.
Usually it's the unexpected ones that are the real issue :P

**Comment by ghost** [comment]
> Usually it's the unexpected ones that are the real issue :P

Uh... okay. So, does that mean you want me to re-test the entire tool?

**Comment by KFreon** [comment]
I don't think it's necessary, but a quick test of a few things isn't a bad idea.
I tested a few mods I have when I did it, but as you've seen that doesn't always work.

**Comment by ghost** [comment]
> I don't think it's necessary, but a quick test of a few things isn't a bad idea.

Alright. Unless you can be more specific as to what to test, that probably means a full re-test, then.

Definitely won't get to TPF Tools until tomorrow then. We'll see how it goes.

**Comment by ghost** [comment]
@KFreon -- Okay, I think we're good, Wewt!

I've re-tested all functions and haven't run into any problems. I also tested installation, extraction, and .mod building for base game, DLC mods, and BW DLC. No problems as far as I can tell. There's certainly a chance something will sneak through the cracks, but I'd say things are looking very robust.

I'll let you close when you're ready. Should be able to get some testing on TPF Tools done later today :)
