### ISSUE TITLE
Interpreter: Handle all structs that are serialized to just values

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Explorer/ME3Explorer#324]
Most structs follow the standard property format of Name, type, size and value, and are thus decoded easily. Some structs, however, are more thoroughly serialized, and just have their values. Some of these are already handled with bespoke deserializers (see #177), but there are a lot that aren't. Luckliy, some of @HeffU's code here on github has a nice list in it of which structs are like this:
-         Vector
-         Color
-         LinearColor
-         TwoVectors
-         Vector4
-         Vector2D
-         Rotator
-         Guid
-         Plane
-         Box
-         Quat
-         Matrix
-         IntPoint
-         ActorReference
-         PolyReference
-         AimTransform
-         NavReference
-         CoverReference
-         CoverInfo
-         CoverSlot
-         BioRwBox
-         BioMask4Property
-         RwVector2
-         RwVector3
-         RwVector4
-         BioRwBox44

Since there are so many, and some of them (like CoverSlot) are very complicated, I'd rather have a general solution than one for each.

**Comment by ghost** [comment]
A General Solution definitely seems like the way to go. Looking forward to this.
