### ISSUE TITLE
PCCEditor2 Tree View is incredibly slow to build

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Explorer/ME3Explorer#326]
On a large file like BioP_Char, the Tree View takes 4 seconds to load.

**Comment by Mgamerz** [comment]
When profiling code for my PCC Data dumping tools I find that the name lookups are the main issue. I don't know how you would make it faster though... Caching everything I guess?

**Comment by SirCxyrtyx** [comment]
I've made big improvements to the Tree building algorithm, and it's even faster than the Export View now. Despite my best efforts, the Export View remains slower, and I don't think I can do anything about that without writing a virtualizing listbox implementation (not going to happen).

So my question is this: I'm tempted to switch the default view of the PCCEditor to Tree View to improve the startup time of the tool, and also because I find the Tree View more useful most of the time. Is that something other people would want? @Kinkojiro, @giftfish, you're both heavy users, thoughts?

Edit: I've also made a few usability improvements to Tree View, including making the Goto# thing work with it, keeping the node visually highlighted after clicking away, re-selecting the correct node after edit, and auto-expanding the root node, in case that sways your opinion.

**Comment by ghost** [comment]
@Sir -- I've never used the Tree view, myself. I use exclusively the normal list view. I'm only sort of aware tree view is present. Not really aware of the advantages/disadvantages of either. Haven't explored it.

**Comment by SirCxyrtyx** [comment]
You're missing out then. Everything's all logically organized and easily find-able instead of being in one giant unusable list.

**Comment by ghost** [comment]
Well, looking at it, it looks like ME3Creator's Content Tree or whatnot.

I've gotten used to navigating the big list, and one thing I like about it is that everything _isn't_ nested. I can just scroll through the file and at-a-glance see all the types of exports in it. For a lot of the work I do, it's often useful to have all objects of one type grouped together, which allows easier comparisons. The giant list is very efficient for this; nesting isn't.

I think both are usable and valuable, just depends on what you're trying to do :)

EDIT: Only thing I really dislike about tree view is how small the font is. It's much smaller than the standard import/export list. On my laptop screen, it's hard to read; definitely not a fan of that. The entire toolset needs new fonts, but we'll get to that with the revamp :)

**Comment by Mgamerz** [comment]
I much prefer the list. I never see a need to browse by tree because I can
search for what I am already looking for rather than needing to use the
tree to find it.

**Comment by Mgamerz** [comment]
Additionally, is defaulting to hex view very useful? Does anyone go
straight to export and hex edit a lot vs looking at props and scripts and
such?

**Comment by Kinkojiro** [comment]
I use the tree v export about 50:50.   When you are handling actors in a level the tree is incredibly useful.   I would probably use the tree more if it is faster to build.   The main issues with it is the inability to hex edit, and the way it folds the tree down if you change the class, import data or editing the class or something in the header.   Quite often I will want to copy some properties from one object to another, just can't do that in the tree.

**Comment by SirCxyrtyx** [comment]
Hex editing in Tree View has been enabled for a while now actually. You may need to click on another tab, like the properties tab, and then back to Hex to get the "Save Hex Changes" button to enable though. I'll see if I can fix that. As for the tree folding down on meta-data changes, I'll fix that too.

Consensus seems to be to leave Exports View as the default. The speed issue is only really a problem on large files anyway.

@Mgamerz, I can reorder the tabs to put the properties tab first. That probably makes more sense.

**Comment by Mgamerz** [comment]
Would it be possible to multi thread the loading (not sure how... Maybe
read exports in batches of say 100)? I know sfxgame and mplobby (or any
files in reckoning) take ages to load because they include huge amounts of
unnecessary duplicated garbage.
On Apr 18, 2016 9:33 AM, "SirCxyrtyx" notifications@github.com wrote:

Hex editing in Tree View has been enabled for a while now actually. You may
need to click on another tab, like the properties tab, and then back to Hex
to get the "Save Hex Changes" button to enable though. I'll see if I can
fix that. As for the tree folding down on meta-data changes, I'll fix that
too.

Consensus seems to be to leave Exports View as the default. The speed issue
is only really a problem on large files anyway.

@Mgamerz https://github.com/Mgamerz, I can reorder the tabs to put the
properties tab first. That probably makes more sense.

**Comment by SirCxyrtyx** [comment]
The bottleneck isn't loading the file, even the huge ones like MPLobby only take ~300ms. It's the UI initialization. Adding ~50,000 items to a ListBox takes a few seconds, no matter how it's done. Only way I can think of to solve that would be something like WPF's virtualizing StackPanel, so making Export View load faster will have to wait for the WPF rewrite.

The Tree view UI initialization on the other hand is pretty cheap, since most items are not rendered because their parents are collapsed. So once I reduced the tree-building algorithm to O(n), it became very speedy.

**Comment by Mgamerz** [comment]
There's no lazy-load listbox? I guess winforms was made before that was a thing. It works well on mobile, strange theres not really a desktop equivalent.

**Comment by Mgamerz** [comment]
https://msdn.microsoft.com/en-us/library/system.windows.forms.listview.virtualmode(v=vs.110).aspx

This is the same way Android and other mobile systems handle large lists. Is essentially a lazy loading that uses only visible elements.
