### ISSUE TITLE
TPF Tools, Bulk Extract TPFs

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#329]
@KFreon -- For the rewrite.

This seems to only work for TPFs. Do we also want it to work for METPFs?

**Comment by starkgate** [comment]
Just giving an opinion on that : I've never seen a mod using METPFs, apart from ALOT, so I don't think it would be necessary to include that option, unless there is demand.

**Comment by ghost** [comment]
@CreeperLava -- That certainly makes sense. Just seems weird that we wouldn't support the fiel format specifically created for the toolset. I wasn't sure if it was an oversight or not.
