### ISSUE TITLE
Bottom Taskbar spotty functionality

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#33]
JohnP and I have reported this issue previously. 

Often the tool-switching buttons on the bottom taskbar don't work. It seems to depend on exactly which combination of tools are open. I know the Dialogue Editor, for example, doesn't like it. So, when I have the Dialgoue Editor + PCCEd2 open, neither button on the TB will work properly.

**Comment by ghost** [comment]
FYI, "Interpret" windows from PCCEd and Sequence Editor are not added to the Taskbar, when opened. We may not want it to, but the current behavior is that the user can end up with a big backlog of open Interpret windows, if they are constantly swapping between open tools. This then increasing the load of the toolset.

**Comment by ghost** [comment]
Ok, I got it to break.
1. Open Dialogue Editor + Conditionals Editorr.
2. Edit something in the dialogue editor and save. 
3. Edit something in the Conditionals editor and save. Reject the TOC update.
4. Now, clicking on the taskbar buttons doesn't change tools.

Also, the TOC update can likely be pulled from the Conditionals tools. It's not necessary, since there's no guarantee the file being edited is in a game directory. Plus, the TOCing mechanism is likely out of date and doesn't use AutoTOC. I'll submit this as another issue, as well.

**Comment by HeffU** [comment]
Trying to replicate these steps but for me the Dialogue Editor doesn't even get a taskbar button at all, which version did you do this on?

**Comment by HeffU** [comment]
This _should_ be fixed now, at least from what tests we've done.

**Comment by ghost** [comment]
Just wanted to update this as of rev742.

I do agree this seems to be fully fixed. I no longer have problems with clicking on the icons not changing to the proper tool. It's been working perfectly for a good while now.
