### ISSUE TITLE
TPF Tools, Allow Build TPF to Include "NOT IN TREE"

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#332]
@KFreon -- For re-write.

We'd need to be a little careful with this, but I think it should be allowed. Right now these are ignored -- even when checked -- since the tool considers them "invalid".

The "Build TPF" feature is one of the best things about TPF Tools. It is _miles_ easier than having to create text files for TPFs by hand. It saves _mountains_ of time and eases workflow. But, the thing is, unless a texture mod creator has all DLC installed, they are bound to need to include references for textures that won't be in their trees. The only option, then, is to have to edit the .def file manually to include them, which creates another step.

So, maybe an option like "Build TPF > Allow Not In Tree", or something like that.

**Comment by starkgate** [comment]
Doesn't the Build TPF with all include the NFIT textures in the TPF ?

**Comment by ghost** [comment]
@CreeperLava -- To quote myself:

> Right now these [NOT IN TREE] are ignored -- even when checked -- since the tool considers them "invalid".

And to reiterate, no, they are not. Not for either type of TPF, regardless of what type of "Build" is used.
