### ISSUE TITLE
ME3Creator: Importing size: 1 byteproperties (bug minor)

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#335]
When importing a byte property with a size of 1, ME3Creator treats it as a size 8 (name) and imports the subsequent data as well.

I found this importing an emitter.   The ParticleSystemColor/Location/Spawn etc have a setting called LODValidity among other 1 byte properties.

To fix I think ME3Creator should look a byteproperty at the size rather than assume it is always a name reference.

BTW in 749 interpreter doesn't read a 1 byte byteproperty.   Testbuild this seems to have been fixed.

**Comment by SirCxyrtyx** [comment]
Thought I'd fixed this. Seems I hadn't. Thanks for the heads up.

As for the interpreter, the byteproperty improvements in the testbuild I gave you (did you notice the dropdown for setting enum byteproperties?) are but a small preview of the beauty that will be the post stable Interpreter. _Everything_ will be displayed correctly, and _everything_ will be editable.

**Comment by Kinkojiro** [comment]
I did it is fantastic.  Probably not the place but 2 minor bugs:

If you have the byte property blank and accidentally click set value it adds a "" name and sets it.  Probably better to default to "none"

In property editor the object pane doesn't allow any changes (works via interpreter though).

**Comment by Mgamerz** [comment]
If it edits things, does it keep the name interpreter?
