### ISSUE TITLE
Package Editors, Missing Features

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#336]
@SirCxyrtyx -- I think I remember you saying that the ME1/ME2 Package Editors are supposed to have all the features of PCCEd2. I'm not seeing a couple things that I use, though, so thought I'd toss this up.

Missing:
- **Go to.** This box is invaluable for quickly navigating through the gigantic list. I scroll when I'm browsing, or when I'm trying to compare a variety of same-named exports to each other, but otherwise I use this box to quickly get to different exports.
- **Replace with BIN.** This is a hugely important feature to have. I see you have Export to BIN, but I see no way to Import, and replace an object's hex. Is there some alternative to this feature I'm not seeing?
- **Info tab.** I use this a lot when working between ME3Creator and PCCEd2. The Archetypes field can be very important, and the index almost always is. ME3Creator provides the mean to edit these fields, and once I open a file back in PCCEd2, I check all of them to make sure things look right. It's easy to click up and down the exports, watching changes to this tab to be certain I've made proper edits.

---

There are several other omissions, but I don't know how necessary they are as I don't use all of them. For example, Cloning is totally broken, so obviously you wouldn't want to add that. The ModMaking stuff I haven't tested. The Header Editor seems weird; I wouldn't even know what to put in it; blank fields provide no context. There are more, but those are some examples, where it seems logical that you've omitted them, at least for now, until we work on revamps.

**Comment by SirCxyrtyx** [comment]
The Header editor probably shouldn't even exist really. The various count and offset fields are going to be set automatically to the correct values when saving the pcc, so it's both dangerous and pointless to edit them manually. I'm not sure what use editing the package flags field would be.
