### ISSUE TITLE
Main Window scrolling/minimizing quirks

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#34]
Minimizing tool windows has always been wonky. They'll minimize, but then the main window will force you to scroll to access them. and their position is very haphazard.

Is it possible to always "dock" the minimized tool/window to the top or bottom so scrolling isn't required? And, is it possible to dock multiple windows in a more organized manner?

**Comment by ghost** [comment]
@SirCxyrtyx -- I _was_ just going to say that I think this can be closed. At some point, Heff did some GUI work to make sure all minimized tool windows snapped to the bottom of the main window; probably when he worked on the taskbar. That part now works perfectly. I just tried to break it by opening, minimizing, and moving a bunch of tool/interpreter windows, and they all behaved nicely.

However, I did find one little glitch. If you have minimized tools docked to he bottom and then resize the main window to trigger the appearance of scroll bars, the tools get covered. Dragging the corner to make the window taller doesn't help; they stay stuck to that position:

![docked_tools](https://cloud.githubusercontent.com/assets/13645804/13788518/420ac92a-ea9d-11e5-887c-c8a55c234256.PNG)

Is it possible for these to automatically "bump" themselves up if the scroll bar appears, then bump themselves back down when it disappears?

If so, then I think this issue can be closed :)

**Comment by SirCxyrtyx** [comment]
One, I have no idea how to do what's requested here (which is why this issue has lain fallow for almost a month.) And two, we're going to ditch Winforms anyway, so not much point in refining this interface. Closing.

**Comment by ghost** [comment]
Sounds good!
