### ISSUE TITLE
rev750 MIPs invert normals

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#340]
This one is kind of hard to explain, so here is a picture of a normal I autofixed to create MIPs :
![mips inverted normals](https://cloud.githubusercontent.com/assets/12874678/14761670/a787978a-0968-11e6-9a77-f89ae12fe344.png)
On the left, MIP level 12 and on the right, MIP level 11. As you can see, the normal is inverted (ie blue becomes purple and vice versa) from one level to the other. This continues the whole way down to 1x1.

Test file : https://mega.nz/#!ogFTXCha!2iqZ8ygZ3wCM_IMIciVO1IWCHzpIxV3kZfJq889SahA

**Comment by KFreon** [comment]
OO that is interesting.
Wonder if it changes how the texture looks?

**Comment by starkgate** [comment]
I haven't received any reports that may support this, but my guess is it would, yes. Perhaps you would see some odd transitions from bump to hollow.
I'm not sure how many textures are affected by this in ALOT since I just noticed this issue, but I suppose there are quite a bit. Would there be a way to bulk regenerate MIPs ?

**Comment by KFreon** [comment]
Unfortuntately there isn't a way I know of.
You might be able to script dxtex or something.

**Comment by ghost** [comment]
So it sounds like I'll need a bug annotation for this on the wiki.

Is it only autofixing V8U8 files? Are any other normal formats affected?

**Comment by starkgate** [comment]
No, only V8U8. At least for ME3, I haven't tested ME1 and ME2.

**Comment by ghost** [comment]
Okay, so it certainly could be affecting 3DC norms, but we just don't know. I assume you tested DXT1/5 norms for ME3?

I'll try to do some testing between wiki stuff, if you don't get to it first :)

**Comment by starkgate** [comment]
Yes, DXT1 and DXT5 are fine.
