### ISSUE TITLE
rev750 Autofix 2x1 textures for MIPs

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#341]
This is an issue I had reported in #298, that apparently had been fixed (although I didn't test it), but is still present in the new stable. @giftfish Maybe you forgot to test that one ?

I'm reposting what I had written at the time, just replace rev748 by rev750.

Some textures (only 2x1 V8U8 from my testing, but it may apply to others), can't be autofixed for MIPs. If I autofix, extract then load again, here is what I get :
![capture](https://cloud.githubusercontent.com/assets/12874678/14365327/627b11ce-fd0d-11e5-92c7-19c4eb2318f9.PNG)
rev718 _does_ detect the autofixed MIPs though, and so does the DDS Checker :

Output for rev748 autofix :

```
magic               : 0x20534444 - DDS 
dwSize          : 0x0000007C - 124
dwFlags         : 0x00021007 - [DDSD_CAPS] [DDSD_HEIGHT] [DDSD_WIDTH] [DDSD_PIXELFORMAT] [DDSD_MIPMAPCOUNT] 
dwHeight            : 0x00000200 - 512
dwWidth         : 0x00000400 - 1024
dwPitchOrLinearSize : 0x00000000 - 0
dwDepth         : 0x00000000 - 0
dwMipMapCount       : 0x0000000A - 10
dwReserved1
                    00 = 0x00000000 - 00000000  
                    01 = 0x00000000 - 00000000  
                    02 = 0x00000000 - 00000000  
                    03 = 0x00000000 - 00000000  
                    04 = 0x00000000 - 00000000  
                    05 = 0x00000000 - 00000000  
                    06 = 0x00000000 - 00000000  
                    07 = 0x00000000 - 00000000  
                    08 = 0x00000000 - 00000000  
                    09 = 0x00000000 - 00000000  
                    10 = 0x00000000 - 00000000  
ddspf.dwSize        : 0x00000020 - 32
ddspf.dwFlags       : 0x00080000 - 
ddspf.dwFourCC      : 0x00000000 - 
```

Output for Photoshop DDS :

```
magic               : 0x20534444 - DDS 
dwSize          : 0x0000007C - 124
dwFlags         : 0x000A1007 - [DDSD_CAPS] [DDSD_HEIGHT] [DDSD_WIDTH] [DDSD_PIXELFORMAT] [DDSD_MIPMAPCOUNT] [DDSD_LINEARSIZE] 
dwHeight            : 0x00000200 - 512
dwWidth         : 0x00000400 - 1024
dwPitchOrLinearSize : 0x00100000 - 1048576
dwDepth         : 0x00000000 - 0
dwMipMapCount       : 0x0000000B - 11
dwReserved1
                    00 = 0x00000000 - 00000000  
                    01 = 0x00000000 - 00000000  
                    02 = 0x00000000 - 00000000  
                    03 = 0x00000000 - 00000000  
                    04 = 0x00000000 - 00000000  
                    05 = 0x00000000 - 00000000  
                    06 = 0x00000000 - 00000000  
                    07 = 0x00000000 - 00000000  
                    08 = 0x00000000 - 00000000  
                    09 = 0x00000000 - 00000000  
                    10 = 0x00000000 - 00000000  
ddspf.dwSize        : 0x00000020 - 32
ddspf.dwFlags       : 0x00080000 - 
ddspf.dwFourCC      : 0x00000000 - 
```

Test files : http://filebin.ca/2cyKaUFs0xkp

**Comment by ghost** [comment]
@CreeperLava -- FYI, none of K's tools will receive fixes from here on out. Not for the stable branch on Nexusmods, anyway. 

K, Sir, and I are still discussion changes to how development will process, but there's a chance the dev branch wont' see fixes either. K will be forking Texplorer, TPF Tools and Image Engine (and possibly ModMaker) and be re-writing them entirely.

Also, these 4 fix fine for me in rev749; I tested them, and just verified again. If they don't work in the stable, then something else was changed that I wasn't made aware of.

**Comment by starkgate** [comment]
Did you try to extract them and reload them after autofixing them ? You should see them requiring autofix again. And again, indefinitely^^.

**Comment by ghost** [comment]
@CreeperLava -- Okay, yeah, that I do see. That I didn't test, I just autofixed them, which did work.

The thing is... are you sure they aren't _installing_ properly? B/c one other thing I see is that when they are autofixed, TPF Tools displays the proper number of mips for them. Exporting is also fine; the mips are there in GIMP. Upon reloading them in the tool, then they're "gone".

So, I get there might be a problem with extracting/reloading, but do we actually know there's any kind of install problem? Do we have in game confirmation? I guess it doesn't really matter; it's not going to be fixed until the re-write, but K might need to know _for_ the re-write.

Also, you might want to hold off on submitting any more issues, Creeper. Once K forks, then you'll be able to submit issues directly to his fork and he can be aware of them if/when he works on the re-write.

Autofix is a can of worms, unfortunately. We could work on it for another 6 months and still not find all the problems. Folks are going to have to settle for the improvements it has :)

**Comment by starkgate** [comment]
I prefer to post them here in the meantime so that I don't forget about it later. It's just a matter of redirecting the issues I just reported to the new fork, right ?

On the issue, if I extract and load the MIPs, TPF/DDS still displays 1 MIP, not 9. It is probably a problem with the DDS header, there had been similar issues in the past.
