### ISSUE TITLE
(suggestion) easier "save HEX changes" in wwise bank editor

### ISSUE THREAD

**Issue by MrFob** [ME3Explorer/ME3Explorer#342]
If you want to add something to a wwise bank, you need the "Save HEX changes" very often and it's fairly well hidden in the menu.

Would be great to do one or both of those 2 things:
1. Give it a hotkey (e.g. Ctrl + H)
2. Save Hex changes automatically when you click on another object in the HIRC tab

Cheers!

**Comment by SirCxyrtyx** [comment]
How's this?
![image](https://cloud.githubusercontent.com/assets/5533111/14771659/dfa41376-0a46-11e6-88a8-39b572734297.png)

**Comment by MrFob** [comment]
Looks great. Thanks!
