### ISSUE TITLE
(suggestion) display audio IDs in HEX

### ISSUE THREAD

**Issue by MrFob** [ME3Explorer/ME3Explorer#343]
Not sure if this is feasible but the "ID" property in audio objects (such as wwise streams or "play"/"stop" events) is currently displayed as integers in the pcc editor property window. Usually, you only need those to identify the items in wwise sound banks where they are referred to in HEX code. Therefore, it would be easier if those IDs would be displayed in HEX in the first place. This also doesn't loose info since it's just a random number anyway. So if we display random HEX or a random integer doesn't really matter.

**Comment by SirCxyrtyx** [comment]
Not really possible due to the way the properties view works, sorry.
