### ISSUE TITLE
Make cloning better in PCC Editor

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Explorer/ME3Explorer#344]
Right now, PCC Editor doesn't do cloning itself. Clone Dialog and Clone Dialog 2 need to be removed and replaced with a built in solution à la ME3Creator.

**Comment by ghost** [comment]
@SirCxyrtyx -- it seems like we should have a dev discussion on the forums about these two tools and how to merge them... or something? ME3Creator is the newer tool with more robust features and I think was meant to supplant PCC Ed2 at some point, but you're obviously doing a lot of work on PCC Ed. It just seems weird to replicate all the features in both tools.

@Kinkojiro -- Can you comment at all? You're probably most familiar with ME3Creator. I've used it quite a bit, but not nearly as much as you.

**Comment by Kinkojiro** [comment]
I use them as fundamentally 2 different tools:

PCCEd2 is great for editing PCCs properties and basic export editing.  It is non-exclusive (don't know the techical term) which means you can edit files whilst the game is live.

ME3Creator is really a pcc creator.   For cloning and copying imports and exports across files, viewing static actors in levels, and editing the import and export tables and creating properties from scratch it is far superior.   However it is an arse to actually edit the pcc properties (hex only).  I never ever use Clone Dialog.

ME3Creator is "exclusive" so the file cannot be used by the game or any other program whilst you are editing it.  Probably WV made it that way because it was more stable.  Which is fine when you are doing those kind of things. But would be a disaster for PCCEditor.

So I would be happy with leaving ME3Creator as a separate tool and removing clone dialog altogether.   If they were merged we would want it to be sure that the stability wasn't impacted by using such invasive tools and we didn't create a botched version of both.  I would much rather have a very good creation tool and a very good editing tool rather than an average one that saves me the 5 seconds of switching between them.

What would be useful in PCCEditor would be the Hex Converter.  It is a tiny thing, but when you are hex editing properties I end up loading ME3Cr just for that.

**Comment by SirCxyrtyx** [comment]
@Kinkojiro, what do you mean by "creating properties from scratch"?

**Comment by Kinkojiro** [comment]
So if for example an export object has a property in the property database that is not in that file (like say I want to add an interpactor bHidden property).   I add the name to that list.  Then go creator view and add the name, property type, length and value. It creates the hex. Then copy and paste the finished property into the objects hex.

The especially applies to actors and their components where the number of possible properties is vast but no actor has them all.

**Comment by SirCxyrtyx** [comment]
To implement the latest Interpreter features, I scanned the class definitions of all Classes in the game and created a database that the Interpreter uses to determine what type everything is (also what the Sequence Editor uses to figure out the names of input links). It would be pretty simple, using that information, to create a feature to add properties to an object that it could have but doesn't. So all that could be done in a couple of clicks.

**Comment by Kinkojiro** [comment]
Great.  :+1:

**Comment by ghost** [comment]
> PCCEd2 is great for editing PCCs properties and basic export editing. It is non-exclusive (don't know the techical term) which means you can edit files whilst the game is live.

WAT?! Seriously? I never tried this.

You're saying I can have the game running, a save loaded with Shepard in potentially the level that I'm editing, edit the PCC, save it, and then... what, just reload?

**Comment by ghost** [comment]
> ME3Creator is really a pcc creator. For cloning and copying imports and exports across files, viewing static actors in levels, and editing the import and export tables and creating properties from scratch it is far superior. However it is an arse to actually edit the pcc properties (hex only). I never ever use Clone Dialog.

@Kinkojiro, so you don't think that the property editing features should just be added to ME3Creator and be done with it? That's what seems sort of strange to me. It's deficient in only that particular category. It seems like if that was remedied, then we wouldn't need both tools.

That doesn't account for the file structuring, or the lack of live editing you're talking about, though.

**Comment by Kinkojiro** [comment]
> You're saying I can have the game running, a save loaded with Shepard in potentially the level that I'm editing, edit the PCC, save it, and then... what, just reload?

Firstly yes you can do that but only if you are changing properties so the file size doesn't change.   Primarily this means moving actors around or slightly adjust values in an interp.

If you are interested here is a tutorial I did for a guy who is helping me create a scene for EGM.
[https://youtu.be/yV9NYVCLO2I?t=4m24s](https://youtu.be/yV9NYVCLO2I?t=4m24s)  it shows pretty much how I use it for basic stuff in game.

> so you don't think that the property editing features should just be added to ME3Creator and be done with it?

Secondly - lets define the terms.   Editing properties means changing the values associated with properties of export objects.  Things such as location, color, etc etc.  This is done well by PCCEd2.  Creating pccs means adding exports/imports/cloning changing the underlying file in fairly radical sense.   This is done well by ME3Creator.

So to answer your question - PCCEd2 already does this.   To answer the one I think you meant - why not put all the pcc creation tools under one roof - that would be fine - if it can be done without making PCCEd2 less useful as a tool for doing what it is good at.  For me though it is not a priority.

**Comment by ghost** [comment]
> If you are interested here is a tutorial I did for a guy who is helping me create a scene for EGM.
> https://youtu.be/yV9NYVCLO2I?t=4m24s it shows pretty much how I use it for basic stuff in game.

Just saw what you did at about 6 minutes in with turning the actor.

Wow, I wish I would have known this 2 years ago. I've probably wasted a couple months of my life with having to exit and relaunch the game between edits.

This will be _especially_ handy for NPC appearance editing, as it's all the same type of adjustments :)

---

And yes "combining under one roof" is what I meant. I get that each tool has their own strengths, it's just that there is so much duplication. It begs the question of "why not combine them"? But, if they can't really be combined while retaining the best features of each, that would explain why. You're far more experienced in both than I am at this point, so I certainly defer to your judgement.

**Comment by ghost** [comment]
@Kinkojiro -- Very fun watching, Kinko. I'm beyond itchy to get back to ThaneMOD :)

**Comment by SirCxyrtyx** [comment]
Thanks for sharing that video Kinkojiro. That's actually incredibly useful for me to see how someone uses the toolset. Gives me all sorts of ideas for improving workflow. For instance, it looks like a Save, Save As separation would be a time saver for PCCed and Seqed.

**Comment by ghost** [comment]
@SirCxyrtyx -- God yes. Not having to re-choose the file constantly when saving. Would be wonderful.

I figured we'd get into all this stuff when re-designing the UI; it's just happening a bit sooner than I expected, lol.

**Comment by Kinkojiro** [comment]
+1 to save and save as

**Comment by ghost** [comment]
The "Done" box also needs to go the way of the dodo.

What we need is a progress bar and output text for each Dev tool, similar to K's tools. That way, the tool can display a message about what operation has taken place and when it's complete. No clicks needed.

The Save/Save As separation would also be good for every Dev Tool to have. When modding I'm overwriting the same file 99% of the time; I'm almost never re-saving it as a new file.

**Comment by SirCxyrtyx** [comment]
Yeah, I'm hesitant to keep making changes to the tools when I know we're just going to redesign them soon-ish anyway, but on the other hand, I (and you I'm sure) want it now.

I'll do save and save as right now, as that's simple. Axeing the done box and replacing it with progress bars and stuff will have to wait for the redesign.

**Comment by ghost** [comment]
Sounds good, Sir :)

**Comment by SirCxyrtyx** [comment]
For now, removed Clone dialog and Clone Dialog 2.
