### ISSUE TITLE
Interpreter -- Array editing

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#345]
As per my question to @SirCxyrtyx on the forums, looks like we still need a little more support for certain editing features in arrays.

Interpdatas often have SFXSceneGroups. When they do, Interpgroups are assigned to specific SceneGroups simply by listing them after a specific group in the array. Therefore, when adding a new Interpgroup, you need to be able to select _which_ SceneGroup to add it to. In short, adding it to the bottom of the array doesn't work, as then it's automatically assigned to whatever SceneGroup happens to be the last one in the array.

**Comment by SirCxyrtyx** [comment]
Thoughts on best way to do this? A few ideas I had:
- Add buttons to move an element up or down
- Enable "Add Array Element" button when an element is selected, and add an element above that element when clicked
- Change "Add Array Element" button to "Add Array Element At" and add an extra text box that defaults to the index at the end of the array

**Comment by ghost** [comment]
@SirCxyrtyx -- Hm, I like both your first and second options. 

The first is useful if you need to make a change after the fact. The second one works well for initial changes :)

To be clear about how the second option works, if I click on the 6th element in the array, it will add the new one there, and shuffle the rest down, correct?

**Comment by SirCxyrtyx** [comment]
Yeah. So if the first element is selected, the new element becomes the first.

**Comment by ghost** [comment]
@SirCxyrtyx -- Cool. Then, yeah, implementing both of those first 2 options sounds ideal :)
