### ISSUE TITLE
ME3Creator - importing sequence objects with variable links. [bug]

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#347]
This is such an old bug that I have been working around it so long that it was only when I went to make a tutorial on how to do something that I remembered it is a bug.

If you import an export object such as a SeqAct_ToggleHidden where the source has a variable links that are connected, the import fails. It creates an error and stops half way through.  Cloning works fine.

Output links that are connected work, but event or variable links cause this error.  The workaround is just to disconnect it in the source before importing.

**Comment by SirCxyrtyx** [comment]
I can't seem to replicate this. Can you specify a case where it happens for you? (file cloning from, export number being cloned, and file cloning to)

**Comment by Kinkojiro** [comment]
Ok. Forget it.   I tried it yesterday and it didn't work. It seems to today on testbuild.  As I say I have gotten used to working around it.   If I manage to replicate what caused the error I will put it up again.  Sorry.

BTW does anyone else have a problem launching ME3Creator from the stable 2.0.0 version?

**Comment by SirCxyrtyx** [comment]
Yeah, ME3Creator won't start in 2.0.1, sorry about that. Download [this ](https://www.dropbox.com/s/zvwlyxc7oxovhr8/ME3Creator.exe.config?dl=0) and put it in the folder with the exe and it should work.

**Comment by ghost** [comment]
@SirCxyrtyx -- Kinko mentioned the stable, though. And, he's right; it won't load at all.

It looks like the ME3Creator.exe.config file was left out of the stable somehow, which is the same thing that's missing from 2.0.1. How could that have happened? 

Kfreon had taken the non-debug version down, as Texplorer wouldn't work with whatever files were removed as part of creating that version. The other (normal) version he left up should have been the standard dev version from 749 with the fixes; no files should have been removed.

We're going to need to confirm that nothing else is missing and push a hotfix for the Stable.

**Comment by Kinkojiro** [comment]
I wouldn't about the stable.   Only serious modders will use ME3Cr (i.e. those who upgrade the set with the beta).  Putting out a hotfix now might just annoy players.   It is not like a TOC or imaging tool.

**Comment by SirCxyrtyx** [comment]
It's a build process artifact. It only gets copied to the output directory if the project is rebuilt. If it's built normally, it won't. Had I not recommended that Kfreon delete his output directory and build it again, this would not have occurred. So it's not technically an issue with the code, but Human error

However, no matter how it's built, the program should work. I can put in a line that force copies it every time

**Comment by ghost** [comment]
Well, it's not desirable, but I don't think it's a good idea to have an entire tool non-functional.

It's not really a big deal; folks can just copy/paste trees, etc. They won't have to rebuild or anything.

The bigger thing is I'm having problems with Nexus being responsive as far as negotiating a permanent solution to the false AV reports and file moderation problem. Until this is dealt with, every time I push an update, the file is going to get flagged and locked until someone on their end looks at it.

@SirCxyrtyx -- Got it. That explains it :) Thanks for clarifying.

**Comment by ghost** [comment]
I'm comparing 749 with the stable now and there's a significant file count difference. I'll come up with a list and start a new issue.

**Comment by ghost** [comment]
FYI, I have a better idea than pushing a hotfix. See #348 :)
