### ISSUE TITLE
ME3Creator broken in Stable v2.0

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#348]
There's a significant difference in file count comparing r749 with the stable.

Here's the differences I'm seeing:
- config.ini
- ME3Creator.exe.config
- SEND TO KFREON.txt
- SharpPlink-Win32.svnExe
- SharpSvn.dll
- SharpSvn-DB44-20-Win32.dll
- SharpSvn-SASL21-23-Win32.dll

There's also a bunch of .logs, but I'm assuming those don't matter. I'm guessing it's only the ME3Creator file above that's a problem. The DLLs appear to be related to the SVN. Not sure if the INI or TXT file matter.

How about if instead of creating a whole new version via a hotfix, I just pop up the exe.config as a update/patch type download, @SirCxyrtyx?

Then I also don't have to deal with Nexus locking the file, lol.

**Comment by KFreon** [comment]
The SEND TO ME thing should be gone.
The SVN stuff and plink shouldn't be necessary either.

The other two I guess are...I've never seen them, and I don't know why they'd be missing.

**Comment by ghost** [comment]
@KFreon --

All the config.ini has in it is:
`[Paths]
gamePath=R:\Games\Origin Games\Mass Effect 3\`
That's not my drive location; so I assume it's one of the devs. File has a date of 10/2015.

Okay, well, if we just want me to upload the ME3Creator.exe.config to Nexus, let me know. I can do it tomorrow morning; heading to bed soon :)

**Comment by SirCxyrtyx** [comment]
I'd say put it in the optional file category and don't post anything prominent about it on the main page. Kinkojiro's kind of right about it not affecting most everybody who will be using the stable.

**Comment by ghost** [comment]
Okie doke. Will get to it this morning. and update the thread when it's up.

Yeah, I see the point, I do. Part of it is principle; it's the new stable and an entire tool shouldn't be broken. Part is I'm thinking about new users. Nexus makes us a lot more visible and if someone just wants to jump in and explore, they'll try to open the tool and get hit with the error message.

But yes, modders like us will be using the Beta for most of our purposes -- especially considering all the work you've done on it already, lol!

**Comment by Mgamerz** [comment]
You should add that .config file to the gitignore so it doesn't get included by devs.

**Comment by ghost** [comment]
Uploaded.

Hopefully the AV won't kick it. Looks like Nexus might be hooking me up to try to permafix the situation. We'll see how it goes :)

**Comment by Mgamerz** [comment]
@giftfish  Have you been able to get ME3Creator to run? I am running it on Beta and getting System.BadImageFormatException (not a valid win32 application) on the Microsoft.DirectX.dll (and its 2 cohorts) which typically means its become corrupted. Not sure if my system, or the issue itself. I'm downloading the SDK where WV got those files from (ancient and no longer maintained) to see if they are different.

**Comment by SirCxyrtyx** [comment]
Works fine for me.

**Comment by Mgamerz** [comment]
Interesting. I can build it, but it will not run. Debug or release mode. 
`System.BadImageFormatException was unhandled
Message: An unhandled exception of type 'System.BadImageFormatException' occurred in mscorlib.dll
Additional information: Could not load file or assembly 'Microsoft.DirectX.dll' or one of its dependencies.  is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)` comes up as soon as it tries to load and it dies. I wonder if its because its running in a VM. Shouldn't cause it to throw that error though. Those files all exist, and I even copied those dll libraries into the build directory from C:\Windows\Assembly.

Edit: Nope, still dies. Running from ME3Explorer just does nothing, running directly throws 'stopped working...'. I have the config file mentioned in this thread in my program folder, pretty sure you already had committed it by 2.0.2. Cursory internet scans seem to say its a 32bit/64bit binary issue, but it still fails in x86 mode.

**Comment by ghost** [comment]
Hm, once I drop in the missing config file, I'm getting sporadic results. I can open the toolset 3x and it will still throw the same error. Another 3 times and it will open fine.

Windows log shows this for the instances where it won't open:

`Faulting application name: ME3Creator.exe, version: 1.0.0.0, time stamp: 0x570f59f4
Faulting module name: KERNELBASE.dll, version: 6.1.7601.19160, time stamp: 0x56bcd5c3
Exception code: 0xe0434352
Fault offset: 0x0000c52f
Faulting process id: 0x%9
Faulting application start time: 0x%10
Faulting application path: %11
Faulting module path: %12
Report Id: %13`

And this for a NET error:

```
Application: ME3Creator.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException
   at ME3Creator.Program.Main()
```

Let me check Windows Update and see if I'm missing any again.

**Comment by ghost** [comment]
Seems fine in 2.0.2. Opened 10x and no problems there.

**Comment by ghost** [comment]
@SirCxyrtyx -- Do we know what's going on with this? There's definitely inconsistencies in the stable, even with including the missing file.

I take it the debug output I posted wasn't helpful?

**Comment by SirCxyrtyx** [comment]
Whoops, closed this prematurely. And no, unfortunately not. I'm pretty stumped as to the problem.

**Comment by Mgamerz** [comment]
Was stable built as release or debug? I could not run me3creator in release
mode but for some reason it works in debug. Unreleated to the amarok lib
problem. I think release and stable may build as different architectures, I
see some are built only for x86 in debug mode.

**Comment by ghost** [comment]
@KFreon -- Tagging you due to FemShep's question above, since you created the stable builds.

There does seem to be a problem, but if you review the above posts, we seem to be at a standstill until we can gather a bit more info :]
