### ISSUE TITLE
Beta: QuickBMS [actually only maybe] and XboxLZX.bms can be removed

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#349]
The XboxLZX.bms file in the exec/ folder is used to decompress Xbox .xxx files. The one warranty voider included seems to only work for the startup.pcc file. I wrote up one that works for all of the basegame pcc files for xbox, but the tool was removed in r681, so either it can be restored (doubt it'll see much use since the tools don't properly detect the endianness and assume pc without significant reworking,) or these files can be removed. For decompressing PC pcc's, the decompress.exe file is used, which was provided by gibbed (this is how the pcc repacker works, though I am unsure if it saves using alt mode or not. Alt mode is the only one that uses this method).

There are two more BMS files, but I don't know what they do. A cursory code search may turn up what they are supposed to do and if QuickBMS is necessary. QuickBMS is a quick decompression algorithm writing tool where you can write decompressors "simply" without having to write an entire program to do it, you just write the decompression script. It's... good, but its a very advanced definition of "simply".

**Comment by SirCxyrtyx** [comment]
Doesn't look like bms is used anywhere anymore. I'll get rid of it all.
