### ISSUE TITLE
Interp Editor export name bug

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#35]
The Interp Editor doesn't seem to like changes to the export list.

When clicking on a matinee track, the tool will display the export number and name In the bottom-left panel. The number always stays correct, but the name will be borked if the export list has been modified. It will match the number to the incorrect name.

**Comment by HeffU** [comment]
I'll look into this, likely related to the changes I did earlier

**Comment by ghost** [comment]
No, it's been like this since SirCxytyx released it. Definitely not your doing.

**Comment by HeffU** [comment]
Ah, well I might as well look at it anyway, should be a quick fix hopefully.

**Comment by HeffU** [comment]
Hmm, the only place I can see that it does this it actually prints the class name rather than the name of the object, but of course that could also still get broken on index change.

Does it always break, or only if something was added/removed before it in the export table?

**Comment by ghost** [comment]
Seems to always break once the export table is modified. It only affects edited objects, though.

Right now I'm looking at a file where I've added a new Interpgroup to the Interp. It's export 2889. And, while it's an interpgroup, the tool labels it as "BioEvtSysTrackLookAt".

Another thing to note is that everything is properly labeled in the matinee timeline up top. It's only the bottom left panel that shows the borked information.

Oh, weird. Noticing something else. They're swapped. In this new 2889 interpgroup for the player I only have 1 track, which is indeed a "Look at" track. Up in the timeline if I click on the group, the bottom left panel identified it as "2889 Look at track". Then if I click on the track itself, the panel identifies it as "2890 Interpgroup".

I feel like it's something wrong with the +1 to exports or something.

**Comment by SirCxyrtyx** [comment]
Hmm, this may be an issue with the PCCObject getClassName function, which would have larger implications. Could you send me the edited file which is giving you trouble?

**Comment by SirCxyrtyx** [comment]
Looks like the class names are off by one for everything actually, the issue was just masked by the fact that interptracks are all grouped together by class in the export list, so the issue would only show up on the first interptrack of a class. I'll have a fix up soon.

(I swear, half the bugs we have are caused by the export list starting at 1 instead of 0)

**Comment by ghost** [comment]
Verified in rev742.
