### ISSUE TITLE
Beta: Add tooltips to menu items

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#352]
Looking at some tools, it is hard to know what the menu items do. For example, in SFAR TOC Updater, what does Check SFAR mean? What about Check and Rebuild? Running either prompts for an SFAR and then says "Done.". No idea what it did, or what the two options do. I think adding tooltips to menu items (which can be done through the properties pane) would help a lot for newer users. I put it on my mod manager program, and it seemed to help a lot of users understand what some of the more ambiguous worded items meant.

(This tool has a wiki article that explains it, but users shouldn't have to go to a web page to figure something like this out when something could easily be shown in the window)

**Comment by ghost** [comment]
Stuff like this should wait until the GUI and tool overhaul. There's no reason to spend time adding in a bunch of tooltips when menu options and GUI are going to end up changing for everything.
