### ISSUE TITLE
Suggestions:  (Beta) Sequence Editor add Break all links option

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#353]
The new sequence editor is a great improvement with all the input labels.

When breaking links it comes up with 2 options (variable and output).   Most often I want to break all the links when I have cloned or imported an object.   Adding a 3rd option to do that would be handy.

**Comment by SirCxyrtyx** [comment]
Sounds good. How about I also make it so _Edit_ -> _Add Objects_ removes all links on the object it's adding to a sequence? Seems like that would always be the desired behavior.

**Comment by SirCxyrtyx** [comment]
I could also make _Edit_ -> _Add Objects_ automatically set the ParentSequence property.

**Comment by Kinkojiro** [comment]
Both good ideas. +1 +1 

Adding it and automatically removing links would also stop leaving of connected links to objects in other sequences accidentally - which I have done on many occasions.
