### ISSUE TITLE
Beta: Remove C# Script Compiler, Change Script DB Icon 

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#354]
This I believe is a C# script compiler that compiles essentially a c# file into an executable piece of code. WV added it because it was easy to just copy and paste things. This doesn't really have anything to do with the toolset goals and is better accomplished by something like SharpDevelop, a mini IDE that can compile scripts directly for C#. (Edit: verified it is just a notepad that attempts to compile C# code. This has no usefulness to anyone really using the toolset)

Additionally, the "C# Script DB" icon is wrong. It's a game script database, nothing to do with C# here. Just similarly worded tools.

**Comment by SirCxyrtyx** [comment]
I'm pretty sure the Script Compiler is used by Modmaker. But the front end should go, definitely.

**Comment by KFreon** [comment]
It is definitely used by modmaker. 
I didn't even know there was a UI.

**Comment by ghost** [comment]
This is more stuff that can wait until the GUI overhaul, etc. The icon can absolutely wait.

**Comment by SirCxyrtyx** [comment]
Fixed in 2.0.11
