### ISSUE TITLE
Suggestion (Beta):  Interpreter hex editor improvements

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#357]
So I thought 2.0.2 had removed the hex editor!

Anyway the only problem with the Interpreter view of hex is it defaults to 4 bytes.   This makes the hex much longer than the interpreter.

Is it possible to default to 16 across (or have an option to do so?)

**Comment by SirCxyrtyx** [comment]
I guess I figured that the most frequent use case of that tab would be the interpreter part, in which case the hex should take up the least amount of space possible. And in cases where someone did want to edit hex, they could expand the view out to 16 bytes across, which would make the interpreter tree somewhat cramped for space.

I have two ideas for fulfilling your request. 
- Add an option in a menu to set the default width of the hex box.
- Preserve the set width. So if you expand it to 16 bytes, then open another instance of Package Editor,  it will be set to 16 bytes.

**Comment by Kinkojiro** [comment]
You are correct of course.  The vast majority of people (especially with all your enhancements never have to edit hex).    Either would be good, it is annoying every time you want to edit hex to have to expand it.

**Comment by Kinkojiro** [comment]
So I have some other ideas that would improve the hex editor in PackageEd.

(1) Transfer ME3 Creator's Hex Converter.   This is a very neat little tool and very useful if you cant convert integers into hex in your head.
(2) Like ME3 Creator the tool creates a hex length somewhere depending on your selection.
(3) As above the ability to change the view.   The more I think about it the best solution would be a button at the top (left of the export/expand/collapse) to toggle the view.  The majority of the time interpreter is good so just toggling in and out if I am editing a function or binary would be fine.  Dragging is messy because there is no column count at the top.  No need to record the last used view between sessions.
(4) Keep the "Interpret" button working if you want a separate window.  The reason is sometimes I want to use multiple windows.   For example I want to add an import to an object property.  By clicking on interpret and opening the INT window I can now go into the import tab, find the import number I was looking at and enter it.
(5) Adding a Save Hex button rather than using the menu.

**Comment by SirCxyrtyx** [comment]
Hmm. The interpreter toolbar is getting a little crowded. Maybe I could replace the Export/expand/collapse buttons (none of which have ever seemed very useful to me) with a hex width toggle button and a save hex changes button.

**Comment by Kinkojiro** [comment]
+1 
The expand was useful when interpreter would collapse every time you changed something, given that has been fixed it seems superfluous.  I personally have never used the export function.

**Comment by Mgamerz** [comment]
Occasionally I have exported two trees that need compared, especially between Xbox and PC files.

**Comment by SirCxyrtyx** [comment]
> Like ME3 Creator the tool creates a hex length somewhere depending on your selection.

![image](https://cloud.githubusercontent.com/assets/5533111/14939102/ce8357d6-0eed-11e6-8efe-3519323fabbb.png)

You're talking about the bar at the bottom with Start, Length, and End right?

**Comment by Kinkojiro** [comment]
Yes re the bar at the bottom.  Thanks for sorting this.
