### ISSUE TITLE
Beta: (Feature): Hex Editor displays byte/short/word in decimal from current position

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#359]
I don't know how many times I have to look up what a hex digit is in the hexviews. If one could have a little box that displayed what the value under the currently selected byte (or start of selection) in terms of byte/short/word that'd be mega useful.

**Comment by SirCxyrtyx** [comment]
I'm not entirely clear on what you're asking for here. So if a byte is selected, you want like a thing in the statusbar that says what that byte is in decimal? And if two bytes are selected it would display it converted to an int16 , and for four bytes display it as an int32? What about if 3 or more than 4 are selected? Nothing then?

**Comment by Mgamerz** [comment]
It would read the bytes from the current position. Not selected. Say I
click on 0x20, then it would show a representation of a byte/short/word as
of it was interpreting a number from that position. So it would read
0x20-0x23 for a word.
