### ISSUE TITLE
ME3Creator, Add Property Editor

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#36]
ME3Creator is basically PCCEd2 on steroids + additional functionality. 

Yet, it's missing the ability to edit properties in the Export Object Data tab. Right now, the user must exit ME3Creator and then re-open the file in PCCEd2 to edit this data. It would be nice if the ability to edit these properties was replicated from PCCEd2.

**Comment by HeffU** [comment]
Depending on how things develop, I might end up replacing the existing pcc lib in ME3Creator and putting in my own, and then adding a new UI for that. This would allow editing of all properties, including arrays and structs etc. This is quite far on the horizon though, unless I suddenly lose my day job <.<

**Comment by ghost** [comment]
Lol, sounds good.

Some UI adjustment would be nice. A little while back I couldn't figure out how to clone an import in the same PCC. I tried right-clicking the desired import (nothing), then I was looking all over the "Importer View" (also nothing), and then was wondering if the "Import Object Data" tab (which is where intra-file export cloning is located) was simply missing. 

Turns out that I had to right click the object in the "Content Tree". I was unaware there were any editing features in this tab; I thought was simply a different way to display a PCC's information.

Those Dev tool wiki articles will be handy when they're finished, lol.

**Comment by SirCxyrtyx** [comment]
As of d06f8637c14aceaff9c7d8a3a3079c414b03ab87, (rev740) right clicking an import gives the option to clone it.

**Comment by ghost** [comment]
@SirCxyrtyx -- Thanks for this! :)

**Comment by SirCxyrtyx** [comment]
So, if I just replaced the properties view with an embedded Interpreter, would that be good?

**Comment by ghost** [comment]
Hrm. I'd think so. It's a little different than the main Properties pane where everything is more readable, but I don't see why that wouldn't be a a good solution -- especially between now and overhauling the tools.

Let me tag @Kinkojiro to see if he anticipates any problems I'm missing :)

**Comment by Kinkojiro** [comment]
Yes replacing the properties view with interpreter would be great (I am loving me some interpreter action).  It is just awesome.
