### ISSUE TITLE
2.0.3Beta, Interpreter Missing Expand/Collapse All

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#361]
Seems like this was removed in 2.0.3, and as far as I can tell, it hasn't been relocated?

I'd appreciate it if we could return it, unless there's been some other change that makes this problematic. It was something implemented at my request and is a huge time saver when there are 40+ nodes (which is often, when editing appearance of NPCs).

**Comment by ghost** [comment]
I am seeing that you've forced the nodes to _stay_ expanded/collapsed, @SirCxyrtyx, and that is a welcome change :dancer: 

Just need to get those buttons back to expand/collapse in a single click rather than 40 separate clicks >.<

**Comment by SirCxyrtyx** [comment]
I removed them since the toolbar was getting crowded. If you're using them I can definitely restore them. How do you feel about putting them in a context menu instead?

**Comment by ghost** [comment]
@SirCxyrtyx -- Context menu should be fine. What would I be clicking on? Something like right-click on a node and then expand/collapse all?

**Comment by SirCxyrtyx** [comment]
I figured just right-click anywhere in the interpreter. But right-clicking on a node and then having the option to expand/collapse it and all of it's children sounds more useful.

**Comment by ghost** [comment]
Sounds great :)

Thanks much.
