### ISSUE TITLE
Clone entire sequences

### ISSUE THREAD

**Issue by SirCxyrtyx** [ME3Explorer/ME3Explorer#363]
Sometimes, especially for Sequence references, having a new copy of an entire sequence would be very useful.

**Comment by SirCxyrtyx** [comment]
If I'm doing this I may as well let you clone any sequence object. Current plan is to have a "Clone" option in the context menu, which clones an object and adds it to the sequence. If the object being cloned is a sequence, it also clones all of it's children, recursively, and adds the clones to the new sequence. I've actually got what I described working already, but I haven't tested it very thoroughly.

**Comment by Kinkojiro** [comment]
SirC.  Nice idea.   Should be very handy.

Will it correctly set input/output links is you clone a sequence, also parent/child relationships and index numbers?

**Comment by SirCxyrtyx** [comment]
Yes to all. For index numbers it's currently checking all exports with the same name and then giving the next highest index for that name. I think that's how it should be done.

Currently it's not cloning sequences referenced by SequenceReferences, as I'm hoping that won't be necessary. I'll make sure to test that theory in game before I release this though.

**Comment by SirCxyrtyx** [comment]
Thought about it some more, and sequences referenced by SequenceReferences definitely do need to be cloned. Only problems is that they won't work with the global views that are saved if you have the  "Use Global Sequence Ref View Saves" option checked. So you'll have to untangle them again.

**Comment by SirCxyrtyx** [comment]
The standard saving method doesn't work if exports are added, so I implemented an Me3Creator-style save method that reconstructs the PCC. If cloning has been done, the Sequence Editor uses this method, and if cloning has not been done, it uses the standard method of appending changed exports to the end.

It seems to me that the reconstruction method is just generally far superior to the append method, and I'd rather have the toolset use it whenever possible. Is the presence of a seekfreeshadercache the only thing that would prevent a reconstruction save from working? If so, I could just have it check for the presence of one, and if it exists, use the append method, and if it does not, use the reconstruction method.

**Comment by Kinkojiro** [comment]
As far as I am aware it is the only thing that causes a problem.

The binary data for textures and soundbanks also contain file offsets but I haven't found an issue with their implementation and using ME3Creator.

**Comment by Kinkojiro** [comment]
BTW did you change it so when you add an item to a sequence it adjusts all the parent/child relationships?  If so useful thanks.

**Comment by SirCxyrtyx** [comment]
Yeah, it adds it to the sequence's SequenceObject array and adjusts both the link and the ParentSequence property of the object.

**Comment by ghost** [comment]
This is great. I think I asked about it a while back, and now I just make another post in your Aria thread Sir, that basically amounts to the same thing. I'll start a new Issue for it, though :)

**Comment by Kinkojiro** [comment]
One thing that would be useful would to re-index cloned sequences with their object number.  I do this manually anyway because it prevents accident duplication.  It also means if there is a problem the index number usually shows up in Heffs log output.

**Comment by SirCxyrtyx** [comment]
resolved in bd9343a4c9d81c0d2a4c671309d7081f77ab06e3

**Comment by ghost** [comment]
Wewt! Can't wait to try this :D
