### ISSUE TITLE
Enhancement : Euler track shows rotation information (minor)

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#366]
So I am messing around with a cutscene.  The InterpTrackMove Euler track struct prop (I believe) sets actor rotation.   At the moment the values and tangents show X/Y/Z.   Is it possible to mark them Pitch/Roll/Yaw?

I think the values are in degrees already.

@giftfish will probably be able to confirm this.

**Comment by SirCxyrtyx** [comment]
Can't do this, sorry. Even the UDK can't do it.
![](https://docs.unrealengine.com/latest/images/Engine/Matinee/TrackReference/SplitMoveTrack.jpg)

And yes, it is in degrees.

**Comment by ghost** [comment]
What's a bit strange is that BW uses pitch/roll/yaw in the BioStage objects, so you'd think they'd do the same thing for the ITM (my shorthand for InterpTrackMove):
![itm_directions](https://cloud.githubusercontent.com/assets/13645804/15215916/b323be70-1809-11e6-882f-b6ec40e84de7.PNG)

**Comment by SirCxyrtyx** [comment]
BioStage is a class written by Bioware, but InterpTrackMove was written by Epic Games. As for why Epic did it that way? They would have had to create a new struct just for Euler Tracks instead of re-using InterpCurveVector. Probably would make the code quite a bit more complicated.

**Comment by ghost** [comment]
@SirCxyrtyx -- Yeah, I was wondering if it was some type of BW-specialized thing. Makes sense with what you're saying about the ICV objects. Thanks for elaborating :)

**Comment by Kinkojiro** [comment]
Ok, understood.  It is a very minor thing.   Just got to remember Z is yaw.

Thanks for explaining.
