### ISSUE TITLE
ME3 Interpreter chokes on some pcc files when ME3 is not installed

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#373]
I have attached a problem file from TESTPATCH (as a .txt extension, rename to .pcc) that demonstrates a PARSE ERROR that occurs in Interpreter. Open it in package editor, go to Default__SFXSFXWaveManager_Horde... and then go to interpreter. You will see PARSE ERROR.
![image](https://cloud.githubusercontent.com/assets/2738836/15551748/9dffe6a2-2274-11e6-9692-211544bd025d.png)

Not sure what the issue is. Files in Patch001.sfar are a treasure trove for gameplay tweaking.

[Patch_SFXWaveManager_Horde.txt](https://github.com/ME3Explorer/ME3Explorer/files/282642/Patch_SFXWaveManager_Horde.txt)

**Comment by Mgamerz** [comment]
Also choking on some basegame files, like SFXPawn_Ravager.pcc's SFX_AI_Ravager defaults export.

Actually its throwing PARSE ERROR on quite a lot of exports I am testing.

**Comment by SirCxyrtyx** [comment]
Works just fine in 2.0.5 for me. Does this happen if you use the version downloaded from github, or are you building this with VS?

**Comment by Mgamerz** [comment]
I built it from VS, which looking at commit history is the same as 2.0.5. Built it this morning after I submitted the pull request. I just downloaded the prebuild 2.0.5 and I am seeing the same issue. The machine I am using doesn't have ME3 installed (well, "properly installed". I have it installed but no registry keys for it, just a copy of my game folder). I'll run it in VS and see if I can dig up the bug. My pathing for ME3 shows not found but that shouldn't cause the bug... right?

**Comment by SirCxyrtyx** [comment]
> The machine I am using doesn't have ME3 installed.

Ah. An ME3 installation is required for some parts of the interpreter to work, and unfortunately it's not particularly obvious to the user which parts. I'll see if I can figure out a way for it to fail more gracefully in that situation.

**Comment by Mgamerz** [comment]
Dies right here.
https://github.com/ME3Explorer/ME3Explorer/blob/6bfac649c1ea7edb5d7128ec09bb01d230b3a9a9/ME3Explorer/Unreal/UnrealObjectInfo.cs#L275

In the meantime I will just manually set the path. I always ignore the message cause I only really use Package Editor on this machine.

**Comment by SirCxyrtyx** [comment]
Should no longer give Parse Error when ME3 isn't installed. Immutable structs cannot be parsed unless ME3 is installed, so it will just show the raw hex for those.
