### ISSUE TITLE
Sequence Editing pccs without a main sequence

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#374]
Over the years I have seen some pcc's that have Seq type objects but no main sequence, and their code is the same style as one as things like BioD file with a sequence that you can open in sequence editor. However, these ones lack their main sequence, so it won't open in there. I'm wondering if it's possible to open these in sequence editor even without a main sequence. An example is in SFXPawn_Ravager.pcc there are some sequence exports with input and output links but there is no way to know what these do since you can't open them in sequence editor.

```
=======================================================================
#71 [CB: 0x00]SFXGameContent.SFXAI_Ravager.OnToggleSwarmerSpawning.Seq(ObjectProperty) (Superclass: Class) (Data Offset: 0x 6DC04)
=======================================================================
#72 [CB: 0x00]SFXGameContent.SFXAI_Ravager.OnToggleSwarmerSpawning(Function) (Superclass: Class) (Data Offset: 0x 6DC34)
==============Function==============
Childindex : 69
Unknown1 : 70
Unknown2 : 178
Script Size : 118
Flags ( Defined Public  )
Native Index: 0
Script:
20 : If(Seq){If (!(Seq.InputLinks[0].bHasImpulse)) Goto(0x52);}
4B : bStopSpawnsFromKismet = False;
53 : Goto(0xAF)
56 : If (!(Seq.InputLinks[1].bHasImpulse)) Goto(0x98);
79 : bStopSpawnsFromKismet = True;
81 : Goto(0xAF)
84 : bStopSpawnsFromKismet = !bStopSpawnsFromKismet;
93 : Return ();
95 : \\End of Script
```

This is a fairly obvious one, but it implies there is something coming in from kismet to this sequence object, and i'm wondering if there are others or a sequence that is actually editable.

**Comment by SirCxyrtyx** [comment]
Since 2.0.4, all sequences a file has are displayed in the Sequence Editor.

SFXPawn_Ravager.pcc does not have any sequences in it. The function you pasted above is from the SFXAI_Ravager class which is an AIController, not a SequenceObject. If I'm reading it right, it looks like a sequence object can be passed to that function.

**Comment by Mgamerz** [comment]
I see. Haven't done much sequence editing beyond a few value changes and output link repointing.
