### ISSUE TITLE
Bug Minor 2.0.6 Importing RB_BodySetups

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#376]
I have had this error when copying RB_BodySetups, but not every RBB.  The import fails in either ME3Cr or PackEd.

A good example is in BioD_Nor_370Medical - copying the RBB 867 (ChairUtility01 is the underlying mesh).

Not sure why it is failing - it seems to get part way through the Aggregate Geometry and something causes it to fail.  The error Failed: _Omnitool (which happens to be name zero in that file). However from the hex that is copied it fails during a section that is vector values rather than names.

Not hard to manually rebuild the RBB in hex but wanted to flag.

**Comment by SirCxyrtyx** [comment]
Luckily this was easy to fix, since I'd already fixed the same issue in the Interpreter. Thanks for reporting that it existed in the importing code too.
