### ISSUE TITLE
Suggestion:  Interpretor for UDK Explorer

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#379]
I am attempting to see what I can move between UDK and ME3.   So far not a lot of luck with Materials.  For some reason UDK explorer is the only package editor without a decent interpreter.   If it is not a lot of work to transfer it - can this be done?

**Comment by SirCxyrtyx** [comment]
I'll look into it. Could you send me the file you're opening on UDK Explorer?

**Comment by Kinkojiro** [comment]
here you go:

[sphere_level.udk](https://onedrive.live.com/redir?resid=D6F7D3DCEF47E9D!184928&authkey=!AE0uE_0kmmvcikY&ithint=file%2cudk)

I managed to recreate the water texture sphere from ME1/2.  Trying to get the material to do the same in ME3 is hard, even if all the expressions are available in the engine.
