### ISSUE TITLE
Certain tools crashing if no ME3 game path is found.

### ISSUE THREAD

**Issue by HeffU** [ME3Explorer/ME3Explorer#38]
For users without the game installed, or in such a non-standard path that it cant be autodetected, some of the tools crash instantly when starting.
A more reasonable reaction would be something like a pop-up explaining why the tool couldn't start.

**Comment by mirh** [comment]
Or _along_ that, even another pop-up that asks you where to look for. 
Database scanner for example throws

> System.ArgumentNullException: value can't be null.
> Parameter name: path
>    in System.IO.Directory.GetFiles(String path, String searchPattern)
>    in ME3Explorer.ScriptDB.ScriptDB.startScanToolStripMenuItem_Click(Object sender, EventArgs e) in s:\GitHub\Repos\ME3\ME3Explorer\ME3Explorer\ScriptDB\ScriptDB.cs:riga 37
>    in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    in System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    in System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    in System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    in System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    in System.Windows.Forms.Control.WndProc(Message& m)
>    in System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    in System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    in System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by SirCxyrtyx** [comment]
Fixed by b0ec3566a6cbee1abc21e1dfd19f976184c6c329
