### ISSUE TITLE
Bug Conditionals editor - using arguments a-1

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#380]
If you make a new conditional with an argument (a-1) that allows a parameter to be set, the hex produced is this:

![](https://dl.dropboxusercontent.com/u/64867763/Misc/2016-06_Hex1_bug.png)

Whilst an identical conditional in the main file shows this:

![](https://dl.dropboxusercontent.com/u/64867763/Misc/2016-06_Hex2_bug.png)

Note the extra 0 integer at the end.

**Comment by SirCxyrtyx** [comment]
Show images by using the link syntax, but with a ! in front of it.
This:
```
![](https://dl.dropboxusercontent.com/u/64867763/Misc/2016-06_Hex2_bug.png)
```
produces this:
![](https://dl.dropboxusercontent.com/u/64867763/Misc/2016-06_Hex2_bug.png)

**Comment by SirCxyrtyx** [comment]
Probably a silly question, but I assume that not having those four zeroes causes the conditional to not work?

**Comment by Kinkojiro** [comment]
Actually a good question.  I originally found it because I was having problems with a conditional.   I fixed it using a seqcompareint rather than a conditional.  I went back and checked the conditionals again with a console event and it actually works whether or not you have the zeroes.  It must have been something else that was causing the error.

Sorry for wasting your time.

**Comment by SirCxyrtyx** [comment]
No problem. I asked before devoting any time to it.
