### ISSUE TITLE
Hex Converter as a full utility

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#381]
This little tool should really be it's own utility. Embedding it to ME3Creator stinks bit, as then you have to have that tool open just to use the converter.

Any way we could pull this feature out on its own? The GUI could use some tweaking, but we can wait on that until the transition to WPF is complete.

Let me know and I can whip up a new set of icons prior to its release :)

**Comment by SirCxyrtyx** [comment]
It could easily be made a seperate tool. You can open it from the Package Editor's Edit menu too btw.

**Comment by Kinkojiro** [comment]
I only use it with package ed or ME3Creator but the best reason to do this would be so it can be an icon on the bar.  Stop having to search for that small window via alt tab.

**Comment by ghost** [comment]
> Ii could easily be made a seperate tool. You can open it from the Package Editor's Edit menu too btw.

Oh snap. Bear with me, Sir, I'm just now starting to mod again after not doing so since releasing BO and taking a break for the stable, lol.

Still, let's do this. Like Kinko says, even easier to use it outside of any specific tool and to locate the little box that can otherwise be hiding on the screen. Give me a day or two notice before you want to toss it into a build and I can get the icons made :)

**Comment by SirCxyrtyx** [comment]
I can put it in the next build once I have the icons :)

**Comment by ghost** [comment]
Wewwwwt. Okay, let me finish wrestling with the stupid sound sequencing, then I'll whip them up for us :)

**Comment by ghost** [comment]
@SirCxyrtyx -- Sent you the link on the forums for the icons :)
