### ISSUE TITLE
Sequence Editor: Add output link

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#382]
Not sure if this is a silly suggestion or not, as I'm not a big sequence editing expert. However, there _is_ an option to add input links, which then begs the question, why not have the same option for output links? Right now, if you clone in an object and it has no "Out" node, then the only way to add one is to dump the BIN, open in HxD, insert it manually, re-import the BIN, etc.

Be way easier if we could: Right click > Add Output link, just like we can with Input link :)

**Comment by ghost** [comment]
Oh snap.

And now I see the new "Add Property" in Package Editor.

Sir, you rock <3

Closing issue :)

**Comment by SirCxyrtyx** [comment]
"Add Property" is part of the interpreter, so you can do this from the sequence editor as well.
