### ISSUE TITLE
SFAR Editor 2: Make live decompression/preview on-demand rather than automatic

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#386]
In SFAR Editor 2 when you click on a file entry it decompresses the entry and shows the hex on the right. In practical use I don't of anyone who wants to look at decompressed hex when using SFAR Editor 2 and the only thing it does is make the tool slow to load as you click stuff. It should be on-demand as the user requests (highly doubt they'll ever...) or simply removed.

**Comment by SirCxyrtyx** [comment]
There really isn't any point to displaying the hex there is there. I'll just remove it.
