### ISSUE TITLE
Unsaved Changes Prompt

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#387]
As we start to overhaul the GUI of the tools, this would be a nice feature to add.

If the user attempts to close a file w/o saving, there's a prompt just to make sure. Sometimes I leave files open on my PC for a couple hours and I forget if I saved. I don't do it often, but it's happened. Then there's always accidental mouse clicks, etc. It would be a nice safeguard is all.

**Comment by SirCxyrtyx** [comment]
Added in 2.0.11

**Comment by ghost** [comment]
Wewt! Thanks :D
