### ISSUE TITLE
2.0.8 Installing 1x2 textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#389]
This is a very similar issue to #292 and the other 2x1 issues I reported. A user of ALOT reported to me that at least 2 textures seemed to install correctly but didn't have an impact in-game. Turns out both of these were 1x2 (128x256 and 1024x2048), which I don't think is just a coincidence. It looks like TPF/DDS Tools still can't manage these :/.
Testing files : [2x1 textures.zip](https://github.com/ME3Explorer/ME3Explorer/files/337618/2x1.textures.zip)

Feel free to mark this as won't fix if you're still applying the feature freeze on K's tools, but I would love to see a fix for this :).

**Comment by ghost** [comment]
My guess is this is something to do with mipmaps, b/c GUI texture replacement works fine, and they are also 1x2.

Regardless, though, no changes to K's tools until if/when he re-writes them.

**Comment by starkgate** [comment]
GUI are 2x1, not 1x2. Not sure if it matters a whole lot, but it could have an impact. Sad that we won't be able to use these textures until then, but alright.
