### ISSUE TITLE
New Tool: Port + Improve TankMaster's TLK Editor

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#390]
Leaving this here for when we incorporate TankMaster's TLK editor.

It cannot handle ampersands. The vanilla TLK contains these, but his will not compile when ampersands are present. 

Also, we need to implement some debug output upon failure to compile. Something to at least point the user to the problematic line in the XML :)

**Comment by ghost** [comment]
I've changed the title to more accurately reflect what needs to be done.

FYI, TankMaster's Git [is here](https://github.com/MatthewGenerous/MassEffect-ModTools).

When porting his tool, we want to make some changes:
- As explained in the OP, his tool still has bugs with certain characters. We need to make sure the ported/edited tool can handle all characters that the vanilla game does. Ampersands and others.
- We don't want the tool to split TLKs into 10 XMLs when decompiling. At the very least, we want this optional and not mandatory.
- We may want to incorporate the ability to "stitch" XMLs together. For example, it would be great if I could have the tool take all XMLs from ME2 and ME3 and compile them into a single XML with strings all in numerical order. Or, select multiple TLKs to start and decompile into the same XML. This would allow modders to search all text for both games in a single file, rather than having to repeat searches in a dozen+ files -_-
- We'll need to confirm that handling for localizations with female TLK sections works properly. Most modders use the INT localization which doesn't have a female TLK. I see no reason why it shouldn't work, but it needs to be tested.
- String tags should be case-insensitive.
- We need some debug output upon failure to compile. A line or string reference... something.
- The issue with the negative string IDs _needs to be fixed_. This is something I've been talking about since 2013, but it's difficult to explain. I'll attempt to do so below.

The reason this needs to be fixed is that those negative string IDs are _real_ numbers referenced by the game. I explain it on the forums [here](http://me3explorer.freeforums.org/post12245.html#p12245). To try to further clarify and summarize:
- If a string appears in the TLK, it is referenced by a game file.
- String IDs that appear as "-214#########" are **incorrect**. For some reason the tool is calculating this number. I have no idea why. It might have been due to the "position" mechanic currently in the toolset, but TankMaster removed this mechanic, and the negative numbers still exist.
- These "-214#########" strings correspond to "no data" references as seen in the Dialogue Editor. There might be other instances (sequence object labels?), I don't know. However, it's very easy to see the pattern. 

Using Thane's Huerta dialogue as an example (citprs_hosp_tha_inv_d_dlg, BioD_CitHub_HospitalP2_LOC_INT.pcc), take a look at reply 7. This is an autocontinue, which means the convo flips back to Thane without Shepard speaking. However, there is a string reference for _every_ line like this in game. In the editor, you can see in this case the string ID is 641236 and that it has no associated data ("no data").

Yet, using a Ctrl+F in the TLK for this string returns no results. This is because it's been replaced by a different number: -2146842412. See below:

> ```
> <string>
>     <id>641235</id>
>     <position>58059</position>
>     <data>I'm back on the Normandy on an important mission. Sure could use you.</data>
> </string>
> <string>
>     <id>-2146842412</id>
>     <position>58060</position>
>     <data>-1</data>
> </string>
> <string>
>     <id>641237</id>
>     <position>58061</position>
>     <data>You don't have to wrestle down krogan and break their necks. I'm sure we could find you lighter work.</data>
> </string>
> ```

This mechanic leads the modder to think the string isn't referenced by the TLK, **when it is**. What's more, if the modder attempts to re-purpose that string for something else, it will create a problem for whatever file references it b/c now it _will_ have data associated with it. The game will use it.

Here's how this series of 3 strings should look in our new TLK editor:

> ```
>   <String id="641235">I'm back on the Normandy on an important mission. Sure could use you.</String>      
>   <String id="641236">-1</String>
>   <String id="641237">You don't have to wrestle down krogan and break their necks. I'm sure we could find you lighter work.</String>
> ```

---

I think that's all the ideas I had for the new tool. Like the existing tool it should handle both ME3 and ME3 TLKs.

Will post more ideas if I think of them :)

**Comment by SirCxyrtyx** [comment]
- The negative numbers are correct. The tool does no calculation, that's just what's in the tlk file. If I changed it to the way you wanted it, that would cause the xml->tlk conversion to produce incorrect tlk files. What I could do is add an extra attribute to the string element to display the number that you want to be there (calculated using TankMaster's formula in [this post](http://me3explorer.freeforums.org/post12300.html#p12300)). The tool would ignore it, but you'd be able to search for it.
  It could look something like:

> ```
>   <String id="641235">I'm back on the Normandy on an important mission. Sure could use you.</String>      
>   <String id="-2146842412" calculatedId="641236">-1</String>
>   <String id="641237">You don't have to wrestle down krogan and break their necks. I'm sure we could find you lighter work.</String>
> ```
- I _could_ make string tags case-insensitive. Wouldn't technically be xml anymore, but that's not really a big deal I suppose.
- Giving a line number on failure should be simple enough.

**Comment by ghost** [comment]
@SirCxyrtyx --
1. Okay, so the TLK file actually has them in that format. Weird. I still don't understand why, even from re-reading TankMaster's explanation. DLG files don't use a -214... reference, they use the proper string. I wonder why BW did it this way. Maybe it's just some weird behind the scenes artifact of their software.
2. I like the idea of the calculation. It's going to complicate the TLK and that's a disadvantage, but I think it's important that modders can search for a string in the decompiled TLK and get accurate results. Opening every DLG obviously isn't practical. One important question, though: would this make all existing TLKs/XML made with TankMaster's tool incompatible? DLC mod TLKs, for example, will never have any of these numbers. But, vanilla TLKs, will of course.
3. If capitalizing string tags is proper XML convention, then let's leave it. It's affected by the next point, anyway :)
4. Implementing a line number for a failure is fabulous :)

**Comment by ghost** [comment]
@SirCxyrtyx -- Just to clarify, I trust the bugs with certain unsupported characters haven't been fixed in 2.0.12? Anything I can do to help debug which characters work and which don't?

**Comment by SirCxyrtyx** [comment]
No, I haven't fixed any unsupported character bugs. Is there a list?

I would like to point out that [ampersands aren't a legal character in xml and need to be escaped](http://stackoverflow.com/a/1091953/1968930).

**Comment by ghost** [comment]
@SirCxyrtyx -- I don't think there's any list. Essentially, the list is any character BioWare uses. 

For example, I've edited Bau's email that in the vanilla game uses "ST&R". I was unable to retain the ampersand in my edited version since the XML wouldn't compile. I wasn't aware of the concept of "escaping" (and most folks who haven't done a lot of XML work likely aren't either), so I'll need to add that to the wiki once I write the TLK article.

The best thing to do for all unsupported characters would be to search through a decompiled TLK for ampersands, since all unsupported characters I've seen turn into things like: `&#38;`. 

Looking at your link, there are 5 characters folks will need to know how to "escape":

 `"   &quot; '   &apos;  <   &lt;  >   &gt;  &   &amp;`

In our original editor, I know the bullets BioWare used in the timeline didn't translate properly. I don't know if these have been fixed by TankMaster or not. I'll do some testing with 2.0.12 and decompile some vanilla TLKs. See which, if any, additional characters I can track down, then add them to this thread :)

**Comment by ghost** [comment]
Searching through the ME3 base game TLK, here's examples of the corrupted areas I found. Good news is that it looks like TankMaster fixed a bunch. The timeline now decompiles fine (the dashes were borked before. Copyright/trademark syllables in the credits also used to bork. So, less work here than I thought. Possibly no work, as it seems that maybe everything is "escaped" as it should be.

**CODES:**

`&lt;` -- less than, <
`&gt;` -- greater than, >
`&amp;` -- ampersand, &
`&lt;br&gt;` -- This seems to be a break: `<br>`. What I don't know is why it's used in some areas and not others. There's plenty of paragraph returns that don't use this.

**EXAMPLES**:

`<String id="351553">&gt;&gt;&gt;error in li1210&lt;sp&gt;</String>`
`<String id="168814">&lt;CUSTOM0&gt;h.&lt;CUSTOM1&gt;m</String>`
`<String id="338130">Weapon Upgrade
Squad bonus +&lt;CUSTOM2&gt;% assault rifle damage. Upgrades assault rifles, battle rifles, and machine guns for your entire squad.
This upgrade strengthens a weapon's mass effect field generator, increasing the velocity of each slug fired.</String>`
`<String id="163209">Squad &amp; Player</String>`
`<String id="316405">It's bad enough that I've spent two years on this miserable rock trying to scratch the damned Protheans' leavings from the stone, but now I've come down with a sickness that even my extensive medical journals can't diagnose. &lt;br&gt;With any luck, I'll be able to decipher these writings and learn the secrets of these ruins before my health fails completely.</String>`
`<String id="325927">&lt;font color='#FF0000'&gt;&lt;CUSTOM0&gt; Credits&lt;/font&gt;</String>`
`<String id="330645"> Thane Krios&lt;br&gt;</String>`
- These "Custom#" fields seem to deal with the game needing to compute a value in order to fill it in.
- No idea about the font color stuff.
- Not sure what's going on with certain paragraph breaks using that notation and others not using it.

@SirCxyrtyx -- Anything to fix here? Looks like all the stuff I've found needs to be "escaped", as you explained. The breaks are the only thing not on the list, but my guess is they're there due to using the </> symbols.

There are changes I want to make to the GUI of the tool, but I'm not sure we want to go there yet. Do we?

**Comment by SirCxyrtyx** [comment]
That all looks fine. Doesn't look like anything is corrupted anymore.

If you've got GUI ideas, I'm all ears.

**Comment by ghost** [comment]
Lawl. Okay, give me a couple days :)

No more spreadsheets, promise. Well... unless things get really complicated. ...Which they shouldn't!

**Comment by SirCxyrtyx** [comment]
This seems to have worked out properly, so I'm going to close this. GUI improvement stuff can be a new issue when/if that happens.
