### ISSUE TITLE
Current Beta, TLK Manager broken

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#391]
New TLKs can be added (I haven't check removal) but the manager is no longer using the sort priority as defined by the user. 

Using the same order of TLKs in both the stable and current beta, the Dialogue Editor in the stable will use the sort priority correctly, but the Beta version will always show the contents of the base game TLK.

**Comment by SirCxyrtyx** [comment]
Fairly certain this has been fixed in 2.0.11
