### ISSUE TITLE
In version 2.0 where is the  PCConsoleTOC.bin updater?

### ISSUE THREAD

**Issue by DrCrowTGamer15** [ME3Explorer/ME3Explorer#393]
I just downloaded version 2.0 and I can't find the PCConsoleTOC.bin updater that was on older releases, and so now my game is stuck on an infinite loading screen when I start it up because I can't update this file.

I have read the FAQ and that stuff but none of it tells me where to find this tool so my game will work, if you could help me I would be grateful, thank you for your time.

**Comment by SirCxyrtyx** [comment]
The TOC.bin updater was removed in 2.0 because it is obsolete. You'll want to use Auto TOC, which can be found under User Tools > TOC Tools. Open it and click "Generate All TOCs".

**Comment by DrCrowTGamer15** [comment]
Okay, thanks a bunch.  Sorry if that was a stupid question but I was completely baffled by this problem, thanks again.

**Comment by ghost** [comment]
@DrCrowTGamer15 - In the future, please reference the relevant wiki article for the tool. For example:

http://me3explorer.wikia.com/wiki/TOC_Tools

It'll likely get you an answer more quickly than we can.
