### ISSUE TITLE
New Tool: Plot Editor (port TankMaster)

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#396]
For reference:
[TankMaster's Github](https://github.com/MatthewGenerous/MassEffect-ModTools)
[TankMaster's ME3Exp Research Thread on PlotManagerNativeObjects](http://me3explorer.freeforums.org/done-research-plot-manager-native-objects-t1318.html)

This tool is sorely needed for all three games. It controls the amount of content modding possible, primarily due to the ability to add/edit plot IDs (bools and integers). In the case of ME2 and ME1, it also controls the ability to add and modify conditionals:
- **ME3**: Conditionals are controlled via the CND file, for which we have a separate editor. However, state transitions, the quest map, outcome, consequence, and codex maps, are all housed in the SFXGameInfoSP_SF.pcc. The DLC equivalents are the "Startup" files.
- **ME2**: Conditionals are controlled via the bioautoconditionals class inside the PlotManager.pcc. This is a _completely_ different system than ME3. All other non-DLC "maps" are housed in the ME2 Startup_INT.pcc.
- **ME1**: Conditionals seem to be controlled in a manner identical to ME2, though stored inside the PlotManager.u file. All other non-DLC "maps" are housed in the ME1 PlotManagerAuto.upk.

Ideally, we want a single tool that can handle all this. One unified "Plot Editor". The existing Conditional Editor should be rolled into it, if possible. If this isn't practical due to the different nature of the CND versus package files, then it can remain separate.

Note that TankMaster's existing Natives Editor is **incomplete**. It consists only of a quest map editor, codex editor, and state transition editor, and all editors are not finished. Some you can only add things but not delete them, others have missing features, and others yet are not implemented at all. We'll want to finish features for all existing maps, in addition to implementing a consequence and outcome editor. No idea what those maps are for, btw.

**Comment by SirCxyrtyx** [comment]
I _will_ need an icon for this one.

**Comment by ghost** [comment]
Ha ha. Will get on that today.

Things going any better with all 3 games? Or are you sticking to ME3 for now?

Also, are you pulling in the CND Editor or leaving it separate? I can reuse the background if you're pulling it in.

**Comment by SirCxyrtyx** [comment]
I'm not going to attempt anything with regard to ME2 or ME1 until I've got it working properly for ME3. 

I'm leaving the CND Editor separate for now. It's going to be complicated enough just getting it to a place where it works properly within the context of the toolset without adding new features yet.

**Comment by ghost** [comment]
Okie doke. New icon incoming soon :)

**Comment by ghost** [comment]
@SirCxyrtyx -- [This should work](https://drive.google.com/open?id=0B6dpXB1BUPrvVWhFVWtWcm9TRnM).

**Comment by ghost** [comment]
Did I just see you commit a functioning Plot Editor, @SirCxyrtyx ?? :astonished:

**Comment by SirCxyrtyx** [comment]
I've terribly mangled TankMaster's beautiful code to do so, but it appears to be functioning within the toolset. I'll see about a new release so you can play with it and the new coalesced tool.

> Some you can only add things but not delete them, others have missing features, and others yet are not implemented at all.

I'm unsure how the functionality of this compares to whatever the last release TankMaster made had, but (from my extremely limited testing) the quest map editor, codex editor, and state transition editor all seem fully functional.

**Comment by ghost** [comment]
> I've terribly mangled TankMaster's beautiful code to do so, but it appears to be functioning within the toolset. I'll see about a new release so you can play with it and the new coalesced tool.

Aww, that's a little sad. Why the mangling?

> I'm unsure how the functionality of this compares to whatever the last release TankMaster made had, but (from my extremely limited testing) the quest map editor, codex editor, and state transition editor all seem fully functional.

From memory, TankMaster intended to have the ability add AND remove state event IDs, quest IDs, and codex sections/pages. The removal part was not completely implemented. I think there might have also been certain variables that weren't fully supported for state transitions. I could probably read through his thread and come up with a list. That said, @kinkojiro and I should also be able to figure it out just by tinkering with the new tool.

Something that would also be useful is the ability to generate an empty file with a single click. That way you can start from scratch and you don't have to duplicate an existing file and then delete a bunch of stuff. ...Especially if deleting everything isn't fully supported.

**Comment by ghost** [comment]
@SirCxyrtyx -- Should we close this issue and put additional suggestions and bug reports into new issues? Or stick with this one?

First suggestions: 
- change tool name from "Natives Editor" to "Plot Editor". When you open the tool, it's still called Natives Editor
- assign proper icon to the tool, as it appears in the tool window next to the (new) name
- omg a Search feature... finding the proper bools and integers has always been less than fun. You literally have to scroll up and down the list clicking on State Events and hope you find what you're looking for. 

Looks fantastic! :D

**Comment by SirCxyrtyx** [comment]
We'll count the name and icon as wrap-up of this. The search feature ought to be a new issue though.
