### ISSUE TITLE
V2.0.11 Bug:  .UPK Unreal resource files cannot be opened/UDK explorer not available

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#402]
Isn't Package Ed supposed to replace .UDK explorer as well?

If so I cannot open resource (.upk) files.

Here is a sample file.  
https://dl.dropboxusercontent.com/u/64867763/MapMod/Minuteman.upk

**Comment by SirCxyrtyx** [comment]
It probably should eventually, but integrating it wasn't a priority for the GUI Overhaul. For now you'll still have to use UDK Explorer.

**Comment by Kinkojiro** [comment]
No problems it is very minor thing, but can you put UDK explorer back in?  Otherwise I have to keep multiple copies of ME3Explorer.

**Comment by SirCxyrtyx** [comment]
Whoops, there isn't a way to open it from ME3Explorer is there? I'll add that back in. The exe is still there in the folder though.
