### ISSUE TITLE
AltSaveToFile method missing, called by .mod file in me3explorer modmaker

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#403]
I have a user on the ME3MP discord who is using the me3explorer toolkit to install a .mod file. It is throwing a message about a missing save method which was removed recently.

http://puu.sh/r1gSk/d8279deacc.jpg

I don't know what mod, but it may be an idea to say this version doesn't support those old .mod files.

**Comment by SirCxyrtyx** [comment]
Looks like they're using a version between 2.0.5 to 2.0.10. IF they aren't a modder, you should advise them to use the stable, which should support that .mod just fine. If they are a modder, they can upgrade to 2.0.11, which will also handle that .mod
