### ISSUE TITLE
V2.0.11: Crashes using Package Editor and Meshplorer

### ISSUE THREAD

**Issue by Ottemis** [ME3Explorer/ME3Explorer#404]
The new version seems to be crashing consistently upon trying to open PCCs through Meshplorer or Package Editor from outside my game's known install paths (ME2 and ME3), though it also crashes when I open them from there, just less frequently. It sometimes also crashes directly upon opening Package Editor.

It also didn't pop the initial startup window, it has apparently autodetected my game's install paths but won't trigger treescan on it's own. I've not tried triggering a treescan through Texplorer, I have tried copying an existing treescan into the exec folder (though I don't think it matters).

I've checked my .NET version and I have the required version 4.6.1. or higher (I downloaded it and attempted install to make sure as Windows only shows I have version 4.6 installed and gives very little information). 
I'm running on Windows 10 Pro.

I've attached two outputs from windows event viewer, windows application logs
[me3explorer event viewer errors.txt](https://github.com/ME3Explorer/ME3Explorer/files/457877/me3explorer.event.viewer.errors.txt)

**Comment by Ottemis** [comment]
Running as Admin doesn't help. I have zero issues running v2.0.10. I'm in the Netherlands (Europe) btw. Adding a picture of the crash.

![me3explorer crash](https://cloud.githubusercontent.com/assets/22038757/18293762/340df6c6-7495-11e6-90b7-69cddd1e5d69.JPG)

**Comment by SirCxyrtyx** [comment]
I think I've got this figured out. In the interest of being thorough though, could you tell me what ME3Explorer shows in the Settings > Game Paths menu? Does it show the correct paths for all the games you have installed?

Oh, and the initial setup window doesn't do a treescan. That still needs to be started from Texplorer.

**Comment by Ottemis** [comment]
E:\Games\Origin Games\Mass Effect 2\
E:\Games\Origin Games\Mass Effect 3\

Those are correct.

**Comment by SirCxyrtyx** [comment]
Looks like the crash is due to ME1 not being installed (which obviously shouldn't be a requirement). This should be fixed in the next release. Thanks for the bug report!

**Comment by Ottemis** [comment]
No problem, glad I could help. For completions sake I'll install it and try it again =)

**Comment by Ottemis** [comment]
Just reporting back, works with ME1 installed as you said.
