### ISSUE TITLE
Bug: Sequence editor: Cloning objects, resets and auto-save view

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#405]
For some reason when you clone an object in sequence editor it collapses the screen view down to a mess (or expands it so everything is hugely spaced out).   Normally this is only a minor annoyance because you can reload the view and everything is back.   For some reason though if the auto-save view function is on it saves the layout as its new collapsed look.    This is disastrous when you are editing a complex 40-50 object sequence.

The weird thing is I always have had the auto-save view off for this very reason.   Somehow the sequence editor defaults to "save" when you upgrade perhaps.

If this could be fixed or at least default to no auto-save that would be great.

**Comment by SirCxyrtyx** [comment]
@Kinkojiro, I think I may have fixed the view being messed up by cloning in [2.0.15](http://me3explorer.freeforums.org/beta-2-0-15-t2556.html), but I'm not sure since it would never happen to me. Can you confirm if it's been fixed?

**Comment by Kinkojiro** [comment]
Yes.  This appears to be fixed.  Now cloning and/or adding don't seem to move it around.

Thanks very much.
