### ISSUE TITLE
Bug Minor: 2.0.12 Dialogue editor Game selector opens behind main mod pane

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#406]
Not 100% sure this isn't just me, but maybe others can check to confirm.

When you open dialogue editor from the Create Mods menu the "Which game files do you want to edit?" opens beneath the main window (if always on top is ticked).   You can keyboard around it but mouse cannot highlight it.

**Comment by SirCxyrtyx** [comment]
Can confirm. Guess I'll have to set that dialog to be always on top as well.
