### ISSUE TITLE
V2.0.12: Saving in Meshplorer

### ISSUE THREAD

**Issue by Ottemis** [ME3Explorer/ME3Explorer#408]
A story in two pictures:
![image](https://cloud.githubusercontent.com/assets/22038757/18419212/dfdac8b2-7855-11e6-9715-08c1e5459224.png)

![image](https://cloud.githubusercontent.com/assets/22038757/18419223/2caa877c-7856-11e6-988e-e65a01824990.png)

When you replace a mesh (upk replacement), it automatically saves and gives you the "Done" popup. I'm assuming as much as I don't get a popup about unsaved changes when closing Meshplorer afterwards and changes show up in my PCC.
However, when you change a material assignment for a mesh, no autosave, no save button. Heh.

**Comment by ghost** [comment]
ROFL. I've been laughing about this for 20 minutes now and it's STILL funny.

Ah, those standardized menus are going to come in handy, @SirCxyrtyx :)

**Comment by SirCxyrtyx** [comment]
Well, for now, you can always use the save button in the taskpane. Guess I didn't fully think things through when removing auto-save from meshplorer.

**Comment by ghost** [comment]
@SirCxyrtyx -- Not your fault. Most menus have a save button :)

**Comment by Ottemis** [comment]
It's fine, I can work around it =)

**Comment by ghost** [comment]
Yay for standard menu features!

**Comment by Ottemis** [comment]
Awesome, ty <3
