### ISSUE TITLE
Bug: Sequence Editor moving views

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#411]
@SirCxyrtyx -- I triggered this error again, only... it's triggering every time I open the editor which is a bit annoying, lol.

![sequence_ed_migrationerror](https://cloud.githubusercontent.com/assets/13645804/18530615/272d69bc-7a87-11e6-8d7a-d37d22c45494.PNG)

I don't quite understand the "Data property" reference in the error message. What should I be checking?

Also, interestingly, my game isn't installed to the C:, so there really shouldn't be problems copying _from_ there.

**Comment by SirCxyrtyx** [comment]
Unfortunately not something you can check on your end. Still don't know why this isn't working, but the next release will have a (hopefully) more useful error message.

**Comment by ghost** [comment]
A bit more info on this:
1. The message triggers 3x, once for each game
2. From what I can see, all views are properly copied. The same number of files exists in both locations for all 3 games.
3. Deleting the SequenceViews directory in the game folders fixes the error.

New error message doesn't seem any more helpful. The directories are correct.

![seqedmove2](https://cloud.githubusercontent.com/assets/13645804/18557108/74057202-7b22-11e6-8fef-d84930c7e0b6.PNG)

**Comment by SirCxyrtyx** [comment]
I haven't actually fixed this, but I don't think I can. Some computers will just be bothersome about file movement. I changed the error message to instruct people how to move their Sequence Views manually.
