### ISSUE TITLE
Unhandled Exception Meshplorer

### ISSUE THREAD

**Issue by Ottemis** [ME3Explorer/ME3Explorer#412]
I get these on and off using Meshplorer, Gift said I should just start posting these up.
If I get any more i'll toss them up here as well if that's useful.

This is while browsing through the various meshes in meshplorer, not a particularly large PCC (BIOG_HMF_HIR_PRO.pcc).

![i169 cimgpsh_orig](https://cloud.githubusercontent.com/assets/22038757/18531676/c855a0d4-7ad7-11e6-9be2-c931258d96f5.png)

Attaching a txt with the full report.
[meshplorer error.txt](https://github.com/ME3Explorer/ME3Explorer/files/473543/meshplorer.error.txt)

Haven't added toolset version for this error as it's an old issue that's just still present in V2.0.12.

**Comment by SirCxyrtyx** [comment]
Thanks for reporting bugs! The whole 3D rendering system really ought to be rewritten, but as it's very complicated and mostly works, rewriting it is low priority.
