### ISSUE TITLE
New GUI doesn't work very well on small screens (e.g. 720p or slightly larger)

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#414]
Some of the dialogs in ME3Explorer are too tall to be used on screens with limited height. I have a macbook air with 1366 by 768 resolution, and its not usable when dialogs come up. For example, the very first dialog for setup is too tall for me to see anything below 'Setting up ME3Explorer'. The about window is also too tall. Since the dialogs can't be resized there is no way to know what they do below.

Otherwise it looks pretty good. I was a bit skeptical of a GUI overhaul but this is pretty nice.

**Comment by ghost** [comment]
This issue replicates #398  that talks about incorporating scaling options into the toolset.

@SirCxyrtyx -- Keep open whichever you wish, but one should be closed since issues can't be merged.
