### ISSUE TITLE
Plot Editor: Instance Version not saving

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#418]
This happens in TankMaster's version, as well. Sometimes it just doesn't want to save certain changes. Right now I can't get the instance version saved in either version of the editor. I can probably hex it in for now if I can find the right part in the code :)

**Comment by ghost** [comment]
More info on this.

I got it to work, but I think it requires you to click into a new field in order for the new value to "take". Hitting enter doesn't do it, b/c that actually changes the value, which is a weird behavior.

**Comment by SirCxyrtyx** [comment]
All instance version fields, or just one in particular?

**Comment by ghost** [comment]
> All instance version fields, or just one in particular? 

The only one I tested was associated with the bool variable.

Maybe we could prevent `Enter` from changing it and leave that behavior to arrow keys? Then use `Enter` in the more typical method to save that field?

**Comment by SirCxyrtyx** [comment]
`Enter` doesn't change the value for me. In what way is it changing it?
I'm making it so any change to the field will take instantly, no need to click out. (which is really how it ought to have been all along)
