### ISSUE TITLE
2.0.13 Installing ME2 textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#419]
Installing ME2 textures doesn't work anymore, apparently. Here is the debug log when I try :

> 15:30:36:  Installing mod:  Floor01_Diff | 0/1 mods completed.
> 
> 15:30:36:  Load file : D:\ORI\Mass Effect 2\BioGame\CookedPC\BioA_ProNor_600IllusiveMan.pcc
> 15:30:36:  File already decompressed. Reading decompressed data.
> 15:30:36:  Reading Names...
> 15:30:36:  Reading Imports...
> 15:30:36:  Reading Exports...
> 15:30:36:  Prefetching Export Name Data...
> 15:30:36:  Now replacing textures in texture: Floor01_Diff
> 15:30:36:  Replacement complete. Now saving pcc: D:\ORI\Mass Effect 2\BioGame\CookedPC\BioA_ProNor_600IllusiveMan.pcc
> 15:30:36:  Writing pcc to: D:\ORI\Mass Effect 2\BioGame\CookedPC\BioA_ProNor_600IllusiveMan.pcc
> Refreshing header to stream...
> 15:30:36:  Opening filestream and writing to disk...
> 15:30:36:  Load file : D:\ORI\Mass Effect 2\BioGame\CookedPC\BioA_ProNor_600IllusiveMan.pcc
> 15:30:36:  File already decompressed. Reading decompressed data.
> 15:30:36:  Reading Names...
> 15:30:36:  Reading Imports...
> 15:30:36:  Reading Exports...
> 15:30:36:  Prefetching Export Name Data...
> 15:30:36:  Now saving pcc: D:\ORI\Mass Effect 2\BioGame\DLC\DLC_EXP_Part02\CookedPC\BioP_ArvLvl5.pcc...
> 15:30:36:  Load file : D:\ORI\Mass Effect 2\BioGame\DLC\DLC_EXP_Part02\CookedPC\BioP_ArvLvl5.pcc
> 15:30:36:  File is compressed
> 15:30:36:  Unknown error with mod:  Floor01_Diff, skipping.
> 15:30:36:  (Error:  LZO decompression failed!)
> 15:30:36:  All mods were skipped.

Trying to install the same texture in 2.0.8 worked. Test file : https://mega.nz/#!NslCiBID!ew6qsUf6YM3ixRawVDW4hkmhbO-47oXDw332SgcJOpE

Edit : I received the same error with a ME1 texture installation.

**Comment by ghost** [comment]
I'm guessing this is related to the GUI overhaul, as I don't think anyone has tested texture installation with it so far. We expected that it would break certain things.

Does ME3 work?

**Comment by starkgate** [comment]
Yes, ME3 worked. I used the same texture for all 3 games, the only difference is that I used a DXT1c in ME1 and ME2, and a DXT5 in ME3.

**Comment by KFreon** [comment]
LZO decompression failure...Interesting.
I was getting that when I was trying to get rid of LZO2.dll to clean up the directory (IN MY BRANCH not this one).
I'll go check that I didn't somehow break it.

**Comment by SirCxyrtyx** [comment]
Yep, problem was trying to get rid of lzo2helper.dll
I got a bit _too_ zealous in trying to clean out old and unused stuff it seems.
