### ISSUE TITLE
v2.0.13: Meshplorer Preview Funkyness

### ISSUE THREAD

**Issue by Ottemis** [ME3Explorer/ME3Explorer#420]
When replacing a mesh in Meshplorer using 'Import from UDK', I've noticed that while replacing LOD1, sometimes the preview will display LOD2 even though LOD1 is selected. I've tried to replicate this since seeing it happen about an hour ago but couldn't trigger it so that's unfortunate, but I thought to mention it anyways.

Second issue, quite possibly related. When replacing LOD2, sometimes it will have LOD1 and LOD2 checked in the dropdown afterwards, and this will cause the previewer to display 'one' of the two LODs **_sticks wet finger in the air**_. I have been able to replicate this one, but that was just a matter of replacing LODs till I was slightly blue in the face to see it pop up again. I have a pic:

![capture](https://cloud.githubusercontent.com/assets/22038757/18652370/3d9f74ac-7ed2-11e6-8e05-dfc10b586df8.JPG)

I know the double LOD selection thing is an old issue, at least I remember having spotted this before (read many months ago). It previewing the wrong LOD I can't rightly say though. Made this report based on testing with v2.0.13. So yes, Meshplorer preview funkyness.

**Comment by Ottemis** [comment]
Oh, one more thing, though it's unrelated to the preview issue. You removed autosave from Meshplorer no? I'm pretty sure it still autosaves on LOD replacement atmo.

**Comment by SirCxyrtyx** [comment]
A lot has happened to Meshplorer since this was posted. I'm going to assume this is no longer an issue.
