### ISSUE TITLE
v2.0.13: Texplorer ME2 treescan errors

### ISSUE THREAD

**Issue by Ottemis** [ME3Explorer/ME3Explorer#422]
While running treescan for ME2 it pops up the following error:
![capture2](https://cloud.githubusercontent.com/assets/22038757/18682912/60d7aa42-7f6e-11e6-9e74-26890d022225.JPG)

Pressing ignore, the scan continues but it shows the error several more times before finishing. On finish it shows me the following:
![capture3](https://cloud.githubusercontent.com/assets/22038757/18683318/08837b3a-7f70-11e6-948c-194848a82ce4.JPG)

These are all DLC files. Full list attached.
[error-texplorer-me2-scan.txt](https://github.com/ME3Explorer/ME3Explorer/files/483380/error-texplorer-me2-scan.txt)

I've tested this with v2.0.13, v2.0.12 and v2.0.10. Problems exist for v2.0.13 and v2.0.12 but not v2.0.10. It looks like it won't scan with DLC anymore since the GUI update in v2.0.11.

**Comment by SirCxyrtyx** [comment]
Same problem as #419, so I'm closing this. Thanks for the report though, it helped me figure out the problem.

**Comment by Ottemis** [comment]
Cool =) Yeah I'd seen than one, figured it might be easier to track down with more error logs etc.
