### ISSUE TITLE
v2.0.14, v2.0.15, Initial Setup Triggering Incorrectly

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#428]
@SirCxyrtyx -- This is a weird one.

I've had no problems with this, but yesterday after installing EGM to test for @Kinkojiro, the toolset started triggering initial setup upon launch.

I've since turned off EGM and BO, the latter which I've had disabled for a little while due to working on TM. Initial setup still triggers. To be clear, disabling those two DLC should have reverted my game to the _exact_ condition it was in -- with the exact same version of the toolset (v2.0.14) -- as before the setup started to trigger in error. Yet, this didn't resolve the situation. Neither did updating to v2.0.15.

As far as I know, we've been using the presence of TOC.bin in the DLC root to detect whether DLC is properly extracted. We do this since old extraction methods left the TOC in the SFAR, which is what caused problems.

I can verify that every BW DLC and DLC mod in my DLC folder has a TOC file right where it should be. Everything is extracted, so the message should not be triggering.

Any ideas?

**Comment by SirCxyrtyx** [comment]
Initial setup will trigger under two conditions if the disable initial setup option isn't enabled:
- The toolset cannot find the ME3 Executable
- Any directory in ME3's BIOGame/DLC/ other than "_metadata" does not have a file that's name ends with "pcconsoletoc.bin" (case insensitive) 

When you say disable, do you mean removing the folder, or just renaming it?

When the Initial setup window pops up, does the DLC extraction part claim there are any un-extracted dlcs?

**Comment by ghost** [comment]
Disable -- I mean renaming it. Oooh... and I bet that's what it is. I expected the toolset to ignore invalid DLC folder names like the game does. It does not. Kinko has some strange bug right now where EGM's installer will sometimes create an _empty_ DLC_CON_MAPMOD folder. I retained it last night (shut it off with renaming) since I wasn't sure what was going on.

Going to tag @Kinkojiro so he sees this, but close now that the mystery is solved :)

Thanks, @SirCxyrtyx !
