### ISSUE TITLE
v2.0.15, TLK Tool Compile Broken for old files

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#429]
I should have reported this earlier, but keep forgetting. I've been using TankMaster's still.

We need to strip some of the original code of this tool. Right now when trying to compile a TLK from an XML that doesn't match the old format, it throws an error with a link to an online help file created back in 2010:

![tlk_ed1](https://cloud.githubusercontent.com/assets/13645804/19022157/2748a6c0-8886-11e6-9ca3-6369ee1f5bfc.PNG)

It then follows with this error:

![tlk_ed2](https://cloud.githubusercontent.com/assets/13645804/19022168/48f1b9d8-8886-11e6-976f-5329b929c2ca.PNG)

So, A-the first error is inaccurate, B- the help doc is not ours and is 6 years old, and C- it encourages folks to report a bug to someone other than us on a website that has been read-only for 2 years. Ack.

From there, it refuses to compile the TLK... yet still triggers the "Finished creating TLK message". 

Here's a list of changes we need to make:
- Change tool name to "ME3 + ME2 TLK Editor"; this is what we have in the main window
- File menu: Remove entirely for now; it's unnecessary.
- Help menu: Remove both existing options, which both point to the original authors. Replace with, "Forums" (with link to forums) and "Report Bugs" (linked to Git Issue page).
- Add "DerPlaya - ME2 TLK Tool" under 3rd party tools (Gocek is already listed)
- Fixes for the errors above, plus removal of those dialogs so they can't trigger upon any legitimate errors
- Successful completion message should only be triggered if the TLK is indeed created

The rest of the GUI can wait until we tackle it as part of the GUI overhaul

I need to make a new icon to include the ME3/ME2 since we now have an ME1 TLK Editor (which also needs an icon. Will get these to you soon, Sir :)

**Comment by SirCxyrtyx** [comment]
> Help menu: Remove both existing options, which both point to the original authors. Replace with, "Forums" (with link to forums) and "Report Bugs" (linked to Git Issue page).

The about window points to the original authors, but the How To Use window is just instructions on tool usage. Why get rid of that?

Could you post the file that this error occurred on?

**Comment by ghost** [comment]
@SirCxyrtyx -- 

1.**Error** --It occurred to me that I wasn't clear about something in the original post. The tool will decompile fine. It's compiling that creates the problem. None of my mod TLKs will compile with the tool; they will all compile with TankMaster's version.

Here's a link to one: 
[DLC_MOD_URZ_INT.zip](https://github.com/ME3Explorer/ME3Explorer/files/514015/DLC_MOD_URZ_INT.zip)

**2. How To** -- I have three issues with it. One is uniformity; no other tools have this. Two, if we are going to incorporate a feature like this, I'd rather have little tutorial flags that can be toggled on and off. Three, once the wiki article is up, then we don't need a "How To" in the tool _and_ on the wiki. The wiki is supposed to be the tool reference, and putting the same information in both places means we have to manage it in both places to make sure it matches.

If we want to keep it until I have the wiki article up, then I'm okay with that. However, once the article is up, then it should be removed and users pointed to the article via a wiki link.
