### ISSUE TITLE
Coalesced Editor, Small changes

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#431]
Tiny housekeeping things, @SirCxyrtyx  --
- Tool name needs to be updated to "Coalesced Editor", unless we want to call it "Coalesced Converter"
- Assign the old Coalesced Editor icon to the tool. I'll make a new one, now that we don't need to differentiate between the Editor/Operator, but we can use the old one for now.
  -Do we want to keep it in Create Mods or move it to Utilities > Converters?

GUI stuff later.

**Comment by SirCxyrtyx** [comment]
I'd say Create Mods. Doesn't seem right to group it with Hex Converter and Image Engine.
