### ISSUE TITLE
texplorer tree issue

### ISSUE THREAD

**Issue by tbonegrady** [ME3Explorer/ME3Explorer#433]
when I start the tree scan for me3 it goes for a few seconds then just fucks itself up over and freezes

Problem Event Name: CLR20r3
  Problem Signature 01: ME3Explorer.exe
  Problem Signature 02: 3.0.0.0
  Problem Signature 03: 57f403cc
  Problem Signature 04: CSharpImageLibrary
  Problem Signature 05: 3.1.6.0
  Problem Signature 06: 570836b8
  Problem Signature 07: 5a
  Problem Signature 08: 78
  Problem Signature 09: Debugger.Break
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: f449
  Additional Information 2: f449a79db6c3c9a0ea43b67c586e7b9a
  Additional Information 3: 3f82
  Additional Information 4: 3f822b8ddc4ceafd532ec1b16b401d94

**Comment by KFreon** [comment]
Are you running it through Visual Studio?
That Debugger.Break seems to indicate that, is all.

**Comment by tbonegrady** [comment]
No I'm not running visual studio
mån 24 okt. 2016 kl. 4:24 em skrev Kael notifications@github.com:

**Comment by KFreon** [comment]
Windows 10?
Vanilla files?

**Comment by tbonegrady** [comment]
No windows 7 64-bit
tis 25 okt. 2016 kl. 3:31 em skrev Kael notifications@github.com:

**Comment by tbonegrady** [comment]
No not vanilla files for BIOGame
tis 25 okt. 2016 kl. 3:32 em skrev Felixbruhh mac55tyler@gmail.com:

**Comment by KFreon** [comment]
Treescan won't work on non vanilla files due to the way things are modified by the toolset.

**Comment by tbonegrady** [comment]
Thanks for the fix man
ons 26 okt. 2016 kl. 3:15 em skrev Kael notifications@github.com:
