### ISSUE TITLE
ModMaker Script Compiler Error

### ISSUE THREAD

**Issue by deadspear** [ME3Explorer/ME3Explorer#434]
It seems like the Optional Meshes have a problem while installing: http://i626.photobucket.com/albums/tt341/mamorak/Slika%20nove%20bitne%20slike%202.png

**Comment by ghost** [comment]
@deadspear -- For Sir to troubleshoot this, we'll likely need the .mod file that you're attempting to install. Please upload via zip to this thread.

Also, please verify what version of the toolset you're using.

**Comment by deadspear** [comment]
3.0.0.
If this zip doesn't work the main thing can be downloaded from the main A lot of textures nexus page, under optional downloads.
[Hair and Vorcha HR Meshes-363-2-0.zip](https://github.com/ME3Explorer/ME3Explorer/files/528444/Hair.and.Vorcha.HR.Meshes-363-2-0.zip)

**Comment by SirCxyrtyx** [comment]
I'm quite confused as to how this is happening, but I have attempted a fix. Could you try using this to run the .mods and see if that fixes it?
[ME3Explorer Test Build for DeadSpear.zip](https://github.com/ME3Explorer/ME3Explorer/files/532170/ME3Explorer.Test.Build.for.DeadSpear.zip)

**Comment by deadspear** [comment]
It seems to have fixed it. I don't get any errors.

**Comment by deadspear** [comment]
No in game errors either so its safe to assume it works.

**Comment by SirCxyrtyx** [comment]
Thanks for testing it!
