### ISSUE TITLE
v3.0, Toolset TPFs incompatible with Texmod

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#435]
Originally reported by Tarshana, [here](http://me3explorer.freeforums.org/v3-build-tpf-issues-t2576.html).

Summary: TPFs made with the toolset are incompatible with Texmod. There's no error, they just don't work in game.

**Comment by KFreon** [comment]
I FIXED IT!!!
Three entire days and a bit of a fourth, but I fixed it.

**Comment by Tarshana** [comment]
You are the awesome!!! Thank you so much for doing that!

**Comment by KFreon** [comment]
It'll be in the next build that gets released :)

**Comment by ghost** [comment]
Nice work, K :)
