### ISSUE TITLE
3.0 - Crash when unpacking DLCs

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#436]
I just reinstalled ME1, ME2, ME3 and downloaded ME3Explorer 3.0 on a new Win10x64 install. Here is what I get on the first time setup, when I hit the Unpack DLCs button. Note that all my ME3 DLCs aren't unpacked.
![](http://i.imgur.com/1Zvob07.png)
There is no IO or CPU activity after that, so it's not just a visual freeze. I tried running it a second time, it crashed in the same manner, except it didn't even display "Unpacking Extended Cut...".
Here is VS's debug :
![](http://i.imgur.com/kGTXVGk.png)
Translation : TimeSpan doesn't accept NaN floating point values. Whatever that means, I hope it helps.

**Comment by starkgate** [comment]
I successfully unpacked the DLCs with v2.0.8. I then was able to build the tree with 3.0 without encountering further problems.

**Comment by ghost** [comment]
Strange that it didn't detect your HDD required space. Wonder if that's involved at all.

**Comment by starkgate** [comment]
Could be. I ran it as admin, so permissions shouldn't be an issue.

**Comment by KFreon** [comment]
I had a problem unpacking Extended Cut too, but I thought it was my bad.
Didn't actually break though.
