### ISSUE TITLE
Mod Maker Script compiler Error, cs1704

### ISSUE THREAD

**Issue by Frost212** [ME3Explorer/ME3Explorer#440]
--Copy pasta'd this from the forums (SirCxyrtyx had replied, but not solved, and giftfish got rid of the thread)-- Also as a note to giftfish, this is not the same error (Same type, but different cause) as #434 (Or so it would seem).

Trying to install .mod files and receiving a script compiler error, cs 1704

Does the problem persist across multiple mods? -- Yes

Which mods? Provide URLs. --http://www.nexusmods.com/masseffect3/mods/157 , http://www.nexusmods.com/masseffect3/mods/461/? , http://www.nexusmods.com/masseffect3/mods/118/ , http://www.nexusmods.com/masseffect3/mods/238 , http://www.nexusmods.com/masseffect3/mods/208/ , http://www.nexusmods.com/masseffect3/mods/306/? , And quite a few others (Don't think you want me to put like 30 links here =P)

Have you contacted the mod author about the problem? -- No, because they're not ~all~ by the same authors. Seemed to be a generic issue with the .mod files made in earlier revisions. 
Game affected (ME1/ME2/ME3) -- Me3
ME3Explorer version/revision used -- v3.0.0
Tool used when experiencing the problem -- Mod Maker
Windows version (e.g., Win7x64) -- Win10 x64
Game localization (English, etc) -- English
Is your game pirated, EXE cracked, etc? -- No
Have you tried properly vanillaing your game using this wiki article? -- Yes

Describe what you have done to troubleshoot the issue. -- The only troubleshooting help i saw about this specific issue, was a previous thread, posted by SirCxyrtyx, that stated that it was fixed in v3.0 (Obviously it was not =/) The only true "Work around" I have found, is go to back to using v 2.0.

Embed all relevant screenshots of errors, the problem tool, debug output, and examples of the problem http://puu.sh/rAy9H/f91f574c76.png

**Comment by SirCxyrtyx** [comment]
I've committed a fix for #434, and I'm fairly confident it will fix this as well. If you want to confirm though, you can test out the build I posted [here.](https://github.com/ME3Explorer/ME3Explorer/issues/434#issuecomment-254082273)
