### ISSUE TITLE
Texture cloning quirks

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#443]
@SirCxyrtyx -- Here's a brief summary of the problem as I understand it. @Kinkojiro, please correct me if I feck any of this up.

There's a problem related to cloning textures with mips in the toolset. This is due to the variation in where mips are stored. The parent texture and larger mips are in the TFC, the smaller mips are in the PCC. 

If I'm understanding Kinko correctly, within the Texture2D object there's binary data that refers to the location of the mip offsets in the PCC. This means that if the modder clones that texture into a different PCC those offset references become incorrect.

Strangely, this isn't always a problem. Sometimes the texture will still render fine in game; other times it won't. Kinko has said sometimes it can be fixed by changing the texture group to Shadowmap. This is the easy fix.

The other two ways to fix this are:
- Use Texplorer to replace the texture. This will change the mip offsets so they are correct for the new file. The downside of this method is it forces the modder to insert new textures and create a new TFC when they may simply want to use the existing vanilla texture.
- Use a very, very old version of Texplorer (e.g., r653) that allows individual mip replacement. This will allow the modder to replace the missing mip levels in the modded PCC. The downside of this method is having to use a very old version of the toolset. I'm also a bit unclear about workflow since versions this old have all sorts of issues scanning on DLC mods, certain Add/replace features of Texplorer are a bit wonky, etc.

**Potential solution**
It seems like cloning in a texture needs an additional step. This step would search for these offset references in the source file and then change them so they fit the new "address" in the destination file.

Does this seem like a viable solution?

**Comment by ghost** [comment]
@SirCxyrtyx -- If you end up needing an example of a file where the "shadowmap" trick works, I used it for Bailey's new datapad and can toss you that file. I also noticed the other day that this ends up still triggering some mip-related output in the logger. The game is stable, but the output is present, nonetheless.

Let me know if you need a copy of the file for testing/research :)

**Comment by SirCxyrtyx** [comment]
Seems like a simple enough fix. I'll just have it correct the offsets during file save.
