### ISSUE TITLE
Crash when loading BMP textures

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#444]
Loading a BMP texture in TPF Tools or IE results in an instant crash. I run ME3Explorer as admin.
![devenv_2016-10-25_18-54-28](https://cloud.githubusercontent.com/assets/12874678/19695741/9e9c4464-9ae4-11e6-906f-d82234609eb6.png)
![devenv_2016-10-25_18-54-47](https://cloud.githubusercontent.com/assets/12874678/19695740/9e8ff222-9ae4-11e6-87a6-2bc81fdc3f09.png)

Crash texture : 
[MASSEFFECT2.EXE_0x3AF35864.zip](https://github.com/ME3Explorer/ME3Explorer/files/551237/MASSEFFECT2.EXE_0x3AF35864.zip)
Interestingly, it didn't crash when loading a texture that had been converted to BMP by IE (as opposed to the other one, converted by Photoshop).
Working texture :
[MASSEFFECT2.EXE_0x3AF35864_1.zip](https://github.com/ME3Explorer/ME3Explorer/files/551266/MASSEFFECT2.EXE_0x3AF35864_1.zip)

**Comment by KFreon** [comment]
Works for me.
Wait, are you on Windows 10 yet?

**Comment by starkgate** [comment]
I am, yes.

**Comment by KFreon** [comment]
Is it repeatable? As in, does it appear random (indicating possible memory issue), or every time (indicating cosmic radiation affecting your PC...)

Also, I'm guessing that Additional Information says something like "Attempted to read protected memory." Dunno about the second bit, but that usually happens when I've done something wrong in the code relating to Windows Codecs.

Have you got any programs that give you DDS or photoshop thumbnails in Explorer or something?

**Comment by starkgate** [comment]
1. Yes, it is repeatable. I just tried it again in TPF Tools and IE, same result as before. Must be cosmic radiations, I'm afraid. We need personal force fields for computers, why hasn't this been done already ?
2. I shouldn't have any special codecs, I haven't installed any at least. No DDS thumbnails, besides, these are BMP textures. Could it be that the way I saved it in PS matters ? I used RGB/8, whereas V8U8 and ATI2 are saved in 16 bits iirc ?

**Comment by KFreon** [comment]
Windows handles BMP's so they should know how they work.
And besides, that texture you linked works for me...
You've got VS in the background there, exactly where does it crash in the code?

**Comment by starkgate** [comment]
I'd like to test, but when I try to build the source code, it fails. See log here :
http://pastebin.ca/3733289
If I hit Start and run the last successful build (whichever that would be ?), here is what I get :
![devenv_2016-10-27_08-47-30](https://cloud.githubusercontent.com/assets/12874678/19757250/287710e0-9c22-11e6-8d1e-149f74c8fbd1.png)

**Comment by KFreon** [comment]
Hurrrrr. This is like the old school DLL Hell.
Easy solution: comment out that line. You might actually be able to Continue through that exception.

**Comment by starkgate** [comment]
lol, I like your thinking. I'll try that, we'll see how it goes.
Edit : Well, it also crashes with the source version, so at least the bug is consistent. Once I load a BMP in IE, it crashes. Note that it doesn't crash instantly when loaded in IE, you have to hit Convert for it to crash.

Here is the VS log :

> Format: Format: BMP  IsMippable: False
> Image Loading: 114
> Image Preview: 0
> Exception thrown: 'System.AccessViolationException' in CSharpImageLibrary.exe
> Bypass prompt for source file: D:\Stuff\Other\Useful things\Code Repository\C#\CSharpImageLibrary\CSharpImageLibrary\ViewModel.cs.
> Bypass prompt for source file: D:\Stuff\Other\Useful things\Code Repository\C#\CSharpImageLibrary\CSharpImageLibrary\ViewModel.cs.
> The thread 0x20cc has exited with code 0 (0x0).
> The thread 0x2020 has exited with code 0 (0x0).
> The thread 0x20a0 has exited with code 0 (0x0).
> The program '[6444] ME3Explorer.vshost.exe: Program Trace' has exited with code 0 (0x0).
> The program '[6444] ME3Explorer.vshost.exe' has exited with code 0 (0x0).

And pictures of VS debug :
VS first pops up 2 windows asking to browse for ImageEngine.cs and ViewModel.cs.
![devenv_2016-10-27_19-09-45](https://cloud.githubusercontent.com/assets/12874678/19777565/1c91bb34-9c79-11e6-9e83-e62b584d83b6.png)
When I close the windows, it throws this error :
![devenv_2016-10-27_19-10-01](https://cloud.githubusercontent.com/assets/12874678/19777566/1c9bb30a-9c79-11e6-9b29-6b63c75a74e4.png)
Once I hit continue, it crashes.

**Comment by KFreon** [comment]
I don't know why it doesn't know that they're included in the debug package...
Anyway, so it's after you click Convert.
Any particular thing to convert to?

EDIT: OK I got it to happen for me too. 
Also, for future reference, the source files are at "me3explorer/packages/csharplibrary".

EDIT 2: Fixed it. Not going to get into the ME3 branch for a while though :(
