### ISSUE TITLE
Wrong game detection

### ISSUE THREAD

**Issue by NDaniel90** [ME3Explorer/ME3Explorer#447]
I uninstalled Mass Effect 3 some time ago but the Explorer keeps detecting it and crashes when I try to manually remove the path during setup. Quite annyoing. Why not include a feature to MANUALLY specify which installments you wanna work with? Why force the user to unpack ME3's DLC contents for 2 hours if all he wants to do is some texture tweaking in ME1?

**Comment by mirh** [comment]
Mhh.. It sound similar to #78. 
What happens if you rename HKLM\SOFTWARE\Wow6432Node\BioWare\Mass Effect 3 key ?

**Comment by SirCxyrtyx** [comment]
when exactly does it crash? Right after clicking the "Paths Ok" Button? Does it give an error message before crashing?

**Comment by ghost** [comment]
Closing for lack of info. Will reopen if the problem is repeated and identified.
