### ISSUE TITLE
3.0 - Crash when trying to convert to TGA

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#448]
IE crashes as soon as I select the TGA format : 
![me3explorer_2016-11-03_13-48-13](https://cloud.githubusercontent.com/assets/12874678/19966538/7c6d2dd8-a1cc-11e6-92b2-31a43580a4b3.png)
VS debug is nice enough to tell us where the issue comes from :
![devenv_2016-11-03_13-48-38](https://cloud.githubusercontent.com/assets/12874678/19966539/7c6fd844-a1cc-11e6-9e0a-2874585625af.png)

**Comment by KFreon** [comment]
Saving not supported yet.
I'll get there.
