### ISSUE TITLE
Meshplorer viewport constant aspect ratio

### ISSUE THREAD

**Issue by epicabsol** [ME3Explorer/ME3Explorer#450]
The projection matrix of the Meshplorer preview window should respect the aspect ratio of the control.

![image](https://cloud.githubusercontent.com/assets/4462127/20089504/2ad57c0a-a53c-11e6-82dc-8a087f441983.png)

I'm working on a patch now. Maybe I should try making a single directx control for reusability in all the tools, instead of all this duplicated code?

**Comment by epicabsol** [comment]
Fixed by #451

**Comment by SirCxyrtyx** [comment]
As for the single directx control thing, that sounds awesome! All the 3d rendering in ME3Explorer was written a long time ago by someone who is no longer involved in the project. I have basically zero knowledge of how any of that stuff works, so If you can improve it in any way that would be really cool.

**Comment by ghost** [comment]
Sounds great. I'll put up a forum thread and put Ben into the coding group. That way if he needs to ask any detailed, technical questions, he can :)
