### ISSUE TITLE
Pathing problem, only ME1 present

### ISSUE THREAD

**Issue by cristi1990an** [ME3Explorer/ME3Explorer#452]
I don't have ME2 and ME3 installed and the Explorer crashes when I confirm the path for only ME1.

**Comment by ghost** [comment]
In the future, please create a separate title and description of your issue. Short title, detailed description. You cannot fit all information we need to troubleshoot a potential bug, in a title.

For example:
- When does the toolset crash? During Initial Setup or when accessing the pathing option from the Settings?
- Is there an error message? If so, post the complete message.
- Do you have a legal version of the game installed, or a cracked copy?
