### ISSUE TITLE
Also, I'm getting this error when trying to install a certain mod in ME1.

### ISSUE THREAD

**Issue by cristi1990an** [ME3Explorer/ME3Explorer#453]
''Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.''

**Comment by ghost** [comment]
To my knowledge, there is no way to install a mod for ME1, unless you are talking about a texture TPF. Either way, this isn't a sufficient bug report. If you need help with this error, please post a thread in the Toolset Help forum, by following the directions in the sticky post.
