### ISSUE TITLE
Stable 3.0 -- TPF ME2 game textures install random error

### ISSUE THREAD

**Issue by alvarome** [ME3Explorer/ME3Explorer#455]
Hi:

I´m having a random error when installing some upscalled textures in ME2 game using TPF/DDS Tools.

I say random because afected textures may (or may not) be the same in different modding runs. 

I´m having this issue with the same batch of (77) textures always. I have to say I already had this error with Stable 2.0 in the past but it never bothered me too much because a second modding run used to fix this easily.

On my side, I have also ran a few mem test and all were negative (no error). I have 16Gb RAM and a just a few months old PC. BTW, I use much more memory intensive applications here flawlessly and, add to the previous, I haven´t had this issue neither in any ME3 game modding run (where much more textures are installed) nor installing many other ME2 game textures.. 

What moved me to open this file now is that at ALOT for ME2 mod page at Nexus there are more users reporting this issue lately.

That batch of textures are always loaded and analysed fine in TPF tools, not beign flagged at all. I migth be wrong here but the upscalled textures seem fine to me.

But when the install run finishes, I always receive a message reporting not all valid textures were installed. 

Checking debug log, the very few textures not installed were always skipped due a System.OutOfMemoryException error.

Here you got debug logs for two different modding runs using the same textures in different days. 

https://mega.nz/#!oAAkBD4D!Mfbpy2CmQXTMKjTvcrUfVYexh_xFjP0h14BKAF3b2_Y

Both modding runs were done onto vanilla Me2 game.

Both modding runs were done just after opening toolset. No previous toolset operations.

Notice in first modding, past nov-13th, skipped textures were as follows:

0xD4913993 --> 4096x4096 --> ATI2 --> HMF_ARM_CTHb_Nav_Norm_Stack
0xE57B1A3F --> 2048x2048 --> DXT1 --> HMF_ARM_CTHa_Cer_Diff
0xF1EB9877 --> 4096x4096 --> ATI2 --> HMF_ARM_CTHe_Rou_Norm_Stack
0xFCF4719D --> 1024x1024 --> DXT5 --> HMF_ARM_CTHd_Tnt_Mask_02
0xFF4507AC --> 4096x4096 --> DXT5 --> HMF_ARM_CTHb_Nav_Diff_Stack

In second modding run, today, skipped textures were as follows:

0xC4457DAF --> 2048x2048 --> ATI2 --> HMF_ARM_CTHc_Exe_Norm_Stack
0xC9992B30 --> 2048x2048 --> DXT5 --> HMF_ARM_CTHd_Tnt_Diff

Textures were not even contiguous during the modding run.

Here you got the batch of textures used:

https://mega.nz/#!gF5hmRhQ!ICGt9FLX2Zqq0OxJVNcMDs-emv_j2RUPg4GvUFKzkdY

Beign aware of this issue, I use to run, then, individual, single texture, modding runs to install those left behind and that uses to fix it.

HTH!
Alvaro

**Comment by ghost** [comment]
I'm just going to mention here that if this error i in v2.0 then there was a reason it wasn't fixed, as any fix is likely to break something else. This is why K's tools are in archival state and errors like this shouldn't be reported.

@KFreon, will leave this open so you can take a look, but I'm going to tag with your name and "no fix".

**Comment by KFreon** [comment]
Yeah this is something that should be fixed in the rewrite.
I'm pretty sure it's due to how images are handled on the back end. The memory isn't getting released and/or reclaimed fast enough, so it "runs out".
That'll be further alleviated by the rewrite cos it'll be 64 bit as well.

**Comment by ghost** [comment]
> That'll be further alleviated by the rewrite cos it'll be 64 bit as well. 

Yaaaay.
