### ISSUE TITLE
Stable 3.0 -- TPF ME2 game texture not installed / not showing up ingame

### ISSUE THREAD

**Issue by alvarome** [ME3Explorer/ME3Explorer#456]
Hi:

I´m having an issue with an upscalled texture that:

1.- It´s loaded and analysed fine in TPF tools
2.- TPF report successful install. Debug log shows no error.
3.- Upscalled texture is not showing up ingame. No vissual glitch either. Just vanilla texture.

Here you got texture details:

First data colum is for the .dds file.

Second colum for the vanilla texture -collected on the fly by Texplorer-

Third colum for the installed texture -collected on the fly by Texplorer-

Notice vanilla / modded texture data is the very same but for the LOD group. So looks like game data is updated but no texture size change, i.e. surprisingly. -?-

![image](https://cloud.githubusercontent.com/assets/17484308/20413241/b4cad272-ad23-11e6-9678-11fc6d2c3b58.png)

Here you got upscalled texture, debug log and screenshots showing vanilla texture, texture after install (just like vanilla) and how the upscalled texture should be ingame.

https://mega.nz/#!lJh21R5b!Zen8u8m6qpoOXM-BQAOK1Gl_z7ZC7oCMg6mcckWYEHg

I might be wrong here but upscalled texture .dds file seems to be fine.

It´s a 1x2 non-squared texture but, AFAIK, those are not a problem for current Stable. 

Only thing that I see as a clue here -if so- is that it is a textures.tfc texture and not a .pcc one. -?-

HTH!
Alvaro

**Comment by ghost** [comment]
@alvarome -- Just a reminder that K's tools are in archival state and won't see fixes for things like this. The toolset does have problems with certain non-square textures, so this could be involved.

@KFreon -- Please close after you've taken a look :)

**Comment by KFreon** [comment]
Non square textures have been an issue in the past, as have textures smaller than 4x4. 
Perhaps this is related to those? 
Either way, it's on the list for testing when I get around to testing...
