### ISSUE TITLE
Memory Overflow and Indexing Error that Crashes Levels on Load

### ISSUE THREAD

**Issue by CompuStrategistErmUser** [ME3Explorer/ME3Explorer#458]
I have been regularly experiencing errors any time I use the tool with large amounts of textures or at times, specific mods.

Here is a sample of the output text I've seen in the Debug log Unknown error with mod:  **HMF_ARM_SHPa_Tor_Tint, skipping.
12:24:54 PM:  (Error:  Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index)**

and

**" (Error: Arithmetic operation resulted in an overflow.)11:46:25 PM: All mods were skipped)."**

Any time I try to load a save, the problem causes a crash or freeze for whichever DLC is affected by the error. Generally, I assume due to the mention of "memory" that this is caused by the program being overburdened by the sheer load of the textures (Regularly, texture overhauls are 2048x2048) or the amount of files it has to edit at a time (I've gotten this error consistently when trying to replace eye and paper placeable textures; since these are used practically everywhere, I assume the amount of changes required as the cause)

Admittedly, I am a new GITHUB user, and as such, I have no idea how to add a "Bug" label to this issue, but I assure you, this is causing regular crashes and is caused by these errors.

**Comment by KFreon** [comment]
For a new github user, you've put a decent amount of info in while staying concise :)

One thing that'd help though, is there a situation where you can reliably cause this issue? Like a certain set of mods (preferably a small set) that when installed fail in this fashion?

Thing is, those errors could happen anywhere for any mod. We need a way to cause this error on our machines.

**Comment by CompuStrategistErmUser** [comment]
The easiest way I can reproduce the Index Out of Range error is in trying to install the paper texture from 
http://www.nexusmods.com/masseffect3/mods/380/? 
As an added oddity, I found this error every time I attempted to install the HR Set Armor Pack  on these 13 specific files: 
_hmf arm shpa tor strip
hmm arm shpa tor norm
hmf arm shpa tor spec
hmm arm shpa tor spec
hmm arm shpa sld norm
hmf arm shpa tor tint
hmm arm shpa sld diff
hmm arm shpa sld spec
mf arm shpa tor norm
mm arm shpa tor tint
hmm arm shpa tor strip
hmf arm shpa tor diff
hmm arm shpa tor diff_ 
I made it stop throwing the error by installing only these files, and isolated them to only install to the DLC_EXP_Pack002 and DLC_EXP_Pack003/DLC_EXP_Pack003_Base PCCs (I unchecked any PCC that wasn't Pack002, Pack003, and Pack003_Base in the texture properties and then hit "Install Checked") I have no idea why this worked, but it did..

The Out Of Memory Exception was consistently thrown for anything using "HR" or 4086x4086 textures, but I recently found it when installing the Vorcha textures from Vorcha and Batarian Upscale http://www.nexusmods.com/masseffect3/mods/384/?

I've gotten it when attempting to install the Eye textures for Character Texture Overhaul http://www.nexusmods.com/masseffect3/mods/116/?

As well as the armor from HR Kaiden Default Armor http://www.nexusmods.com/masseffect3/mods/290/?


EDIT_

An added detail that may help (hopefully); I've gotten two memory based errors. One is the Out of Memory Exception, but another one I would get with higher resolution textures was the Memory Overflow error. I have even seen the second error when loading textures prior to scanning them. This was the case for the High-res Clothing mod http://www.nexusmods.com/masseffect3/mods/345/?

**Comment by KFreon** [comment]
Nice report. I'll have to remember this one when I get back to working on this stuff again.

An aside though, "Out of Memory" I know well, but can you screenshot or describe what the error looks like for "Memory Overflow"?
If you mean the "Arithmetic Overflow" from the OP, then don't worry about it, I know that one too. Don't know why you're getting it, but at least I know what it is :)

**Comment by CompuStrategistErmUser** [comment]
I finally got the appropriate error from HRKaiden Default Armor

**Now saving pcc: C:\Program Files\Origin Games\Mass Effect 3\BIOGame\DLC\DLC_MOD_EGM_Squad\CookedPCConsole\BioD_CitSam_500Cell_Conv_LOC_INT.pcc...
6:37:03 PM:  Now saving pcc: C:\Program Files\Origin Games\Mass Effect 3\BIOGame\DLC\DLC_MOD_EGM_Squad\CookedPCConsole\BioH_Jacob_EGM.pcc...
6:37:04 PM:  Unknown error with mod:  HMM_ARM_KAIa_Diff, skipping.
6:37:04 PM:  (Error:  Arithmetic operation resulted in an overflow.)
6:37:04 PM:  All mods were skipped.**

I also have each individual memory based error, if you would like to see them. 

(These were also caused by the HR Kaiden Default Armor mod during various installation attempts)
**Unknown error with mod:  HMM_ARM_KAIa_Diff, skipping.6:19:06 PM:  (Error:  Insufficient memory to continue the execution of the program.)6:19:06 PM:** 

**Error checking texture: Exception from HRESULT: 0x889800036:18:59 PM:** 

**Unknown error with mod:  HMM_ARM_KAIa_Norm, skipping.6:20:34 PM:  (Error:  Exception of type 'System.OutOfMemoryException' was thrown.)6:20:34 PM:**


Bear in mind that I am using a severely limited setup in comparison to what is generally acceptable (Only 4GB of RAM), however, I have unexpectedly been given additional RAM for my computer, so my own machine capabilities may change as well. 
That said, I haven't installed it yet, so if you require me to use my current RAM, please let me know.

**Comment by KFreon** [comment]
4GB could be an issue, if you have other programs running.
If you're sticking with 4GB, close absolutely everything you can including stuff in the tray (bottom right) and wait for a bit, then try installing again. Hopefully there'll be enough space in there.

Now, 4GB is small, so I'd definitely recommend installing more RAM.

**Comment by Kinkojiro** [comment]
BioH_Jacob_EGM.pcc is an EGM specific file that I know if you edit with any version of texplorer prior to 3.0 it will crash and shred the file.  Just check that you are using the latest version.

**Comment by CompuStrategistErmUser** [comment]
BioH_Jacob_EGM.pcc was the last file listed in the Debug Window when I would run Texplorer (Earlier version than 3) for eye texture replacement prior to it crashing, so I think what you mentioned is definitely responsible for the eye texture crash at least.

**Comment by ghost** [comment]
Kfreon's tools are in archival state.
