### ISSUE TITLE
v 3.0.1 Issues cloning in PackEd

### ISSUE THREAD

**Issue by Ottemis** [ME3Explorer/ME3Explorer#460]
I was using 2.0.14 before to do my cloning, having switched to 3.0.1 now I seem unable to clone in an entire tree with PackEd via drag & drop. Instead it'll only clone in the Mat (first nested entry) and I can't manually add in the other nested entries either. This does work using v2.0.14,

![untitled-2](https://cloud.githubusercontent.com/assets/22038757/21086150/f7c8afd2-c019-11e6-8d90-48c8e0ac01a1.jpg)

----------------

I **can** clone an entire tree by using right mouse button 'clone tree' functionality in the same instance of PackEd, but it will add in a bunch of extra entries under the MDL that weren't present in the entry I cloned. I don't see why they are there as the original entry doesn't have them and works fine, plus it clogs up my export list.

Trying this a second time now, with a freshly opened 3.0.1, this does work without adding the extra entries under the MDL, but the first issue I've described is still there.

**Comment by Ottemis** [comment]
Additionally, is there a reason right click cloning ups the index number of the cloned object when drag&drop cloning doesn't?

![image](https://cloud.githubusercontent.com/assets/22038757/21098713/ce2f808c-c06a-11e6-9f08-e361acdebe72.png)

In that same line, right click cloning preserves class names, while drag&drop cloning doesn't. Now personally I don't much mind whether it does or doesn't as I have to change values there regardless so I'm stuck waiting for PackEd to reload between changes either way, but I found it curious.

**Comment by Ottemis** [comment]
I've also done more testing with drag and drop cloning of single nested entries using v3.0.1, and I can **sometimes** get this to work, where most times it'll reload but no new entry appears which is what I observed all day yesterday.

Problems cloning a whole package via drag&drop persist through more testing.

**Comment by ghost** [comment]
>In that same line, right click cloning preserves class names, while drag&drop cloning doesn't. Now personally I don't much mind whether it does or doesn't as I have to change values there regardless so I'm stuck waiting for PackEd to reload between changes either way, but I found it curious.

Both methods should work the same, as far as I know. The index is almost always (always?) be changed when cloning an object. A majority of the time, you don't want two objects with the same index. Some object classes seem to ignore this convention, but I'd say a majority use it.

@SirCxyrtyx -- Might this be due to the change in texture cloning regarding the mipmap issue... if you implemented it? I can't remember.

**Comment by Ottemis** [comment]
Yeah I've never had to change index for what I'm cloning and seeing my method didn't change the index upon clone I've never had to touch it before now. But that's neither here nor there, as it stands both methods don't do the same thing and that's definitely curious.

**Comment by Kinkojiro** [comment]
I had a similar issue with dragging and dropping a skelmesh object between files.    Every other object it worked, just for some reason this skelmesh wouldn't.  eventually I used ME3Creators import to work around it.

If somebody wants to replicate - try dragging and dropping HMF_ARM_MIRc_MDL obj#8023 from BioH_Miranda_AAP.pcc to BioD_End001_436CRMiranda.pcc  files: [DragDrop_Skelmesh.7z](https://dl.dropboxusercontent.com/u/64867763/Misc/DragDrop_Skelmesh.7z)
