### ISSUE TITLE
Initial Setup Crash

### ISSUE THREAD

**Issue by initialsetuperror** [ME3Explorer/ME3Explorer#461]
When I try to unpack the DLCs, it immediately stops working and I'm forced to close it. I've check the the net framework (4.6.2) and everything else is fine. Is there a solution to this? 
![isc](https://cloud.githubusercontent.com/assets/24553507/21156972/bf8d2440-c145-11e6-95e0-addaac1f4d61.JPG)

**Comment by ghost** [comment]
Help requests should *always* be accompanied by the version of the toolset you're using. We need this information to troubleshoot.

**Comment by ghost** [comment]
Closing this issue since the reporter never responded.
