### ISSUE TITLE
Request for Help

### ISSUE THREAD

**Issue by LordDaeman** [ME3Explorer/ME3Explorer#463]
I may be doing it incorrectly but I was trying to replace files within the DLC pcc for the purpose of removing the visors on Jack, Grunt and Thane's DLC outfits. They weren't read in the tree for some reason and when I matched the hashes to figure out the reason, there was no difference. The hashes on the file matched hashes of their counterparts within the tree. So I opted to change them myself in Texplorer since they were dds files. Upon completion I ensured that the textures were replaced, saved it and have the notification saying it was successful. Launched the game and switch party outfits but the outfits remained unchanged. Despite the different textures in the file. I'm hoping to get some advice on what I've done incorrectly and perhaps help in accomplishing my desired task.

**Comment by ghost** [comment]
This isn't the place for modding-related help requests. Visit the [forum](http://me3explorer.freeforums.org/) if you have questions.
