### ISSUE TITLE
ME1 tools are nowhere to be found

### ISSUE THREAD

**Issue by mirh** [ME3Explorer/ME3Explorer#465]
![me1](https://cloud.githubusercontent.com/assets/9366725/22543746/36565e02-e932-11e6-97e1-2529ded0f444.png) Was fine until GUI overhaul 
Or perhaps it's just me that cannot find package editor :\

**Comment by ghost** [comment]
http://me3explorer.freeforums.org/beta-2-0-11-gui-overhaul-t2521.html

Git is not for asking toolset usage questions. Please stick to the forums for those.

**Comment by mirh** [comment]
> The Package Editor and Sequence Editor can now handle files from ME1, ME2, and ME3. 

I have none of that.
