### ISSUE TITLE
Repacking unmodified sfar content with original checksum

### ISSUE THREAD

**Issue by romulus2k4** [ME3Explorer/ME3Explorer#473]
Hello.

What I am trying to achieve is this:

I am trying to unpack the contents of all the sfar,  then later use the extracted unmodified content to pack it back into sfar while maintaining the original hash/checkum of the sfar they were extracted from.

Can this be done?

**Comment by Mgamerz** [comment]
You asked this on my fork of this project for the XENON build - this is not possible. A hash is a mathematical function that proves a file is the exact same as somewhere else. We do not have the capability to repack SFARs in the exact same way from scratch, as we do not possess the original algorithms used to create the sfar - we can make a compatible version, but not an original. I replied to your comment on my XENON version page, but in summary:

- If you want to move an archive (you said to optical media) in chunks, put it into a winrar or 7zip archive and use the file splitting option to the correct size. Transfer this to your target and put all the files in one folder, and then unzip the archive.
- Compression of individual PCCs is worse than compression of the entire archive as deduplicated data is not used across files (though it is a streaming compress, so it is limited in that regard)



Mgamerz

**Comment by ghost** [comment]
This question seems to have been answered and is not development related, so closing this issue.
