### ISSUE TITLE
Command Line arguments can be removed in upcoming releases

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#474]
I added some command line options to ME3Explorer several years ago, which I know had to be somewhat reworked when 3.0 stable came out. They're in the main app.xaml.cs. These operations are no longer required as I have written some new command line tools that work better than the hack job implementation I added back then. If you want to remove these items to clean up the code base, go ahead as I am no longer using these options (nor will my userbase be in an upcoming update of my software).

There are a few other command line options that I am not sure if they are still used that existed before I added those items.

**Comment by SirCxyrtyx** [comment]
closed by 4098e386cdef4f931df2dd5269301c159b7c4cbd
