### ISSUE TITLE
Texplorer 2.0 - Change Game button not showing

### ISSUE THREAD

**Issue by woodenworks** [ME3Explorer/ME3Explorer#475]
I'm trying to build a tree for ME1, but the button to change the game I'm modding is hidden.  Adjusting the window size, maximizing, etc. don't have any effect.
![image](https://user-images.githubusercontent.com/32019593/30514073-88e1b2fa-9adc-11e7-8649-4038949c574e.png)

ME3Explorer 3.0.0
Win10x64
ME1 & 2 on Steam, ME3 on Origin (All Legal)

**Comment by KFreon** [comment]
I'm guessing you have a high DPI setting? Like 150% scaling when you go to Display Settings on the Desktop?
Unfortunately the tool doesn't behave too well when this is the case :(

**Comment by ghost** [comment]
As specified on the wiki, bugs with Kfreon's Tools should no longer be reported as they are in legacy mode.  Feature suggestions can be made on Kfreon's fork. See the link below for more info.

http://me3explorer.wikia.com/wiki/Reporting_Bugs
