### ISSUE TITLE
3.0.0 - Game crashes when attempting to load modified pcc file

### ISSUE THREAD

**Issue by princep444** [ME3Explorer/ME3Explorer#476]
This seems to be an ongoing issue, probably for about 4 years. I've been trying to load mp powers without power id conflicts, and replacing the files in the default.sfar using the sfar editor creates a major issue when attempting to load mp powers in single player, causing the game to crash. I'm not so sure this issue has been fixed yet, considering how many times I've tried to get this to work.

**Comment by Mgamerz** [comment]
I doubt this is an ME3Explorer issue. There are hundreds of thousands of ways the engine won't load your files, from missing references (which there will be many of if you just move the power file) to conflicts, etc.
