### ISSUE TITLE
Automatic update of old mod version hangs

### ISSUE THREAD

**Issue by Verequus** [ME3Explorer/ME3Explorer#477]
When I was trying to apply this [mod](https://www.nexusmods.com/masseffect3/ajax/downloadfile?id=740), ME3Explorer complained that the mod was for version 2. It offered to convert the mod into the format of version 3, but after 20 minutes of no progress I killed the ME3Explorer process.

**Comment by ghost** [comment]
Your link is broken. ModMaker will offer to update mods, but it's not foolproof.

Either way, Kfreon's tools are in legacy state and will no longer be updated. See info here:

http://me3explorer.wikia.com/wiki/Reporting_Bugs
