### ISSUE TITLE
Array Properties, Stores

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#479]
When changing the class link for SFXGUIData_Store objects, PackEd is changing _how_ it reads the "StoreItemArray" array property from "StoreItemData" to "Int". Of course this then corrupts the object data.

Note that these objects are unusual in typically referencing **exports** for their class.

Vanilla:
![array_store_bug4](https://user-images.githubusercontent.com/13645804/38783801-5f248894-40bc-11e8-9bbf-494779675732.JPG)
![array_store_bug3](https://user-images.githubusercontent.com/13645804/38783803-62daa3c4-40bc-11e8-884b-c17f16e65716.JPG)

Modded:
![array_store_bug1](https://user-images.githubusercontent.com/13645804/38783805-6909d936-40bc-11e8-8636-d4bb46a6084c.JPG)
![array_store_bug2](https://user-images.githubusercontent.com/13645804/38783809-6b1a8f04-40bc-11e8-8225-f1e13e832024.JPG)

**Comment by Kinkojiro** [comment]
This is normal.  Once you change the name of a class ME3Explorer's property database doesn't know where to lookup structs/arrays from.  To edit you need to change the name back and then revert it once finished.

The only way to solve this would be to add IF(name not found) THEN (use superclass) type of solution in property db.

**Comment by ghost** [comment]
@Kinkojiro -- Kk, busy today but will try this tonight or tomorrow and update the issue.

Thanks!

**Comment by ghost** [comment]
Just getting back to this.

Now that I'm trying this, @Kinkojiro , did you mean that to edit the object I have to _temporarily_ change the class link back to the original object? If I do that the toolset does read the array properly, but, as soon as I change it back, the array is borked again. 

Here's another quick pick, since I re-did the file just a little bit:
![store_again](https://user-images.githubusercontent.com/13645804/38944588-24025c1c-42e9-11e8-8425-c53c83d0b0c4.JPG)

So, to be clear, what link do you keep in place for the final state of the file? The link to export 28 (blue box), since that allows it to be read by the toolset, or the link to 592 (red box), since that's technically correct? (In other words, is this strictly a toolset thing or will the game not recognize the new class, either?)

---

@SirCxyrtyx -- Does Kinko's suggestion above sound feasible, or would it create problems overall? Is this a feature we could incorporate into PackEd ("Add Class")?

**Comment by SirCxyrtyx** [comment]
My plan is to have it look in the file for a class definition if it doesn't have one. and then load superclass properties.

**Comment by SirCxyrtyx** [comment]
fixed by 2f68ddd415309967b6bfa2370b6e259538266f4f
