### ISSUE TITLE
Graphical glitch

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#53]
This one I'm unsure if me3explorer is directly causing it, but as Texmod seems to display the said texture correctly...
http://filebin.ca/2BiAwRngcvYc/bug.7z
The modded files cause strange graphical glitches (see the .PNGs). These glitches are altered by the distance from the texture.
Extracting the vanilla files then generating the mips in TPF/DDS and reinstalling them stalls TPF/DDS in rev711 and 717 after having vanilla'd. Heff, you mentioned some non-standard Mips for textures with different width/length. Could they be the cause of it ?

**Comment by HeffU** [comment]
Something real weird happening here, where the largest mip level is seemingly corrupted ingame.
Probably related to the lowest mip levels being 4x8/4x4 rather than 1x2/1x1.

**Comment by HeffU** [comment]
Turns out this is a super old issue, at least that's a relief that it aint something we broke recently.
http://me3explorer.freeforums.org/i-d-need-some-help-on-this-please-t1164.html?hilit=aquarium
