### ISSUE TITLE
Favorite folders

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#54]
I just realized it might a very useful feature to add some sort of a favorite system.
Let me explain : for now, when the user has to search on his computer for any file (TPFs, DDS, MOD, TocBin...), me3explorer opens a window with the exact same location as the last time it was opened. It might be convenient when you just use one file type and you have all of your files in the same folder, but when having to switch between folders everytime, it becomes quite tedious.

My idea would be to add a config option that allows you to set specific folders for each functions. Like, if I chose C:\TPFs for TPFTools, TPF Tools, and only TPFTools, would always open this folder by default. 
Ideally, having a Windows explorer-like favorites system would be nice, but I don't think it is feasible.

**Comment by starkgate** [comment]
@KFreon This can probably be closed now, since you switched to a better folder selection system, which allows for favorites.

**Comment by KFreon** [comment]
Oh excellent.
