### ISSUE TITLE
ARGB Texplorer thumbs not rendered properly

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#56]
This has been a bug probably since Texplorer was made. Here's a comparison:

![Image of comparison](http://i.imgur.com/fx6Pt0L.png)

Texplorer's thumb on the left and what the extracted texture looks like in GIMP on the right. This is ME3 hash 0xF98BC2E0.

TPF Tools _does_ display the extracted texture properly when the DDS is loaded in rev710.

It might be notable that Paint.NET -- which is usually pretty robust with DDSes -- won't open the extracted texture; it throws an "invalid format" error. GIMP opens it, but provides some options to check/uncheck prior to opening: whether to load mipmaps  and to "autodecode YCoCg/AExp format. No idea what the latter thing is.

**Comment by starkgate** [comment]
These GIMP options are standard when loading DDS', I see them for every single one.

**Comment by ghost** [comment]
Yeah, you're right. Just not used to that, yet, lol.

**Comment by KFreon** [comment]
Don't see this anymore.
Let me know if this still happens.

**Comment by ghost** [comment]
@KFreon -- Just wanted to say this fix was sooo worth it. There are so many more thumbnails in Texplorer I can see now :)

**Comment by KFreon** [comment]
Glad to hear it :D
