### ISSUE TITLE
Autofix fails on some MIPS

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#58]
I have some DDS' that seemed clean in rev717-. When scanning them in rev'718', some MIPS flags appeared. When trying to fix them, autofix fails.
![wut](https://cloud.githubusercontent.com/assets/12874678/9273055/bc78074e-4288-11e5-900f-21655c22a995.PNG)
Log : http://pastebin.ca/3104086
Testing files : http://filebin.ca/2C6faNfUqFHN/test.7z

Most of these DDS' installed fine in rev717. A user reported one of these DDS' failed to install in rev717, it just stalled TPF/DDS. This one I successfully autofixed in rev718 and installed in rev717. So it looks like 2 similar/mirrored bugs. Interesting.
http://filebin.ca/2C6itVYfPczh/MASSEFFECT3.EXE_0x13B463A5.7z

**Comment by starkgate** [comment]
Updated with new information.

**Comment by starkgate** [comment]
This one doesn't happen anymore, or happens differently. Please refer to #65

**Comment by HeffU** [comment]
Fixed in 718.
