### ISSUE TITLE
PCCEditor2 - Adding a name should reload the name table

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#59]
As it stands, when you add a name in PCCEditor2, you have to change tabs and back to the Names tab to see the new name. It should auto reload, preferably not rescrolling the list.

**Comment by SirCxyrtyx** [comment]
Now refreshes the name table while preserving scroll position and selection. I also changed the messagebox from "Done" to "examplename added at index 2242".
