### ISSUE TITLE
PCCEditor2 - Hex Editor's paste feature only works if you copy from within the hex editor

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#60]
If you have hex from a text file (say I typed out a wall of hex, such as 014600000000000026000000000000001C00000000000000030000001704000000000000180400000000000019040000000000000E02000000000000, it inputs their ASCII codes instead of the actual content. One could check the input from the clipboard to see if it is a set of valid hex characters, and then interpret it as such.

**Comment by SirCxyrtyx** [comment]
It seems that, fortuitously, the Be.Windows.Forms.HexBox source is included in this project instead of the just the dll. So I can do this after all. New rev with this should be up soon.
