### ISSUE TITLE
Extracting autofixed texture problem

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#64]
Autofixing, then extracting a texture through TPF/DDS option "Extract All" or by selecting the texture and clicking "Extract" only extracts the original texture. This results, when putting the texture back in TPF/DDS, in it being flagged again.

http://filebin.ca/2CTY65OMyOSR/MASSEFFECT3.EXE_0x7FDBBB2C.dds

Interestingly, it does work with "duplicated" textures. I'm having a real hard time trying to give exhaustive bug reports with these sneaky, complicated bugs^^.

**Comment by starkgate** [comment]
This issue can also be merged with #65

**Comment by HeffU** [comment]
Fixed in 718.
