### ISSUE TITLE
Graphics card specific problem

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#65]
In rev717, the textures linked below cause stalling for some people in TPF/DDS. They are flagged as Mips in rev'718', but not in rev717. Autofixing in rev'718' then directly installing works. 

Autofixing, then extracting these specific textures through TPF/DDS option "Extract All" or by selecting the texture and clicking "Extract" only extracts the original texture. This results, when putting the texture back in TPF/DDS, in it being flagged again. Extracting other textures, that were already being flagged before, does work.

Interestingly, the stalling in rev717 didn't occur for an AMD user, who installed one of the textures without problems in rev717. I can confirm stalling does occur for my Nvidia card, but can't generalize the observation to all AMD/Nvidia cards.

Here is a summary of the situation :
Nvidia
MASSEFFECT3.EXE_0x7FDBBB2C 717:Stall 718:MIPS Flag
AMD
MASSEFFECT3.EXE_0x7FDBBB2C 717:Fine 718:Not tested

Testing files : http://filebin.ca/2CVSWCnuTfL9/wtf.7z http://filebin.ca/2C6faNfUqFHN/test.7z 
http://filebin.ca/2CTY65OMyOSR/MASSEFFECT3.EXE_0x7FDBBB2C.dds

**Comment by HeffU** [comment]
Fixed in 718, related to a workaround for textures with duplicated mip levels.
