### ISSUE TITLE
Conditionals Editor | Remove automatic TOCing feature

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#66]
The automatic TOC function can likely be pulled from the Conditionals Editor. It's not necessary, since there's no guarantee the file being edited is in a game directory. Plus, the TOCing mechanism is likely out of date and doesn't use AutoTOC. That makes it incompatible with DLC Mods.

Having the tool auto trigger the TOC results in having to click/press two more buttons every time the user saves... which is annoying.

Any tool that automatically TOCs -- besides Texplorer, TPF Tool, and Mod Maker -- should probably have the TOCing function removed. Mod creators frequently edit files that aren't inside the game directory, so this "feature" is more of a hindrance than it is helpful.

**Comment by Mgamerz** [comment]
The command line feature for Automatic TOC updating should not be removed
FYI (I don't think that's what you're specifically talking about, but the
CL version should not be removed as its in use by people)

**Comment by SirCxyrtyx** [comment]
Removed from Conditionals editor and Sequence Editor. If there are other tools that do this, I am not aware of them.

**Comment by ghost** [comment]
I'm pretty sure those are the only ones. I'll reopen the issue if I come across any others.

Thanks!
