### ISSUE TITLE
Generate thumbnails per folder

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#68]
I just noticed that there is no option to regenerate thumbnails in a folder. I can only regenerate a specific texture's thumbnail or to regenerate all of them. Pretty extreme as choice goes^^.
This is especially useful to those who import their trees on a fresh me3explorer rev and don't build it from there. Thumbnails are not present unless they are copied with the tree.

**Comment by KFreon** [comment]
Done :D
