### ISSUE TITLE
rev718 in-game graphical glitches

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#69]
I had a discussion with users (Pulsifer, SimonDJ) that downloaded ALOT and experienced graphical glitches using RC rev718. The cause is very likely to not be the mod, as there weren't any reports of this issue before rev718. Also, it is confirmed that reinstalling the mod through rev717 fixes the graphical glitches.
Another interesting aspect of these users is Windows. One of them has W10, the other W8 and two of them have W7.
Here is the information I could collect :

The installation process does finish successfully, no flags whatsoever, except for some NFIT typical of a setup without all DLCs.
BUT, after installing, graphical glitches appear in game, that didn't appear when installing with rev717. It is confirmed for W7, W8 and W10 (http://me3explorer.freeforums.org/post19172.html#p19172). It looks pretty bad :
![2dc2f12573dc7a45c958673486945873](https://cloud.githubusercontent.com/assets/12874678/9413391/e68feb88-4831-11e5-92a7-36542ff68492.jpg)
![e83d716af0c6bf64a072cea6bfa8d109](https://cloud.githubusercontent.com/assets/12874678/9413393/e6e187d6-4831-11e5-992f-074c44e9f741.jpg)
![a7f3910873f92ab47b7fc739e73a32f6](https://cloud.githubusercontent.com/assets/12874678/9413392/e6dc2cbe-4831-11e5-81ba-a8f5e9ca9ffd.jpg)
![2015-08-22_00002](https://cloud.githubusercontent.com/assets/12874678/9421082/8f6facbc-486d-11e5-9de2-cc100afd1324.jpg)
![2015-08-22_00006 jpg original](https://cloud.githubusercontent.com/assets/12874678/9421083/8f88ffb4-486d-11e5-8050-ee495d319b34.jpg)

It kinda looks like meshes with grey placeholder texture applied on it. Two debug logs from Pulsifer :
http://filebin.ca/2CvEveCZ7hi6/Debuglog1.txt (loading, autofixing, installing)
http://pastebin.ca/3120081 (only loading)

This is all the information I have for now, I'll update the issue if I find more. The interpretation is beyond my knowledge, it's such a mess... Hopefully that will help.

**Comment by HeffU** [comment]
Possibly, or at least partially fixed in 0310d5a516d323b7938f53f7b47e1aeb4b9d06ce, had to revert to the old way of property handling for now.

**Comment by starkgate** [comment]
Obsolete issue, closing.
