### ISSUE TITLE
D3D Device

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#70]
So, made some testing with Pulsifer. He is running W10, rev718 and has some D3D Device problems, which I don't experience, so I made some tests with him. I am unsure if W10 is the cause of it, or at least partially, as deadspear apparently also had this problem with W7 and an older rev (unsure?). 

![screenshot3](https://cloud.githubusercontent.com/assets/12874678/9419212/182f7ef6-485a-11e5-87ee-df8219597f59.jpg)

When autofixing the NFIT textures (don't ask), this happens :
"09.45.04:  Fixing: 
     FORMAT -> Current: DXT1  Expected: 
     MIPS -> Current: 12  Expected: 0
09.45.04:  Failed to autofix image, skipping:
Microsoft (R) D3DX9 Texture Converter
Copyright (C) Microsoft Corp 2001. All rights reserved.

Failed to create D3D device"

If I try to do the same on my end, this happens :
"22:33:30:  Fixing: 
     FORMAT -> Current: DXT5  Expected: 
     MIPS -> Current: 12  Expected: 0"

Autofixing Mips :
"22.59.03: Fixing:
FORMAT -> Current: DXT1 Expected:
MIPS -> Current: 1 Expected: 0
22.59.03: Failed to autofix image, skipping:
Microsoft (R) D3DX9 Texture Converter
Copyright (C) Microsoft Corp 2001. All rights reserved.

Failed to create D3D device"
The lack of name here is not an error on my part, it didn't appear on debug.

Autofixing formats (whatever the format afaik) :
"23.07.24: Fixing: WPN_BLSj_Spec
FORMAT -> Current: DXT3 Expected: DXT5
MIPS -> Current: 11 Expected: 10
23.07.24: Failed to autofix image, skipping:
Microsoft (R) D3DX9 Texture Converter
Copyright (C) Microsoft Corp 2001. All rights reserved.

Failed to create D3D device"
"23.08.49: Fixing: WPN_ASLd_Spec
FORMAT -> Current: DXT5 Expected: DXT1
MIPS -> Current: 12 Expected: 10
23.08.54: Failed to autofix image, skipping:
Microsoft (R) D3DX9 Texture Converter
Copyright (C) Microsoft Corp 2001. All rights reserved.

Failed to create D3D device"

These are then all flagged as _AUTOFIX FAILED_.

There is no D3D Device problem when using rev717. In W7, no problem at all autofixing anything (except for #71). In W10, weeeell :
![screenshot5](https://cloud.githubusercontent.com/assets/12874678/9419539/d7ce9b00-485c-11e5-9f29-54c490185020.jpg)

Testing files (unfixed MIPS, FORMAT DXT1,DXT3...) :
https://mega.nz/#!gksWRCZR!sSagTrjeeETO_gZ7NL5o1J_DJTNckL528lvUkIPwdTU

**Comment by HeffU** [comment]
For now I'm gonna guess that this was just a d3ddevice problem all along, until more testing can show more details. Will keep this open.

**Comment by KFreon** [comment]
This should be solved now since external tools are no longer used.
Windows can handle D3D stuff for me :)
