### ISSUE TITLE
Version Switcher and special characters

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#72]
Version Switcher doesn't seem to support special characters (e.g. "è"). When I went 718 to 717, it created a new folder named "Biblioth├¿ques" instead of copy/pasting it to "Bibliothèques".
![capture](https://cloud.githubusercontent.com/assets/12874678/9421132/3b32e8d4-486e-11e5-8abe-5d4d6e727041.PNG)
It doesn't seem to support spaces either :
![me3 version switch](https://cloud.githubusercontent.com/assets/12874678/9423307/f80d4954-48be-11e5-9c46-65829b4cfeb2.PNG)

**Comment by HeffU** [comment]
This turns out to be an encoding problem with batch scripts, wont be able to find a perfect workaround but will see what I can dig up. Otherwise we might think about re-writing it to its own sub process instead of using the script.

**Comment by Mgamerz** [comment]
https://social.technet.microsoft.com/Forums/scriptcenter/en-US/fa73b809-602d-405e-a981-264d0fb8a8b4/utf8-characters-eg-are-not-supporting-in-batch-file?forum=ITCG

**Comment by Mgamerz** [comment]
Also
http://stackoverflow.com/questions/11962172/echo-utf-8-characters-in-windows-batch

**Comment by HeffU** [comment]
Yeah, I went through those earlier, but they're dependent on the users code page being compatible, and it doesn't look like any one page will work for all users. I'd guess that 65001 or 850 would be the best, gonna go with one of those.
