### ISSUE TITLE
Windows 10 GUI problems

### ISSUE THREAD

**Issue by HeffU** [ME3Explorer/ME3Explorer#74]
Some users are experiencing problems with the UI after the latest windows 10 update, for example the tree-building dialog wont show up.

**Comment by HeffU** [comment]
Additional reports say that this might be caused by antivirus's blocking the toolset from searching files for the users that experienced this.

**Comment by Mgamerz** [comment]
My AV picks up pretty much every .exe in the toolkit. I think because it's
a new file (to them). Has anyone seen what the toolkit looks like with text
scaling on? I know it blows up my mod manager.

**Comment by ghost** [comment]
Do we have any more information about these Win10 problems? So that issues can be addressed for the stable?

**Comment by KFreon** [comment]
This looks to be done right?

**Comment by ghost** [comment]
@KFreon I was just thinking about this yesterday.

If we want, I can toss up a poll/comment thread on the forum, specifically for Windows 10 users. See if whatever past issues present have been solved or if there's lingering problems we need to know about.

Just let me know :)

**Comment by KFreon** [comment]
Yeah we should do that, cos otherwise, this can be closed and we're that one little step closer to the stable :)

**Comment by ghost** [comment]
Give me 5 :)

**Comment by ghost** [comment]
And, poll is up. Adding a link here for easy reference:

http://me3explorer.freeforums.org/windows-10-users-the-toolset-t2026.html

**Comment by ghost** [comment]
So far, we have no votes indicating problems, but only 6 votes. 

As five of the six are still on Windows 7, we basically have N=1 at this point, lol.

**Comment by ghost** [comment]
@SirCxyrtyx , @KFreon -- I'm going to suggest we close this. We haven't gotten many votes in the forum poll, but it seems whatever issues originally existed have been rectified. No votes about anything being broken in the poll, and no reports of issues here, outside of the initial reports back in August.

Once we close this, I'll also close the forum poll and archive the thread as it is no longer relevant.

**Comment by SirCxyrtyx** [comment]
Sounds good.
