### ISSUE TITLE
MIPS counting problems

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#75]
I found some inconsistent results with MIPS modding for a specific texture (128x256 0xCFC054A8) in rev717/718, haven't searched for any other yet, but there are surely more. For the vanilla texture :
- Texplorer displays 7 MIPS
- TPF/DDS thinks there are 8 Tree MIPS
- Extracting the texture using Texmod results in a 7 MIPS texture

Furthermore, autofixing a modded texture of size 512x1024, would bring us to 9 or 10 MIPS following Texplorer's or TPF/DDS' logic. In rev716 (probably before too), the autofixed texture has 11 MIPS. In rev717, the autofixed texture has 10 MIPS. In rev718, it has 11 MIPS. The installation of the 10 MIPS stalled, the 11 MIPS went fine.

In-game, the 11 MIPS looks fine except for a visible MIPS transition that should not happen. Not sure if this is due to the 11 MIPS (abnormal number ?), or just a bad MIPS creation algorithm that doesn't take into account transitions.

Some coherence would be appreciated for clarity^^. I suppose the rewrite will fix all that, but I wanted to inform you of this problem anyways.
http://filebin.ca/2DNNLuWsVSvj/test.7z

**Comment by KFreon** [comment]
That's super weird...
For a texture 512x1024 it should have 11 mips. 

That's how many get generated by the ImageEngine, so I musta made a mistake in that older version to have it generate so many mips.

**Comment by starkgate** [comment]
Still a wrong MIPS count in 723 compared to 718 (one less MIPS than normal). Here are test files with different versions of a texture : extracted with texmod, without mips, autofixed with 718 and autofixed with 723.
http://filebin.ca/2PjYDoX5SF6D/MIPSCount.7z

**Comment by KFreon** [comment]
I have no idea what's going on here, but lets take a look at the numbers of your images and see if we can get on the same page (or just me onto your page).

### 718

This one says it has 11 mipmaps, but its dimensions are 512x1024
512 = 2^9, so the max number of mips it can have is 7, otherwise it won't have width.
i.e. the mip dimensions are:
1x2, 2x4, 4x8, 8x16, 16x32, 32x64, 64x128, 128x256, 256x512, 512x1024

This leads me to the conclusion that 718 mipmapping was wrong, at least in count.

### 723

Totally broken...whoops.

### My end (dunno what's different)

When I do the conversion, I get 9 mips as expected.
Maybe I included the wrong version or something...

**Comment by starkgate** [comment]
Ugh, it's a mess. It's been too long since I've written this, so I'll need some time to readjust my thinking. I think you can ignore my first posts, I'll give a summary below.

I checked autofix with 718 _again_, and it does autofix to 11 MIPS, just like 723.

Now, let's look at it from another point of view : the vanilla texture (128x256) extracted through Texmod has 7 MIPS. Here is a screenshot of the extract menu for the vanilla texture :
![capture3](https://cloud.githubusercontent.com/assets/12874678/11955454/6ca278f4-a8b2-11e5-94e6-9e595a42b675.PNG)
So it is absolutely logical that the 512x1024 would have 9 MIPS, in this case. If you look at the Texplorer tree after installing :
![capture2](https://cloud.githubusercontent.com/assets/12874678/11955348/898134fc-a8b1-11e5-95fc-19ff156791fa.PNG)
The 2 surplus MIPS apparently get deleted when installing.
Also, I checked it : the texture autofixed through 718 OR 723 does work in game perfectly fine.

You can see that ME3 actually **doesn't need** some MIPS. This is something I and Heff noticed about a lot of textures in the tree (although not all) : ME3 has a pretty inconsistent MIP usage, sometimes it goes down to 1x1 :
![capture4](https://cloud.githubusercontent.com/assets/12874678/11955520/e3deec40-a8b2-11e5-9ede-e559365e268d.PNG)
Sometimes it has 3 4x4 in a row, etc...
![capture5](https://cloud.githubusercontent.com/assets/12874678/11955533/0555d03c-a8b3-11e5-9215-83e2b10a0857.PNG)
You can't have a general formula for this type of thing, which is probably the problem with this.

**Summary of the summary** : rev718 and 723 both have a working MIPS autofixing mechanic. Both autofix to 11 MIPS following your formula, and in both cases, 2 MIPS get deleted when installing the texture, which brings us down to 9 MIPS. Which is perfectly normal knowing that the vanilla texture has 7 MIPS.
I _think_ you can close this issue now, unless you want to dabble with a dynamical MIPS formula. Which would, IMHO, not be very useful. It works (kinda), as is. The only thing left to do is make 723 DDS' compatible with everything else (ie older me3explorer and Photoshop among others), see #108.

I'm on the me3explorer chat if needed.

Please tell me if I need to clarify or test anything, I'm not sure my explanation is very good.

**Comment by KFreon** [comment]
That's a good review of the details, thank you for that.
I wouldn't trust that selection window too much though. It does a bit of filtering to get rid of mips that it considers invalid e.g. there's an index but no data (offset = -1).

Regardless, 732 works! Yaaay! I couldn't figure out why it wouldn't.
I've got a new one on the way, but I'll close this and we can re-open if need be.
