### ISSUE TITLE
Unhandled exception in PCC Editor: can't find BIOGame_INT.tlk

### ISSUE THREAD

**Issue by mirh** [ME3Explorer/ME3Explorer#78]
I can see in ProcMon that ME3explorer looks in HKLM\SOFTWARE\Wow6432Node\BioWare\Mass Effect 3 (which I don't have indeed, but that's another matter)

Then it looks in ME3 explorer own folder (and of course it's not there)
Blot is the same of #38, but I believe that unwanted side effects should be solved too, together with root cause

**Comment by Mgamerz** [comment]
In my modmanager I look in the 64 and 32 bit registry keys then the default
program folder locations, otherwise I give up.

**Comment by mirh** [comment]
Try to delete \exec\history.log
And you should see the same behavior.

**Comment by SirCxyrtyx** [comment]
Fixed by b0ec3566a6cbee1abc21e1dfd19f976184c6c329
