### ISSUE TITLE
ME2 package editor doesn't show classes list

### ISSUE THREAD

**Issue by mirh** [ME3Explorer/ME3Explorer#79]
Which is, that drop-down list next to "Tree View" button for the records.

**Comment by ghost** [comment]
As far as I know this is a feature that hasn't been implemented yet. The dropdown is in the GUI, but it doesn't work yet (and isn't intended to).

Marking this as an enhancements, please correct me if I'm wrong, guys.

**Comment by SirCxyrtyx** [comment]
Haven't actually tested this since I don't have ME2 installed, but the code to make it work was already there, just not reachable because of an oversight of mine. So I'm confident that it functions properly.

**Comment by ghost** [comment]
I'll test on the next RC; I have it installed.

**Comment by mirh** [comment]
Confirmed fixed in latest RC.
