### ISSUE TITLE
Debug Logger and File EXE assembly versions do not match

### ISSUE THREAD

**Issue by Mgamerz** [ME3Explorer/ME3Explorer#88]
Running 720 (soon to be 721) I am noticing that windows decorate it with the correct version as specified in the ME3Explorer project settings. In this instance In Application/Assembly Information I can see it is version 720. However the debug logger, which I think is part of KFreon Lib (that lib seems to have a lot of duplicate code in it) reports that this is version 718. For helping debug this will cause confusion.

**Comment by Mgamerz** [comment]
The code that seems to be relevant is DebugOutput.cs in KFreonLib:

```
            DebugOutput.PrintLn("Build Version: " + System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString());
```

Though this should have worked.

This issue is reflected in my branch (femshepdev) as well as the bugfix branch.

**Comment by SirCxyrtyx** [comment]
Ongoing vigilance is required on this I suppose, but the assembly version for KFreon Lib has been getting updated along with ME3Explorer.
