### ISSUE TITLE
rev721/722 Wrong extension for autofixed bmp, png etc

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#94]
First of all, thank you so much to the devs for bringing this rev ! As the forum is pretty much down right now, I'll just take a moment here to write a bit on what this rev changed for me : me3explorer now works on VMWare (and probably VirtualBox too). This wasn't the case for rev717 and 718, probably due to the fact that the VM's graphics card was not supported.

While doing some autofixing, I noticed that using the "Extract All" button extracted fixed non-DDS files using their initial extension. At first I thought that the textures weren't autofixed, but when I tried opening one of them, IrfanView warned me that it was indeed a DDS texture with the wrong extension, and opened it successfully as a DDS.
Selecting a single texture and clicking "Extract" does rename the texture to .DDS.
I also noticed the RAM climbing high up to 600-1200 Mo when autofixing these BMPs, which is a lot higher than in preceding revs. Is this normal ?

**Comment by KFreon** [comment]
This is related to the other report about things not being flagged for being the wrong format.
Tis also fixed.

**Comment by starkgate** [comment]
I can confirm it is fixed in 723. But another bug appeared when it comes to extracting textures, see #114.
