### ISSUE TITLE
rev721/722 No error flag for wrong texture format eg BMP

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#96]
Analysing BMPs and PNGs (probably other non-DDS formats too) in TPF/DDS doesn't flag them as being the wrong format, even if they can be (and have to be) autofixed, as the "Run Autofix" button isn't greyed out.

**Comment by KFreon** [comment]
Turned out to be a rather long string of bugs relating to how autofix marked things as fixed and altered their pathings to point to the new texture.

Seems fixed now though.

**Comment by starkgate** [comment]
Confirmed to work in rev723, awesome !
