### ISSUE TITLE
rev721/722 ARGB to DXT5 conversion

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#97]
Trying to autofix an ARGB texture to DXT5 causes .NET to throw the error below, accompanied by a popup saying the application encountered an error and must be closed.
Interestingly, choosing "Close the program" on this popup doesn't actually close it, me3explorer continues its process, ignoring the error. Me3explorer also prints "Error checking texture: one or more errors happened" in the log and flags the texture as "AUTOFIX FAILED".
I use .NET 4.6, maybe it helps.

Nom d’événement de problème:   CLR20r3
  Signature du problème 01:    ME3Explorer.exe
  Signature du problème 02:    1.1.721.684
  Signature du problème 03:    561dab9a
  Signature du problème 04:    CSharpImageLibrary
  Signature du problème 05:    1.8.0.0
  Signature du problème 06:    560ceab9
  Signature du problème 07:    48
  Signature du problème 08:    78
  Signature du problème 09:    Debugger.Break
  Version du système:  6.1.7601.2.1.0.256.1
  Identificateur de paramètres régionaux: 1036
  Information supplémentaire n° 1:   d5c8
  Information supplémentaire n° 2:   d5c8efa7846c54d07198ec05e906d47a
  Information supplémentaire n° 3:   dc4f
  Information supplémentaire n° 4:   dc4f59fbb2dcc109da1b26627978894a

**Comment by starkgate** [comment]
More information : loading the texture alone causes me3explorer to immediately crash with the said error. It stays frozen even after choosing "Close the program", so hard quit via task manager is the only solution. The same happens for some DXT1 to ARGB files (not all of them).
Test files (correspond to the errors in the log) : https://mega.nz/#!M9UgGDgQ!KiYnJxzgHfGwp-9QrvyXKT7JpqMm3nfscl1zAC7eOuI
Log : http://pastebin.ca/3196904

I don't have the time to organize the log and do some more exhaustive testing, sorry :/.

**Comment by Mgamerz** [comment]
I dot think me3explorer fully closes because of running threads and some
extra exes.

**Comment by KFreon** [comment]
Those files you posted are all broken, but your other bug report (ARGB -> DXT1) has them correct and it was due to the textures not actually being ARGB. 
They were mostly A8L8 which is an alpha/luminescence format, and a few RGB (no alpha).
Support for those two formats has now been added.
Those files you posted are all broken, but your other bug report (ARGB -> DXT1) has them correct and it was due to the textures not actually being ARGB. 
They were mostly A8L8 which is an alpha/luminescence format, and a few RGB (no alpha).
Support for those two formats has now been added.

**Comment by starkgate** [comment]
Oops, sorry about that. They were definitely not broken when I loaded them into me3explorer, something must have gone wrong when I extracted them.

**Comment by starkgate** [comment]
Well, this seems even more broken than it was before sadly :/. The textures aren't even recognized anymore by TPF/DDS, as you can see in the log in the picture below. Note that these are definitely not 'normal' textures, they seem to be pretty buggy by themselves. I don't have 'normal' ARGB to DXT5 to test out, so I don't know if this applies to all textures.
![capture](https://cloud.githubusercontent.com/assets/12874678/11763917/e0f0eaf2-a11d-11e5-9bfc-cedf13bfdcd1.PNG)
Test files, fixed^^
http://filebin.ca/2Pjc2AAsFVcv/ARGB_DXT5.7z

**Comment by starkgate** [comment]
The test files simply crash rev725, just like 718. I think we could ignore this problem, as it is specific to the textures I linked.

**Comment by KFreon** [comment]
None of those new test files open in any program I have either :P  
Where do you get these?

**Comment by starkgate** [comment]
I don't remember, it was a part of one of the hundreds of TPFs I extracted for ALOT. I don't even have the original files anymore, I've fixed them via photoshop since then.
